/* oxlint-disable max-lines, open-pencil/no-hand-rolled-color -- generated accessible menu runtime remains beside its adapter */
import { DROPDOWN_MENU_MODULE_TYPE, DROPDOWN_MENU_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { VueModuleAdapter, VueModuleRuntimeOptions } from './types'

const DROPDOWN_MENU_RUNTIME = `<!-- Auto-generated by OpenPencil compiler. Do not edit by hand. -->
<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  useAttrs,
  useId,
  watch
} from 'vue'
import type { CSSProperties } from 'vue'

import {
  adjacentOpenPencilTabStop,
  isTopOpenPencilLayer,
  registerOpenPencilLayer,
  safeOpenPencilHref
} from './__openpencil_layer'

type Placement =
  | 'bottomLeft' | 'bottom' | 'bottomRight'
  | 'topLeft' | 'top' | 'topRight'
  | 'leftTop' | 'left' | 'leftBottom'
  | 'rightTop' | 'right' | 'rightBottom'
type MenuEntry =
  | { type: 'item'; label: string; href: string; disabled: boolean; danger: boolean; shortcut: string }
  | { type: 'separator' }
interface DropdownMenuConfig {
  triggerLabel: string
  showTriggerLabel: boolean
  showTriggerChevron: boolean
  triggerMode: 'click' | 'hover'
  placement: Placement
  closeOnSelect: boolean
  closeOnEscape: boolean
  closeOnOutsidePress: boolean
  menuWidth: number
  triggerBackground: string
  triggerTextColor: string
  menuBackground: string
  itemTextColor: string
  accentColor: string
  dangerColor: string
  items: readonly MenuEntry[]
}

defineOptions({ inheritAttrs: false })
const props = defineProps<{ config: DropdownMenuConfig }>()
const attrs = useAttrs()
const open = ref(false)
const trigger = ref<HTMLButtonElement | null>(null)
const menu = ref<HTMLElement | null>(null)
const activeIndex = ref(-1)
const position = ref({ left: -10000, top: -10000 })
const token = Symbol('open-pencil-dropdown-menu')
const baseId = useId().replaceAll(':', '')
const menuId = baseId + '-menu'
const authoredTriggerId = baseId + '-authored-trigger'
const triggerFallbackId = baseId + '-trigger-fallback'
const authoredTriggerLabelledBy = authoredTriggerId + ' ' + triggerFallbackId
let desiredFocus: 'first' | 'last' | 'none' = 'first'
let releaseLayer: ((restoreFocus?: boolean) => void) | null = null
let hoverTimer: number | null = null

const disabled = computed(() => attrs.disabled !== undefined && attrs.disabled !== false)
const items = computed(() =>
  props.config.items.map((item) =>
    item.type === 'item' ? { ...item, safeHref: safeOpenPencilHref(item.href) } : item
  )
)
const enabledIndexes = computed(() =>
  items.value.flatMap((item, index) => (item.type === 'item' && !item.disabled ? [index] : []))
)
const hostStyle: CSSProperties = {
  boxSizing: 'border-box',
  display: 'inline-flex',
  minHeight: '44px',
  minWidth: '44px',
  position: 'relative' as const
}
const triggerStyle = computed<CSSProperties>(() => ({
  alignItems: 'center',
  appearance: 'none',
  background: props.config.triggerBackground,
  border: 0,
  borderRadius: '8px',
  boxSizing: 'border-box',
  color: props.config.triggerTextColor,
  cursor: disabled.value ? 'not-allowed' : 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  gap: '8px',
  height: '100%',
  justifyContent: 'center',
  minHeight: '44px',
  minWidth: '44px',
  opacity: disabled.value ? 0.5 : 1,
  outlineOffset: '2px',
  padding: '0 14px',
  touchAction: 'manipulation',
  width: '100%'
}))
const overlayTriggerStyle = computed<CSSProperties>(() => ({
  ...triggerStyle.value,
  background: 'transparent',
  color: 'inherit',
  inset: 0,
  padding: 0,
  position: 'absolute' as const,
  zIndex: 1
}))
const menuStyle = computed<CSSProperties>(() => ({
  background: props.config.menuBackground,
  color: props.config.itemTextColor,
  left: position.value.left + 'px',
  top: position.value.top + 'px',
  width: props.config.menuWidth + 'px'
}))

function idealPosition(placement: Placement, triggerRect: DOMRect, width: number, height: number) {
  const gap = 8
  const centeredX = triggerRect.left + (triggerRect.width - width) / 2
  const centeredY = triggerRect.top + (triggerRect.height - height) / 2
  if (placement === 'bottomLeft') return { left: triggerRect.left, top: triggerRect.bottom + gap }
  if (placement === 'bottom') return { left: centeredX, top: triggerRect.bottom + gap }
  if (placement === 'bottomRight') return { left: triggerRect.right - width, top: triggerRect.bottom + gap }
  if (placement === 'topLeft') return { left: triggerRect.left, top: triggerRect.top - height - gap }
  if (placement === 'top') return { left: centeredX, top: triggerRect.top - height - gap }
  if (placement === 'topRight') return { left: triggerRect.right - width, top: triggerRect.top - height - gap }
  if (placement === 'leftTop') return { left: triggerRect.left - width - gap, top: triggerRect.top }
  if (placement === 'left') return { left: triggerRect.left - width - gap, top: centeredY }
  if (placement === 'leftBottom') return { left: triggerRect.left - width - gap, top: triggerRect.bottom - height }
  if (placement === 'rightTop') return { left: triggerRect.right + gap, top: triggerRect.top }
  if (placement === 'right') return { left: triggerRect.right + gap, top: centeredY }
  return { left: triggerRect.right + gap, top: triggerRect.bottom - height }
}

function updatePosition(): void {
  if (!open.value || !trigger.value || !menu.value) return
  const width = menu.value.offsetWidth
  const height = menu.value.offsetHeight
  const ideal = idealPosition(props.config.placement, trigger.value.getBoundingClientRect(), width, height)
  const inset = 8
  position.value = {
    left: Math.max(inset, Math.min(ideal.left, window.innerWidth - width - inset)),
    top: Math.max(inset, Math.min(ideal.top, window.innerHeight - height - inset))
  }
}

function focusItem(index: number): void {
  activeIndex.value = index
  nextTick(() => {
    menu.value
      ?.querySelector<HTMLElement>('[data-openpencil-dropdown-index="' + index + '"]')
      ?.focus({ preventScroll: true })
  })
}

function openMenu(focus: 'first' | 'last' | 'none' = 'first'): void {
  if (disabled.value) return
  clearHoverTimer()
  desiredFocus = focus
  open.value = true
}

function closeMenu(restoreFocus = true): void {
  clearHoverTimer()
  releaseLayer?.(restoreFocus)
  releaseLayer = null
  open.value = false
  activeIndex.value = -1
}

function toggleMenu(): void {
  if (open.value) closeMenu()
  else openMenu('first')
}

function clearHoverTimer(): void {
  if (hoverTimer !== null) window.clearTimeout(hoverTimer)
  hoverTimer = null
}

function scheduleHoverClose(): void {
  if (props.config.triggerMode !== 'hover') return
  clearHoverTimer()
  hoverTimer = window.setTimeout(() => closeMenu(false), 140)
}

function onTriggerKeydown(event: KeyboardEvent): void {
  if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
    event.preventDefault()
    openMenu(event.key === 'ArrowUp' ? 'last' : 'first')
  } else if (event.key === 'Escape' && open.value && props.config.closeOnEscape) {
    event.preventDefault()
    closeMenu()
  }
}

function onMenuKeydown(event: KeyboardEvent): void {
  if (!isTopOpenPencilLayer(token)) return
  const indexes = enabledIndexes.value
  if (event.key === 'Escape' && props.config.closeOnEscape) {
    event.preventDefault()
    event.stopPropagation()
    closeMenu()
    return
  }
  if (event.key === 'Tab') {
    const destination = trigger.value && menu.value
      ? adjacentOpenPencilTabStop(trigger.value, menu.value, event.shiftKey)
      : undefined
    event.preventDefault()
    closeMenu(false)
    destination?.focus({ preventScroll: true })
    return
  }
  if (indexes.length === 0) return
  let next = activeIndex.value
  if (event.key === 'Home') next = indexes[0]
  else if (event.key === 'End') next = indexes[indexes.length - 1]
  else if (event.key === 'ArrowDown') {
    const at = Math.max(-1, indexes.indexOf(activeIndex.value))
    next = indexes[(at + 1) % indexes.length]
  } else if (event.key === 'ArrowUp') {
    const at = indexes.indexOf(activeIndex.value)
    next = indexes[(at <= 0 ? indexes.length : at) - 1]
  } else return
  event.preventDefault()
  focusItem(next)
}

function onItemSelect(hasHref: boolean): void {
  if (props.config.closeOnSelect) closeMenu(!hasHref)
}

function onDocumentPointerDown(event: PointerEvent): void {
  if (!open.value || !props.config.closeOnOutsidePress || !isTopOpenPencilLayer(token)) return
  const target = event.target
  if (!(target instanceof Node)) return
  if (trigger.value?.contains(target) || menu.value?.contains(target)) return
  closeMenu(false)
}

watch(open, async (value) => {
  if (!value) return
  await nextTick()
  if (!open.value || !menu.value) return
  releaseLayer?.(false)
  releaseLayer = registerOpenPencilLayer(token, menu.value)
  updatePosition()
  if (desiredFocus === 'none') return
  const indexes = enabledIndexes.value
  const index = desiredFocus === 'last' ? indexes[indexes.length - 1] : indexes[0]
  if (index !== undefined) focusItem(index)
})

onMounted(() => {
  document.addEventListener('pointerdown', onDocumentPointerDown, true)
  window.addEventListener('resize', updatePosition)
  window.addEventListener('scroll', updatePosition, true)
})
onBeforeUnmount(() => {
  clearHoverTimer()
  releaseLayer?.(false)
  document.removeEventListener('pointerdown', onDocumentPointerDown, true)
  window.removeEventListener('resize', updatePosition)
  window.removeEventListener('scroll', updatePosition, true)
})
</script>

<template>
  <div
    v-bind="$attrs"
    data-openpencil-dropdown-host=""
    :style="hostStyle"
    @mouseenter="config.triggerMode === 'hover' && openMenu('none')"
    @mouseleave="scheduleHoverClose"
  >
    <div
      v-if="$slots.default"
      :id="authoredTriggerId"
      aria-hidden="true"
      data-openpencil-dropdown-authored-trigger=""
      inert
      style="align-items:center;display:inline-flex;height:100%;justify-content:center;max-width:100%;min-width:0;pointer-events:none;width:100%"
    >
      <slot />
    </div>
    <button
      ref="trigger"
      type="button"
      :aria-controls="menuId"
      :aria-expanded="open"
      :aria-label="$slots.default ? undefined : config.triggerLabel"
      :aria-labelledby="$slots.default ? authoredTriggerLabelledBy : undefined"
      aria-haspopup="menu"
      :disabled="disabled"
      :style="$slots.default ? overlayTriggerStyle : triggerStyle"
      @click="toggleMenu"
      @focus="config.triggerMode === 'hover' && openMenu('none')"
      @keydown="onTriggerKeydown"
    >
      <span
        v-if="$slots.default"
        :id="triggerFallbackId"
        class="openpencil-trigger-fallback"
      >{{ config.triggerLabel }}</span>
      <template v-if="!$slots.default">
        <span v-if="config.showTriggerLabel">{{ config.triggerLabel }}</span>
        <svg
          v-if="config.showTriggerChevron"
          aria-hidden="true"
          focusable="false"
          style="height:16px;width:16px"
          viewBox="0 0 24 24"
        >
          <path d="M6 9L12 15L18 9" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
        </svg>
      </template>
    </button>
  </div>

  <Teleport to="body">
    <Transition name="openpencil-dropdown">
      <div
        v-if="open"
        :id="menuId"
        ref="menu"
        class="openpencil-dropdown-menu"
        data-openpencil-dropdown-menu=""
        role="menu"
        :style="menuStyle"
        @keydown="onMenuKeydown"
        @mouseenter="clearHoverTimer"
        @mouseleave="scheduleHoverClose"
      >
        <template v-for="(item, index) in items" :key="index">
          <div v-if="item.type === 'separator'" class="openpencil-dropdown-separator" role="separator" />
          <button
            v-else-if="item.disabled || !item.safeHref"
            type="button"
            :aria-disabled="item.disabled || undefined"
            class="openpencil-dropdown-item"
            :data-openpencil-dropdown-index="index"
            :disabled="item.disabled"
            role="menuitem"
            :style="{ color: item.danger ? config.dangerColor : config.itemTextColor }"
            :tabindex="activeIndex === index ? 0 : -1"
            @click="onItemSelect(false)"
            @focus="activeIndex = index"
          >
            <span>{{ item.label }}</span><kbd v-if="item.shortcut">{{ item.shortcut }}</kbd>
          </button>
          <a
            v-else
            class="openpencil-dropdown-item"
            :data-openpencil-dropdown-index="index"
            :href="item.safeHref"
            role="menuitem"
            :style="{ color: item.danger ? config.dangerColor : config.itemTextColor }"
            :tabindex="activeIndex === index ? 0 : -1"
            @click="onItemSelect(true)"
            @focus="activeIndex = index"
          >
            <span>{{ item.label }}</span><kbd v-if="item.shortcut">{{ item.shortcut }}</kbd>
          </a>
        </template>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.openpencil-dropdown-menu{border:1px solid rgb(127 127 127 / .25);border-radius:10px;box-shadow:0 12px 36px #0f172a2e;box-sizing:border-box;display:grid;gap:2px;max-height:calc(100dvh - 16px);overflow:auto;padding:6px;position:fixed;z-index:1000}
.openpencil-dropdown-item{align-items:center;appearance:none;background:transparent;border:0;border-radius:7px;box-sizing:border-box;cursor:pointer;display:flex;font:inherit;gap:16px;justify-content:space-between;min-height:44px;outline-offset:-2px;padding:9px 12px;text-align:left;text-decoration:none;width:100%}
.openpencil-dropdown-item:hover,.openpencil-dropdown-item:focus-visible{background:rgb(127 127 127 / .15)}
.openpencil-dropdown-item:disabled{cursor:not-allowed;opacity:.45}
.openpencil-dropdown-item kbd{font:inherit;font-size:.8em;opacity:.65}
.openpencil-dropdown-separator{background:rgb(127 127 127 / .25);height:1px;margin:4px}
.openpencil-trigger-fallback{clip:rect(0 0 0 0);clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px}
.openpencil-dropdown-enter-active,.openpencil-dropdown-leave-active{transition:opacity 140ms ease,transform 140ms ease}
.openpencil-dropdown-enter-from,.openpencil-dropdown-leave-to{opacity:0;transform:translateY(-4px)}
@media (prefers-reduced-motion:reduce){.openpencil-dropdown-enter-active,.openpencil-dropdown-leave-active{transition:none}}
</style>
`

export function buildOpenPencilVueDropdownMenu(options?: VueModuleRuntimeOptions): string {
  if (!options?.microfrontend) return DROPDOWN_MENU_RUNTIME
  return DROPDOWN_MENU_RUNTIME.replace(
    "import type { CSSProperties } from 'vue'",
    "import type { CSSProperties } from 'vue'\nimport { microfrontendPortalTarget } from './__microfrontend-context'"
  )
    .replace(
      'const attrs = useAttrs()',
      "const attrs = useAttrs()\nconst portalTarget = microfrontendPortalTarget() ?? 'body'"
    )
    .replace('<Teleport to="body">', '<Teleport :to="portalTarget">')
}

export const DROPDOWN_MENU_VUE_MODULE_ADAPTER: VueModuleAdapter = Object.freeze({
  pluginId: DROPDOWN_MENU_PLUGIN_ID,
  moduleType: DROPDOWN_MENU_MODULE_TYPE,
  componentName: 'OpenPencilDropdownMenu',
  runtimePath: 'src/__openpencil_dropdown_menu.vue',
  importPath: '../__openpencil_dropdown_menu.vue',
  usesLayerRuntime: true,
  buildRuntime: buildOpenPencilVueDropdownMenu
})
