const LAYER_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])'
].join(',')

interface OpenPencilLayerEntry {
  token: symbol
  element: HTMLElement
  restoreFocus: HTMLElement | null
  locksBody: boolean
}

const layers: OpenPencilLayerEntry[] = []
let bodyLockCount = 0
let previousBodyOverflow: string | null = null

function lockBody(): void {
  if (bodyLockCount === 0) {
    previousBodyOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
  }
  bodyLockCount += 1
}

function unlockBody(): void {
  bodyLockCount = Math.max(0, bodyLockCount - 1)
  if (bodyLockCount !== 0) return
  document.body.style.overflow = previousBodyOverflow ?? ''
  previousBodyOverflow = null
}

export function registerOpenPencilLayer(
  token: symbol,
  element: HTMLElement,
  locksBody = false
): (restoreFocus?: boolean) => void {
  const existing = layers.findIndex((entry) => entry.token === token)
  if (existing >= 0) layers.splice(existing, 1)
  const entry: OpenPencilLayerEntry = {
    token,
    element,
    restoreFocus: document.activeElement instanceof HTMLElement ? document.activeElement : null,
    locksBody
  }
  layers.push(entry)
  if (locksBody) lockBody()
  let released = false
  return (restoreFocus = true) => {
    if (released) return
    released = true
    const index = layers.findIndex((candidate) => candidate.token === token)
    const wasTop = index >= 0 && index === layers.length - 1
    if (index >= 0) layers.splice(index, 1)
    if (locksBody) unlockBody()
    if (!wasTop || !restoreFocus) return
    const next = layers[layers.length - 1]
    const target = next?.element ?? entry.restoreFocus
    if (target?.isConnected) target.focus({ preventScroll: true })
  }
}

export function adjacentOpenPencilTabStop(
  trigger: HTMLElement,
  layer: HTMLElement,
  backwards: boolean
): HTMLElement | undefined {
  const candidates = [...document.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)].filter(
    (element) =>
      !layer.contains(element) &&
      element.tabIndex >= 0 &&
      !element.matches(':disabled') &&
      element.getClientRects().length > 0
  )
  if (!candidates.includes(trigger)) candidates.push(trigger)
  const ordered = candidates
    .map((element, order) => ({ element, order, tabIndex: element.tabIndex }))
    .sort((left, right) => {
      const leftPositive = left.tabIndex > 0
      const rightPositive = right.tabIndex > 0
      if (leftPositive !== rightPositive) return leftPositive ? -1 : 1
      if (leftPositive && left.tabIndex !== right.tabIndex) return left.tabIndex - right.tabIndex
      return left.order - right.order
    })
  const index = ordered.findIndex(({ element }) => element === trigger)
  return index < 0 ? undefined : ordered[index + (backwards ? -1 : 1)]?.element
}

export function isTopOpenPencilLayer(token: symbol): boolean {
  return layers[layers.length - 1]?.token === token
}

export function openPencilFocusableElements(container: HTMLElement): HTMLElement[] {
  return [...container.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)].filter(
    (element) => !element.hasAttribute('disabled') && element.getAttribute('aria-hidden') !== 'true'
  )
}

export function focusOpenPencilLayer(container: HTMLElement): void {
  ;(openPencilFocusableElements(container)[0] ?? container).focus({ preventScroll: true })
}

export function trapOpenPencilLayerTab(event: KeyboardEvent, container: HTMLElement): void {
  if (event.key !== 'Tab') return
  const focusable = openPencilFocusableElements(container)
  if (focusable.length === 0) {
    event.preventDefault()
    container.focus({ preventScroll: true })
    return
  }
  const first = focusable[0]
  const last = focusable[focusable.length - 1]
  const active = document.activeElement
  if (event.shiftKey && (active === first || active === container || !container.contains(active))) {
    event.preventDefault()
    last.focus({ preventScroll: true })
  } else if (!event.shiftKey && (active === last || !container.contains(active))) {
    event.preventDefault()
    first.focus({ preventScroll: true })
  }
}

export function safeOpenPencilHref(value: string): string | undefined {
  if (!value || value.includes('\\\\') || /[\\u0000-\\u001F\\u007F]/.test(value)) return undefined
  if (value.startsWith('/') && !value.startsWith('//')) return value
  if (value.startsWith('#') && value.length > 1) return value
  try {
    const url = new URL(value)
    const hostname = url.hostname.toLowerCase()
    const local =
      hostname.endsWith('.') ||
      ['localhost', 'localdomain', 'home.arpa'].includes(hostname) ||
      ['.localhost', '.local', '.localdomain', '.home.arpa'].some((suffix) =>
        hostname.endsWith(suffix)
      )
    const address = /^(?:\\d{1,3}\\.){3}\\d{1,3}$/.test(hostname) ||
      (hostname.startsWith('[') && hostname.endsWith(']'))
    if (
      url.protocol === 'https:' &&
      url.username === '' &&
      url.password === '' &&
      url.hash === '' &&
      (url.port === '' || url.port === '443') &&
      !local &&
      !address &&
      url.href === value
    ) return value
  } catch {
    // Invalid absolute URLs are intentionally not navigable.
  }
  return undefined
}
`

export const VUE_LAYER_RUNTIME_PATH = 'src/__openpencil_layer.ts'

export function buildVueLayerRuntime(): string {
  return LAYER_RUNTIME
}
