/* oxlint-disable open-pencil/no-hand-rolled-color -- emitted standalone CSS cannot import OpenPencil color helpers */
import { MODAL_MODULE_TYPE, MODAL_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { VueModuleAdapter } from './types'

const MODAL_RUNTIME = `<!-- Auto-generated by OpenPencil compiler. Do not edit by hand. -->
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, useAttrs, useId, watch } from 'vue'
import type { CSSProperties } from 'vue'

import {
  focusOpenPencilLayer,
  isTopOpenPencilLayer,
  registerOpenPencilLayer,
  trapOpenPencilLayerTab
} from './__openpencil_layer'

interface ModalConfig {
  triggerLabel: string
  showTriggerIcon: boolean
  showTriggerLabel: boolean
  title: string
  content: string
  showCloseButton: boolean
  closeOnBackdrop: boolean
  closeOnEscape: boolean
  showCancelButton: boolean
  cancelLabel: string
  showConfirmButton: boolean
  confirmLabel: string
  panelWidth: number
  footerAlign: 'left' | 'center' | 'right'
  panelBackground: string
  textColor: string
  accentColor: string
  overlayOpacity: number
}

defineOptions({ inheritAttrs: false })
const props = defineProps<{ config: ModalConfig }>()
const attrs = useAttrs()
const open = ref(false)
const panel = ref<HTMLElement | null>(null)
const token = Symbol('open-pencil-modal')
const baseId = useId().replaceAll(':', '')
const titleId = baseId + '-title'
const contentId = baseId + '-content'
const authoredTriggerId = baseId + '-authored-trigger'
const triggerFallbackId = baseId + '-trigger-fallback'
const authoredTriggerLabelledBy = authoredTriggerId + ' ' + triggerFallbackId
let releaseLayer: (() => void) | null = null

const disabled = computed(() => attrs.disabled !== undefined && attrs.disabled !== false)
const hostStyle: CSSProperties = {
  boxSizing: 'border-box',
  display: 'inline-flex',
  minHeight: '44px',
  minWidth: '44px',
  position: 'relative' as const
}
const triggerStyle = computed<CSSProperties>(() => ({
  alignItems: 'center',
  appearance: 'none',
  background: props.config.accentColor,
  border: 0,
  borderRadius: '8px',
  boxSizing: 'border-box',
  color: '#FFFFFF',
  cursor: disabled.value ? 'not-allowed' : 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  gap: '8px',
  height: '100%',
  justifyContent: 'center',
  minHeight: '44px',
  minWidth: '44px',
  opacity: disabled.value ? 0.5 : 1,
  outlineOffset: '2px',
  padding: '0 14px',
  touchAction: 'manipulation',
  width: '100%'
}))
const overlayTriggerStyle = computed<CSSProperties>(() => ({
  ...triggerStyle.value,
  background: 'transparent',
  color: 'inherit',
  inset: 0,
  padding: 0,
  position: 'absolute' as const,
  zIndex: 1
}))
const backdropStyle = computed<CSSProperties>(() => ({
  background: 'rgb(0 0 0 / ' + props.config.overlayOpacity + ')'
}))
const panelStyle = computed<CSSProperties>(() => ({
  background: props.config.panelBackground,
  color: props.config.textColor,
  width: 'min(' + props.config.panelWidth + 'px, calc(100vw - 32px))'
}))
const footerStyle = computed<CSSProperties>(() => ({
  justifyContent:
    props.config.footerAlign === 'left'
      ? 'flex-start'
      : props.config.footerAlign === 'center'
        ? 'center'
        : 'flex-end'
}))

function show(): void {
  if (!disabled.value) open.value = true
}

function close(): void {
  open.value = false
}

function onBackdrop(event: MouseEvent): void {
  if (event.target === event.currentTarget && props.config.closeOnBackdrop) close()
}

function onPanelKeydown(event: KeyboardEvent): void {
  const element = panel.value
  if (!element || !isTopOpenPencilLayer(token)) return
  if (event.key === 'Escape' && props.config.closeOnEscape) {
    event.preventDefault()
    event.stopPropagation()
    close()
    return
  }
  trapOpenPencilLayerTab(event, element)
}

watch(open, async (value) => {
  if (!value) {
    releaseLayer?.()
    releaseLayer = null
    return
  }
  await nextTick()
  if (!open.value || !panel.value) return
  releaseLayer?.()
  releaseLayer = registerOpenPencilLayer(token, panel.value, true)
  focusOpenPencilLayer(panel.value)
})

onBeforeUnmount(() => releaseLayer?.())
</script>

<template>
  <div v-bind="$attrs" data-openpencil-modal-host="" :style="hostStyle">
    <div
      v-if="$slots.default"
      :id="authoredTriggerId"
      aria-hidden="true"
      data-openpencil-modal-authored-trigger=""
      inert
      style="align-items:center;display:inline-flex;height:100%;justify-content:center;max-width:100%;min-width:0;pointer-events:none;width:100%"
    >
      <slot />
    </div>
    <button
      type="button"
      :aria-expanded="open"
      aria-haspopup="dialog"
      :aria-label="$slots.default ? undefined : config.triggerLabel"
      :aria-labelledby="$slots.default ? authoredTriggerLabelledBy : undefined"
      :disabled="disabled"
      :style="$slots.default ? overlayTriggerStyle : triggerStyle"
      @click="show"
    >
      <span
        v-if="$slots.default"
        :id="triggerFallbackId"
        class="openpencil-trigger-fallback"
      >{{ config.triggerLabel }}</span>
      <template v-if="!$slots.default">
        <svg
          v-if="config.showTriggerIcon"
          aria-hidden="true"
          focusable="false"
          style="height:18px;width:18px"
          viewBox="0 0 24 24"
        >
          <rect fill="none" height="16" rx="2" stroke="currentColor" stroke-width="2" width="18" x="3" y="4" />
          <path d="M3 9H21" fill="none" stroke="currentColor" stroke-width="2" />
        </svg>
        <span v-if="config.showTriggerLabel">{{ config.triggerLabel }}</span>
      </template>
    </button>
  </div>

  <Teleport to="body">
    <Transition name="openpencil-modal">
      <div
        v-if="open"
        data-openpencil-modal-backdrop=""
        :style="backdropStyle"
        class="openpencil-modal-backdrop"
        @click="onBackdrop"
      >
        <section
          ref="panel"
          aria-modal="true"
          :aria-describedby="contentId"
          :aria-labelledby="titleId"
          class="openpencil-modal-panel"
          data-openpencil-modal-panel=""
          role="dialog"
          :style="panelStyle"
          tabindex="-1"
          @keydown="onPanelKeydown"
        >
          <header class="openpencil-modal-header">
            <h2 :id="titleId">{{ config.title }}</h2>
            <button
              v-if="config.showCloseButton"
              type="button"
              aria-label="Close dialog"
              class="openpencil-modal-close"
              @click="close"
            >
              <svg aria-hidden="true" focusable="false" viewBox="0 0 24 24">
                <path d="M6 6L18 18M18 6L6 18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2" />
              </svg>
            </button>
          </header>
          <p :id="contentId" class="openpencil-modal-content">{{ config.content }}</p>
          <footer
            v-if="config.showCancelButton || config.showConfirmButton"
            class="openpencil-modal-footer"
            :style="footerStyle"
          >
            <button v-if="config.showCancelButton" type="button" class="openpencil-modal-action" @click="close">
              {{ config.cancelLabel }}
            </button>
            <button
              v-if="config.showConfirmButton"
              type="button"
              class="openpencil-modal-action openpencil-modal-confirm"
              :style="{ background: config.accentColor }"
              @click="close"
            >
              {{ config.confirmLabel }}
            </button>
          </footer>
        </section>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.openpencil-modal-backdrop{align-items:center;display:flex;inset:0;justify-content:center;padding:16px;position:fixed;z-index:1000}
.openpencil-modal-panel{border:0;border-radius:12px;box-shadow:0 24px 80px #00000040;box-sizing:border-box;max-height:calc(100dvh - 32px);overflow:auto;padding:24px;outline:none}
.openpencil-modal-header{align-items:start;display:grid;gap:16px;grid-template-columns:minmax(0,1fr) auto}
.openpencil-modal-header h2{font-size:1.25rem;line-height:1.4;margin:0;overflow-wrap:anywhere}
.openpencil-modal-content{line-height:1.5;margin:16px 0 0;overflow-wrap:anywhere;white-space:pre-wrap}
.openpencil-modal-close,.openpencil-modal-action{appearance:none;background:transparent;border:1px solid currentColor;border-radius:8px;color:inherit;cursor:pointer;font:inherit;min-height:44px;min-width:44px;outline-offset:2px;padding:10px 16px}
.openpencil-modal-close{align-items:center;border:0;display:inline-flex;justify-content:center;padding:10px;width:44px}
.openpencil-modal-close svg{height:24px;width:24px}
.openpencil-modal-footer{display:flex;flex-wrap:wrap;gap:8px;margin-top:24px}
.openpencil-modal-confirm{border-color:transparent;color:#fff;font-weight:600}
.openpencil-trigger-fallback{clip:rect(0 0 0 0);clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px}
.openpencil-modal-enter-active,.openpencil-modal-leave-active{transition:opacity 180ms ease}
.openpencil-modal-enter-from,.openpencil-modal-leave-to{opacity:0}
@media (prefers-reduced-motion:reduce){.openpencil-modal-enter-active,.openpencil-modal-leave-active{transition:none}}
</style>
`

export function buildOpenPencilVueModal(): string {
  return MODAL_RUNTIME
}

export const MODAL_VUE_MODULE_ADAPTER: VueModuleAdapter = Object.freeze({
  pluginId: MODAL_PLUGIN_ID,
  moduleType: MODAL_MODULE_TYPE,
  componentName: 'OpenPencilModal',
  runtimePath: 'src/__openpencil_modal.vue',
  importPath: '../__openpencil_modal.vue',
  usesLayerRuntime: true,
  buildRuntime: buildOpenPencilVueModal
})
