/* oxlint-disable open-pencil/no-hand-rolled-color -- emitted standalone CSS cannot import OpenPencil color helpers */
import { SLIDE_MENU_MODULE_TYPE, SLIDE_MENU_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { VueModuleAdapter } from './types'

const SLIDE_MENU_RUNTIME = `<!-- Auto-generated by OpenPencil compiler. Do not edit by hand. -->
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, useAttrs, useId, watch } from 'vue'
import type { CSSProperties } from 'vue'

import {
  focusOpenPencilLayer,
  isTopOpenPencilLayer,
  registerOpenPencilLayer,
  safeOpenPencilHref,
  trapOpenPencilLayerTab
} from './__openpencil_layer'

interface SlideMenuItem { label: string; href: string }
interface SlideMenuConfig {
  presentation: 'menu' | 'dialog'
  direction: 'left' | 'right' | 'top' | 'bottom'
  triggerLabel: string
  showTriggerIcon: boolean
  showTriggerLabel: boolean
  title: string
  description: string
  items: readonly SlideMenuItem[]
  closeOnBackdrop: boolean
  showCloseButton: boolean
  panelSize: number
  panelBackground: string
  textColor: string
  overlayOpacity: number
}

defineOptions({ inheritAttrs: false })
const props = defineProps<{ config: SlideMenuConfig }>()
const attrs = useAttrs()
const open = ref(false)
const panel = ref<HTMLElement | null>(null)
const token = Symbol('open-pencil-slide-menu')
const baseId = useId().replaceAll(':', '')
const titleId = baseId + '-title'
const descriptionId = baseId + '-description'
const authoredTriggerId = baseId + '-authored-trigger'
const triggerFallbackId = baseId + '-trigger-fallback'
const authoredTriggerLabelledBy = authoredTriggerId + ' ' + triggerFallbackId
let releaseLayer: (() => void) | null = null

const disabled = computed(() => attrs.disabled !== undefined && attrs.disabled !== false)
const items = computed(() =>
  props.config.items.map((item) => ({ ...item, safeHref: safeOpenPencilHref(item.href) }))
)
const hostStyle: CSSProperties = {
  boxSizing: 'border-box',
  display: 'inline-flex',
  minHeight: '44px',
  minWidth: '44px',
  position: 'relative' as const
}
const triggerStyle = computed<CSSProperties>(() => ({
  alignItems: 'center',
  appearance: 'none',
  background: '#2563EB',
  border: 0,
  borderRadius: '8px',
  boxSizing: 'border-box',
  color: '#FFFFFF',
  cursor: disabled.value ? 'not-allowed' : 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  gap: '8px',
  height: '100%',
  justifyContent: 'center',
  minHeight: '44px',
  minWidth: '44px',
  opacity: disabled.value ? 0.5 : 1,
  outlineOffset: '2px',
  padding: '0 14px',
  touchAction: 'manipulation',
  width: '100%'
}))
const overlayTriggerStyle = computed<CSSProperties>(() => ({
  ...triggerStyle.value,
  background: 'transparent',
  color: 'inherit',
  inset: 0,
  padding: 0,
  position: 'absolute' as const,
  zIndex: 1
}))
const backdropStyle = computed<CSSProperties>(() => ({
  background: 'rgb(0 0 0 / ' + props.config.overlayOpacity + ')'
}))

function closedTransform(): string {
  if (props.config.presentation === 'dialog') {
    if (props.config.direction === 'left') return 'translate(calc(-50% - 48px), -50%)'
    if (props.config.direction === 'right') return 'translate(calc(-50% + 48px), -50%)'
    if (props.config.direction === 'top') return 'translate(-50%, calc(-50% - 48px))'
    return 'translate(-50%, calc(-50% + 48px))'
  }
  if (props.config.direction === 'left') return 'translate3d(-100%, 0, 0)'
  if (props.config.direction === 'right') return 'translate3d(100%, 0, 0)'
  if (props.config.direction === 'top') return 'translate3d(0, -100%, 0)'
  return 'translate3d(0, 100%, 0)'
}

const panelStyle = computed<CSSProperties>(() => {
  const size = props.config.panelSize + 'px'
  const base = {
    '--openpencil-slide-closed': closedTransform(),
    background: props.config.panelBackground,
    color: props.config.textColor
  }
  if (props.config.presentation === 'dialog') {
    return {
      ...base,
      left: '50%',
      maxHeight: 'calc(100dvh - 32px)',
      top: '50%',
      transform: 'translate(-50%, -50%)',
      width: 'min(' + size + ', calc(100vw - 32px))'
    }
  }
  const bounded = 'min(' + size + ', calc(100dvh - 16px))'
  if (props.config.direction === 'left') {
    return { ...base, height: '100dvh', left: 0, top: 0, width: 'min(' + size + ', calc(100vw - 16px))' }
  }
  if (props.config.direction === 'right') {
    return { ...base, height: '100dvh', right: 0, top: 0, width: 'min(' + size + ', calc(100vw - 16px))' }
  }
  if (props.config.direction === 'top') return { ...base, height: bounded, left: 0, top: 0, width: '100vw' }
  return { ...base, bottom: 0, height: bounded, left: 0, width: '100vw' }
})

function show(): void {
  if (!disabled.value) open.value = true
}

function close(): void {
  open.value = false
}

function onBackdrop(event: MouseEvent): void {
  if (event.target === event.currentTarget && props.config.closeOnBackdrop) close()
}

function onPanelKeydown(event: KeyboardEvent): void {
  const element = panel.value
  if (!element || !isTopOpenPencilLayer(token)) return
  if (event.key === 'Escape') {
    event.preventDefault()
    event.stopPropagation()
    close()
    return
  }
  trapOpenPencilLayerTab(event, element)
}

watch(open, async (value) => {
  if (!value) {
    releaseLayer?.()
    releaseLayer = null
    return
  }
  await nextTick()
  if (!open.value || !panel.value) return
  releaseLayer?.()
  releaseLayer = registerOpenPencilLayer(token, panel.value, true)
  focusOpenPencilLayer(panel.value)
})

onBeforeUnmount(() => releaseLayer?.())
</script>

<template>
  <div v-bind="$attrs" data-openpencil-slide-menu-host="" :style="hostStyle">
    <div
      v-if="$slots.default"
      :id="authoredTriggerId"
      aria-hidden="true"
      data-openpencil-slide-menu-authored-trigger=""
      inert
      style="align-items:center;display:inline-flex;height:100%;justify-content:center;max-width:100%;min-width:0;pointer-events:none;width:100%"
    >
      <slot />
    </div>
    <button
      type="button"
      :aria-controls="baseId + '-panel'"
      :aria-expanded="open"
      aria-haspopup="dialog"
      :aria-label="$slots.default ? undefined : config.triggerLabel"
      :aria-labelledby="$slots.default ? authoredTriggerLabelledBy : undefined"
      :disabled="disabled"
      :style="$slots.default ? overlayTriggerStyle : triggerStyle"
      @click="show"
    >
      <span
        v-if="$slots.default"
        :id="triggerFallbackId"
        class="openpencil-trigger-fallback"
      >{{ config.triggerLabel }}</span>
      <template v-if="!$slots.default">
        <span v-if="config.showTriggerIcon" aria-hidden="true" class="openpencil-slide-icon">
          <i /><i /><i />
        </span>
        <span v-if="config.showTriggerLabel">{{ config.triggerLabel }}</span>
      </template>
    </button>
  </div>

  <Teleport to="body">
    <Transition name="openpencil-slide">
      <div
        v-if="open"
        data-openpencil-slide-menu-backdrop=""
        :style="backdropStyle"
        class="openpencil-slide-backdrop"
        @click="onBackdrop"
      >
        <section
          :id="baseId + '-panel'"
          ref="panel"
          aria-modal="true"
          :aria-describedby="descriptionId"
          :aria-labelledby="titleId"
          class="openpencil-slide-panel"
          data-openpencil-slide-menu-panel=""
          role="dialog"
          :style="panelStyle"
          tabindex="-1"
          @keydown="onPanelKeydown"
        >
          <header class="openpencil-slide-header">
            <div>
              <h2 :id="titleId">{{ config.title }}</h2>
              <p :id="descriptionId">{{ config.description }}</p>
            </div>
            <button
              v-if="config.showCloseButton"
              type="button"
              aria-label="Close menu"
              class="openpencil-slide-close"
              @click="close"
            >
              <svg aria-hidden="true" focusable="false" viewBox="0 0 24 24">
                <path d="M6 6L18 18M18 6L6 18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2" />
              </svg>
            </button>
          </header>
          <nav aria-label="Menu links">
            <ul class="openpencil-slide-list">
              <li v-for="(item, index) in items" :key="index">
                <a v-if="item.safeHref" :href="item.safeHref" @click="close">{{ item.label }}</a>
                <button v-else type="button" @click="close">{{ item.label }}</button>
              </li>
            </ul>
          </nav>
        </section>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.openpencil-slide-icon{display:inline-flex;flex-direction:column;gap:4px;height:14px;justify-content:center;width:18px}
.openpencil-slide-icon i{background:currentColor;display:block;height:2px;width:18px}
.openpencil-slide-backdrop{inset:0;position:fixed;z-index:1000}
.openpencil-slide-panel{border:0;box-shadow:0 24px 80px #00000040;box-sizing:border-box;overflow:auto;padding:24px;position:absolute;outline:none}
.openpencil-slide-header{align-items:start;display:grid;gap:16px;grid-template-columns:minmax(0,1fr) auto;margin-bottom:24px}
.openpencil-slide-header h2{font-size:1.25rem;line-height:1.4;margin:0;overflow-wrap:anywhere}
.openpencil-slide-header p{line-height:1.5;margin:8px 0 0;overflow-wrap:anywhere;white-space:pre-wrap}
.openpencil-slide-close{align-items:center;appearance:none;background:transparent;border:0;border-radius:8px;color:inherit;cursor:pointer;display:inline-flex;height:44px;justify-content:center;min-width:44px;outline-offset:2px;padding:10px;width:44px}
.openpencil-slide-close svg{height:24px;width:24px}
.openpencil-slide-list{display:grid;gap:4px;list-style:none;margin:0;padding:0}
.openpencil-slide-list a,.openpencil-slide-list button{appearance:none;background:transparent;border:0;border-radius:8px;box-sizing:border-box;color:inherit;cursor:pointer;display:flex;font:inherit;min-height:44px;outline-offset:2px;padding:10px 12px;text-align:left;text-decoration:none;width:100%}
.openpencil-slide-list a:hover,.openpencil-slide-list button:hover{background:rgb(127 127 127 / .15)}
.openpencil-trigger-fallback{clip:rect(0 0 0 0);clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;white-space:nowrap;width:1px}
.openpencil-slide-enter-active,.openpencil-slide-leave-active{transition:background-color 220ms ease}
.openpencil-slide-enter-active .openpencil-slide-panel,.openpencil-slide-leave-active .openpencil-slide-panel{transition:opacity 220ms ease,transform 220ms ease}
.openpencil-slide-enter-from .openpencil-slide-panel,.openpencil-slide-leave-to .openpencil-slide-panel{opacity:0;transform:var(--openpencil-slide-closed)}
@media (prefers-reduced-motion:reduce){.openpencil-slide-enter-active,.openpencil-slide-leave-active,.openpencil-slide-enter-active .openpencil-slide-panel,.openpencil-slide-leave-active .openpencil-slide-panel{transition:none}}
</style>
`

export function buildOpenPencilVueSlideMenu(): string {
  return SLIDE_MENU_RUNTIME
}

export const SLIDE_MENU_VUE_MODULE_ADAPTER: VueModuleAdapter = Object.freeze({
  pluginId: SLIDE_MENU_PLUGIN_ID,
  moduleType: SLIDE_MENU_MODULE_TYPE,
  componentName: 'OpenPencilSlideMenu',
  runtimePath: 'src/__openpencil_slide_menu.vue',
  importPath: '../__openpencil_slide_menu.vue',
  usesLayerRuntime: true,
  buildRuntime: buildOpenPencilVueSlideMenu
})
