import type { IRDocStateDecl } from '#compiler/ir/types'
import type { CompilerOptions } from '#compiler/types'

import { safeNativeStateDefault } from '../native-shared'

const EXPO_VERSION = '~57.0.10'
const REACT_VERSION = '19.2.3'
const REACT_NATIVE_VERSION = '0.86.2'
const EXPO_ROUTER_VERSION = '~57.0.10'

export function buildExpoPackageJson(options: CompilerOptions, router: boolean): string {
  const dependencies: Record<string, string> = {
    expo: EXPO_VERSION,
    react: REACT_VERSION,
    'react-native': REACT_NATIVE_VERSION,
    'react-native-safe-area-context': '~5.7.0'
  }
  if (router) {
    dependencies['expo-constants'] = '~57.0.9'
    dependencies['expo-linking'] = '~57.0.5'
    dependencies['expo-router'] = EXPO_ROUTER_VERSION
    dependencies['expo-status-bar'] = '~57.0.1'
    dependencies['react-native-screens'] = '~4.26.0'
  }
  return `${JSON.stringify(
    {
      name: safePackageName(options.packageName),
      version: '0.0.0',
      private: true,
      engines: { node: '>=22.13.0' },
      main: router ? 'expo-router/entry' : 'expo/AppEntry',
      scripts: {
        start: 'expo start',
        android: 'expo start --android',
        ios: 'expo start --ios',
        typecheck: 'tsc --noEmit'
      },
      dependencies,
      devDependencies: { '@types/react': '~19.2.2', typescript: '~6.0.3' }
    },
    null,
    2
  )}\n`
}

export function buildExpoAppJson(options: CompilerOptions, router: boolean): string {
  const packageName = safePackageName(options.packageName)
  const scheme = safeExpoScheme(packageName)
  const productName = options.productName?.trim() || options.packageName.trim() || 'OpenPencil App'
  const expo = {
    name: productName,
    slug: packageName,
    version: '1.0.0',
    orientation: 'default',
    userInterfaceStyle: 'automatic',
    newArchEnabled: true,
    ...(router ? { scheme, plugins: ['expo-router'] } : {})
  }
  return `${JSON.stringify({ expo }, null, 2)}\n`
}

export function buildExpoTsConfig(): string {
  return `${JSON.stringify(
    {
      extends: 'expo/tsconfig.base',
      compilerOptions: {
        strict: true,
        paths: { '@/*': ['./src/*'] }
      },
      include: ['**/*.ts', '**/*.tsx', '.expo/types/**/*.ts', 'expo-env.d.ts']
    },
    null,
    2
  )}\n`
}

export function buildExpoGitignore(): string {
  return [
    'node_modules',
    '.expo',
    'dist',
    '*.jks',
    '*.p8',
    '*.p12',
    '*.key',
    '*.mobileprovision',
    ''
  ].join('\n')
}

export function buildExpoReadme(router: boolean): string {
  return `# OpenPencil Expo export

This directory contains source code generated by OpenPencil's Expo static MVP. It is not a signed or installable application bundle.

## Run locally

Expo SDK 57 requires Node.js 22.13 or newer.

\`\`\`sh
npm install
npm run typecheck
npx expo start
\`\`\`

Open the project in Expo Go or an iOS/Android simulator from the Expo development server.${
    router
      ? ' Pages are wired through Expo Router under `app/`.'
      : ' This export uses a single `App.tsx` entry without a navigation router.'
  }

## Static MVP boundary

Supported output includes native \`View\`, \`Text\`, \`Image\`/\`ImageBackground\`, \`Pressable\`, \`TextInput\`, and \`Switch\` primitives; basic layout, color, border, typography, and image styles; bundled static images; basic local/document state; simple actions;${
    router ? ' and multi-page Expo Router routes.' : ' and one static page.'
  }

The exporter currently degrades these features to static fallbacks and reports warnings: map/chart/rich-text plugin modules, raw SVG/vector markup, motion and generated effects, uploads, Supabase/server workflows, analytics/Stripe flows, persistence, advanced validation/forms/overlays, responsive/hover/CSS-only styling, and web-specific compiler options.

OpenPencil generated these source files only. It did not run \`npm install\`, \`expo prebuild\`, Gradle, Xcode, signing, or a device/simulator build. Run the commands above and review export warnings before shipping.
`
}

export function buildExpoFontStub(): string {
  return `/** Replaced with an expo-font hook when a native font manifest is supplied. */
export function useOpenPencilFonts(): boolean {
  return true
}
`
}

export function buildExpoRootApp(): string {
  return `import { SafeAreaProvider } from 'react-native-safe-area-context'

import { useOpenPencilFonts } from './src/generated-fonts'
import Page from './src/pages/index'

export default function App() {
  const fontsReady = useOpenPencilFonts()
  if (!fontsReady) return null
  return (
    <SafeAreaProvider>
      <Page />
    </SafeAreaProvider>
  )
}
`
}

export function buildExpoRouterLayout(): string {
  return `import { Stack } from 'expo-router'
import { SafeAreaProvider } from 'react-native-safe-area-context'

import { useOpenPencilFonts } from '../src/generated-fonts'

export default function RootLayout() {
  const fontsReady = useOpenPencilFonts()
  if (!fontsReady) return null
  return (
    <SafeAreaProvider>
      <Stack screenOptions={{ headerShown: false }} />
    </SafeAreaProvider>
  )
}
`
}

export function buildExpoRouteProxy(routeFile: string, pageSlug: string): string {
  const depth = routeFile.split('/').length - 1
  const prefix = '../'.repeat(depth)
  return `export { default } from '${prefix}src/pages/${pageSlug}'\n`
}

export function buildExpoDocumentState(states: readonly IRDocStateDecl[]): string {
  const defaults = Object.fromEntries(
    states.map((state) => [state.name, safeNativeStateDefault(state)])
  )
  return `import { useSyncExternalStore } from 'react'

const values: Record<string, unknown> = ${JSON.stringify(defaults, null, 2)}
const listeners = new Set<() => void>()

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => listeners.delete(listener)
}

export function getDocState<T>(name: string): T {
  return values[name] as T
}

export function useDocState<T>(name: string): T {
  return useSyncExternalStore(subscribe, () => getDocState<T>(name), () => getDocState<T>(name))
}

export function setDocState<T>(name: string, next: T | ((previous: T) => T)): void {
  const previous = getDocState<T>(name)
  values[name] = typeof next === 'function' ? (next as (value: T) => T)(previous) : next
  for (const listener of listeners) listener()
}
`
}

function safePackageName(value: string): string {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return normalized || 'openpencil-expo-app'
}

function safeExpoScheme(packageName: string): string {
  const normalized = packageName.replaceAll('_', '-')
  return /^[a-z]/.test(normalized) ? normalized : `openpencil-${normalized}`
}
