/** Extra catalog semantics are hashed only for extended schemas, preserving prior plain receipts. */
export const MANAGED_CATALOG_SOURCE = String.raw`
async function extendedCatalog(client, schema) {
  if (!schema.some((table) => table.catalog)) return []
  if (schema.some((table) => !table.catalog || !Array.isArray(table.catalog.enums) || !Array.isArray(table.catalog.constraints) || !Array.isArray(table.catalog.indexes))) fail('Managed preview extended catalog is invalid.')
  const enums = (await client.query("SELECT t.typname AS name,t.typtype AS kind,pg_get_userbyid(t.typowner) AS owner,t.typacl::text AS acl,coalesce(array_agg(e.enumlabel::text ORDER BY e.enumsortorder) FILTER(WHERE e.enumlabel IS NOT NULL),ARRAY[]::text[]) AS labels FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace LEFT JOIN pg_enum e ON e.enumtypid=t.oid WHERE n.nspname='public' AND t.typtype<>'c' AND t.typcategory<>'A' GROUP BY t.oid,t.typname,t.typtype,t.typowner,t.typacl ORDER BY t.typname")).rows
  exact(enums.map((row) => JSON.stringify([row.name,row.kind,row.owner,row.labels])), schema.flatMap((table) => table.catalog.enums.map((entry) => JSON.stringify([entry.name,'e','openpencil_admin',entry.labels]))))
  const constraints = (await client.query("SELECT c.relname AS table_name,k.conname AS name,k.contype AS kind,ARRAY(SELECT a.attname::text FROM unnest(k.conkey) WITH ORDINALITY p(attnum,position) JOIN pg_attribute a ON a.attrelid=k.conrelid AND a.attnum=p.attnum ORDER BY p.position) AS columns,coalesce(r.relname,'') AS target_table,coalesce(rn.nspname,'') AS target_schema,ARRAY(SELECT a.attname::text FROM unnest(k.confkey) WITH ORDINALITY p(attnum,position) JOIN pg_attribute a ON a.attrelid=k.confrelid AND a.attnum=p.attnum ORDER BY p.position) AS target_columns,k.confdeltype AS delete_action,k.confupdtype AS update_action,k.confmatchtype AS match_type,k.condeferrable AS deferrable,k.condeferred AS deferred,k.convalidated AS validated FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_class r ON r.oid=k.confrelid LEFT JOIN pg_namespace rn ON rn.oid=r.relnamespace WHERE n.nspname='public' ORDER BY c.relname,k.conname")).rows
  exact(constraints.map((row) => JSON.stringify([row.table_name,row.name,row.kind,row.columns,row.target_table,row.target_schema,row.target_columns,row.delete_action,row.update_action,row.match_type,row.deferrable,row.deferred,row.validated])), schema.flatMap((table) => table.catalog.constraints.map((entry) => JSON.stringify([table.name,entry.name,entry.kind,entry.columns,entry.targetTable ?? '',entry.kind==='f'?'public':'',entry.targetColumns ?? [],entry.deleteAction ?? ' ',entry.kind==='f'?'a':' ',entry.kind==='f'?'s':' ',false,false,true]))))
  const indexes = (await client.query("SELECT t.relname AS table_name,c.relname AS name,a.amname AS method,ARRAY(SELECT at.attname::text FROM unnest(i.indkey) WITH ORDINALITY p(attnum,position) JOIN pg_attribute at ON at.attrelid=i.indrelid AND at.attnum=p.attnum ORDER BY p.position) AS columns,i.indoption::int2[] AS options,i.indisunique AS is_unique,i.indisprimary AS is_primary,i.indisvalid AS valid,i.indisready AS ready,i.indnkeyatts=i.indnatts AS no_include,i.indpred IS NULL AS no_predicate,i.indexprs IS NULL AS no_expression,NOT i.indnullsnotdistinct AS distinct_nulls,i.indimmediate AS immediate,NOT EXISTS(SELECT 1 FROM unnest(i.indclass) o(oid) JOIN pg_opclass op ON op.oid=o.oid JOIN pg_namespace ns ON ns.oid=op.opcnamespace WHERE NOT op.opcdefault OR ns.nspname<>'pg_catalog') AS default_opclass FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace JOIN pg_am a ON a.oid=c.relam WHERE n.nspname='public' ORDER BY t.relname,c.relname")).rows
  exact(indexes.map((row) => JSON.stringify([row.table_name,row.name,row.method,row.columns,row.options,row.is_unique,row.is_primary,row.valid,row.ready,row.no_include,row.no_predicate,row.no_expression,row.distinct_nulls,row.immediate,row.default_opclass])), schema.flatMap((table) => table.catalog.indexes.map((entry) => JSON.stringify([table.name,entry.name,'btree',entry.columns,entry.options,entry.unique,entry.primary,true,true,true,true,true,true,true,true]))))
  return [enums,constraints,indexes]
}
`
