import { walkNativeNodes } from '#compiler/adapters/native-shared'
import type { ComponentDef, IRTree } from '#compiler/ir/types'
import { sha256 } from '@noble/hashes/sha2'
import { bytesToHex } from '@noble/hashes/utils'

import {
  VR_TOUR_MODULE_TYPE,
  VR_TOUR_PLUGIN_ID,
  resolveVRTourModule
} from '@open-pencil/core/plugins'

import { VR_TOUR_DEPENDENCIES, VR_TOUR_RUNTIME_SOURCE } from '../source'
import { collectHybridAssets } from './assets'
import { VR_TOUR_HYBRID_BUILD, VR_TOUR_HYBRID_OWNERSHIP_FILE } from './build'
import { VR_TOUR_HYBRID_ENTRY } from './entry'

export type VRTourHybridTarget = 'expo' | 'flutter' | 'taro'

export interface VRTourHybridEmission {
  files: Map<string, string | Uint8Array>
  tourIds: ReadonlySet<string>
}

export function vrTourHybridKey(sourceId: string): string {
  return 'tour-' + bytesToHex(sha256(new TextEncoder().encode(sourceId))).slice(0, 32)
}

/** Source-only preparation. No compiler-side bundling, downloads or arbitrary executable config. */
export function emitVRTourHybridProject(
  irs: readonly IRTree[],
  components: readonly ComponentDef[],
  target: VRTourHybridTarget
): VRTourHybridEmission {
  const files = new Map<string, string | Uint8Array>()
  const tours = new Map<string, { key: string; config: Record<string, unknown> }>()
  const roots = [...irs, ...components]
  for (const root of roots) {
    const nodes =
      'variants' in root && root.variants?.length
        ? root.variants.flatMap((variant) => variant.children)
        : root.children
    walkNativeNodes(nodes, (node) => {
      if (node.kind !== 'element') return
      const module = node.module
      if (
        !module ||
        module.pluginId !== VR_TOUR_PLUGIN_ID ||
        module.moduleType !== VR_TOUR_MODULE_TYPE ||
        Object.hasOwn(module, 'panoramaUrlExpr')
      )
        return
      const resolved = resolveVRTourModule({
        version: 1,
        pluginId: module.pluginId,
        moduleType: module.moduleType,
        configVersion: module.configVersion,
        config: module.payload
      })
      if (!resolved?.ok) return
      const key = vrTourHybridKey(node.sourceId)
      const config = structuredClone(module.payload)
      const previous = tours.get(node.sourceId)
      if (previous && JSON.stringify(previous.config) !== JSON.stringify(config))
        throw new Error('Conflicting VR tour source identity')
      tours.set(node.sourceId, { key, config })
    })
  }
  const tourIds = new Set(tours.keys())
  if (!tours.size) return { files, tourIds }
  if (tours.size > 100) throw new RangeError('VR hybrid export supports at most 100 tours')
  const assets = collectHybridAssets(
    roots,
    [...tours.values()].map((tour) => tour.config),
    files
  )
  files.set(
    'vr-tour-web/package.json',
    JSON.stringify(
      {
        name: 'openpencil-vr-tour-web',
        private: true,
        type: 'module',
        scripts: { build: 'node build.mjs' },
        dependencies: VR_TOUR_DEPENDENCIES,
        devDependencies: { esbuild: '0.28.2' }
      },
      null,
      2
    ) + '\n'
  )
  files.set(
    'vr-tour-web/manifest.json',
    JSON.stringify(
      {
        version: 1,
        target,
        tours: [...tours].map(([sourceId, tour]) => ({ sourceId, ...tour })),
        assets
      },
      null,
      2
    ) + '\n'
  )
  files.set('vr-tour-web/runtime.ts', VR_TOUR_RUNTIME_SOURCE)
  files.set('vr-tour-web/entry.ts', VR_TOUR_HYBRID_ENTRY)
  files.set('vr-tour-web/build.mjs', VR_TOUR_HYBRID_BUILD)
  files.set('vr-tour-web/.gitignore', 'node_modules/\ndist/\n')
  files.set('vr-tour-web/README.md', hybridReadme(target))
  if (target === 'expo')
    files.set(
      'src/vr-tour-html.ts',
      '// Generated by node vr-tour-web/build.mjs.\nexport const vrTourHtmlById: Readonly<Record<string, string>> = {}\n'
    )
  if (target === 'flutter') {
    const placeholder =
      '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body><p role="alert">全景播放器尚未准备。请先运行 node vr-tour-web/build.mjs。 Panorama is not prepared; run node vr-tour-web/build.mjs before launching.</p></body></html>'
    const owned: Array<{ path: string; sha256: string }> = []
    for (const tour of tours.values()) {
      const path = `${tour.key}.html`
      files.set(`assets/vr-tour/${path}`, placeholder)
      owned.push({ path, sha256: bytesToHex(sha256(new TextEncoder().encode(placeholder))) })
    }
    files.set(
      `assets/vr-tour/${VR_TOUR_HYBRID_OWNERSHIP_FILE}`,
      JSON.stringify({ version: 1, files: owned }, null, 2) + '\n'
    )
  }
  return { files, tourIds }
}

function hybridReadme(target: VRTourHybridTarget): string {
  const output = {
    expo: 'Output: src/vr-tour-html.ts. The Expo start/android/ios scripts prepare it before launching.',
    flutter:
      'Output: assets/vr-tour/*.html. Rebuild before flutter run whenever tour configuration or images change.',
    taro: 'Output: vr-tour-web/dist/*.html. Deploy this directory to HTTPS, configure the WeChat business domain, and set the exported VR_TOUR_BASE_URL. No deployment happens during export or build.'
  }[target]
  return `# VR Tour WebView preparation / 全景播放器准备

This directory contains the reviewed Photo Sphere Viewer runtime and authored static tour data.
It is an explicit WebView component; the surrounding exported pages remain native.

From the exported project root, use Node.js 22 or newer:

\`\`\`sh
${target === 'expo' ? 'npm install' : 'npm install --prefix vr-tour-web'}
node vr-tour-web/build.mjs
\`\`\`

${output}

The HTML bundles local JavaScript, CSS and referenced saved images. No script CDN or runtime npm download is used.
Saved images are losslessly chunked in assets/ only to keep source archive files bounded. The build verifies and reassembles them.
Image downloads still require the user to select Load panorama; external HTTPS images also require CORS.
Unbundled /assets/vr-tour/ images show an actionable error; add their chunks and manifest entries before rebuilding, or use an allowed HTTPS image.
The renderer limits decoded display width to 4096 pixels for mobile GPU use while preserving the original source files. This is not a universal device-memory guarantee.
Dynamic panoramaUrl bindings remain blocked in these source-only adapters. Use the React/Vue export for live rental-backend bindings.
Gyroscope/headset support is not included. Android/iOS WebView and WeChat account/domain/device acceptance remain post-export checks.
Pages dispose the viewer on pagehide. Native wrappers also release the surface when leaving/backgrounding it.

全景播放器与已保存素材一起打包，界面沿用文档语言。请在运行原生项目之前完成上面的准备命令。
微信小程序还需要自行部署 HTTPS 网页、配置业务域名；个人类型小程序不能使用 web-view。
这两张住宅示例是不同住宅，不代表同一套房的相邻房间。素材来源见 SOURCES.json（如有）。
`
}
