/* oxlint-disable eslint/max-lines -- This builder emits one self-contained, dependency-free runtime module. */
// The contents of `src/__preview-bridge.ts` that each web adapter writes
// into a dev-mode preview project. The file is a plain template literal —
// the compiler is Bun/Node-only, but the runtime it emits ships to the
// in-iframe preview build and gets compiled by Vite there.
//
// Contract with PreviewPane.vue (docs/lowcode-phase-0.md §5.4 + Phase 2 §7):
//
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'select',   id }
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'navigate', route }
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'theme',    theme }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'select',   id }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'navigate', route }
//
// Every payload also carries the per-frame `channel` written into the
// iframe's browsing-context name by PreviewPane. The generated runtime reads
// the expected parent origin from that one-time boot context before Browser
// Preview clears it, so the bridge never uses a wildcard postMessage target.
//
// `id` is `null` when nothing is selected; otherwise the SceneNode id that
// the web adapter emitted as `data-node-id`. The iframe runtime only
// surrenders a click to the editor when the user is holding Alt/Option —
// plain clicks still flow to the user's onClick handlers so the live
// preview keeps working as an app, not just a static highlight target.
//
// Phase 2 §7: `navigate` rides the same channel so the editor and the
// iframe's History API router stay in sync. Inbound `navigate` drives
// `history.pushState` + a synthetic `popstate` (the way to programmatically
// route in any history-API router from outside React). Outbound `navigate`
// fires from a `history.pushState` monkeypatch (react-router-dom's nav goes
// through pushState without firing popstate) plus a `popstate` listener
// (back/forward). A `suppressOutbound` flag breaks the echo loop on inbound.
//
// A separately gated WebDriver channel exists only inside this dev bridge.
// The parent must opt the frame into it through the one-time boot context;
// commands remain source/origin/channel bound and can only use exact bounded
// test locators. Responses never expose form values or network material.

export function buildPreviewBridge(options: { readonly documentState?: boolean } = {}): string {
  return `// Auto-generated by OpenPencil compiler — canvas↔preview bridge.
// Only emitted when CompilerOptions.devMode is true.

const INBOUND_SOURCE = 'op-lowcode-editor'
const OUTBOUND_SOURCE = 'op-lowcode-preview'
const CHANNEL_PROTOCOL = 'open-pencil-preview-v2'
const MAX_CHANNEL_LENGTH = 128
const MAX_NODE_ID_LENGTH = 512
const MAX_ROUTE_LENGTH = 2048
const MAX_DOC_STATE_NAME_LENGTH = 128
const MAX_DOC_STATE_VALUES = 4096
const MAX_DOC_STATE_STRING_LENGTH = 65536
const MAX_PORTABLE_MESSAGE_BYTES = 256 * 1024
const MAX_MOTION_DEBUG_ENTRIES = 256
const MAX_AUTOMATION_REQUEST_ID_LENGTH = 128
const MAX_AUTOMATION_LOCATOR_LENGTH = 512
const MAX_AUTOMATION_INPUT_LENGTH = 4096
const MAX_AUTOMATION_TEXT_LENGTH = 8192
const MAX_AUTOMATION_TIMEOUT_MS = 15000
const MAX_AUTOMATION_SCAN_ELEMENTS = 4096
const MAX_AUTOMATION_REQUESTS = 8
// Backend preview data belongs to the runtime, never the document or collaboration channel.
const MIRROR_DOCUMENT_STATE = ${options.documentState !== false}
// Editor-only preview selection chrome. Keep these fixed, high-contrast colors
// independent from generated app theme tokens so the canvas↔preview bridge is
// readable even when the user design overrides runtime CSS variables.
const PREVIEW_SELECTION_OVERLAY_BORDER = '2px solid #4c8bf5'
const PREVIEW_SELECTION_OVERLAY_BACKGROUND = '#4c8bf514'

interface DocStore {
  getState: () => Record<string, unknown>
  setState: (partial: Record<string, unknown>) => void
  subscribe: (
    listener: (state: Record<string, unknown>, prev: Record<string, unknown>) => void
  ) => () => void
}

declare global {
  interface Window {
    __openPencilPreviewBridge?: boolean
    __openPencilPreviewPort?: MessagePort | null
    // Phase 3 §4.6 — the adapter-owned lowcode docState store, exposed by
    // the generated state module so the bridge can mirror state across peers.
    __opDocStore?: DocStore
  }
}

interface InboundSelect {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'select'
  id: string | null
}
interface InboundNavigate {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'navigate'
  route: string
}
interface InboundDocState {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'docState'
  name: string
  value: unknown
}
interface InboundTheme {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'theme'
  theme: 'light' | 'dark'
}
interface InboundMotionDebug {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'motionDebug'
  enabled: boolean
}
type AutomationLocator = 'testId' | 'buttonText' | 'placeholder' | 'body'
type AutomationError =
  | 'ambiguous-target'
  | 'forbidden-target'
  | 'invalid-request'
  | 'not-found'
  | 'not-visible'
  | 'operation-failed'
  | 'scan-limit'

interface InboundAutomationBase {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'automation'
  requestId: string
}
interface InboundAutomationClick extends InboundAutomationBase {
  action: 'click'
  by: 'testId' | 'buttonText'
  locator: string
}
interface InboundAutomationSet extends InboundAutomationBase {
  action: 'set'
  by: 'testId' | 'placeholder'
  locator: string
  value: string
}
interface InboundAutomationWait extends InboundAutomationBase {
  action: 'wait'
  by: AutomationLocator
  locator: string
  text: string | null
  timeoutMs: number
}
interface InboundAutomationRead extends InboundAutomationBase {
  action: 'read-safe-text'
  by: AutomationLocator
  locator: string
}
type InboundAutomation =
  | InboundAutomationClick
  | InboundAutomationSet
  | InboundAutomationWait
  | InboundAutomationRead
type Inbound =
  | InboundSelect
  | InboundNavigate
  | InboundDocState
  | InboundTheme
  | InboundMotionDebug
  | InboundAutomation

interface PreviewFrameContext {
  protocol: typeof CHANNEL_PROTOCOL
  channel: string
  parentOrigin: string
  transport: 'window' | 'message-port'
  automation: boolean
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function hasExactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean {
  const keys = Object.keys(value)
  return keys.length === expected.length && keys.every((key) => expected.includes(key))
}

function readFrameContext(): PreviewFrameContext | null {
  try {
    const candidate: unknown = JSON.parse(window.name)
    if (!isRecord(candidate)) return null
    const legacyContext = hasExactKeys(candidate, [
      'protocol',
      'channel',
      'parentOrigin',
      'transport'
    ])
    const automationContext = hasExactKeys(candidate, [
      'protocol',
      'channel',
      'parentOrigin',
      'transport',
      'automation'
    ])
    if (!legacyContext && !automationContext) return null
    if (
      candidate.protocol !== CHANNEL_PROTOCOL ||
      typeof candidate.channel !== 'string' ||
      candidate.channel.length < 16 ||
      candidate.channel.length > MAX_CHANNEL_LENGTH ||
      !/^[A-Za-z0-9_-]+$/.test(candidate.channel) ||
      typeof candidate.parentOrigin !== 'string' ||
      (candidate.transport !== 'window' && candidate.transport !== 'message-port') ||
      (automationContext && typeof candidate.automation !== 'boolean')
    ) {
      return null
    }
    const parsed = new URL(candidate.parentOrigin)
    const canonicalTauriOrigin = candidate.parentOrigin === 'tauri://localhost'
    if (
      !canonicalTauriOrigin &&
      (parsed.origin !== candidate.parentOrigin || parsed.username || parsed.password)
    ) {
      return null
    }
    return {
      protocol: CHANNEL_PROTOCOL,
      channel: candidate.channel,
      parentOrigin: candidate.parentOrigin,
      transport: candidate.transport,
      automation: automationContext && candidate.automation === true
    }
  } catch {
    return null
  }
}

function allowsAutomationContext(context: PreviewFrameContext): boolean {
  if (!import.meta.env.DEV) return false
  if (!context.automation || context.transport !== 'window') return false
  if (context.parentOrigin === 'tauri://localhost') return true
  try {
    const parsed = new URL(context.parentOrigin)
    return (
      parsed.protocol === 'http:' &&
      (parsed.hostname === 'localhost' || parsed.hostname === '127.0.0.1') &&
      parsed.port !== ''
    )
  } catch {
    return false
  }
}

function validRoute(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length > 0 &&
    value.length <= MAX_ROUTE_LENGTH &&
    value.startsWith('/') &&
    !value.startsWith('//') &&
    !value.includes('\\\\') &&
    !/[\\u0000-\\u001f\\u007f]/.test(value)
  )
}

function validDocStateValue(value: unknown): boolean {
  const pending: unknown[] = [value]
  const seen = new Set<object>()
  let values = 0
  let bytes = 0
  while (pending.length > 0) {
    const current = pending.pop()
    values += 1
    if (values > MAX_DOC_STATE_VALUES) return false
    if (
      current === null ||
      typeof current === 'boolean' ||
      (typeof current === 'number' && Number.isFinite(current))
    ) {
      bytes += 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      continue
    }
    if (typeof current === 'string') {
      if (current.length > MAX_DOC_STATE_STRING_LENGTH) return false
      bytes += current.length * 2
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      continue
    }
    if (!isRecord(current) && !Array.isArray(current)) return false
    if (seen.has(current)) return false
    seen.add(current)
    if (Array.isArray(current)) {
      bytes += current.length * 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      pending.push(...current)
      continue
    }
    if (Object.getOwnPropertySymbols(current).length > 0) return false
    const descriptors = Object.getOwnPropertyDescriptors(current)
    for (const [key, descriptor] of Object.entries(descriptors)) {
      if (
        key.length > MAX_DOC_STATE_NAME_LENGTH ||
        !descriptor.enumerable ||
        !Object.hasOwn(descriptor, 'value')
      ) {
        return false
      }
      bytes += key.length * 2 + 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      pending.push(descriptor.value)
    }
  }
  return true
}

function validMotionDebugSnapshot(value: unknown): boolean {
  if (!isRecord(value)) return false
  const entries = Object.getOwnPropertyDescriptor(value, 'entries')?.value
  return (
    Array.isArray(entries) &&
    entries.length <= MAX_MOTION_DEBUG_ENTRIES &&
    validDocStateValue(value)
  )
}

function validAutomationRequestId(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length >= 16 &&
    value.length <= MAX_AUTOMATION_REQUEST_ID_LENGTH &&
    /^[A-Za-z0-9_-]+$/.test(value)
  )
}

function validAutomationLocator(by: unknown, locator: unknown): by is AutomationLocator {
  if (
    by !== 'testId' &&
    by !== 'buttonText' &&
    by !== 'placeholder' &&
    by !== 'body'
  ) {
    return false
  }
  if (typeof locator !== 'string') return false
  if (by === 'body') return locator === ''
  return (
    locator.length > 0 &&
    locator.length <= MAX_AUTOMATION_LOCATOR_LENGTH &&
    !/[\\u0000-\\u001f\\u007f]/.test(locator)
  )
}

function parseAutomationInbound(value: Record<string, unknown>): InboundAutomation | null {
  if (!validAutomationRequestId(value.requestId)) return null
  if (value.action === 'click') {
    if (
      !hasExactKeys(value, [
        'source',
        'channel',
        'type',
        'requestId',
        'action',
        'by',
        'locator'
      ]) ||
      (value.by !== 'testId' && value.by !== 'buttonText') ||
      !validAutomationLocator(value.by, value.locator)
    ) {
      return null
    }
    return value as unknown as InboundAutomationClick
  }
  if (value.action === 'set') {
    if (
      !hasExactKeys(value, [
        'source',
        'channel',
        'type',
        'requestId',
        'action',
        'by',
        'locator',
        'value'
      ]) ||
      (value.by !== 'testId' && value.by !== 'placeholder') ||
      !validAutomationLocator(value.by, value.locator) ||
      typeof value.value !== 'string' ||
      value.value.length > MAX_AUTOMATION_INPUT_LENGTH
    ) {
      return null
    }
    return value as unknown as InboundAutomationSet
  }
  if (value.action === 'wait') {
    if (
      !hasExactKeys(value, [
        'source',
        'channel',
        'type',
        'requestId',
        'action',
        'by',
        'locator',
        'text',
        'timeoutMs'
      ]) ||
      !validAutomationLocator(value.by, value.locator) ||
      (value.text !== null &&
        (typeof value.text !== 'string' ||
          value.text.length === 0 ||
          value.text.length > MAX_AUTOMATION_INPUT_LENGTH ||
          /[\\u0000-\\u001f\\u007f]/.test(value.text))) ||
      !Number.isSafeInteger(value.timeoutMs) ||
      (value.timeoutMs as number) < 0 ||
      (value.timeoutMs as number) > MAX_AUTOMATION_TIMEOUT_MS
    ) {
      return null
    }
    return value as unknown as InboundAutomationWait
  }
  if (value.action === 'read-safe-text') {
    if (
      !hasExactKeys(value, [
        'source',
        'channel',
        'type',
        'requestId',
        'action',
        'by',
        'locator'
      ]) ||
      !validAutomationLocator(value.by, value.locator)
    ) {
      return null
    }
    return value as unknown as InboundAutomationRead
  }
  return null
}

function parseInbound(value: unknown, channel: string): Inbound | null {
  if (!isRecord(value) || value.source !== INBOUND_SOURCE || value.channel !== channel) return null
  if (value.type === 'select' && hasExactKeys(value, ['source', 'channel', 'type', 'id'])) {
    return value.id === null ||
      (typeof value.id === 'string' && value.id.length > 0 && value.id.length <= MAX_NODE_ID_LENGTH)
      ? (value as unknown as InboundSelect)
      : null
  }
  if (value.type === 'navigate' && hasExactKeys(value, ['source', 'channel', 'type', 'route'])) {
    return validRoute(value.route) ? (value as unknown as InboundNavigate) : null
  }
  if (
    value.type === 'docState' &&
    hasExactKeys(value, ['source', 'channel', 'type', 'name', 'value']) &&
    typeof value.name === 'string' &&
    value.name.length > 0 &&
    value.name.length <= MAX_DOC_STATE_NAME_LENGTH &&
    validDocStateValue(value.value)
  ) {
    return value as unknown as InboundDocState
  }
  if (value.type === 'theme' && hasExactKeys(value, ['source', 'channel', 'type', 'theme'])) {
    return value.theme === 'light' || value.theme === 'dark'
      ? (value as unknown as InboundTheme)
      : null
  }
  if (
    value.type === 'motionDebug' &&
    hasExactKeys(value, ['source', 'channel', 'type', 'enabled']) &&
    typeof value.enabled === 'boolean'
  ) {
    return value as unknown as InboundMotionDebug
  }
  if (value.type === 'automation') return parseAutomationInbound(value)
  return null
}

const frameContext = typeof window === 'undefined' ? null : readFrameContext()

if (typeof window !== 'undefined' && frameContext && !window.__openPencilPreviewBridge) {
  window.__openPencilPreviewBridge = true

  function postToParent(payload: Record<string, unknown>): void {
    if (frameContext.transport === 'message-port') {
      window.__openPencilPreviewPort?.postMessage({
        ...payload,
        source: OUTBOUND_SOURCE,
        channel: frameContext.channel
      })
      return
    }
    window.parent.postMessage(
      { ...payload, source: OUTBOUND_SOURCE, channel: frameContext.channel },
      frameContext.parentOrigin
    )
  }

  const overlay = document.createElement('div')
  overlay.setAttribute('data-op-preview-overlay', '')
  overlay.style.position = 'fixed'
  overlay.style.left = '0px'
  overlay.style.top = '0px'
  overlay.style.width = '0px'
  overlay.style.height = '0px'
  overlay.style.pointerEvents = 'none'
  overlay.style.border = PREVIEW_SELECTION_OVERLAY_BORDER
  overlay.style.background = PREVIEW_SELECTION_OVERLAY_BACKGROUND
  overlay.style.boxSizing = 'border-box'
  overlay.style.zIndex = '2147483647'
  overlay.style.display = 'none'
  overlay.style.transition = 'all 80ms linear'
  document.documentElement.appendChild(overlay)

  let currentId: string | null = null
  // §7 decision #f: suppress outbound navigate while replaying an inbound
  // navigate, so the editor→iframe→editor echo loop never fires.
  let suppressOutbound = false
  let motionDebugTimer: ReturnType<typeof setInterval> | null = null

  function postMotionDebug(
    status: 'ready' | 'unavailable' | 'error',
    snapshot?: unknown,
    error?: string
  ): void {
    postToParent({ type: 'motionDebug', status, snapshot, error })
  }

  function inspectMotion(): void {
    const runtime = (
      window as Window & {
        __OPENPENCIL_MOTION_RUNTIME__?: { inspect?: () => unknown }
      }
    ).__OPENPENCIL_MOTION_RUNTIME__
    if (!runtime || typeof runtime.inspect !== 'function') {
      postMotionDebug('unavailable')
      return
    }
    try {
      const snapshot = runtime.inspect()
      if (!validMotionDebugSnapshot(snapshot)) {
        postMotionDebug('error', undefined, 'Motion diagnostics exceed the preview safety limit.')
        return
      }
      postMotionDebug('ready', snapshot)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      postMotionDebug('error', undefined, message.slice(0, MAX_DOC_STATE_STRING_LENGTH))
    }
  }

  function setMotionDebugEnabled(enabled: boolean): void {
    if (motionDebugTimer !== null) {
      clearInterval(motionDebugTimer)
      motionDebugTimer = null
    }
    if (!enabled) return
    inspectMotion()
    motionDebugTimer = setInterval(inspectMotion, 250)
  }

  // PreviewPane owns the theme control for both generated web targets. Keep
  // the DOM contract framework-neutral and explicit so Tailwind's class-based
  // dark mode, data-theme selectors, and native form controls all agree.
  function applyTheme(theme: 'light' | 'dark'): void {
    const root = document.documentElement
    root.dataset.theme = theme
    root.classList.toggle('light', theme === 'light')
    root.classList.toggle('dark', theme === 'dark')
    root.style.colorScheme = theme
  }

  // Alias the real pushState BEFORE patching, so the patch can forward
  // calls (including our own replay) without re-entering itself.
  const nativePushState = history.pushState.bind(history)

  function updateOverlay(): void {
    if (!currentId) {
      overlay.style.display = 'none'
      return
    }
    const el = document.querySelector(
      \`[data-node-id="\${CSS.escape(currentId)}"]\`
    ) as HTMLElement | null
    if (!el) {
      overlay.style.display = 'none'
      return
    }
    const r = el.getBoundingClientRect()
    overlay.style.display = 'block'
    overlay.style.left = \`\${r.left}px\`
    overlay.style.top = \`\${r.top}px\`
    overlay.style.width = \`\${r.width}px\`
    overlay.style.height = \`\${r.height}px\`
  }

  function postOutboundNavigate(route: string): void {
    if (suppressOutbound) return
    if (validRoute(route)) postToParent({ type: 'navigate', route })
  }

  // Client routers call history.pushState directly and do NOT dispatch
  // popstate; patching pushState observes navigation without coupling the
  // bridge to either React or Vue.
  history.pushState = function (
    this: History,
    ...args: Parameters<typeof history.pushState>
  ): void {
    nativePushState(...args)
    postOutboundNavigate(location.pathname)
  } as typeof history.pushState

  // popstate covers browser back/forward + our own synthetic dispatch.
  window.addEventListener('popstate', () => {
    postOutboundNavigate(location.pathname)
  })

  // Phase 3 §4.6 — runtime docState collaboration. Mirror the generated
  // store's per-key changes across peers. suppressDocStateOutbound breaks the
  // remote→setState→subscribe→outbound echo, mirroring suppressOutbound above.
  let suppressDocStateOutbound = false

  function wireDocStore(store: DocStore): void {
    if (!MIRROR_DOCUMENT_STATE) return
    store.subscribe((state, prev) => {
      if (suppressDocStateOutbound) return
      for (const name of Object.keys(state)) {
        if (state[name] !== prev[name]) {
          if (
            name.length > 0 &&
            name.length <= MAX_DOC_STATE_NAME_LENGTH &&
            validDocStateValue(state[name])
          ) {
            postToParent({ type: 'docState', name: name, value: state[name] })
          }
        }
      }
    })
  }

  // The generated state module may evaluate before or after this bridge; cover both —
  // wire now if the store is already up, else wait for its ready event.
  if (window.__opDocStore) {
    wireDocStore(window.__opDocStore)
  } else {
    window.addEventListener(
      'op-docstore-ready',
      () => {
        if (window.__opDocStore) wireDocStore(window.__opDocStore)
      },
      { once: true }
    )
  }

  interface AutomationTargetResult {
    element: HTMLElement | null
    error: AutomationError | null
  }

  const automationRequestIds = new Set<string>()
  const automationRequestOrder: string[] = []
  let activeAutomationRequests = 0

  function postAutomationResult(
    requestId: string,
    ok: boolean,
    status: 'clicked' | 'set' | 'matched' | 'read' | 'rejected' | 'timeout',
    text: string | null,
    error: AutomationError | null
  ): void {
    postToParent({ type: 'automationResult', requestId, ok, status, text, error })
  }

  function rememberAutomationRequest(requestId: string): boolean {
    if (automationRequestIds.has(requestId)) return false
    automationRequestIds.add(requestId)
    automationRequestOrder.push(requestId)
    if (automationRequestOrder.length > 128) {
      const oldest = automationRequestOrder.shift()
      if (oldest) automationRequestIds.delete(oldest)
    }
    return true
  }

  function normalizedText(value: string): string {
    return value.trim().split(/\\s+/).join(' ')
  }

  function elementVisible(element: HTMLElement): boolean {
    if (element.hidden || element.closest('[hidden],[aria-hidden="true"]')) return false
    const style = getComputedStyle(element)
    if (style.display === 'none' || style.visibility === 'hidden' || style.opacity === '0') {
      return false
    }
    const rect = element.getBoundingClientRect()
    return rect.width > 0 && rect.height > 0
  }

  const AUTOMATION_NATIVE_CONTROL_SELECTOR =
    'a[href],button,input,textarea,select,option,optgroup,datalist,fieldset,legend,label,output,progress,meter,details,summary'
  const AUTOMATION_PRIVATE_TEXT_SELECTOR =
    'script,style,noscript,template,[contenteditable]:not([contenteditable="false"]),[role~="textbox" i],[data-op-sensitive]'

  function safeVisibleText(root: HTMLElement, allowButtonRoot = false): string {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
    const parts: string[] = []
    let bytes = 0
    let visited = 0
    while (walker.nextNode()) {
      visited += 1
      if (visited > MAX_AUTOMATION_SCAN_ELEMENTS) break
      const parent = walker.currentNode.parentElement
      const nativeControl = parent?.closest(AUTOMATION_NATIVE_CONTROL_SELECTOR)
      if (
        !parent ||
        parent.isContentEditable ||
        parent.closest(AUTOMATION_PRIVATE_TEXT_SELECTOR) ||
        (nativeControl !== null &&
          !(allowButtonRoot && root instanceof HTMLButtonElement && nativeControl === root)) ||
        !elementVisible(parent)
      ) {
        continue
      }
      const text = normalizedText(walker.currentNode.nodeValue ?? '')
      if (!text) continue
      const remaining = MAX_AUTOMATION_TEXT_LENGTH - bytes
      if (remaining <= 0) break
      parts.push(text.slice(0, remaining))
      bytes += Math.min(text.length, remaining)
    }
    return normalizedText(parts.join(' ')).slice(0, MAX_AUTOMATION_TEXT_LENGTH)
  }

  function readableAutomationTextTarget(
    element: HTMLElement,
    by: AutomationLocator,
    locator: string
  ): boolean {
    if (by !== 'testId' || element === document.body || element === document.documentElement) {
      return false
    }
    const exactTestId =
      element.getAttribute('data-testid') === locator ||
      element.getAttribute('data-test-id') === locator
    if (!exactTestId && !element.hasAttribute('data-op-automation-readable')) return false
    return (
      !element.isContentEditable &&
      element.closest(AUTOMATION_PRIVATE_TEXT_SELECTOR) === null &&
      element.closest(AUTOMATION_NATIVE_CONTROL_SELECTOR) === null
    )
  }

  function scannedElements(selector: string): HTMLElement[] | AutomationError {
    const nodes = document.querySelectorAll(selector)
    if (nodes.length > MAX_AUTOMATION_SCAN_ELEMENTS) return 'scan-limit'
    const elements: HTMLElement[] = []
    for (const node of nodes) {
      if (node instanceof HTMLElement) elements.push(node)
    }
    return elements
  }

  function findAutomationTarget(by: AutomationLocator, locator: string): AutomationTargetResult {
    if (by === 'body') {
      return document.body
        ? { element: document.body, error: null }
        : { element: null, error: 'not-found' }
    }
    const selector =
      by === 'buttonText'
        ? 'button'
        : by === 'placeholder'
          ? 'input[placeholder],textarea[placeholder]'
          : '[data-testid],[data-test-id],[data-node-id]'
    const scanned = scannedElements(selector)
    if (!Array.isArray(scanned)) return { element: null, error: scanned }
    const matches = scanned.filter((element) => {
      if (by === 'buttonText') return safeVisibleText(element, true) === locator
      if (by === 'placeholder') return element.getAttribute('placeholder') === locator
      return (
        element.getAttribute('data-testid') === locator ||
        element.getAttribute('data-test-id') === locator ||
        element.getAttribute('data-node-id') === locator
      )
    })
    if (matches.length === 0) return { element: null, error: 'not-found' }
    if (matches.length !== 1) return { element: null, error: 'ambiguous-target' }
    return { element: matches[0] ?? null, error: null }
  }

  function forbiddenSetTarget(element: HTMLElement): boolean {
    if (!(element instanceof HTMLInputElement) && !(element instanceof HTMLTextAreaElement)) {
      return true
    }
    if (element.disabled || element.readOnly) return true
    if (element instanceof HTMLInputElement) {
      const type = element.type.toLowerCase()
      if (type === 'password' || type === 'email' || type === 'file' || type === 'hidden') {
        return true
      }
    }
    const sensitiveMarker = [
      element.autocomplete,
      element.getAttribute('name') ?? '',
      element.id,
      element.getAttribute('placeholder') ?? ''
    ].join(' ')
    return /(password|passcode|secret|token|one[- ]?time|otp|verification code)/i.test(
      sensitiveMarker
    )
  }

  function setAutomationText(element: HTMLInputElement | HTMLTextAreaElement, value: string): void {
    const prototype =
      element instanceof HTMLTextAreaElement
        ? HTMLTextAreaElement.prototype
        : HTMLInputElement.prototype
    const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set
    if (!setter) throw new Error('Missing native value setter')
    setter.call(element, value)
    element.dispatchEvent(new Event('input', { bubbles: true, composed: true }))
    element.dispatchEvent(new Event('change', { bubbles: true, composed: true }))
  }

  async function waitForAutomation(data: InboundAutomationWait): Promise<void> {
    if (data.text !== null && data.by !== 'testId') {
      postAutomationResult(data.requestId, false, 'rejected', null, 'forbidden-target')
      return
    }
    const deadline = Date.now() + data.timeoutMs
    while (true) {
      const result = findAutomationTarget(data.by, data.locator)
      if (result.element && elementVisible(result.element)) {
        if (
          data.text !== null &&
          !readableAutomationTextTarget(result.element, data.by, data.locator)
        ) {
          postAutomationResult(data.requestId, false, 'rejected', null, 'forbidden-target')
          return
        }
        const matchesText =
          data.text === null || safeVisibleText(result.element).includes(data.text)
        if (matchesText) {
          postAutomationResult(data.requestId, true, 'matched', null, null)
          return
        }
      } else if (
        result.error !== null &&
        result.error !== 'not-found' &&
        result.error !== 'not-visible'
      ) {
        postAutomationResult(data.requestId, false, 'rejected', null, result.error)
        return
      }
      if (Date.now() >= deadline) {
        postAutomationResult(data.requestId, false, 'timeout', null, 'not-found')
        return
      }
      await new Promise<void>((resolve) => setTimeout(resolve, 50))
    }
  }

  async function runAutomation(data: InboundAutomation): Promise<void> {
    if (!allowsAutomationContext(frameContext)) return
    if (!rememberAutomationRequest(data.requestId)) {
      postAutomationResult(data.requestId, false, 'rejected', null, 'invalid-request')
      return
    }
    if (activeAutomationRequests >= MAX_AUTOMATION_REQUESTS) {
      postAutomationResult(data.requestId, false, 'rejected', null, 'operation-failed')
      return
    }
    activeAutomationRequests += 1
    try {
      if (data.action === 'wait') {
        await waitForAutomation(data)
        return
      }
      const result = findAutomationTarget(data.by, data.locator)
      if (!result.element) {
        postAutomationResult(
          data.requestId,
          false,
          'rejected',
          null,
          result.error ?? 'not-found'
        )
        return
      }
      if (!elementVisible(result.element)) {
        postAutomationResult(data.requestId, false, 'rejected', null, 'not-visible')
        return
      }
      if (data.action === 'read-safe-text') {
        if (!readableAutomationTextTarget(result.element, data.by, data.locator)) {
          postAutomationResult(data.requestId, false, 'rejected', null, 'forbidden-target')
          return
        }
        postAutomationResult(
          data.requestId,
          true,
          'read',
          safeVisibleText(result.element),
          null
        )
        return
      }
      if (data.action === 'set') {
        if (forbiddenSetTarget(result.element)) {
          postAutomationResult(data.requestId, false, 'rejected', null, 'forbidden-target')
          return
        }
        setAutomationText(result.element as HTMLInputElement | HTMLTextAreaElement, data.value)
        postAutomationResult(data.requestId, true, 'set', null, null)
        return
      }
      const disabled =
        (result.element instanceof HTMLButtonElement && result.element.disabled) ||
        result.element.getAttribute('aria-disabled') === 'true' ||
        result.element.closest('[inert]') !== null
      if (disabled) {
        postAutomationResult(data.requestId, false, 'rejected', null, 'forbidden-target')
        return
      }
      result.element.click()
      postAutomationResult(data.requestId, true, 'clicked', null, null)
    } catch {
      postAutomationResult(data.requestId, false, 'rejected', null, 'operation-failed')
    } finally {
      activeAutomationRequests -= 1
    }
  }

  function handleInbound(data: Inbound): void {
    if (data.type === 'select') {
      currentId = typeof data.id === 'string' ? data.id : null
      updateOverlay()
      return
    }
    if (data.type === 'navigate') {
      const route = data.route
      // No-op if the iframe is already at this route — avoids stray
      // outbound traffic on init or on duplicate page-id watcher fires.
      if (location.pathname === route) return
      suppressOutbound = true
      try {
        nativePushState(null, '', route)
        window.dispatchEvent(new PopStateEvent('popstate'))
      } finally {
        suppressOutbound = false
      }
      return
    }
    if (data.type === 'docState') {
      if (!MIRROR_DOCUMENT_STATE) return
      const store = window.__opDocStore
      if (!store) return
      if (!Object.hasOwn(store.getState(), data.name)) return
      // Apply the remote value without re-broadcasting it back out.
      suppressDocStateOutbound = true
      try {
        store.setState({ [data.name]: data.value })
      } finally {
        suppressDocStateOutbound = false
      }
      return
    }
    if (data.type === 'theme') {
      if (data.theme !== 'light' && data.theme !== 'dark') return
      applyTheme(data.theme)
      return
    }
    if (data.type === 'motionDebug') {
      setMotionDebugEnabled(data.enabled === true)
      return
    }
    if (data.type === 'automation') void runAutomation(data)
  }

  if (frameContext.transport === 'message-port') {
    const port = window.__openPencilPreviewPort
    if (port) {
      port.addEventListener('message', (event: MessageEvent) => {
        const data = parseInbound(event.data, frameContext.channel)
        if (data) handleInbound(data)
      })
      port.start()
      window.addEventListener('pagehide', () => port.close(), { once: true })
    }
  } else {
    window.addEventListener('message', (event: MessageEvent) => {
      if (event.source !== window.parent) return
      if (event.origin !== frameContext.parentOrigin) return
      const data = parseInbound(event.data, frameContext.channel)
      if (data) handleInbound(data)
    })
  }

  // Alt/Option-click is the "select in canvas" affordance — plain clicks pass
  // through so the user's onClick handlers still fire as in any real app.
  document.addEventListener(
    'click',
    (event) => {
      if (!event.altKey) return
      const target = event.target as Element | null
      const host = target?.closest('[data-node-id]') as HTMLElement | null
      const id = host?.dataset.nodeId
      if (!id) return
      event.preventDefault()
      event.stopPropagation()
      if (id.length <= MAX_NODE_ID_LENGTH) postToParent({ type: 'select', id })
    },
    true
  )

  window.addEventListener('scroll', updateOverlay, true)
  window.addEventListener('resize', updateOverlay)

  // Re-derive the overlay rect every frame while highlighted so HMR-induced
  // layout shifts don't strand the box on stale coordinates.
  function tick(): void {
    if (currentId) updateOverlay()
    requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

export {}
`
}
