// The contents of `src/__preview-bridge.ts` that each web adapter writes
// into a dev-mode preview project. The file is a plain template literal —
// the compiler is Bun/Node-only, but the runtime it emits ships to the
// in-iframe preview build and gets compiled by Vite there.
//
// Contract with PreviewPane.vue (docs/lowcode-phase-0.md §5.4 + Phase 2 §7):
//
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'select',   id }
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'navigate', route }
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'theme',    theme }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'select',   id }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'navigate', route }
//
// Every payload also carries the per-frame `channel` written into the
// iframe's browsing-context name by PreviewPane. The generated runtime reads
// the expected parent origin from that one-time boot context before Browser
// Preview clears it, so the bridge never uses a wildcard postMessage target.
//
// `id` is `null` when nothing is selected; otherwise the SceneNode id that
// the web adapter emitted as `data-node-id`. The iframe runtime only
// surrenders a click to the editor when the user is holding Alt/Option —
// plain clicks still flow to the user's onClick handlers so the live
// preview keeps working as an app, not just a static highlight target.
//
// Phase 2 §7: `navigate` rides the same channel so the editor and the
// iframe's History API router stay in sync. Inbound `navigate` drives
// `history.pushState` + a synthetic `popstate` (the way to programmatically
// route in any history-API router from outside React). Outbound `navigate`
// fires from a `history.pushState` monkeypatch (react-router-dom's nav goes
// through pushState without firing popstate) plus a `popstate` listener
// (back/forward). A `suppressOutbound` flag breaks the echo loop on inbound.

export function buildPreviewBridge(): string {
  return `// Auto-generated by OpenPencil compiler — canvas↔preview bridge.
// Only emitted when CompilerOptions.devMode is true.

const INBOUND_SOURCE = 'op-lowcode-editor'
const OUTBOUND_SOURCE = 'op-lowcode-preview'
const CHANNEL_PROTOCOL = 'open-pencil-preview-v2'
const MAX_CHANNEL_LENGTH = 128
const MAX_NODE_ID_LENGTH = 512
const MAX_ROUTE_LENGTH = 2048
const MAX_DOC_STATE_NAME_LENGTH = 128
const MAX_DOC_STATE_VALUES = 4096
const MAX_DOC_STATE_STRING_LENGTH = 65536
const MAX_PORTABLE_MESSAGE_BYTES = 256 * 1024
const MAX_MOTION_DEBUG_ENTRIES = 256
// Editor-only preview selection chrome. Keep these fixed, high-contrast colors
// independent from generated app theme tokens so the canvas↔preview bridge is
// readable even when the user design overrides runtime CSS variables.
const PREVIEW_SELECTION_OVERLAY_BORDER = '2px solid #4c8bf5'
const PREVIEW_SELECTION_OVERLAY_BACKGROUND = '#4c8bf514'

interface DocStore {
  getState: () => Record<string, unknown>
  setState: (partial: Record<string, unknown>) => void
  subscribe: (
    listener: (state: Record<string, unknown>, prev: Record<string, unknown>) => void
  ) => () => void
}

declare global {
  interface Window {
    __openPencilPreviewBridge?: boolean
    __openPencilPreviewPort?: MessagePort | null
    // Phase 3 §4.6 — the adapter-owned lowcode docState store, exposed by
    // the generated state module so the bridge can mirror state across peers.
    __opDocStore?: DocStore
  }
}

interface InboundSelect {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'select'
  id: string | null
}
interface InboundNavigate {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'navigate'
  route: string
}
interface InboundDocState {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'docState'
  name: string
  value: unknown
}
interface InboundTheme {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'theme'
  theme: 'light' | 'dark'
}
interface InboundMotionDebug {
  source: typeof INBOUND_SOURCE
  channel: string
  type: 'motionDebug'
  enabled: boolean
}
type Inbound =
  | InboundSelect
  | InboundNavigate
  | InboundDocState
  | InboundTheme
  | InboundMotionDebug

interface PreviewFrameContext {
  protocol: typeof CHANNEL_PROTOCOL
  channel: string
  parentOrigin: string
  transport: 'window' | 'message-port'
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function hasExactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean {
  const keys = Object.keys(value)
  return keys.length === expected.length && keys.every((key) => expected.includes(key))
}

function readFrameContext(): PreviewFrameContext | null {
  try {
    const candidate: unknown = JSON.parse(window.name)
    if (
      !isRecord(candidate) ||
      !hasExactKeys(candidate, ['protocol', 'channel', 'parentOrigin', 'transport'])
    ) {
      return null
    }
    if (
      candidate.protocol !== CHANNEL_PROTOCOL ||
      typeof candidate.channel !== 'string' ||
      candidate.channel.length < 16 ||
      candidate.channel.length > MAX_CHANNEL_LENGTH ||
      !/^[A-Za-z0-9_-]+$/.test(candidate.channel) ||
      typeof candidate.parentOrigin !== 'string' ||
      (candidate.transport !== 'window' && candidate.transport !== 'message-port')
    ) {
      return null
    }
    const parsed = new URL(candidate.parentOrigin)
    const canonicalTauriOrigin = candidate.parentOrigin === 'tauri://localhost'
    if (
      !canonicalTauriOrigin &&
      (parsed.origin !== candidate.parentOrigin || parsed.username || parsed.password)
    ) {
      return null
    }
    return {
      protocol: CHANNEL_PROTOCOL,
      channel: candidate.channel,
      parentOrigin: candidate.parentOrigin,
      transport: candidate.transport
    }
  } catch {
    return null
  }
}

function validRoute(value: unknown): value is string {
  return (
    typeof value === 'string' &&
    value.length > 0 &&
    value.length <= MAX_ROUTE_LENGTH &&
    value.startsWith('/') &&
    !value.startsWith('//') &&
    !value.includes('\\\\') &&
    !/[\\u0000-\\u001f\\u007f]/.test(value)
  )
}

function validDocStateValue(value: unknown): boolean {
  const pending: unknown[] = [value]
  const seen = new Set<object>()
  let values = 0
  let bytes = 0
  while (pending.length > 0) {
    const current = pending.pop()
    values += 1
    if (values > MAX_DOC_STATE_VALUES) return false
    if (
      current === null ||
      typeof current === 'boolean' ||
      (typeof current === 'number' && Number.isFinite(current))
    ) {
      bytes += 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      continue
    }
    if (typeof current === 'string') {
      if (current.length > MAX_DOC_STATE_STRING_LENGTH) return false
      bytes += current.length * 2
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      continue
    }
    if (!isRecord(current) && !Array.isArray(current)) return false
    if (seen.has(current)) return false
    seen.add(current)
    if (Array.isArray(current)) {
      bytes += current.length * 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      pending.push(...current)
      continue
    }
    if (Object.getOwnPropertySymbols(current).length > 0) return false
    const descriptors = Object.getOwnPropertyDescriptors(current)
    for (const [key, descriptor] of Object.entries(descriptors)) {
      if (
        key.length > MAX_DOC_STATE_NAME_LENGTH ||
        !descriptor.enumerable ||
        !Object.hasOwn(descriptor, 'value')
      ) {
        return false
      }
      bytes += key.length * 2 + 8
      if (bytes > MAX_PORTABLE_MESSAGE_BYTES) return false
      pending.push(descriptor.value)
    }
  }
  return true
}

function validMotionDebugSnapshot(value: unknown): boolean {
  if (!isRecord(value)) return false
  const entries = Object.getOwnPropertyDescriptor(value, 'entries')?.value
  return (
    Array.isArray(entries) &&
    entries.length <= MAX_MOTION_DEBUG_ENTRIES &&
    validDocStateValue(value)
  )
}

function parseInbound(value: unknown, channel: string): Inbound | null {
  if (!isRecord(value) || value.source !== INBOUND_SOURCE || value.channel !== channel) return null
  if (value.type === 'select' && hasExactKeys(value, ['source', 'channel', 'type', 'id'])) {
    return value.id === null ||
      (typeof value.id === 'string' && value.id.length > 0 && value.id.length <= MAX_NODE_ID_LENGTH)
      ? (value as unknown as InboundSelect)
      : null
  }
  if (value.type === 'navigate' && hasExactKeys(value, ['source', 'channel', 'type', 'route'])) {
    return validRoute(value.route) ? (value as unknown as InboundNavigate) : null
  }
  if (
    value.type === 'docState' &&
    hasExactKeys(value, ['source', 'channel', 'type', 'name', 'value']) &&
    typeof value.name === 'string' &&
    value.name.length > 0 &&
    value.name.length <= MAX_DOC_STATE_NAME_LENGTH &&
    validDocStateValue(value.value)
  ) {
    return value as unknown as InboundDocState
  }
  if (value.type === 'theme' && hasExactKeys(value, ['source', 'channel', 'type', 'theme'])) {
    return value.theme === 'light' || value.theme === 'dark'
      ? (value as unknown as InboundTheme)
      : null
  }
  if (
    value.type === 'motionDebug' &&
    hasExactKeys(value, ['source', 'channel', 'type', 'enabled']) &&
    typeof value.enabled === 'boolean'
  ) {
    return value as unknown as InboundMotionDebug
  }
  return null
}

const frameContext = typeof window === 'undefined' ? null : readFrameContext()

if (typeof window !== 'undefined' && frameContext && !window.__openPencilPreviewBridge) {
  window.__openPencilPreviewBridge = true

  function postToParent(payload: Record<string, unknown>): void {
    if (frameContext.transport === 'message-port') {
      window.__openPencilPreviewPort?.postMessage({
        ...payload,
        source: OUTBOUND_SOURCE,
        channel: frameContext.channel
      })
      return
    }
    window.parent.postMessage(
      { ...payload, source: OUTBOUND_SOURCE, channel: frameContext.channel },
      frameContext.parentOrigin
    )
  }

  const overlay = document.createElement('div')
  overlay.setAttribute('data-op-preview-overlay', '')
  overlay.style.position = 'fixed'
  overlay.style.left = '0px'
  overlay.style.top = '0px'
  overlay.style.width = '0px'
  overlay.style.height = '0px'
  overlay.style.pointerEvents = 'none'
  overlay.style.border = PREVIEW_SELECTION_OVERLAY_BORDER
  overlay.style.background = PREVIEW_SELECTION_OVERLAY_BACKGROUND
  overlay.style.boxSizing = 'border-box'
  overlay.style.zIndex = '2147483647'
  overlay.style.display = 'none'
  overlay.style.transition = 'all 80ms linear'
  document.documentElement.appendChild(overlay)

  let currentId: string | null = null
  // §7 decision #f: suppress outbound navigate while replaying an inbound
  // navigate, so the editor→iframe→editor echo loop never fires.
  let suppressOutbound = false
  let motionDebugTimer: ReturnType<typeof setInterval> | null = null

  function postMotionDebug(
    status: 'ready' | 'unavailable' | 'error',
    snapshot?: unknown,
    error?: string
  ): void {
    postToParent({ type: 'motionDebug', status, snapshot, error })
  }

  function inspectMotion(): void {
    const runtime = (
      window as Window & {
        __OPENPENCIL_MOTION_RUNTIME__?: { inspect?: () => unknown }
      }
    ).__OPENPENCIL_MOTION_RUNTIME__
    if (!runtime || typeof runtime.inspect !== 'function') {
      postMotionDebug('unavailable')
      return
    }
    try {
      const snapshot = runtime.inspect()
      if (!validMotionDebugSnapshot(snapshot)) {
        postMotionDebug('error', undefined, 'Motion diagnostics exceed the preview safety limit.')
        return
      }
      postMotionDebug('ready', snapshot)
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      postMotionDebug('error', undefined, message.slice(0, MAX_DOC_STATE_STRING_LENGTH))
    }
  }

  function setMotionDebugEnabled(enabled: boolean): void {
    if (motionDebugTimer !== null) {
      clearInterval(motionDebugTimer)
      motionDebugTimer = null
    }
    if (!enabled) return
    inspectMotion()
    motionDebugTimer = setInterval(inspectMotion, 250)
  }

  // PreviewPane owns the theme control for both generated web targets. Keep
  // the DOM contract framework-neutral and explicit so Tailwind's class-based
  // dark mode, data-theme selectors, and native form controls all agree.
  function applyTheme(theme: 'light' | 'dark'): void {
    const root = document.documentElement
    root.dataset.theme = theme
    root.classList.toggle('light', theme === 'light')
    root.classList.toggle('dark', theme === 'dark')
    root.style.colorScheme = theme
  }

  // Alias the real pushState BEFORE patching, so the patch can forward
  // calls (including our own replay) without re-entering itself.
  const nativePushState = history.pushState.bind(history)

  function updateOverlay(): void {
    if (!currentId) {
      overlay.style.display = 'none'
      return
    }
    const el = document.querySelector(
      \`[data-node-id="\${CSS.escape(currentId)}"]\`
    ) as HTMLElement | null
    if (!el) {
      overlay.style.display = 'none'
      return
    }
    const r = el.getBoundingClientRect()
    overlay.style.display = 'block'
    overlay.style.left = \`\${r.left}px\`
    overlay.style.top = \`\${r.top}px\`
    overlay.style.width = \`\${r.width}px\`
    overlay.style.height = \`\${r.height}px\`
  }

  function postOutboundNavigate(route: string): void {
    if (suppressOutbound) return
    if (validRoute(route)) postToParent({ type: 'navigate', route })
  }

  // Client routers call history.pushState directly and do NOT dispatch
  // popstate; patching pushState observes navigation without coupling the
  // bridge to either React or Vue.
  history.pushState = function (
    this: History,
    ...args: Parameters<typeof history.pushState>
  ): void {
    nativePushState(...args)
    postOutboundNavigate(location.pathname)
  } as typeof history.pushState

  // popstate covers browser back/forward + our own synthetic dispatch.
  window.addEventListener('popstate', () => {
    postOutboundNavigate(location.pathname)
  })

  // Phase 3 §4.6 — runtime docState collaboration. Mirror the generated
  // store's per-key changes across peers. suppressDocStateOutbound breaks the
  // remote→setState→subscribe→outbound echo, mirroring suppressOutbound above.
  let suppressDocStateOutbound = false

  function wireDocStore(store: DocStore): void {
    store.subscribe((state, prev) => {
      if (suppressDocStateOutbound) return
      for (const name of Object.keys(state)) {
        if (state[name] !== prev[name]) {
          if (
            name.length > 0 &&
            name.length <= MAX_DOC_STATE_NAME_LENGTH &&
            validDocStateValue(state[name])
          ) {
            postToParent({ type: 'docState', name: name, value: state[name] })
          }
        }
      }
    })
  }

  // The generated state module may evaluate before or after this bridge; cover both —
  // wire now if the store is already up, else wait for its ready event.
  if (window.__opDocStore) {
    wireDocStore(window.__opDocStore)
  } else {
    window.addEventListener(
      'op-docstore-ready',
      () => {
        if (window.__opDocStore) wireDocStore(window.__opDocStore)
      },
      { once: true }
    )
  }

  function handleInbound(data: Inbound): void {
    if (data.type === 'select') {
      currentId = typeof data.id === 'string' ? data.id : null
      updateOverlay()
      return
    }
    if (data.type === 'navigate') {
      const route = data.route
      // No-op if the iframe is already at this route — avoids stray
      // outbound traffic on init or on duplicate page-id watcher fires.
      if (location.pathname === route) return
      suppressOutbound = true
      try {
        nativePushState(null, '', route)
        window.dispatchEvent(new PopStateEvent('popstate'))
      } finally {
        suppressOutbound = false
      }
      return
    }
    if (data.type === 'docState') {
      const store = window.__opDocStore
      if (!store) return
      if (!Object.hasOwn(store.getState(), data.name)) return
      // Apply the remote value without re-broadcasting it back out.
      suppressDocStateOutbound = true
      try {
        store.setState({ [data.name]: data.value })
      } finally {
        suppressDocStateOutbound = false
      }
      return
    }
    if (data.type === 'theme') {
      if (data.theme !== 'light' && data.theme !== 'dark') return
      applyTheme(data.theme)
      return
    }
    if (data.type === 'motionDebug') {
      setMotionDebugEnabled(data.enabled === true)
    }
  }

  if (frameContext.transport === 'message-port') {
    const port = window.__openPencilPreviewPort
    if (port) {
      port.addEventListener('message', (event: MessageEvent) => {
        const data = parseInbound(event.data, frameContext.channel)
        if (data) handleInbound(data)
      })
      port.start()
      window.addEventListener('pagehide', () => port.close(), { once: true })
    }
  } else {
    window.addEventListener('message', (event: MessageEvent) => {
      if (event.source !== window.parent) return
      if (event.origin !== frameContext.parentOrigin) return
      const data = parseInbound(event.data, frameContext.channel)
      if (data) handleInbound(data)
    })
  }

  // Alt/Option-click is the "select in canvas" affordance — plain clicks pass
  // through so the user's onClick handlers still fire as in any real app.
  document.addEventListener(
    'click',
    (event) => {
      if (!event.altKey) return
      const target = event.target as Element | null
      const host = target?.closest('[data-node-id]') as HTMLElement | null
      const id = host?.dataset.nodeId
      if (!id) return
      event.preventDefault()
      event.stopPropagation()
      if (id.length <= MAX_NODE_ID_LENGTH) postToParent({ type: 'select', id })
    },
    true
  )

  window.addEventListener('scroll', updateOverlay, true)
  window.addEventListener('resize', updateOverlay)

  // Re-derive the overlay rect every frame while highlighted so HMR-induced
  // layout shifts don't strand the box on stale coordinates.
  function tick(): void {
    if (currentId) updateOverlay()
    requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

export {}
`
}
