/**
 * Phase 3 §10 v3: scaffold `src/_lowcode_confirm.tsx`, the runtime that backs
 * the `confirm` workflow action. Compiled event handlers `await` the
 * module-level `__opConfirm(message)`, which shows a modal and resolves to the
 * user's choice (`true` = OK, `false` = Cancel). The auto-mounted
 * `<ConfirmHost/>` (mounted by `main.tsx`, like the toast host) subscribes to a
 * tiny module-level store via React's built-in `useSyncExternalStore` and
 * renders the pending prompt — so there is NO new npm dependency. The file is
 * emitted only when a page fires a `confirm` action.
 */

/** The Tailwind utilities the confirm runtime renders. They never appear in the
 *  IR, so the React adapter must seed them into the `@source inline(...)`
 *  safelist (the VFS-served iframe finds no classes on disk) — mirroring
 *  `TOAST_RUNTIME_CLASSES`. */
export const CONFIRM_RUNTIME_CLASSES: readonly string[] = [
  'fixed',
  'inset-0',
  'z-50',
  'flex',
  'items-center',
  'justify-center',
  'bg-foreground/40',
  'mx-4',
  'max-w-sm',
  'rounded-lg',
  'border',
  'border-border',
  'bg-background',
  'p-6',
  'shadow-xl',
  'mb-4',
  'text-sm',
  'text-foreground',
  'justify-end',
  'gap-2',
  'rounded',
  'px-4',
  'py-2',
  'text-muted-foreground',
  'hover:bg-secondary',
  'bg-primary',
  'text-primary-foreground',
  'hover:bg-primary/90'
]

/** Build the contents of `src/_lowcode_confirm.tsx`. */
export function buildLowcodeConfirmRuntime(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 3 §10 v3 / v5). Do not edit by hand.
import { useSyncExternalStore } from 'react'

export interface ConfirmOptions {
  confirmLabel?: string
  cancelLabel?: string
}

interface PendingConfirm {
  message: string
  confirmLabel: string
  cancelLabel: string
  resolve: (ok: boolean) => void
}

// Module-level store: a single pending confirm (or null), read through React's
// useSyncExternalStore. The reference changes only when a confirm opens or
// closes, so getSnapshot is stable between renders (no re-render loop).
let pending: PendingConfirm | null = null
const listeners = new Set<() => void>()

function emitChange(): void {
  for (const listener of listeners) listener()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

function getSnapshot(): PendingConfirm | null {
  return pending
}

/** Ask the user to confirm. Called (and awaited) by compiled event handlers.
 *  Resolves true when OK is clicked, false on Cancel. A second confirm opened
 *  while one is pending resolves the earlier one as cancelled first. */
export function __opConfirm(message: string, options: ConfirmOptions = {}): Promise<boolean> {
  if (pending) pending.resolve(false)
  return new Promise<boolean>((resolve) => {
    pending = {
      message,
      confirmLabel: options.confirmLabel ?? 'OK',
      cancelLabel: options.cancelLabel ?? 'Cancel',
      resolve
    }
    emitChange()
  })
}

function settle(ok: boolean): void {
  const current = pending
  pending = null
  emitChange()
  if (current) current.resolve(ok)
}

/** Renders the pending confirm modal. Auto-mounted by main.tsx — place nothing yourself. */
export function ConfirmHost() {
  const active = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
  if (!active) return null
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/40">
      <div className="mx-4 max-w-sm rounded-lg border border-border bg-background p-6 shadow-xl">
        <p className="mb-4 text-sm text-foreground">{active.message}</p>
        <div className="flex justify-end gap-2">
          <button
            type="button"
            className="rounded px-4 py-2 text-sm text-muted-foreground hover:bg-secondary"
            onClick={() => settle(false)}
          >
            {active.cancelLabel}
          </button>
          <button
            type="button"
            className="rounded bg-primary px-4 py-2 text-sm text-primary-foreground hover:bg-primary/90"
            onClick={() => settle(true)}
          >
            {active.confirmLabel}
          </button>
        </div>
      </div>
    </div>
  )
}
`
}
