/**
 * Phase 3 §9: scaffold for the emitted i18n runtime (`src/_lowcode_i18n.tsx`)
 * and the source-locale message catalog (`src/locales/<source>.json`).
 *
 * The runtime wraps react-intl's `IntlProvider`, holds the active locale in
 * React state, and exposes `useLocale()` ({ locale, setLocale, locales }) so an
 * app can switch languages. v1 ships only the design (source) locale; adding a
 * language is "drop `src/locales/fr.json` + register it in CATALOGS".
 *
 * Display strings (TEXT content, BUTTON text, SELECT/RADIO/CHECKBOX option
 * labels) are externalized at collect time under a content-hash id and rendered
 * via `<FormattedMessage id defaultMessage/>`; `defaultMessage` keeps the source
 * text rendering even before a translation exists.
 */

/** react-intl pin for emitted projects. Mirrors the `packages/compiler`
 *  devDependency (经验 D) so the preview/build VFS resolves the same copy from
 *  the monorepo's hoisted `node_modules` and the exported project never
 *  diverges. react-intl 7.x peers React 18 || 19 — both our targets. */
export const REACT_INTL_VERSION = '^7.1.0'

/** The DEFAULT design (source) locale: the language the canvas strings are
 *  authored in. Phase 3 §9 v8 makes it configurable via `CompilerOptions.
 *  sourceLocale`; this is the fallback when unset. */
export const SOURCE_LOCALE = 'en'

/** Relative path (from `src/`) of a source-locale catalog the runtime imports. */
export function sourceCatalogPath(sourceLocale: string): string {
  return `locales/${sourceLocale}.json`
}

/** Phase 3 §9 — the `import { ... } from 'react-intl'` line for a page/component
 *  file, listing only the symbols it uses: `FormattedMessage` for visible text
 *  (§9 v1), `useIntl` for translated attributes like placeholder (§9 v3).
 *  Returns '' when neither is needed (so non-i18n files stay byte-identical). */
export function buildReactIntlImport(needs: {
  formattedMessage: boolean
  intl: boolean
}): string {
  const names: string[] = []
  if (needs.formattedMessage) names.push('FormattedMessage')
  if (needs.intl) names.push('useIntl')
  if (names.length === 0) return ''
  return `import { ${names.join(', ')} } from 'react-intl'\n`
}

/**
 * Build `src/locales/<source>.json` — the id→source-string map. Keys are sorted
 * for a stable, diff-friendly file across re-compiles.
 */
export function buildLocaleCatalog(messages: ReadonlyMap<string, string>): string {
  const sorted: Record<string, string> = {}
  for (const id of [...messages.keys()].sort()) {
    sorted[id] = messages.get(id) ?? ''
  }
  return JSON.stringify(sorted, null, 2) + '\n'
}

/**
 * Phase 3 §9 v7 — build a target locale catalog (`locales/<code>.json`)
 * pre-filled with authored translations. For each message `id`, the value is
 * `translations[sourceString]` when the document carries a translation for that
 * source message, else the source string itself (so the app always renders and
 * react-intl's `defaultMessage` stays consistent). `translations` maps the
 * SOURCE message string → translated string (see `LowcodeTranslations`); we
 * resolve through the `messages` map's `id → source` to land on a translation.
 * Keys are sorted for a stable, diff-friendly file.
 */
export function buildTranslatedCatalog(
  messages: ReadonlyMap<string, string>,
  translations: Readonly<Record<string, string>> | undefined
): string {
  const sorted: Record<string, string> = {}
  for (const id of [...messages.keys()].sort()) {
    const source = messages.get(id) ?? ''
    sorted[id] = translations?.[source] ?? source
  }
  return JSON.stringify(sorted, null, 2) + '\n'
}

/** Phase 3 §9 v2 — a locale code's JS import binding (codes like `zh-CN` are
 *  not valid identifiers, so strip non-alphanumerics → `zhCN`). */
export function localeIdent(code: string): string {
  const ident = code.replace(/[^a-zA-Z0-9]/g, '')
  return /^[a-zA-Z]/.test(ident) ? ident : `loc${ident}`
}

/**
 * Build `src/_lowcode_i18n.tsx`: the `<I18nProvider>` (IntlProvider + locale
 * state + a `useLocale` context) the app root is wrapped in. Phase 3 §9 v2:
 * `targetLocales` (after the source) drives the catalog imports + registry, so
 * `setLocale('<target>')` resolves a real catalog. Phase 3 §9 v8: `sourceLocale`
 * is the runtime's default locale (was fixed to `'en'`). With source `'en'` and
 * no targets the output is byte-identical to the v1 single-locale runtime.
 */
export function buildLowcodeI18nRuntime(sourceLocale: string, targetLocales: readonly string[]): string {
  const locales = [sourceLocale, ...targetLocales]
  const imports = locales
    .map((code) => `import ${localeIdent(code)} from './locales/${code}.json'`)
    .join('\n')
  const entries = locales
    .map((code) => (localeIdent(code) === code ? code : `${JSON.stringify(code)}: ${localeIdent(code)}`))
    .join(', ')
  return `// Auto-generated by OpenPencil compiler (Phase 3 §9). Do not edit by hand.
import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { IntlProvider } from 'react-intl'
${imports}

/** The design (source) locale — the language the canvas strings were authored in. */
export const SOURCE_LOCALE = ${JSON.stringify(sourceLocale)}

/** Locale code → message catalog. Add a language by importing its JSON and
 *  registering it here (e.g. \`import fr from './locales/fr.json'\` → \`fr\`). */
const CATALOGS: Record<string, Record<string, string>> = { ${entries} }

interface LocaleContextValue {
  locale: string
  setLocale: (locale: string) => void
  locales: string[]
}

const LocaleContext = createContext<LocaleContextValue>({
  locale: SOURCE_LOCALE,
  setLocale: () => undefined,
  locales: [SOURCE_LOCALE]
})

/** Read/switch the active locale anywhere under \`<I18nProvider>\`. */
export function useLocale(): LocaleContextValue {
  return useContext(LocaleContext)
}

/** Wrap the app: react-intl provider + locale state. */
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState(SOURCE_LOCALE)
  const messages = CATALOGS[locale] ?? CATALOGS[SOURCE_LOCALE]
  const value = useMemo(
    () => ({ locale, setLocale, locales: Object.keys(CATALOGS) }),
    [locale]
  )
  return (
    <LocaleContext.Provider value={value}>
      <IntlProvider locale={locale} defaultLocale={SOURCE_LOCALE} messages={messages}>
        {children}
      </IntlProvider>
    </LocaleContext.Provider>
  )
}
`
}

/**
 * Phase 3 §9 v2 — build `src/components/LocaleSwitcher.tsx`: a language picker
 * bound to the i18n runtime's `useLocale`. Not auto-mounted — the developer
 * imports and places it. Only emitted when ≥1 target locale is declared.
 */
export function buildLocaleSwitcher(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 3 §9 v2). Do not edit by hand.
import { useLocale } from '../_lowcode_i18n'

/** A language picker bound to the i18n runtime. Place anywhere under
 *  <I18nProvider>; not auto-mounted. */
export function LocaleSwitcher() {
  const { locale, setLocale, locales } = useLocale()
  return (
    <select value={locale} onChange={(e) => setLocale(e.target.value)}>
      {locales.map((code) => (
        <option key={code} value={code}>
          {code}
        </option>
      ))}
    </select>
  )
}
`
}
