/**
 * Phase 2 §2: scaffold `src/_lowcode_state.ts`, the lowcode runtime that
 * backs document-level state ("Document State"). zustand sits underneath,
 * but the emitted module only exports our three-function API so generated
 * page code never touches zustand symbols directly.
 *
 *   useDocState(name)            — Hook, subscribes the component.
 *   setDocState(name, value|fn)  — Plain function, supports React-style
 *                                  functional updater `(prev) => …`.
 *   getDocStateSnapshot(name)    — Plain function, non-subscribing read.
 *
 * The file is emitted only when `IRTree.docStates.length > 0`; pages that
 * never bind a doc-state ref or fire setVariable don't import from it.
 */
import type { IRDocStateDecl } from '#compiler/ir/types'

/** zustand pin for emitted projects. ^5.x targets React 18+, which matches
 *  the Phase 0 / Phase 1 React floor (18.3.1 and 19.2.0 are both supported). */
export const ZUSTAND_VERSION = '^5.0.0'

const TS_TYPE_BY_STATE_VALUE_TYPE: Record<IRDocStateDecl['type'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  array: 'unknown[]',
  object: 'Record<string, unknown>'
}

/**
 * Build the contents of `src/_lowcode_state.ts`. Caller asserts that
 * `decls.length > 0` — passing an empty list returns the empty string,
 * which the caller treats as "do not emit".
 */
export function buildLowcodeStateRuntime(
  decls: readonly IRDocStateDecl[],
  packageName = 'app'
): string {
  if (decls.length === 0) return ''
  // Stable order so two compiles of the same scene graph produce identical
  // output. Names are validated upstream (`collectDocStates` rejects empty
  // or duplicate names), so a simple string sort is enough.
  const sorted = [...decls].sort((a, b) => a.name.localeCompare(b.name))
  const typeFields = sorted
    .map((d) => `  ${d.name}: ${TS_TYPE_BY_STATE_VALUE_TYPE[d.type]}`)
    .join('\n')
  const defaultFields = sorted
    .map((d) => `  ${d.name}: ${JSON.stringify(d.defaultValue)}`)
    .join(',\n')
  const persisted = sorted.filter((d) => d.persist === true)
  const persistBlock = buildPersistenceBlock(persisted, packageName)
  const persistSubscribe =
    persisted.length > 0
      ? `
subscribePersistedDocState(store)
`
      : ''
  const initialFields = sorted
    .map((d) => {
      const value =
        d.persist === true
          ? `readPersisted(${JSON.stringify(d.name)}, initialDefaults.${d.name})`
          : `initialDefaults.${d.name}`
      return `  ${d.name}: ${value}`
    })
    .join(',\n')
  return `// Auto-generated by OpenPencil compiler (Phase 2 §2). Do not edit by hand.
import { useStore } from 'zustand'
import { createStore, type StoreApi } from 'zustand/vanilla'

type DocState = {
${typeFields}
}

const initialDefaults: DocState = {
${defaultFields}
}

${persistBlock}const initial: DocState = {
${initialFields}
}

const store = createStore<DocState>(() => initial)
${persistSubscribe}

// Phase 3 §4.6 — expose the store so the dev-mode preview bridge can mirror
// runtime docState across collaborators. Harmless in prod (no bridge reads it).
// The ready event lets the bridge wire up regardless of module eval order.
if (typeof window !== 'undefined') {
  ;(window as unknown as { __opDocStore?: unknown }).__opDocStore = store
  window.dispatchEvent(new Event('op-docstore-ready'))
}

export function useDocState<K extends keyof DocState>(name: K): DocState[K] {
  return useStore(store, (s) => s[name])
}

export function setDocState<K extends keyof DocState>(
  name: K,
  value: DocState[K] | ((prev: DocState[K]) => DocState[K])
): void {
  store.setState((s) => {
    const next =
      typeof value === 'function'
        ? (value as (prev: DocState[K]) => DocState[K])(s[name])
        : value
    return { [name]: next } as Partial<DocState>
  })
}

export function getDocStateSnapshot<K extends keyof DocState>(name: K): DocState[K] {
  return store.getState()[name]
}
`
}

function buildPersistenceBlock(decls: readonly IRDocStateDecl[], packageName: string): string {
  if (decls.length === 0) return ''
  const configFields = decls
    .map((d) => {
      const key = d.storageKey ?? `openpencil:${packageName}:${d.name}`
      const version = d.storageVersion ?? null
      return `  ${d.name}: { key: ${JSON.stringify(key)}, version: ${JSON.stringify(version)} }`
    })
    .join(',\n')
  const persistedNames = `[${decls.map((d) => JSON.stringify(d.name)).join(', ')}]`
  return `const persistConfig: Partial<Record<keyof DocState, { key: string; version: string | null }>> = {
${configFields}
}

const persistedNames = ${persistedNames} as (keyof DocState)[]

function readPersisted<K extends keyof DocState>(name: K, fallback: DocState[K]): DocState[K] {
  const config = persistConfig[name]
  if (!config || typeof window === 'undefined') return fallback
  try {
    const raw = window.localStorage.getItem(config.key)
    if (raw === null) return fallback
    const parsed = JSON.parse(raw) as { version?: unknown; value?: unknown } | null
    if (!parsed || parsed.version !== config.version || !('value' in parsed)) return fallback
    return parsed.value as DocState[K]
  } catch {
    return fallback
  }
}

function writePersisted<K extends keyof DocState>(name: K, value: DocState[K]): void {
  const config = persistConfig[name]
  if (!config || typeof window === 'undefined') return
  try {
    window.localStorage.setItem(config.key, JSON.stringify({ version: config.version, value }))
  } catch {
    // localStorage may be unavailable or full; persistence is best-effort.
  }
}

function subscribePersistedDocState(store: StoreApi<DocState>): void {
  if (persistedNames.length === 0) return
  store.subscribe((state, previous) => {
    for (const name of persistedNames) {
      if (Object.is(state[name], previous[name])) continue
      writePersisted(name, state[name])
    }
  })
}

`
}
