/**
 * Phase 3 §10 v2: scaffold `src/_lowcode_toast.tsx`, the runtime that backs the
 * `toast` workflow action. Compiled event handlers call the module-level
 * `__opToast(message, variant)`; the auto-mounted `<ToastHost/>` (mounted by
 * `main.tsx`, like the i18n provider) subscribes to a tiny module-level store
 * via React's built-in `useSyncExternalStore` and renders the active toasts —
 * so there is NO new npm dependency (unlike the zustand-backed doc-state
 * runtime). The file is emitted only when a page fires a `toast` action.
 */

/** The Tailwind utilities the toast runtime renders. They never appear in the
 *  IR, so the React adapter must seed them into the `@source inline(...)`
 *  safelist (the VFS-served iframe finds no classes on disk) — mirroring how
 *  `PAGE_WRAPPER_CLASSES` is seeded for the page wrapper. */
export const TOAST_RUNTIME_CLASSES: readonly string[] = [
  'fixed',
  'bottom-4',
  'right-4',
  'z-50',
  'flex',
  'flex-col',
  'gap-2',
  'rounded',
  'px-4',
  'py-2',
  'text-sm',
  'text-white',
  'shadow-lg',
  'bg-blue-600',
  'bg-green-600',
  'bg-red-600'
]

/** Build the contents of `src/_lowcode_toast.tsx`. */
export function buildLowcodeToastRuntime(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 3 §10 v2). Do not edit by hand.
import { useSyncExternalStore } from 'react'

export type ToastVariant = 'info' | 'success' | 'error'

interface Toast {
  id: number
  message: string
  variant: ToastVariant
}

// Module-level store: a plain list + a listener set, read through React's
// useSyncExternalStore. The list reference changes only when a toast is added
// or removed, so getSnapshot is stable between renders (no re-render loop).
let toasts: Toast[] = []
let seq = 0
const listeners = new Set<() => void>()

function emitChange(): void {
  for (const listener of listeners) listener()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

function getSnapshot(): Toast[] {
  return toasts
}

/** Show a transient toast. Called by compiled event handlers. Auto-dismisses
 *  after 3s. */
export function __opToast(message: string, variant: ToastVariant = 'info'): void {
  const id = ++seq
  toasts = [...toasts, { id, message, variant }]
  emitChange()
  setTimeout(() => {
    toasts = toasts.filter((t) => t.id !== id)
    emitChange()
  }, 3000)
}

const VARIANT_CLASSES: Record<ToastVariant, string> = {
  info: 'bg-blue-600',
  success: 'bg-green-600',
  error: 'bg-red-600'
}

/** Renders the active toasts. Auto-mounted by main.tsx — place nothing yourself. */
export function ToastHost() {
  const active = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
      {active.map((t) => (
        <div
          key={t.id}
          className={'rounded px-4 py-2 text-sm text-white shadow-lg ' + VARIANT_CLASSES[t.variant]}
        >
          {t.message}
        </div>
      ))}
    </div>
  )
}
`
}
