/**
 * Phase 3 §10 v2: scaffold `src/_lowcode_toast.tsx`, the runtime that backs the
 * `toast` workflow action. Compiled event handlers call the module-level
 * `__opToast(message, variant)`; the auto-mounted `<ToastHost/>` (mounted by
 * `main.tsx`, like the i18n provider) subscribes to a tiny module-level store
 * via React's built-in `useSyncExternalStore` and renders the active toasts —
 * so there is NO new npm dependency (unlike the zustand-backed doc-state
 * runtime). The file is emitted only when a page fires a `toast` action.
 */

/** The Tailwind utilities the toast runtime renders. They never appear in the
 *  IR, so the React adapter must seed them into the `@source inline(...)`
 *  safelist (the VFS-served iframe finds no classes on disk) — mirroring how
 *  `PAGE_WRAPPER_CLASSES` is seeded for the page wrapper. */
export const TOAST_RUNTIME_CLASSES: readonly string[] = [
  'fixed',
  'top-4',
  'bottom-4',
  'left-4',
  'right-4',
  // Phase 3 §10 v5: horizontal-centre positions.
  'left-1/2',
  '-translate-x-1/2',
  'z-50',
  'flex',
  'flex-col',
  'gap-2',
  'rounded',
  'px-4',
  'py-2',
  'text-sm',
  'shadow-lg',
  'border',
  'border-border',
  'bg-primary',
  'bg-secondary',
  'bg-destructive',
  'text-primary-foreground',
  'text-secondary-foreground',
  'text-destructive-foreground',
  // Phase 3 §10 v7: the per-toast row layout + manual close (×) button.
  'items-center',
  'ml-auto',
  'opacity-70',
  'hover:opacity-100',
  'cursor-pointer',
  'leading-none'
]

/** Build the contents of `src/_lowcode_toast.tsx`. */
export function buildLowcodeToastRuntime(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 3 §10 v2 / v5). Do not edit by hand.
import { useSyncExternalStore } from 'react'

export type ToastVariant = 'info' | 'success' | 'error'
export type ToastPosition =
  | 'top-left'
  | 'top-center'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right'

export interface ToastOptions {
  position?: ToastPosition
  durationMs?: number
}

interface Toast {
  id: number
  message: string
  variant: ToastVariant
  position: ToastPosition
}

// Module-level store: a plain list + a listener set, read through React's
// useSyncExternalStore. The list reference changes only when a toast is added
// or removed, so getSnapshot is stable between renders (no re-render loop).
let toasts: Toast[] = []
let seq = 0
const listeners = new Set<() => void>()

// Phase 3 §10 v8: cap the number of simultaneously stacked toasts; when a new
// toast pushes past the cap the oldest is dropped so the stack can't grow
// without bound (e.g. a toast fired in a loop / on every keystroke).
const MAX_TOASTS = 5

function emitChange(): void {
  for (const listener of listeners) listener()
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener)
  return () => {
    listeners.delete(listener)
  }
}

function getSnapshot(): Toast[] {
  return toasts
}

/** Remove a toast by id. Shared by the auto-dismiss timer and the manual
 *  close (×) button. */
function dismiss(id: number): void {
  toasts = toasts.filter((t) => t.id !== id)
  emitChange()
}

/** Show a transient toast. Called by compiled event handlers. Auto-dismisses
 *  after \`options.durationMs\` (default 3000ms); pass \`durationMs: 0\` for a
 *  persistent toast that only closes when the user clicks ×. \`options.position\`
 *  picks the screen corner (default 'bottom-right'). */
export function __opToast(
  message: string,
  variant: ToastVariant = 'info',
  options: ToastOptions = {}
): void {
  const position = options.position ?? 'bottom-right'
  const duration = options.durationMs ?? 3000
  // Phase 3 §10 v8: skip a toast whose message + variant duplicates one already
  // on screen, so a repeatedly-fired action doesn't stack identical copies.
  if (toasts.some((t) => t.message === message && t.variant === variant)) return
  const id = ++seq
  let next = [...toasts, { id, message, variant, position }]
  // Phase 3 §10 v8: enforce the stack cap by dropping the oldest toasts.
  if (next.length > MAX_TOASTS) next = next.slice(next.length - MAX_TOASTS)
  toasts = next
  emitChange()
  if (duration > 0) {
    setTimeout(() => {
      dismiss(id)
    }, duration)
  }
}

const VARIANT_CLASSES: Record<ToastVariant, string> = {
  info: 'border-border bg-secondary text-secondary-foreground',
  success: 'border-border bg-primary text-primary-foreground',
  error: 'border-destructive bg-destructive text-destructive-foreground'
}

const POSITION_CLASSES: Record<ToastPosition, string> = {
  'top-left': 'top-4 left-4',
  'top-center': 'top-4 left-1/2 -translate-x-1/2',
  'top-right': 'top-4 right-4',
  'bottom-left': 'bottom-4 left-4',
  'bottom-center': 'bottom-4 left-1/2 -translate-x-1/2',
  'bottom-right': 'bottom-4 right-4'
}

/** Renders the active toasts, grouped into one fixed container per position in
 *  use. Auto-mounted by main.tsx — place nothing yourself. */
export function ToastHost() {
  const active = useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
  const positions = [...new Set(active.map((t) => t.position))]
  return (
    <>
      {positions.map((position) => (
        <div key={position} className={'fixed z-50 flex flex-col gap-2 ' + POSITION_CLASSES[position]}>
          {active
            .filter((t) => t.position === position)
            .map((t) => (
              <div
                key={t.id}
                className={'flex items-center gap-2 rounded border px-4 py-2 text-sm shadow-lg ' + VARIANT_CLASSES[t.variant]}
              >
                <span>{t.message}</span>
                <button
                  type="button"
                  aria-label="Dismiss"
                  onClick={() => dismiss(t.id)}
                  className="ml-auto cursor-pointer leading-none opacity-70 hover:opacity-100"
                >
                  ×
                </button>
              </div>
            ))}
        </div>
      ))}
    </>
  )
}
`
}
