/**
 * Phase 4 §19: form validation.
 *
 * `buildLowcodeValidationRuntime` scaffolds `src/_lowcode_validation.tsx`, a
 * zero-dependency runtime exporting the pure `validateValue` helper that
 * evaluates a field's data-driven core rules (required / pattern / length /
 * numeric range) against its current value. `buildValidationGlue` emits the
 * page-level glue a validated page needs: an errors `useState`, a `__validators`
 * map (one closure per field — core rules call `validateValue`, the optional
 * custom rule is an inline expression over doc-state), and the `__validateField`
 * (onBlur) / `__validateFields` (onSubmit) helpers.
 *
 * The custom-rule expression is emitted with `emitExpression`, so it reads the
 * field's bound doc-state via the page's hoisted `useDocState` consts (the
 * render-committed value — current at blur/submit, the locked timing). The core
 * rules read the field value fresh via `getDocStateSnapshot` to dodge the
 * same-handler render-snapshot staleness (§10 v9 lesson).
 */

import { emitExpression } from '@open-pencil/core/lowcode-validation'

import type { IRFieldValidation } from '#compiler/ir/types'

/** The fixed Tailwind utilities the per-field error `<p>` renders. They never
 *  appear in the IR, so the React adapter must seed them into the
 *  `@source inline(...)` safelist (mirrors `TOAST_RUNTIME_CLASSES`). */
export const VALIDATION_ERROR_CLASSES: readonly string[] = [
  'text-sm',
  'text-red-600',
  'mt-1'
]

/** The className on the per-field error `<p>` (emitted by `element.ts`). */
export const VALIDATION_ERROR_CLASS = VALIDATION_ERROR_CLASSES.join(' ')

/** Build the contents of `src/_lowcode_validation.tsx`. Messages with embedded
 *  values use string concatenation (not template literals) so this builder's
 *  source carries no `${...}`. */
export function buildLowcodeValidationRuntime(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 4 §19). Do not edit by hand.

export interface ValidationRules {
  required?: boolean
  pattern?: string
  minLength?: number
  maxLength?: number
  min?: number
  max?: number
  messages?: {
    required?: string
    pattern?: string
    minLength?: string
    maxLength?: string
    min?: string
    max?: string
  }
}

/**
 * Evaluate a field's data-driven rules against its current value, returning the
 * first failing rule's message (custom or default), or null when valid. An
 * empty optional field skips every rule but \`required\`. Custom (expression)
 * rules are evaluated inline in the page component, not here.
 */
export function validateValue(value: unknown, rules: ValidationRules): string | null {
  const messages = rules.messages
  const str = value == null ? '' : String(value)
  if (rules.required && str.trim() === '') {
    return messages?.required ?? 'This field is required'
  }
  if (str === '') return null
  if (rules.minLength != null && str.length < rules.minLength) {
    return messages?.minLength ?? ('Must be at least ' + rules.minLength + ' characters')
  }
  if (rules.maxLength != null && str.length > rules.maxLength) {
    return messages?.maxLength ?? ('Must be at most ' + rules.maxLength + ' characters')
  }
  if (rules.pattern != null && !new RegExp(rules.pattern).test(str)) {
    return messages?.pattern ?? 'Invalid format'
  }
  if (rules.min != null && Number(value) < rules.min) {
    return messages?.min ?? ('Must be at least ' + rules.min)
  }
  if (rules.max != null && Number(value) > rules.max) {
    return messages?.max ?? ('Must be at most ' + rules.max)
  }
  return null
}
`
}

/**
 * Build the page-level validation glue (a block of indented lines) for a page
 * with ≥1 validated field. Emitted into the page component's hook lines, after
 * the doc-state hoists (the custom-rule expressions reference them).
 */
export function buildValidationGlue(fields: readonly IRFieldValidation[]): string {
  const validators = fields.map((f) => buildValidatorEntry(f)).join('\n')
  return [
    `  const [__fieldErrors, __setFieldErrors] = useState<Record<string, string | null>>({})`,
    `  const __validators: Record<string, () => string | null> = {`,
    validators,
    `  }`,
    `  const __validateField = (id: string): string | null => {`,
    `    const __fn = __validators[id]`,
    `    const __error = __fn ? __fn() : null`,
    `    __setFieldErrors((prev) => ({ ...prev, [id]: __error }))`,
    `    return __error`,
    `  }`,
    `  const __validateFields = (ids: string[]): boolean => {`,
    `    const __next: Record<string, string | null> = {}`,
    `    let __ok = true`,
    `    for (const id of ids) {`,
    `      const __fn = __validators[id]`,
    `      const __error = __fn ? __fn() : null`,
    `      __next[id] = __error`,
    `      if (__error !== null) __ok = false`,
    `    }`,
    `    __setFieldErrors((prev) => ({ ...prev, ...__next }))`,
    `    return __ok`,
    `  }`
  ].join('\n')
}

/** One `"<key>": () => { ... }` entry in the `__validators` map. */
function buildValidatorEntry(field: IRFieldValidation): string {
  const read =
    field.stateKind === 'docState'
      ? `getDocStateSnapshot(${JSON.stringify(field.stateName)})`
      : field.stateName
  const lines = [
    `    ${JSON.stringify(field.key)}: () => {`,
    `      const __value = ${read}`,
    `      let __error = validateValue(__value, ${JSON.stringify(field.rules)})`
  ]
  if (field.custom) {
    // The custom rule is valid when the expression is truthy → the message
    // shows when it is falsy (and no core rule already failed).
    lines.push(
      `      if (__error === null && !(${emitExpression(field.custom.ast)})) __error = ${JSON.stringify(field.custom.message)}`
    )
  }
  lines.push(`      return __error`, `    },`)
  return lines.join('\n')
}

/** Whether any validated field reads its value fresh via `getDocStateSnapshot`
 *  (i.e. is doc-state bound) — drives the runtime-state import. */
export function validationUsesDocStateSnapshot(fields: readonly IRFieldValidation[]): boolean {
  return fields.some((f) => f.stateKind === 'docState')
}
