/**
 * Phase 4 §19: form validation.
 *
 * `buildLowcodeValidationRuntime` scaffolds `src/_lowcode_validation.tsx`, a
 * zero-dependency runtime exporting the pure `validateValue` helper that
 * evaluates a field's data-driven core rules (required / pattern / length /
 * numeric range) against its current value. `buildValidationGlue` emits the
 * page-level glue a validated page needs: an errors `useState`, a `__validators`
 * map (one closure per field — core rules call `validateValue`, the optional
 * custom rule is an inline expression over doc-state, and async custom
 * validators call `validateRemote`), and the `__validateField` (onBlur) /
 * `__validateFieldValue` (onChange) / `__validateFields` (onSubmit) helpers.
 *
 * The custom-rule expression is emitted with `emitExpression`, so it reads the
 * field's bound doc-state via the page's hoisted `useDocState` consts (the
 * render-committed value — current at blur/submit, the locked timing). The core
 * rules read the field value fresh via `getDocStateSnapshot` to dodge the
 * same-handler render-snapshot staleness (§10 v9 lesson). `__validateFieldValue`
 * lets controlled onChange validate the next event value instead of a stale
 * render snapshot.
 */

import type { IRFieldValidation } from '#compiler/ir/types'

import { emitExpression } from '@open-pencil/core/lowcode-validation'

/** The fixed Tailwind utilities the per-field error `<p>` renders. They never
 *  appear in the IR, so the React adapter must seed them into the
 *  `@source inline(...)` safelist (mirrors `TOAST_RUNTIME_CLASSES`). */
export const VALIDATION_ERROR_CLASSES: readonly string[] = ['text-sm', 'text-red-600', 'mt-1']

/** The className on the per-field error `<p>` (emitted by `element.ts`). */
export const VALIDATION_ERROR_CLASS = VALIDATION_ERROR_CLASSES.join(' ')

/** Build the contents of `src/_lowcode_validation.tsx`. Messages with embedded
 *  values use string concatenation (not template literals) so this builder's
 *  source carries no `${...}`. */
export function buildLowcodeValidationRuntime(): string {
  return `// Auto-generated by OpenPencil compiler (Phase 4 §19). Do not edit by hand.

export interface ValidationRules {
  required?: boolean
  pattern?: string
  minLength?: number
  maxLength?: number
  min?: number
  max?: number
  messages?: {
    required?: string
    pattern?: string
    minLength?: string
    maxLength?: string
    min?: string
    max?: string
  }
}

/**
 * Evaluate a field's data-driven rules against its current value, returning the
 * first failing rule's message (custom or default), or null when valid. An
 * empty optional field skips every rule but \`required\`. Custom (expression)
 * rules are evaluated inline in the page component, not here.
 */
export function validateValue(value: unknown, rules: ValidationRules): string | null {
  const messages = rules.messages
  const str = value == null ? '' : String(value)
  if (rules.required && str.trim() === '') {
    return messages?.required ?? 'This field is required'
  }
  if (str === '') return null
  if (rules.minLength != null && str.length < rules.minLength) {
    return messages?.minLength ?? ('Must be at least ' + rules.minLength + ' characters')
  }
  if (rules.maxLength != null && str.length > rules.maxLength) {
    return messages?.maxLength ?? ('Must be at most ' + rules.maxLength + ' characters')
  }
  if (rules.pattern != null && !new RegExp(rules.pattern).test(str)) {
    return messages?.pattern ?? 'Invalid format'
  }
  if (rules.min != null && Number(value) < rules.min) {
    return messages?.min ?? ('Must be at least ' + rules.min)
  }
  if (rules.max != null && Number(value) > rules.max) {
    return messages?.max ?? ('Must be at most ' + rules.max)
  }
  return null
}

export interface RemoteValidationConfig {
  url: string
  method: 'GET' | 'POST'
  message: string
}

/**
 * Run a remote custom validator. The endpoint should return JSON shaped like
 * { valid: true } or { valid: false, message?: string }. Network failures,
 * non-2xx responses, invalid JSON, and missing valid: true all fail closed
 * with the configured fallback message.
 */
export async function validateRemote(
  value: unknown,
  config: RemoteValidationConfig
): Promise<string | null> {
  try {
    const res =
      config.method === 'GET'
        ? await fetch(withValueQuery(config.url, value))
        : await fetch(config.url, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ value })
          })
    const data = await res.json().catch(() => null)
    if (res.ok && data?.valid === true) return null
    return typeof data?.message === 'string' && data.message.trim() !== ''
      ? data.message
      : config.message
  } catch {
    return config.message
  }
}

function withValueQuery(url: string, value: unknown): string {
  const out = new URL(url, window.location.origin)
  out.searchParams.set('value', value == null ? '' : String(value))
  return out.toString()
}
`
}

/**
 * Build the page-level validation glue (a block of indented lines) for a page
 * with ≥1 validated field. Emitted into the page component's hook lines, after
 * the doc-state hoists (the custom-rule expressions reference them).
 */
export function buildValidationGlue(fields: readonly IRFieldValidation[]): string {
  const validators = fields.map((f) => buildValidatorEntry(f)).join('\n')
  return [
    `  const [__fieldErrors, __setFieldErrors] = useState<Record<string, string | null>>({})`,
    `  const __validators: Record<string, (valueOverride?: unknown, includeAsync?: boolean) => Promise<string | null>> = {`,
    validators,
    `  }`,
    `  const __validateField = async (id: string): Promise<string | null> => {`,
    `    const __fn = __validators[id]`,
    `    const __error = __fn ? await __fn() : null`,
    `    __setFieldErrors((prev) => ({ ...prev, [id]: __error }))`,
    `    return __error`,
    `  }`,
    `  const __validateFieldValue = async (id: string, value: unknown, includeAsync = false): Promise<string | null> => {`,
    `    const __fn = __validators[id]`,
    `    const __error = __fn ? await __fn(value, includeAsync) : null`,
    `    __setFieldErrors((prev) => ({ ...prev, [id]: __error }))`,
    `    return __error`,
    `  }`,
    `  const __validateFields = async (ids: string[]): Promise<boolean> => {`,
    `    const __next: Record<string, string | null> = {}`,
    `    let __ok = true`,
    `    for (const id of ids) {`,
    `      const __fn = __validators[id]`,
    `      const __error = __fn ? await __fn() : null`,
    `      __next[id] = __error`,
    `      if (__error !== null) __ok = false`,
    `    }`,
    `    __setFieldErrors((prev) => ({ ...prev, ...__next }))`,
    `    return __ok`,
    `  }`
  ].join('\n')
}

/** One `"<key>": (__valueOverride?: unknown) => { ... }` entry in the
 *  `__validators` map. */
function buildValidatorEntry(field: IRFieldValidation): string {
  const read =
    field.stateKind === 'docState'
      ? `getDocStateSnapshot(${JSON.stringify(field.stateName)})`
      : field.stateName
  const lines = [
    `    ${JSON.stringify(field.key)}: async (__valueOverride?: unknown, __includeAsync = true) => {`,
    `      const __value = __valueOverride !== undefined ? __valueOverride : ${read}`,
    `      let __error = validateValue(__value, ${JSON.stringify(field.rules)})`
  ]
  if (field.custom) {
    // The custom rule is valid when the expression is truthy → the message
    // shows when it is falsy (and no core rule already failed).
    lines.push(
      `      if (__error === null && !(${emitExpression(field.custom.ast)})) __error = ${JSON.stringify(field.custom.message)}`
    )
  }
  if (field.async) {
    lines.push(
      `      if (__includeAsync && __error === null) __error = await validateRemote(__value, ${asyncValidationConfig(field)})`
    )
  }
  lines.push(`      return __error`, `    },`)
  return lines.join('\n')
}

function asyncValidationConfig(field: IRFieldValidation): string {
  const async = field.async
  if (!async) return '{}'
  const url =
    async.urlAst !== undefined
      ? `url: ${emitExpression(async.urlAst)}`
      : `url: ${JSON.stringify(async.urlLiteral ?? '')}`
  return `{ ${url}, method: ${JSON.stringify(async.method)}, message: ${JSON.stringify(async.message)} }`
}

/** Whether any validated field reads its value fresh via `getDocStateSnapshot`
 *  (i.e. is doc-state bound) — drives the runtime-state import. */
export function validationUsesDocStateSnapshot(fields: readonly IRFieldValidation[]): boolean {
  return fields.some((f) => f.stateKind === 'docState')
}

export function validationUsesRemote(fields: readonly IRFieldValidation[]): boolean {
  return fields.some((f) => f.async !== undefined)
}
