import type { IRMotion, IRMotionKeyframe, IRMotionPoint, IRMotionTrack } from '#compiler/ir/motion'

import { colorToCSS } from '@open-pencil/core/color'
import { TRANSPARENT } from '@open-pencil/core/constants'

import {
  compareMotionTrackComposition,
  easingCSS,
  motionCompositionClockVariableName,
  motionCompositionChannels,
  type MotionCompositionChannel,
  motionCompositionVariableName,
  motionCompositionWeightVariableName,
  motionCSSAnimationName,
  motionCSSVariableName
} from './key'
import {
  motionTargetKind,
  vectorMotionBaseDeclarations,
  vectorMotionPropertyRegistrations,
  VECTOR_MOTION_FILL,
  VECTOR_MOTION_STROKE,
  VECTOR_MOTION_STROKE_WIDTH,
  VECTOR_MOTION_TRIM_HIDDEN,
  VECTOR_MOTION_TRIM_OFFSET,
  VECTOR_MOTION_TRIM_VISIBLE
} from './target'
import type { ReactMotionEntry } from './types'

export function buildMotionCSS(entries: readonly ReactMotionEntry[]): string | undefined {
  const active = entries
    .filter((entry) => entry.motion.version !== 3)
    .map((entry) => ({
      ...entry,
      tracks: entry.motion.tracks
        .map((track, index) => ({ track, index }))
        .filter(
          ({ track }) =>
            track.trigger === 'mount' || track.trigger === 'pageEnter' || track.trigger === 'loop'
        )
    }))
    .filter((entry) => entry.tracks.length > 0)
  const registrations = [
    ...vectorMotionPropertyRegistrations(entries.map((entry) => entry.motion)),
    ...entries.flatMap(compositionPropertyRegistrations)
  ]
  const bases = entries.map((entry) => ({
    entry,
    declarations: [
      ...vectorMotionBaseDeclarations(entry.motion),
      ...compositionBaseDeclarations(entry)
    ]
  }))
  if (
    active.length === 0 &&
    registrations.length === 0 &&
    bases.every(({ declarations }) => declarations.length === 0)
  ) {
    return undefined
  }

  const blocks: string[] = ['/* Generated by OpenPencil. */', ...registrations]
  for (const { entry, declarations } of bases) {
    if (declarations.length > 0) {
      blocks.push(`[data-op-motion="${entry.token}"] {\n${indent(declarations.join('\n'))}\n}`)
    }
  }
  for (const entry of active) {
    for (const item of entry.tracks) {
      blocks.push(
        keyframesBlock(motionCSSAnimationName(entry.token, item.index), item.track, entry.motion)
      )
    }
    blocks.push(animationRule(entry.token, entry.tracks))
  }

  const reduced = active.filter((entry) => entry.motion.reducedMotion !== 'allow')
  if (reduced.length > 0) {
    const media: string[] = []
    for (const entry of reduced) {
      if (entry.motion.reducedMotion === 'disable') {
        media.push(`[data-op-motion="${entry.token}"] {\n  animation: none !important;\n}`)
        continue
      }
      for (const item of entry.tracks) {
        if (!hasOpacity(item.track)) continue
        media.push(
          keyframesBlock(
            motionCSSAnimationName(entry.token, item.index, true),
            opacityOnlyTrack(item.track),
            entry.motion
          )
        )
      }
      media.push(reducedAnimationRule(entry.token, entry.tracks))
    }
    blocks.push(`@media (prefers-reduced-motion: reduce) {\n${indent(media.join('\n\n'))}\n}`)
  }
  return `${blocks.join('\n\n')}\n`
}

interface IndexedTrack {
  track: IRMotionTrack
  index: number
}

function compositionPropertyRegistrations(entry: ReactMotionEntry): string[] {
  if (entry.motion.version !== 3) return []
  return entry.motion.tracks.flatMap((track, index) => {
    const sourceIndex = track.composition?.sourceIndex ?? index
    const initialValue = track.composition?.mode === 'accumulate' ? 0 : undefined
    const channels = motionCompositionChannels(track)
    return [
      compositionPropertyRegistration(
        motionCompositionClockVariableName(entry.token, sourceIndex),
        0
      ),
      ...(channels.length > 0
        ? [
            compositionPropertyRegistration(
              motionCompositionWeightVariableName(entry.token, sourceIndex),
              0
            )
          ]
        : []),
      ...channels.map((channel) =>
        compositionPropertyRegistration(
          motionCompositionVariableName(entry.token, sourceIndex, channel),
          initialValue ?? compositionIdentity(channel)
        )
      )
    ]
  })
}

function compositionPropertyRegistration(name: string, initialValue: number): string {
  return `@property ${name} {\n  syntax: "<number>";\n  inherits: false;\n  initial-value: ${number(initialValue)};\n}`
}

function compositionBaseDeclarations(entry: ReactMotionEntry): string[] {
  const motion = entry.motion
  if (motion.version !== 3) return []
  const tracks = [...motion.tracks].sort(compareMotionTrackComposition)
  const expression = (channel: MotionCompositionChannel): string | undefined => {
    let current = String(compositionIdentity(channel))
    let hasChannel = false
    for (let fallbackIndex = 0; fallbackIndex < tracks.length; fallbackIndex++) {
      const track = tracks[fallbackIndex]
      if (!motionCompositionChannels(track).includes(channel)) continue
      hasChannel = true
      const composition = track.composition ?? {
        mode: 'replace' as const,
        weight: 1,
        priority: 0,
        sourceIndex: fallbackIndex
      }
      current = composeChannelExpression(
        current,
        `var(${motionCompositionVariableName(entry.token, composition.sourceIndex, channel)})`,
        channel,
        composition.mode,
        `var(${motionCompositionWeightVariableName(entry.token, composition.sourceIndex)})`
      )
    }
    return hasChannel ? current : undefined
  }
  const opacity = expression('opacity')
  const x = expression('x')
  const y = expression('y')
  const scaleX = expression('scaleX')
  const scaleY = expression('scaleY')
  const rotate = expression('rotate')
  const declarations: string[] = []
  if (opacity) {
    declarations.push(
      `opacity: clamp(0, calc(${number(motion.authoredTransform?.opacity ?? 1)} * ${opacity}), 1);`
    )
  }
  if (x || y) {
    declarations.push(`translate: calc(${x ?? 0} * 1px) calc(${y ?? 0} * 1px);`)
  }
  if (scaleX || scaleY) {
    declarations.push(
      `scale: clamp(0, calc(${scaleX ?? 1}), 100) clamp(0, calc(${scaleY ?? 1}), 100);`
    )
  }
  if (rotate) {
    declarations.push(
      `rotate: calc(${number(motion.authoredTransform?.rotate ?? 0)}deg + ${rotate} * 1deg);`
    )
  }
  return declarations
}

function composeChannelExpression(
  current: string,
  sample: string,
  channel: MotionCompositionChannel,
  mode: NonNullable<IRMotionTrack['composition']>['mode'],
  weight: string
): string {
  if (mode === 'replace') {
    return `((${current}) * (1 - ${weight}) + (${sample}) * ${weight})`
  }
  const contribution =
    mode === 'accumulate' ? sample : `((${sample}) - ${number(compositionIdentity(channel))})`
  return `((${current}) + (${contribution}) * ${weight})`
}

function compositionIdentity(channel: MotionCompositionChannel): number {
  return channel === 'opacity' || channel === 'scaleX' || channel === 'scaleY' ? 1 : 0
}

function animationRule(token: string, tracks: readonly IndexedTrack[]): string {
  return [
    `[data-op-motion="${token}"] {`,
    propertyList(
      'animation-name',
      tracks,
      ({ index }) =>
        `var(${motionCSSVariableName(token, index)}, ${motionCSSAnimationName(token, index)})`
    ),
    propertyList('animation-duration', tracks, ({ track }) => `${track.timing.durationMs}ms`),
    propertyList('animation-delay', tracks, ({ track }) => `${track.timing.delayMs}ms`),
    propertyList('animation-timing-function', tracks, ({ track }) =>
      easingCSS(track.timing.easing)
    ),
    propertyList('animation-iteration-count', tracks, ({ track }) =>
      String(track.timing.iterations)
    ),
    propertyList('animation-direction', tracks, ({ track }) => track.timing.direction),
    propertyList('animation-fill-mode', tracks, ({ track }) => track.timing.fill),
    '}'
  ].join('\n')
}

function reducedAnimationRule(token: string, tracks: readonly IndexedTrack[]): string {
  return [
    `[data-op-motion="${token}"] {`,
    propertyList('animation-name', tracks, (item) =>
      hasOpacity(item.track)
        ? `var(${motionCSSVariableName(token, item.index)}, ${motionCSSAnimationName(token, item.index, true)})`
        : 'none'
    ),
    propertyList(
      'animation-duration',
      tracks,
      ({ track }) => `${Math.min(track.timing.durationMs, 120)}ms`
    ),
    propertyList('animation-delay', tracks, () => '0ms'),
    '}'
  ].join('\n')
}

function propertyList(
  name: string,
  tracks: readonly IndexedTrack[],
  value: (item: IndexedTrack) => string
): string {
  return `  ${name}: ${tracks.map(value).join(', ')};`
}

function keyframesBlock(name: string, track: IRMotionTrack, motion: IRMotion): string {
  const body = track.keyframes
    .map((frame) => {
      const declarations = keyframeDeclarations(frame, track, motion)
      return `  ${percent(frame.offset)} {${declarations.length > 0 ? `\n${indent(declarations.join('\n'), 4)}\n  ` : ''}}`
    })
    .join('\n')
  return `@keyframes ${name} {\n${body}\n}`
}

function keyframeDeclarations(
  frame: IRMotionKeyframe,
  track: IRMotionTrack,
  motion: IRMotion
): string[] {
  const hasPath = frame.pathProgress !== undefined && track.path !== undefined
  return [
    ...transformDeclarations(frame, hasPath),
    ...geometryDeclarations(frame),
    ...paintDeclarations(frame, motion),
    ...effectDeclarations(frame, motion),
    ...pathDeclarations(frame, track, motion),
    ...layoutDeclarations(frame),
    ...(frame.easing ? [`animation-timing-function: ${easingCSS(frame.easing)};`] : [])
  ]
}

function transformDeclarations(frame: IRMotionKeyframe, pathOwnsTranslation = false): string[] {
  const declarations: string[] = []
  if (frame.opacity !== undefined) declarations.push(`opacity: ${number(frame.opacity)};`)
  if (!pathOwnsTranslation && (frame.x !== undefined || frame.y !== undefined)) {
    declarations.push(`translate: ${number(frame.x ?? 0)}px ${number(frame.y ?? 0)}px;`)
  }
  if (frame.scaleX !== undefined || frame.scaleY !== undefined) {
    declarations.push(`scale: ${number(frame.scaleX ?? 1)} ${number(frame.scaleY ?? 1)};`)
  }
  if (frame.rotate !== undefined) declarations.push(`rotate: ${number(frame.rotate)}deg;`)
  if (frame.originX !== undefined || frame.originY !== undefined) {
    declarations.push(
      `transform-origin: ${percent(frame.originX ?? 0.5)} ${percent(frame.originY ?? 0.5)};`
    )
  }
  return declarations
}

function geometryDeclarations(frame: IRMotionKeyframe): string[] {
  const declarations: string[] = []
  if (frame.width !== undefined) declarations.push(`width: ${number(frame.width)}px;`)
  if (frame.height !== undefined) declarations.push(`height: ${number(frame.height)}px;`)
  if (frame.cornerRadius !== undefined) {
    declarations.push(`border-radius: ${number(frame.cornerRadius)}px;`)
  }
  return declarations
}

function paintDeclarations(frame: IRMotionKeyframe, motion: IRMotion): string[] {
  const declarations: string[] = []
  const target = motion.target
  const kind = motionTargetKind(motion)
  if (frame.fillColor && target?.fillColor) {
    declarations.push(`${CSS_FILL_PROPERTY[kind]}: ${colorToCSS(frame.fillColor)};`)
  }
  if (frame.strokeColor && target?.strokeColor) {
    declarations.push(`${CSS_STROKE_PROPERTY[kind]}: ${colorToCSS(frame.strokeColor)};`)
  }
  if (frame.strokeWidth !== undefined && target?.strokeWidth !== undefined) {
    declarations.push(
      `${CSS_STROKE_WIDTH_PROPERTY[kind]}: ${number(frame.strokeWidth)}${kind === 'vector' ? '' : 'px'};`
    )
  }
  return declarations
}

const CSS_FILL_PROPERTY = {
  box: 'background-color',
  text: 'color',
  vector: VECTOR_MOTION_FILL
} as const

const CSS_STROKE_PROPERTY = {
  box: 'border-color',
  text: '-webkit-text-stroke-color',
  vector: VECTOR_MOTION_STROKE
} as const

const CSS_STROKE_WIDTH_PROPERTY = {
  box: 'border-width',
  text: '-webkit-text-stroke-width',
  vector: VECTOR_MOTION_STROKE_WIDTH
} as const

function effectDeclarations(frame: IRMotionKeyframe, motion: IRMotion): string[] {
  const declarations: string[] = []
  const kind = motionTargetKind(motion)
  const hasShadow =
    frame.shadowX !== undefined ||
    frame.shadowY !== undefined ||
    frame.shadowBlur !== undefined ||
    frame.shadowSpread !== undefined ||
    frame.shadowColor !== undefined
  if (kind === 'vector') {
    const filters: string[] = []
    if (frame.blur !== undefined) filters.push(`blur(${number(frame.blur)}px)`)
    if (hasShadow) filters.push(vectorDropShadow(frame))
    if (filters.length > 0) declarations.push(`filter: ${filters.join(' ')};`)
  } else if (frame.blur !== undefined) {
    declarations.push(`filter: blur(${number(frame.blur)}px);`)
  }
  if (hasShadow && kind === 'text') {
    declarations.push(`text-shadow: ${textShadowValue(frame)};`)
  } else if (hasShadow && kind === 'box') {
    declarations.push(`box-shadow: ${boxShadowValue(frame)};`)
  }
  return declarations
}

function pathDeclarations(
  frame: IRMotionKeyframe,
  track: IRMotionTrack,
  motion: IRMotion
): string[] {
  const declarations: string[] = []
  if (frame.pathProgress !== undefined && track.path) {
    const originX = frame.originX ?? 0.5
    const originY = frame.originY ?? 0.5
    const anchorX = (frame.width ?? 0) * originX + (frame.x ?? 0)
    const anchorY = (frame.height ?? 0) * originY + (frame.y ?? 0)
    declarations.push(`offset-path: ${offsetPath(track.path.points, anchorX, anchorY)};`)
    declarations.push(`offset-distance: ${percent(frame.pathProgress)};`)
    declarations.push(`offset-anchor: ${percent(originX)} ${percent(originY)};`)
    declarations.push(`offset-rotate: ${track.path.autoRotate ? 'auto' : '0deg'};`)
  }
  if (
    motionTargetKind(motion) === 'vector' &&
    motion.target?.strokeColor &&
    (frame.trimStart !== undefined || frame.trimEnd !== undefined)
  ) {
    const start = frame.trimStart ?? 0
    const end = frame.trimEnd ?? 1
    declarations.push(`${VECTOR_MOTION_TRIM_VISIBLE}: ${number(Math.max(0, end - start))};`)
    declarations.push(`${VECTOR_MOTION_TRIM_HIDDEN}: ${number(1 - Math.max(0, end - start))};`)
    declarations.push(
      `${VECTOR_MOTION_TRIM_OFFSET}: ${number(-(start + (frame.trimOffset ?? 0)))};`
    )
  }
  return declarations
}

function boxShadowValue(frame: IRMotionKeyframe): string {
  return `${number(frame.shadowX ?? 0)}px ${number(frame.shadowY ?? 0)}px ${number(frame.shadowBlur ?? 0)}px ${number(frame.shadowSpread ?? 0)}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)}`
}

function textShadowValue(frame: IRMotionKeyframe): string {
  return `${number(frame.shadowX ?? 0)}px ${number(frame.shadowY ?? 0)}px ${number(spreadlessShadowBlur(frame))}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)}`
}

function vectorDropShadow(frame: IRMotionKeyframe): string {
  return `drop-shadow(${number(frame.shadowX ?? 0)}px ${number(frame.shadowY ?? 0)}px ${number(spreadlessShadowBlur(frame))}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)})`
}

function spreadlessShadowBlur(frame: IRMotionKeyframe): number {
  // text-shadow/drop-shadow have no spread term; fold it into a non-negative blur.
  return Math.max(0, (frame.shadowBlur ?? 0) + (frame.shadowSpread ?? 0))
}

function layoutDeclarations(frame: IRMotionKeyframe): string[] {
  const declarations: string[] = []
  if (frame.gap !== undefined) declarations.push(`gap: ${number(frame.gap)}px;`)
  if (frame.rowGap !== undefined) declarations.push(`row-gap: ${number(frame.rowGap)}px;`)
  if (frame.columnGap !== undefined) {
    declarations.push(`column-gap: ${number(frame.columnGap)}px;`)
  }
  if (frame.paddingTop !== undefined) {
    declarations.push(`padding-top: ${number(frame.paddingTop)}px;`)
  }
  if (frame.paddingRight !== undefined) {
    declarations.push(`padding-right: ${number(frame.paddingRight)}px;`)
  }
  if (frame.paddingBottom !== undefined) {
    declarations.push(`padding-bottom: ${number(frame.paddingBottom)}px;`)
  }
  if (frame.paddingLeft !== undefined) {
    declarations.push(`padding-left: ${number(frame.paddingLeft)}px;`)
  }
  return declarations
}

function opacityOnly(frame: IRMotionKeyframe): IRMotionKeyframe {
  return {
    offset: frame.offset,
    ...(frame.opacity !== undefined ? { opacity: frame.opacity } : {}),
    ...(frame.easing ? { easing: frame.easing } : {})
  }
}

function opacityOnlyTrack(track: IRMotionTrack): IRMotionTrack {
  const { path: _, ...rest } = track
  return { ...rest, keyframes: track.keyframes.map(opacityOnly) }
}

function hasOpacity(track: IRMotionTrack): boolean {
  return track.keyframes.some((frame) => frame.opacity !== undefined)
}

function number(value: number): string {
  return Object.is(value, -0) ? '0' : String(value)
}

function offsetPath(points: readonly IRMotionPoint[], anchorX = 0, anchorY = 0): string {
  const [first, ...rest] = points
  const commands = [
    `M ${number(first.x + anchorX)} ${number(first.y + anchorY)}`,
    ...rest.map((point) => `L ${number(point.x + anchorX)} ${number(point.y + anchorY)}`)
  ]
  return `path("${commands.join(' ')}")`
}

function percent(offset: number): string {
  return `${number(offset * 100)}%`
}

function indent(value: string, spaces = 2): string {
  const pad = ' '.repeat(spaces)
  return value
    .split('\n')
    .map((line) => `${pad}${line}`)
    .join('\n')
}
