import type { IRMotionKeyframe, IRMotionTrack } from '#compiler/ir/motion'

import { easingCss } from './key'
import type { ReactMotionEntry } from './types'

export function buildMotionCss(entries: readonly ReactMotionEntry[]): string | undefined {
  const active = entries
    .map((entry) => ({
      ...entry,
      tracks: entry.motion.tracks
        .map((track, index) => ({ track, index }))
        .filter(({ track }) => track.trigger === 'mount' || track.trigger === 'loop')
    }))
    .filter((entry) => entry.tracks.length > 0)
  if (active.length === 0) return undefined

  const blocks: string[] = ['/* Generated by OpenPencil. */']
  for (const entry of active) {
    for (const item of entry.tracks) {
      blocks.push(keyframesBlock(animationName(entry.token, item.index), item.track.keyframes))
    }
    blocks.push(animationRule(entry.token, entry.tracks))
  }

  const reduced = active.filter((entry) => entry.motion.reducedMotion !== 'allow')
  if (reduced.length > 0) {
    const media: string[] = []
    for (const entry of reduced) {
      if (entry.motion.reducedMotion === 'disable') {
        media.push(`[data-op-motion="${entry.token}"] {\n  animation: none !important;\n}`)
        continue
      }
      for (const item of entry.tracks) {
        if (!hasOpacity(item.track)) continue
        media.push(
          keyframesBlock(
            reducedAnimationName(entry.token, item.index),
            item.track.keyframes.map(opacityOnly)
          )
        )
      }
      media.push(reducedAnimationRule(entry.token, entry.tracks))
    }
    blocks.push(`@media (prefers-reduced-motion: reduce) {\n${indent(media.join('\n\n'))}\n}`)
  }
  return `${blocks.join('\n\n')}\n`
}

interface IndexedTrack {
  track: IRMotionTrack
  index: number
}

function animationRule(token: string, tracks: readonly IndexedTrack[]): string {
  return [
    `[data-op-motion="${token}"] {`,
    propertyList('animation-name', tracks, ({ index }) => animationName(token, index)),
    propertyList('animation-duration', tracks, ({ track }) => `${track.timing.durationMs}ms`),
    propertyList('animation-delay', tracks, ({ track }) => `${track.timing.delayMs}ms`),
    propertyList('animation-timing-function', tracks, ({ track }) =>
      easingCss(track.timing.easing)
    ),
    propertyList('animation-iteration-count', tracks, ({ track }) =>
      String(track.timing.iterations)
    ),
    propertyList('animation-direction', tracks, ({ track }) => track.timing.direction),
    propertyList('animation-fill-mode', tracks, ({ track }) => track.timing.fill),
    '}'
  ].join('\n')
}

function reducedAnimationRule(token: string, tracks: readonly IndexedTrack[]): string {
  return [
    `[data-op-motion="${token}"] {`,
    propertyList('animation-name', tracks, (item) =>
      hasOpacity(item.track) ? reducedAnimationName(token, item.index) : 'none'
    ),
    propertyList(
      'animation-duration',
      tracks,
      ({ track }) => `${Math.min(track.timing.durationMs, 120)}ms`
    ),
    propertyList('animation-delay', tracks, () => '0ms'),
    '}'
  ].join('\n')
}

function propertyList(
  name: string,
  tracks: readonly IndexedTrack[],
  value: (item: IndexedTrack) => string
): string {
  return `  ${name}: ${tracks.map(value).join(', ')};`
}

function keyframesBlock(name: string, frames: readonly IRMotionKeyframe[]): string {
  const body = frames
    .map((frame) => {
      const declarations = keyframeDeclarations(frame)
      return `  ${percent(frame.offset)} {${declarations.length > 0 ? `\n${indent(declarations.join('\n'), 4)}\n  ` : ''}}`
    })
    .join('\n')
  return `@keyframes ${name} {\n${body}\n}`
}

function keyframeDeclarations(frame: IRMotionKeyframe): string[] {
  const declarations: string[] = []
  if (frame.opacity !== undefined) declarations.push(`opacity: ${number(frame.opacity)};`)
  if (frame.x !== undefined || frame.y !== undefined) {
    declarations.push(`translate: ${number(frame.x ?? 0)}px ${number(frame.y ?? 0)}px;`)
  }
  if (frame.scaleX !== undefined || frame.scaleY !== undefined) {
    declarations.push(`scale: ${number(frame.scaleX ?? 1)} ${number(frame.scaleY ?? 1)};`)
  }
  if (frame.rotate !== undefined) declarations.push(`rotate: ${number(frame.rotate)}deg;`)
  if (frame.easing) declarations.push(`animation-timing-function: ${easingCss(frame.easing)};`)
  return declarations
}

function opacityOnly(frame: IRMotionKeyframe): IRMotionKeyframe {
  return {
    offset: frame.offset,
    ...(frame.opacity !== undefined ? { opacity: frame.opacity } : {}),
    ...(frame.easing ? { easing: frame.easing } : {})
  }
}

function hasOpacity(track: IRMotionTrack): boolean {
  return track.keyframes.some((frame) => frame.opacity !== undefined)
}

function animationName(token: string, index: number): string {
  return `op-${token}-${index}`
}

function reducedAnimationName(token: string, index: number): string {
  return `op-${token}-${index}-reduced`
}

function number(value: number): string {
  return Object.is(value, -0) ? '0' : String(value)
}

function percent(offset: number): string {
  return `${number(offset * 100)}%`
}

function indent(value: string, spaces = 2): string {
  const pad = ' '.repeat(spaces)
  return value
    .split('\n')
    .map((line) => `${pad}${line}`)
    .join('\n')
}
