/* eslint-disable max-lines -- the emitted zero-dependency runtime stays self-contained */
import type { IRMotion, IRMotionKeyframe, IRMotionTrack } from '#compiler/ir/motion'

import { colorToCSS } from '@open-pencil/core/color'
import { TRANSPARENT } from '@open-pencil/core/constants'
import { buildMotionRuntimeKernelSource } from '@open-pencil/motion-runtime/kernel'

import {
  compareMotionTrackComposition,
  easingCss,
  motionCompositionClockVariableName,
  motionCompositionChannels,
  motionCompositionVariableName,
  motionCompositionWeightVariableName,
  motionCssAnimationName,
  motionCssVariableName
} from './key'
import {
  motionTargetKind,
  VECTOR_MOTION_FILL,
  VECTOR_MOTION_STROKE,
  VECTOR_MOTION_STROKE_WIDTH,
  VECTOR_MOTION_TRIM_HIDDEN,
  VECTOR_MOTION_TRIM_OFFSET,
  VECTOR_MOTION_TRIM_VISIBLE
} from './target'
import type { ReactMotionEntry } from './types'

const RUNTIME_TRIGGERS = new Set(['pageExit', 'hover', 'press', 'focus', 'click', 'inView'])

/** Build the zero-dependency delegated WAAPI runtime. */
export function buildMotionRuntime(
  entries: readonly ReactMotionEntry[],
  includeProgrammaticTracks = false,
  devMode = false,
  forceRuntime = false
): string | undefined {
  const runtimeEntries = entries.filter(
    (entry) =>
      entry.motion.version === 3 ||
      includeProgrammaticTracks ||
      entry.motion.tracks.some((track) => RUNTIME_TRIGGERS.has(track.trigger))
  )
  const registry = Object.fromEntries(
    entries.map((entry) => [
      entry.token,
      {
        ...(entry.motion.version === 3 ? { version: 3 as const } : {}),
        reducedMotion: entry.motion.reducedMotion,
        tracks: (entry.motion.version === 3
          ? [...entry.motion.tracks].sort(compareMotionTrackComposition)
          : entry.motion.tracks
        ).map((track, index) => runtimeTrack(track, entry.token, index, entry.motion))
      }
    ])
  )
  if (runtimeEntries.length === 0 && !includeProgrammaticTracks && !devMode && !forceRuntime) {
    return undefined
  }

  // oxlint-disable-next-line open-pencil/no-hand-rolled-color -- The generated dependency-free runtime must serialize sampled colors without importing OpenPencil.
  return `/* Generated by OpenPencil. */
export {}

type MotionTrigger =
  | 'mount'
  | 'pageEnter'
  | 'pageExit'
  | 'hover'
  | 'press'
  | 'focus'
  | 'click'
  | 'inView'
  | 'loop'
type MotionExit = 'none' | 'reverse' | 'reset'
type MotionSamplingChannel = 'opacity' | 'x' | 'y' | 'scaleX' | 'scaleY' | 'rotate'
type MotionEasingName = 'linear' | 'ease' | 'ease-in' | 'ease-out' | 'ease-in-out'
type MotionSamplingEasing =
  | MotionEasingName
  | { type: 'cubicBezier'; x1: number; y1: number; x2: number; y2: number }
  | { type: 'hold' }
  | { type: 'steps'; steps: number; position: 'start' | 'end' }
  | { type: 'spring'; mass: number; stiffness: number; damping: number; velocity: number }
  | { type: 'inertia'; velocity: number; deceleration: number }

${buildMotionRuntimeKernelSource()}

interface MotionSamplingFrame {
  offset: number
  values: Partial<Record<MotionSamplingChannel, number>>
  easing?: MotionSamplingEasing
}

interface MotionFrame {
  [property: string]: string | number | undefined
  offset: number
  opacity?: number
  translate?: string
  scale?: string
  rotate?: string
  transformOrigin?: string
  width?: string
  height?: string
  borderRadius?: string
  backgroundColor?: string
  borderColor?: string
  borderWidth?: string
  color?: string
  WebkitTextStrokeColor?: string
  WebkitTextStrokeWidth?: string
  textShadow?: string
  filter?: string
  boxShadow?: string
  offsetPath?: string
  offsetDistance?: string
  offsetAnchor?: string
  offsetRotate?: string
  strokeDasharray?: string
  strokeDashoffset?: string
  '${VECTOR_MOTION_FILL}'?: string
  '${VECTOR_MOTION_STROKE}'?: string
  '${VECTOR_MOTION_STROKE_WIDTH}'?: string
  '${VECTOR_MOTION_TRIM_VISIBLE}'?: string
  '${VECTOR_MOTION_TRIM_HIDDEN}'?: string
  '${VECTOR_MOTION_TRIM_OFFSET}'?: string
  gap?: string
  rowGap?: string
  columnGap?: string
  paddingTop?: string
  paddingRight?: string
  paddingBottom?: string
  paddingLeft?: string
  easing?: string
}

interface MotionAdvancedColor {
  r: number
  g: number
  b: number
  a: number
}

interface MotionAdvancedPaintTarget {
  kind: 'fill' | 'stroke'
  index: number
  color?: MotionAdvancedColor
  opacity?: number
}

interface MotionAdvancedGradientStopTarget {
  kind: 'fill' | 'stroke'
  paintIndex: number
  stopIndex: number
  position: number
  color: MotionAdvancedColor
}

type MotionAdvancedEffectTarget =
  | { kind: 'blur'; index: number; radius: number }
  | {
      kind: 'shadow'
      index: number
      x: number
      y: number
      blur: number
      spread: number
      color: MotionAdvancedColor
    }

interface MotionAdvancedCornerRadii {
  topLeft: number
  topRight: number
  bottomRight: number
  bottomLeft: number
}

interface MotionAdvancedFrame {
  offset: number
  paints?: MotionAdvancedPaintTarget[]
  gradientStops?: MotionAdvancedGradientStopTarget[]
  effects?: MotionAdvancedEffectTarget[]
  cornerRadii?: MotionAdvancedCornerRadii
  textReveal?: number
  fontAxes?: Array<{ tag: string; value: number }>
  vectorMorph?: { topologyId: string; paths: string[] }
  easing?: MotionSamplingEasing
}

interface MotionAdvancedFill {
  type:
    | 'SOLID'
    | 'GRADIENT_LINEAR'
    | 'GRADIENT_RADIAL'
    | 'GRADIENT_ANGULAR'
    | 'GRADIENT_DIAMOND'
    | 'UNSUPPORTED'
  color: MotionAdvancedColor
  opacity: number
  visible: boolean
  gradientStops?: Array<{ position: number; color: MotionAdvancedColor }>
  gradientTransform?: {
    m00: number
    m01: number
    m02: number
    m10: number
    m11: number
    m12: number
  }
}

interface MotionAdvancedTarget {
  kind: 'box' | 'text' | 'vector'
  fills?: MotionAdvancedFill[]
  strokes?: Array<{
    color: MotionAdvancedColor
    opacity: number
    visible: boolean
    weight: number
  }>
  effects?: Array<{
    type: 'DROP_SHADOW' | 'INNER_SHADOW' | 'LAYER_BLUR' | 'BACKGROUND_BLUR' | 'FOREGROUND_BLUR'
    color: MotionAdvancedColor
    x: number
    y: number
    radius: number
    spread: number
    visible: boolean
  }>
  text?: string
  fontAxes?: Array<{ tag: string; value: number }>
  vectorMorph?: { topologyId: string; pathCount: number }
}

interface MotionAdvancedTrack {
  target: MotionAdvancedTarget
  easing: MotionSamplingEasing
  keyframes: MotionAdvancedFrame[]
}

interface MotionTrack {
  id: string
  trigger: MotionTrigger
  exit: MotionExit
  keyframes: MotionFrame[]
  timing: {
    duration: number
    delay: number
    easing: string
    iterations: number | 'infinite'
    direction: 'normal' | 'reverse' | 'alternate' | 'alternate-reverse'
    fill: 'none' | 'forwards' | 'backwards' | 'both'
  }
  composition?: {
    mode: 'replace' | 'add' | 'accumulate'
    weight: number
    priority: number
    sourceIndex: number
    clock: string
    weightVariable: string
    variables: Partial<Record<MotionSamplingChannel, string>>
    sampling: {
      easing: MotionSamplingEasing
      keyframes: MotionSamplingFrame[]
    }
  }
  css?: {
    variable: string
    animationNames: string[]
  }
  advanced?: MotionAdvancedTrack
}

interface MotionSpec {
  version?: 3
  reducedMotion: 'reduce' | 'disable' | 'allow'
  tracks: MotionTrack[]
}

interface ActiveTrack {
  track: MotionTrack
  animation: Animation
}

type MotionDebugSource = 'automatic' | 'controlled' | 'idle' | 'stopped'

interface MotionDebugEntry {
  readonly nodeId: string
  readonly token: string
  readonly reducedMotion: MotionSpec['reducedMotion']
  readonly trackId: string
  readonly trigger: MotionTrigger
  readonly source: MotionDebugSource
  readonly playState: AnimationPlayState
  readonly currentTime: number | null
  readonly progress: number | null
  readonly timing: Readonly<MotionTrack['timing']>
  readonly exit: MotionExit
  readonly stopped: boolean
}

interface MotionDebugSnapshot {
  readonly capturedAt: number
  readonly entries: readonly MotionDebugEntry[]
  readonly activeAnimationCount: number
}

type MotionWaitStatus = 'finished' | 'stopped' | 'timeout' | 'missing'

interface MotionWaitResult {
  readonly status: MotionWaitStatus
  readonly targetNodeId: string
  readonly trackId?: string
}

interface MotionWaitOptions {
  readonly timeoutMs?: number
  readonly stopOnTimeout?: boolean
}

interface MotionPageExitOptions {
  readonly timeoutMs?: number
}

interface MotionPageExitResult {
  readonly status: MotionWaitStatus
  readonly trackCount: number
  readonly animationCount: number
}

interface OpenPencilMotionRuntimeHandle {
  dispose: () => void
  inspect: (targetNodeId?: string, scope?: Element) => MotionDebugSnapshot
  pageExit: (options?: MotionPageExitOptions) => Promise<MotionPageExitResult>
  play: (targetNodeId: string, trackId?: string, scope?: Element) => void
  stop: (targetNodeId: string, trackId?: string, scope?: Element) => void
  toggle: (targetNodeId: string, trackId?: string, scope?: Element) => void
  wait: (
    targetNodeId: string,
    trackId?: string,
    scope?: Element,
    options?: MotionWaitOptions
  ) => Promise<MotionWaitResult>
}

declare global {
  interface Window {
    __OPENPENCIL_MOTION_RUNTIME__?: OpenPencilMotionRuntimeHandle
  }
}

const registry: Record<string, MotionSpec> = ${JSON.stringify(registry)}
const runtimeTokens = new Set<string>(${JSON.stringify(runtimeEntries.map((entry) => entry.token))})
const runtimeGlobal = globalThis as typeof globalThis & {
  __OPENPENCIL_MOTION_RUNTIME__?: OpenPencilMotionRuntimeHandle
}
runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__?.dispose()
const selector = '[data-op-motion]'
const runtimeDocument = typeof document === 'undefined' ? null : document
const active = new WeakMap<Element, Map<MotionTrigger, ActiveTrack[]>>()
const prepared = new WeakMap<Element, Map<string, ActiveTrack>>()
const automaticStopped = new WeakMap<Element, Set<string>>()
const controlled = new WeakMap<Element, Map<string, ActiveTrack>>()
const controlledProgress = new WeakMap<Element, Map<string, number>>()
const allAnimations = new Set<Animation>()
const observedAnimations = new WeakSet<Animation>()
const manualCompositions = new Map<Animation, { element: Element; track: MotionTrack }>()
const manualCompositionRecords = new WeakMap<
  Animation,
  { element: Element; track: MotionTrack }
>()
const pointerPresses = new Map<number, Element[]>()
const keyboardPresses = new Set<Element>()
const transientTriggers = new WeakMap<Element, Set<MotionTrigger>>()
const TRANSIENT_TRIGGERS = new Set<MotionTrigger>(['hover', 'press', 'focus', 'click', 'inView'])
const PAGE_EXIT_MAX_WAIT_MS = 4_000
let pageExitInFlight: Promise<MotionPageExitResult> | null = null
const manualFrameLoop = createMotionFrameLoop({
  clock: {
    now: () => Math.max(0, globalThis.performance?.now() ?? Date.now()),
    requestFrame: (callback: (timestampMs: number) => void) => requestAnimationFrame(callback),
    cancelFrame: (handle: unknown) => cancelAnimationFrame(handle as number)
  },
  onFrame: updateManualCompositions
})

function specFor(element: Element): MotionSpec | undefined {
  const token = element.getAttribute('data-op-motion')
  return token ? registry[token] : undefined
}

function managedSpecFor(element: Element): MotionSpec | undefined {
  const token = element.getAttribute('data-op-motion')
  return token && runtimeTokens.has(token) ? registry[token] : undefined
}

function matchingElements(
  root: ParentNode,
  targetNodeId: string,
  includeCssOnly = false
): Element[] {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  return elements.filter(
    (element) =>
      element.getAttribute('data-node-id') === targetNodeId &&
      (includeCssOnly ? specFor(element) : managedSpecFor(element))
  )
}

function elementsForNodeId(
  targetNodeId: string,
  scope?: Element,
  includeCssOnly = false
): Element[] {
  if (!runtimeDocument || typeof targetNodeId !== 'string' || targetNodeId.length === 0) return []
  if (scope instanceof Element) {
    let localRoot = scope.closest('[data-op-motion-scope]')
    if (!localRoot) {
      const scoped = matchingElements(scope, targetNodeId, includeCssOnly)
      if (scoped.length > 0) return scoped
    }
    while (localRoot) {
      const scoped = matchingElements(localRoot, targetNodeId, includeCssOnly)
      if (scoped.length > 0) return scoped
      localRoot = localRoot.parentElement?.closest('[data-op-motion-scope]') ?? null
    }
  }
  return matchingElements(runtimeDocument, targetNodeId, includeCssOnly)
}

function motionElements(target: EventTarget | null): Element[] {
  if (!(target instanceof Element)) return []
  const elements: Element[] = []
  for (let element: Element | null = target; element; element = element.parentElement) {
    if (element.matches(selector) && managedSpecFor(element)) elements.push(element)
  }
  return elements
}

const reducedMotionQuery =
  typeof window === 'undefined' || typeof window.matchMedia !== 'function'
    ? null
    : window.matchMedia('(prefers-reduced-motion: reduce)')

function prefersReducedMotion(): boolean {
  return reducedMotionQuery?.matches === true
}

const motionSamplingChannels: readonly MotionSamplingChannel[] = sharedMotionSamplingChannels

function samplingIdentity(channel: MotionSamplingChannel): number {
  return sharedMotionSamplingIdentity(channel)
}

function sampleRuntimeEasing(easing: MotionSamplingEasing, progress: number): number {
  return sharedSampleMotionRuntimeEasing(easing, progress)
}

function sampleRuntimeChannel(
  track: MotionTrack,
  channel: MotionSamplingChannel,
  progress: number
): number {
  return sharedSampleMotionRuntimeChannel(track, channel, progress)
}

function manualTrackProgress(track: MotionTrack, elapsedMs: number) {
  return sharedMotionRuntimeTrackProgress(track, elapsedMs)
}

interface MotionAdvancedStyleSnapshot {
  name: string
  value: string
  priority: string
}

interface MotionAdvancedAttributeSnapshot {
  element: Element
  name: string
  value: string | null
}

interface MotionAdvancedTextSnapshot {
  node: Text
  value: string
}

interface MotionAdvancedSnapshot {
  styles: MotionAdvancedStyleSnapshot[]
  attributes: MotionAdvancedAttributeSnapshot[]
  text: MotionAdvancedTextSnapshot[]
}

const advancedSnapshots = new WeakMap<Element, MotionAdvancedSnapshot>()
const advancedStyleNames = [
  'background-image',
  'background-color',
  'color',
  'border-color',
  'border-width',
  'border-style',
  'border-radius',
  'filter',
  'backdrop-filter',
  'box-shadow',
  'text-shadow',
  '-webkit-text-stroke-color',
  '-webkit-text-stroke-width',
  'font-variation-settings'
] as const
const advancedGeometryAttributeNames = [
  'd',
  'fill',
  'fill-opacity',
  'stroke',
  'stroke-opacity'
] as const

function advancedGeometry(element: Element): Element[] {
  return [...element.querySelectorAll('[data-op-node-id]')]
}

function captureAdvancedSnapshot(element: Element): MotionAdvancedSnapshot {
  const existing = advancedSnapshots.get(element)
  if (existing) return existing
  const style = cssStyleFor(element)
  const styles = style
    ? advancedStyleNames.map((name) => ({
        name,
        value: style.getPropertyValue(name),
        priority: style.getPropertyPriority(name)
      }))
    : []
  const attributes = advancedGeometry(element).flatMap((geometry) =>
    advancedGeometryAttributeNames.map((name) => ({
      element: geometry,
      name,
      value: geometry.getAttribute(name)
    }))
  )
  const text: MotionAdvancedTextSnapshot[] = []
  if (runtimeDocument) {
    const walker = runtimeDocument.createTreeWalker(element, 4)
    for (let node = walker.nextNode(); node; node = walker.nextNode()) {
      text.push({ node: node as Text, value: node.nodeValue ?? '' })
    }
  }
  const snapshot = { styles, attributes, text }
  advancedSnapshots.set(element, snapshot)
  return snapshot
}

function restoreAdvancedSnapshot(element: Element, forget = false): void {
  const snapshot = advancedSnapshots.get(element)
  if (!snapshot) return
  const style = cssStyleFor(element)
  if (style) {
    for (const item of snapshot.styles) {
      if (item.value) style.setProperty(item.name, item.value, item.priority)
      else style.removeProperty(item.name)
    }
  }
  for (const item of snapshot.attributes) {
    if (item.value === null) item.element.removeAttribute(item.name)
    else item.element.setAttribute(item.name, item.value)
  }
  for (const item of snapshot.text) item.node.nodeValue = item.value
  if (forget) advancedSnapshots.delete(element)
}

function interpolateAdvancedNumber(from: number, to: number, progress: number): number {
  return from + (to - from) * progress
}

function interpolateAdvancedColor(
  from: MotionAdvancedColor,
  to: MotionAdvancedColor,
  progress: number
): MotionAdvancedColor {
  return {
    r: Math.min(1, Math.max(0, interpolateAdvancedNumber(from.r, to.r, progress))),
    g: Math.min(1, Math.max(0, interpolateAdvancedNumber(from.g, to.g, progress))),
    b: Math.min(1, Math.max(0, interpolateAdvancedNumber(from.b, to.b, progress))),
    a: Math.min(1, Math.max(0, interpolateAdvancedNumber(from.a, to.a, progress)))
  }
}

interface MotionAdvancedTimedValue<T> {
  offset: number
  easing?: MotionSamplingEasing
  value: T
}

function sampleAdvancedValue<T>(
  track: MotionAdvancedTrack,
  progress: number,
  read: (frame: MotionAdvancedFrame) => T | undefined,
  clone: (value: T) => T,
  blend: (from: T, to: T, progress: number) => T
): T | undefined {
  const frames = track.keyframes.flatMap((frame): MotionAdvancedTimedValue<T>[] => {
    const value = read(frame)
    return value === undefined
      ? []
      : [{ offset: frame.offset, easing: frame.easing, value }]
  })
  if (frames.length === 0) return undefined
  let startIndex = 0
  for (let index = 1; index < frames.length; index++) {
    if (frames[index].offset > progress) break
    startIndex = index
  }
  const start = frames[startIndex]
  const end = frames[startIndex + 1]
  if (!end || progress <= start.offset) return clone(start.value)
  const span = end.offset - start.offset
  if (span <= 0) return clone(end.value)
  const eased = sampleRuntimeEasing(
    start.easing ?? track.easing,
    (progress - start.offset) / span
  )
  return blend(start.value, end.value, eased)
}

function cloneAdvancedPaints(values: MotionAdvancedPaintTarget[]): MotionAdvancedPaintTarget[] {
  return values.map((value) => ({
    ...value,
    ...(value.color ? { color: { ...value.color } } : {})
  }))
}

function blendAdvancedPaints(
  from: MotionAdvancedPaintTarget[],
  to: MotionAdvancedPaintTarget[],
  progress: number
): MotionAdvancedPaintTarget[] {
  return from.map((value, index) => {
    const next = to[index]
    return {
      kind: value.kind,
      index: value.index,
      ...(value.color && next?.color
        ? { color: interpolateAdvancedColor(value.color, next.color, progress) }
        : {}),
      ...(value.opacity !== undefined && next?.opacity !== undefined
        ? { opacity: interpolateAdvancedNumber(value.opacity, next.opacity, progress) }
        : {})
    }
  })
}

function cloneAdvancedStops(
  values: MotionAdvancedGradientStopTarget[]
): MotionAdvancedGradientStopTarget[] {
  return values.map((value) => ({ ...value, color: { ...value.color } }))
}

function blendAdvancedStops(
  from: MotionAdvancedGradientStopTarget[],
  to: MotionAdvancedGradientStopTarget[],
  progress: number
): MotionAdvancedGradientStopTarget[] {
  return from.map((value, index) => ({
    kind: value.kind,
    paintIndex: value.paintIndex,
    stopIndex: value.stopIndex,
    position: interpolateAdvancedNumber(
      value.position,
      to[index]?.position ?? value.position,
      progress
    ),
    color: interpolateAdvancedColor(value.color, to[index]?.color ?? value.color, progress)
  }))
}

function cloneAdvancedEffects(values: MotionAdvancedEffectTarget[]): MotionAdvancedEffectTarget[] {
  return values.map((value) =>
    value.kind === 'shadow' ? { ...value, color: { ...value.color } } : { ...value }
  )
}

function blendAdvancedEffects(
  from: MotionAdvancedEffectTarget[],
  to: MotionAdvancedEffectTarget[],
  progress: number
): MotionAdvancedEffectTarget[] {
  return from.map((value, index) => {
    const next = to[index]
    if (value.kind === 'blur') {
      return {
        kind: value.kind,
        index: value.index,
        radius: interpolateAdvancedNumber(
          value.radius,
          next?.kind === 'blur' ? next.radius : value.radius,
          progress
        )
      }
    }
    const shadow = next?.kind === 'shadow' ? next : value
    return {
      kind: value.kind,
      index: value.index,
      x: interpolateAdvancedNumber(value.x, shadow.x, progress),
      y: interpolateAdvancedNumber(value.y, shadow.y, progress),
      blur: interpolateAdvancedNumber(value.blur, shadow.blur, progress),
      spread: interpolateAdvancedNumber(value.spread, shadow.spread, progress),
      color: interpolateAdvancedColor(value.color, shadow.color, progress)
    }
  })
}

function blendAdvancedCorners(
  from: MotionAdvancedCornerRadii,
  to: MotionAdvancedCornerRadii,
  progress: number
): MotionAdvancedCornerRadii {
  return {
    topLeft: interpolateAdvancedNumber(from.topLeft, to.topLeft, progress),
    topRight: interpolateAdvancedNumber(from.topRight, to.topRight, progress),
    bottomRight: interpolateAdvancedNumber(from.bottomRight, to.bottomRight, progress),
    bottomLeft: interpolateAdvancedNumber(from.bottomLeft, to.bottomLeft, progress)
  }
}

function blendAdvancedFontAxes(
  from: Array<{ tag: string; value: number }>,
  to: Array<{ tag: string; value: number }>,
  progress: number
): Array<{ tag: string; value: number }> {
  return from.map((axis, index) => ({
    tag: axis.tag,
    value: interpolateAdvancedNumber(axis.value, to[index]?.value ?? axis.value, progress)
  }))
}

const advancedPathNumber = /-?(?:\\d+\\.?\\d*|\\.\\d+)(?:e[-+]?\\d+)?/gi

function blendAdvancedPath(from: string, to: string, progress: number): string {
  const toNumbers = [...to.matchAll(advancedPathNumber)].map((match) => Number(match[0]))
  let index = 0
  return from.replace(advancedPathNumber, (token) => {
    const start = Number(token)
    const end = toNumbers[index++]
    if (!Number.isFinite(start) || !Number.isFinite(end)) return token
    return String(Math.round(interpolateAdvancedNumber(start, end, progress) * 1e6) / 1e6)
  })
}

function blendAdvancedVector(
  from: { topologyId: string; paths: string[] },
  to: { topologyId: string; paths: string[] },
  progress: number
): { topologyId: string; paths: string[] } {
  return {
    topologyId: from.topologyId,
    paths: from.paths.map((path, index) =>
      blendAdvancedPath(path, to.paths[index] ?? path, progress)
    )
  }
}

function sampleAdvancedFrame(
  track: MotionAdvancedTrack,
  progress: number
): Omit<MotionAdvancedFrame, 'offset' | 'easing'> {
  return {
    paints: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.paints,
      cloneAdvancedPaints,
      blendAdvancedPaints
    ),
    gradientStops: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.gradientStops,
      cloneAdvancedStops,
      blendAdvancedStops
    ),
    effects: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.effects,
      cloneAdvancedEffects,
      blendAdvancedEffects
    ),
    cornerRadii: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.cornerRadii,
      (value) => ({ ...value }),
      blendAdvancedCorners
    ),
    textReveal: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.textReveal,
      (value) => value,
      interpolateAdvancedNumber
    ),
    fontAxes: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.fontAxes,
      (value) => value.map((axis) => ({ ...axis })),
      blendAdvancedFontAxes
    ),
    vectorMorph: sampleAdvancedValue(
      track,
      progress,
      (frame) => frame.vectorMorph,
      (value) => ({ topologyId: value.topologyId, paths: [...value.paths] }),
      blendAdvancedVector
    )
  }
}

function advancedColorCss(color: MotionAdvancedColor, opacity = 1): string {
  const red = Math.round(Math.min(1, Math.max(0, color.r)) * 255)
  const green = Math.round(Math.min(1, Math.max(0, color.g)) * 255)
  const blue = Math.round(Math.min(1, Math.max(0, color.b)) * 255)
  const alpha = Math.round(Math.min(1, Math.max(0, color.a * opacity)) * 1e6) / 1e6
  return 'rgba(' + red + ', ' + green + ', ' + blue + ', ' + alpha + ')'
}

function advancedGradientCenter(
  transform: NonNullable<MotionAdvancedFill['gradientTransform']>
): { x: number; y: number } {
  return {
    x: Math.round((transform.m00 * 0.5 + transform.m01 * 0.5 + transform.m02) * 1e6) / 1e4,
    y: Math.round((transform.m10 * 0.5 + transform.m11 * 0.5 + transform.m12) * 1e6) / 1e4
  }
}

function advancedGradientAngle(dx: number, dy: number): number {
  const degrees = (Math.atan2(dx, -dy) * 180) / Math.PI
  return Math.round(((degrees % 360) + 360) % 360)
}

function advancedFillCss(fill: MotionAdvancedFill, element: Element): string | undefined {
  if (fill.type === 'UNSUPPORTED' || !fill.visible) return undefined
  if (fill.type === 'SOLID') {
    const color = advancedColorCss(fill.color, fill.opacity)
    return 'linear-gradient(' + color + ', ' + color + ')'
  }
  const stops = fill.gradientStops
  const transform = fill.gradientTransform
  if (!stops || stops.length === 0 || !transform) return undefined
  const stopList = stops
    .map(
      (stop) =>
        advancedColorCss(stop.color, fill.opacity) +
        ' ' +
        Math.round(stop.position * 1e6) / 1e4 +
        '%'
    )
    .join(', ')
  if (fill.type === 'GRADIENT_RADIAL') return 'radial-gradient(circle, ' + stopList + ')'
  const center = advancedGradientCenter(transform)
  if (fill.type === 'GRADIENT_DIAMOND') {
    return 'radial-gradient(circle at ' + center.x + '% ' + center.y + '%, ' + stopList + ')'
  }
  if (fill.type === 'GRADIENT_ANGULAR') {
    const angle = advancedGradientAngle(transform.m00, transform.m10)
    return (
      'conic-gradient(from ' +
      angle +
      'deg at ' +
      center.x +
      '% ' +
      center.y +
      '%, ' +
      stopList +
      ')'
    )
  }
  const bounds = element.getBoundingClientRect()
  const startX = (transform.m00 + transform.m02) * bounds.width
  const startY = (transform.m10 + transform.m12) * bounds.height
  const endX = transform.m02 * bounds.width
  const endY = transform.m12 * bounds.height
  const angle = advancedGradientAngle(endX - startX, endY - startY)
  return 'linear-gradient(' + angle + 'deg, ' + stopList + ')'
}

function projectedAdvancedTarget(
  target: MotionAdvancedTarget,
  frame: Omit<MotionAdvancedFrame, 'offset' | 'easing'>
): MotionAdvancedTarget {
  const fills = target.fills?.map((fill) => ({
    ...fill,
    color: { ...fill.color },
    gradientStops: fill.gradientStops?.map((stop) => ({
      ...stop,
      color: { ...stop.color }
    })),
    gradientTransform: fill.gradientTransform ? { ...fill.gradientTransform } : undefined
  }))
  const strokes = target.strokes?.map((stroke) => ({ ...stroke, color: { ...stroke.color } }))
  const effects = target.effects?.map((effect) => ({ ...effect, color: { ...effect.color } }))
  for (const paint of frame.paints ?? []) {
    const resource = paint.kind === 'fill' ? fills?.[paint.index] : strokes?.[paint.index]
    if (!resource) continue
    if (paint.color) resource.color = { ...paint.color }
    if (paint.opacity !== undefined) resource.opacity = paint.opacity
  }
  for (const stop of frame.gradientStops ?? []) {
    const resource = fills?.[stop.paintIndex]?.gradientStops?.[stop.stopIndex]
    if (!resource) continue
    resource.position = stop.position
    resource.color = { ...stop.color }
  }
  for (const effect of frame.effects ?? []) {
    const resource = effects?.[effect.index]
    if (!resource) continue
    resource.visible = true
    if (effect.kind === 'blur') resource.radius = effect.radius
    else {
      resource.x = effect.x
      resource.y = effect.y
      resource.radius = effect.blur
      resource.spread = effect.spread
      resource.color = { ...effect.color }
    }
  }
  return { ...target, fills, strokes, effects }
}

function setAdvancedStyle(element: Element, property: string, value: string): void {
  cssStyleFor(element)?.setProperty(property, value)
}

function applyAdvancedBoxPaints(element: Element, target: MotionAdvancedTarget): void {
  if (target.fills) {
    const layers = target.fills
      .map((fill) => advancedFillCss(fill, element))
      .filter((value): value is string => value !== undefined)
      .reverse()
    setAdvancedStyle(element, 'background-image', layers.length > 0 ? layers.join(', ') : 'none')
  }
  const stroke = target.strokes?.[0]
  if (stroke) {
    setAdvancedStyle(element, 'border-color', advancedColorCss(stroke.color, stroke.opacity))
  }
}

function applyAdvancedTextPaints(element: Element, target: MotionAdvancedTarget): void {
  const fill = target.fills?.[0]
  if (fill?.type === 'SOLID') {
    setAdvancedStyle(element, 'color', advancedColorCss(fill.color, fill.opacity))
  }
  const stroke = target.strokes?.[0]
  if (stroke) {
    setAdvancedStyle(
      element,
      '-webkit-text-stroke-color',
      advancedColorCss(stroke.color, stroke.opacity)
    )
    setAdvancedStyle(element, '-webkit-text-stroke-width', stroke.weight + 'px')
  }
}

function vectorGeometryForFill(element: Element, index: number): Element[] {
  return advancedGeometry(element).filter(
    (geometry) =>
      geometry.getAttribute('data-op-fill-index') === String(index) &&
      geometry.getAttribute('data-op-paint') !== 'stroke-outline'
  )
}

function applyAdvancedVectorPaints(element: Element, target: MotionAdvancedTarget): void {
  target.fills?.forEach((fill, index) => {
    if (fill.type !== 'SOLID') return
    for (const geometry of vectorGeometryForFill(element, index)) {
      geometry.setAttribute('fill', advancedColorCss(fill.color))
      geometry.setAttribute('fill-opacity', String(fill.opacity))
    }
  })
  const stroke = target.strokes?.[0]
  if (!stroke) return
  for (const geometry of advancedGeometry(element)) {
    if (geometry.getAttribute('data-op-paint') === 'stroke-outline') continue
    if (geometry.getAttribute('stroke') === null || geometry.getAttribute('stroke') === 'none') {
      continue
    }
    geometry.setAttribute('stroke', advancedColorCss(stroke.color))
    geometry.setAttribute('stroke-opacity', String(stroke.opacity))
  }
}

function applyAdvancedEffects(element: Element, target: MotionAdvancedTarget): void {
  if (!target.effects) return
  const filters: string[] = []
  const backdropFilters: string[] = []
  const shadows: string[] = []
  for (const effect of target.effects) {
    if (!effect.visible) continue
    if (
      effect.type === 'LAYER_BLUR' ||
      effect.type === 'FOREGROUND_BLUR'
    ) {
      filters.push('blur(' + effect.radius + 'px)')
      continue
    }
    if (effect.type === 'BACKGROUND_BLUR') {
      backdropFilters.push('blur(' + effect.radius + 'px)')
      continue
    }
    const color = advancedColorCss(effect.color)
    if (target.kind === 'vector') {
      filters.push(
        'drop-shadow(' +
          effect.x +
          'px ' +
          effect.y +
          'px ' +
          Math.max(0, effect.radius + effect.spread) +
          'px ' +
          color +
          ')'
      )
    } else {
      shadows.push(
        (effect.type === 'INNER_SHADOW' ? 'inset ' : '') +
          effect.x +
          'px ' +
          effect.y +
          'px ' +
          effect.radius +
          'px ' +
          effect.spread +
          'px ' +
          color
      )
    }
  }
  setAdvancedStyle(element, 'filter', filters.length > 0 ? filters.join(' ') : 'none')
  setAdvancedStyle(
    element,
    'backdrop-filter',
    backdropFilters.length > 0 ? backdropFilters.join(' ') : 'none'
  )
  if (target.kind === 'text') {
    setAdvancedStyle(element, 'text-shadow', shadows.length > 0 ? shadows.join(', ') : 'none')
  } else if (target.kind === 'box') {
    setAdvancedStyle(element, 'box-shadow', shadows.length > 0 ? shadows.join(', ') : 'none')
  }
}

function applyAdvancedTextReveal(
  snapshot: MotionAdvancedSnapshot,
  target: MotionAdvancedTarget,
  progress: number
): void {
  const total = Array.from(target.text ?? snapshot.text.map((item) => item.value).join('')).length
  let remaining = Math.round(total * Math.min(1, Math.max(0, progress)))
  for (const item of snapshot.text) {
    const characters = Array.from(item.value)
    const visible = Math.min(remaining, characters.length)
    item.node.nodeValue = characters.slice(0, visible).join('')
    remaining -= visible
  }
}

function applyAdvancedFontAxes(
  element: Element,
  target: MotionAdvancedTarget,
  sampled: Array<{ tag: string; value: number }>
): void {
  const axes = new Map((target.fontAxes ?? []).map((axis) => [axis.tag, axis.value]))
  for (const axis of sampled) axes.set(axis.tag, axis.value)
  setAdvancedStyle(
    element,
    'font-variation-settings',
    [...axes].map(([tag, value]) => '"' + tag + '" ' + value).join(', ')
  )
}

function applyAdvancedVectorMorph(
  element: Element,
  morph: { topologyId: string; paths: string[] }
): void {
  for (const geometry of element.querySelectorAll('[data-op-morph-path-index]')) {
    const index = Number(geometry.getAttribute('data-op-morph-path-index'))
    const path = morph.paths[index]
    if (path !== undefined) geometry.setAttribute('d', path)
  }
}

function applyAdvancedProjection(
  element: Element,
  track: MotionAdvancedTrack,
  progress: number
): void {
  const snapshot = captureAdvancedSnapshot(element)
  const sampled = sampleAdvancedFrame(track, progress)
  const target = projectedAdvancedTarget(track.target, sampled)
  if (target.kind === 'box') applyAdvancedBoxPaints(element, target)
  else if (target.kind === 'text') applyAdvancedTextPaints(element, target)
  else applyAdvancedVectorPaints(element, target)
  applyAdvancedEffects(element, target)
  if (sampled.cornerRadii) {
    setAdvancedStyle(
      element,
      'border-radius',
      sampled.cornerRadii.topLeft +
        'px ' +
        sampled.cornerRadii.topRight +
        'px ' +
        sampled.cornerRadii.bottomRight +
        'px ' +
        sampled.cornerRadii.bottomLeft +
        'px'
    )
  }
  if (sampled.textReveal !== undefined) {
    applyAdvancedTextReveal(snapshot, target, sampled.textReveal)
  }
  if (sampled.fontAxes) applyAdvancedFontAxes(element, target, sampled.fontAxes)
  if (sampled.vectorMorph) applyAdvancedVectorMorph(element, sampled.vectorMorph)
}

function clearManualComposition(element: Element, track: MotionTrack): void {
  const style = cssStyleFor(element)
  if (style && track.composition) {
    style.removeProperty(track.composition.weightVariable)
    for (const variable of Object.values(track.composition.variables)) {
      if (variable) style.removeProperty(variable)
    }
  }
  if (track.advanced) restoreAdvancedSnapshot(element)
}

function applyManualComposition(element: Element, track: MotionTrack, animation: Animation): void {
  const composition = track.composition
  const style = cssStyleFor(element)
  const currentTime = safeCurrentTime(animation)
  if (currentTime === null) return
  const timing = manualTrackProgress(track, currentTime)
  if (!timing.contributes) {
    clearManualComposition(element, track)
    return
  }
  if (composition && style) {
    style.setProperty(composition.weightVariable, String(composition.weight))
    for (const channel of motionSamplingChannels) {
      const variable = composition.variables[channel]
      if (!variable) continue
      const sampled = sampleRuntimeChannel(track, channel, timing.progress)
      const identity = samplingIdentity(channel)
      const contribution =
        composition.mode === 'accumulate'
          ? sampled -
            identity +
            timing.completedIterations *
              (sampleRuntimeChannel(track, channel, 1) -
                sampleRuntimeChannel(track, channel, 0))
          : sampled
      style.setProperty(variable, String(contribution))
    }
  }
  if (track.advanced) applyAdvancedProjection(element, track.advanced, timing.progress)
}

function scheduleManualCompositions(): void {
  if (manualCompositions.size > 0) manualFrameLoop.request()
}

function updateManualCompositions(): boolean {
  for (const [animation, record] of manualCompositions) {
    const state = safePlayState(animation)
    if (state === 'idle') {
      clearManualComposition(record.element, record.track)
      manualCompositions.delete(animation)
      continue
    }
    applyManualComposition(record.element, record.track, animation)
    if (state === 'finished') manualCompositions.delete(animation)
  }
  return manualCompositions.size > 0
}

function activateManualComposition(
  element: Element,
  track: MotionTrack,
  animation: Animation
): void {
  if (
    !track.advanced &&
    (!track.composition || Object.keys(track.composition.variables).length === 0)
  ) {
    return
  }
  const record = { element, track }
  manualCompositions.set(animation, record)
  manualCompositionRecords.set(animation, record)
  applyManualComposition(element, track, animation)
  scheduleManualCompositions()
}

function releaseManualComposition(animation: Animation, reset: boolean): void {
  const record = manualCompositions.get(animation) ?? manualCompositionRecords.get(animation)
  if (!record) return
  manualCompositions.delete(animation)
  manualCompositionRecords.delete(animation)
  if (reset) clearManualComposition(record.element, record.track)
  if (reset && record.track.advanced) advancedSnapshots.delete(record.element)
  if (manualCompositions.size === 0) manualFrameLoop.cancel()
}

function playableTrack(track: MotionTrack, policy: MotionSpec['reducedMotion']): MotionTrack | null {
  if (!prefersReducedMotion() || policy === 'allow') return track
  if (policy === 'disable') return null
  if (track.composition) {
    const opacityVariable = track.composition.variables.opacity
    const hasOpacity = track.composition.sampling.keyframes.some(
      (frame) => frame.values.opacity !== undefined
    )
    if (!opacityVariable || !hasOpacity) return null
    return {
      ...track,
      advanced: undefined,
      keyframes: track.keyframes.map((frame) => ({
        offset: frame.offset,
        [track.composition.clock]: frame.offset,
        ...(frame.easing === undefined ? {} : { easing: frame.easing })
      })),
      composition: {
        ...track.composition,
        variables: { opacity: opacityVariable },
        sampling: {
          ...track.composition.sampling,
          keyframes: track.composition.sampling.keyframes.map((frame) => ({
            offset: frame.offset,
            values:
              frame.values.opacity === undefined ? {} : { opacity: frame.values.opacity },
            ...(frame.easing === undefined ? {} : { easing: frame.easing })
          }))
        }
      },
      timing: { ...track.timing, duration: Math.min(track.timing.duration, 120), delay: 0 }
    }
  }
  const opacityProperty = track.composition?.variables.opacity ?? 'opacity'
  const keyframes = track.keyframes.map((frame) => ({
    offset: frame.offset,
    ...(frame[opacityProperty] === undefined
      ? {}
      : { [opacityProperty]: frame[opacityProperty] }),
    ...(frame.easing === undefined ? {} : { easing: frame.easing })
  }))
  if (!keyframes.some((frame) => frame[opacityProperty] !== undefined)) return null
  return {
    ...track,
    advanced: undefined,
    keyframes,
    timing: { ...track.timing, duration: Math.min(track.timing.duration, 120), delay: 0 }
  }
}

function orderedTracks(spec: MotionSpec): MotionTrack[] {
  if (spec.version !== 3) return spec.tracks
  return [...spec.tracks].sort((left, right) => {
    const priority = (left.composition?.priority ?? 0) - (right.composition?.priority ?? 0)
    return priority !== 0
      ? priority
      : (left.composition?.sourceIndex ?? 0) - (right.composition?.sourceIndex ?? 0)
  })
}

function trackAnimation(animation: Animation): void {
  allAnimations.add(animation)
  if (observedAnimations.has(animation)) return
  observedAnimations.add(animation)
  const release = (event: Event) => allAnimations.delete(event.currentTarget as Animation)
  animation.addEventListener('cancel', release)
  animation.addEventListener('finish', release)
}

function cancelAnimation(animation: Animation): void {
  allAnimations.delete(animation)
  releaseManualComposition(animation, true)
  animation.cancel()
}

function startAnimation(
  element: Element,
  sourceTrack: MotionTrack,
  policy: MotionSpec['reducedMotion']
): ActiveTrack | null {
  const track = playableTrack(sourceTrack, policy)
  if (!track) return null
  const animation = element.animate(track.keyframes as Keyframe[], {
    duration: track.timing.duration,
    delay: track.timing.delay,
    easing: track.timing.easing,
    iterations: track.timing.iterations === 'infinite' ? Infinity : track.timing.iterations,
    direction: track.timing.direction,
    fill: track.timing.fill
  })
  trackAnimation(animation)
  activateManualComposition(element, track, animation)
  return { track, animation }
}

function cancelAutomaticAnimations(element: Element): void {
  const byTrack = prepared.get(element)
  if (!byTrack) return
  for (const item of byTrack.values()) cancelAnimation(item.animation)
  prepared.delete(element)
  active.delete(element)
}

function cssStyleFor(element: Element): CSSStyleDeclaration | undefined {
  return (element as Element & { style?: CSSStyleDeclaration }).style
}

function cancelCssAnimations(element: Element, track: MotionTrack): void {
  if (!track.css) return
  const readAnimations = (element as Element & { getAnimations?: () => Animation[] }).getAnimations
  if (!readAnimations) return
  for (const animation of readAnimations.call(element)) {
    const name = (animation as Animation & { animationName?: string }).animationName
    if (name && track.css.animationNames.includes(name)) cancelAnimation(animation)
  }
}

function suppressCssTrack(element: Element, track: MotionTrack): void {
  if (!track.css) return
  cssStyleFor(element)?.setProperty(track.css.variable, 'none')
  cancelCssAnimations(element, track)
}

function restoreCssTracks(element: Element): void {
  const spec = specFor(element)
  const style = cssStyleFor(element)
  if (!spec || !style) return
  for (const track of spec.tracks) {
    if (track.css) style.removeProperty(track.css.variable)
  }
}

function stoppedTracksFor(element: Element): Set<string> {
  const stopped = automaticStopped.get(element) ?? new Set<string>()
  automaticStopped.set(element, stopped)
  return stopped
}

function markTransientTrigger(element: Element, trigger: MotionTrigger): void {
  if (!TRANSIENT_TRIGGERS.has(trigger)) return
  const triggers = transientTriggers.get(element) ?? new Set<MotionTrigger>()
  triggers.add(trigger)
  transientTriggers.set(element, triggers)
}

function clearTransientTrigger(element: Element, trigger: MotionTrigger): void {
  const triggers = transientTriggers.get(element)
  if (!triggers) return
  triggers.delete(trigger)
  if (triggers.size === 0) transientTriggers.delete(element)
}

/** Create automatic WAAPI animations once in authored source order. Inactive
 * tracks are canceled until their trigger runs, preserving later-track-wins
 * compositing without restarting an already active mount, loop, or click. */
function prepareAutomaticAnimations(
  element: Element,
  spec: MotionSpec
): Map<string, ActiveTrack> {
  const existing = prepared.get(element)
  if (existing) return existing
  const byTrack = new Map<string, ActiveTrack>()
  const byTrigger = new Map<MotionTrigger, ActiveTrack[]>()
  for (const sourceTrack of orderedTracks(spec)) {
    const item = startAnimation(element, sourceTrack, spec.reducedMotion)
    if (!item) continue
    byTrack.set(sourceTrack.id, item)
    if (
      sourceTrack.trigger !== 'mount' &&
      sourceTrack.trigger !== 'pageEnter' &&
      sourceTrack.trigger !== 'loop'
    ) {
      cancelAnimation(item.animation)
      continue
    }
    const items = byTrigger.get(sourceTrack.trigger) ?? []
    items.push(item)
    byTrigger.set(sourceTrack.trigger, items)
  }
  if (byTrack.size > 0) prepared.set(element, byTrack)
  if (byTrigger.size > 0) active.set(element, byTrigger)
  return byTrack
}

function replayAnimation(element: Element, item: ActiveTrack): void {
  const { animation } = item
  animation.playbackRate = 1
  animation.currentTime = 0
  activateManualComposition(element, item.track, animation)
  trackAnimation(animation)
  animation.play()
}

function stopAutomaticTracks(element: Element, tracks: readonly MotionTrack[]): void {
  if (tracks.length === 0) return
  const ids = new Set(tracks.map((track) => track.id))
  const stopped = stoppedTracksFor(element)
  for (const track of tracks) {
    stopped.add(track.id)
    suppressCssTrack(element, track)
  }
  const byTrigger = active.get(element)
  if (!byTrigger) return
  for (const [trigger, items] of byTrigger) {
    const retained: ActiveTrack[] = []
    for (const item of items) {
      if (ids.has(item.track.id)) cancelAnimation(item.animation)
      else retained.push(item)
    }
    if (retained.length > 0) byTrigger.set(trigger, retained)
    else byTrigger.delete(trigger)
  }
  if (byTrigger.size === 0) active.delete(element)
}

function releaseControlledTrack(
  element: Element,
  trackId: string,
  item: ActiveTrack,
  resetEffect: boolean
): void {
  const byTrack = controlled.get(element)
  if (!byTrack || byTrack.get(trackId) !== item) return
  item.animation.onfinish = null
  byTrack.delete(trackId)
  if (byTrack.size === 0) controlled.delete(element)
  if (resetEffect) cancelAnimation(item.animation)
}

function finishControlledTrack(element: Element, trackId: string, item: ActiveTrack): void {
  if (item.track.timing.fill === 'forwards' || item.track.timing.fill === 'both') return
  releaseControlledTrack(element, trackId, item, true)
}

function stopControlledElement(
  element: Element,
  trackId?: string,
  resetEffect = true
): void {
  const byTrack = controlled.get(element)
  if (!byTrack) return
  const selected =
    trackId === undefined
      ? [...byTrack.entries()]
      : byTrack.has(trackId)
        ? [[trackId, byTrack.get(trackId) as ActiveTrack] as const]
        : []
  for (const [id, item] of selected) releaseControlledTrack(element, id, item, resetEffect)
}

function tracksFor(spec: MotionSpec, trackId?: string): MotionTrack[] {
  return trackId === undefined
    ? orderedTracks(spec)
    : orderedTracks(spec).filter((candidate) => candidate.id === trackId)
}

function cssAnimationFor(element: Element, track: MotionTrack): Animation | undefined {
  if (!track.css) return undefined
  const readAnimations = (element as Element & { getAnimations?: () => Animation[] }).getAnimations
  if (!readAnimations) return undefined
  try {
    return readAnimations.call(element).find((animation) => {
      try {
        const name = (animation as Animation & { animationName?: string }).animationName
        return name !== undefined && track.css?.animationNames.includes(name)
      } catch {
        return false
      }
    })
  } catch {
    return undefined
  }
}

function automaticTrackFor(element: Element, track: MotionTrack): ActiveTrack | undefined {
  return active
    .get(element)
    ?.get(track.trigger)
    ?.find((item) => item.track.id === track.id)
}

function safePlayState(animation: Animation | undefined): AnimationPlayState {
  if (!animation) return 'idle'
  try {
    return animation.playState ?? 'idle'
  } catch {
    return 'idle'
  }
}

function safeCurrentTime(animation: Animation | undefined): number | null {
  if (!animation) return null
  try {
    const currentTime = animation.currentTime
    return typeof currentTime === 'number' && Number.isFinite(currentTime) ? currentTime : null
  } catch {
    return null
  }
}

function safeProgress(animation: Animation | undefined, track: MotionTrack): number | null {
  if (!animation) return null
  try {
    const progress = animation.effect?.getComputedTiming().progress
    if (typeof progress === 'number' && Number.isFinite(progress)) {
      return Math.max(0, Math.min(1, progress))
    }
  } catch {
    // Detached and canceled effects may reject timing reads in some engines.
  }
  const currentTime = safeCurrentTime(animation)
  if (currentTime === null) return null
  const activeTime = currentTime - track.timing.delay
  if (activeTime <= 0) return 0
  if (track.timing.duration <= 0) return 1
  const iterations = track.timing.iterations === 'infinite' ? Infinity : track.timing.iterations
  const totalDuration = track.timing.duration * iterations
  if (Number.isFinite(totalDuration) && activeTime >= totalDuration) return 1
  return Math.max(0, Math.min(1, (activeTime % track.timing.duration) / track.timing.duration))
}

function inspectionElements(targetNodeId?: string, scope?: Element): Element[] {
  if (!runtimeDocument) return []
  if (targetNodeId !== undefined) {
    return typeof targetNodeId === 'string' && targetNodeId.length > 0
      ? elementsForNodeId(targetNodeId, scope, true)
      : []
  }
  const root: ParentNode = scope instanceof Element ? scope : runtimeDocument
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  return elements.filter((element) => specFor(element) !== undefined)
}

function inspect(targetNodeId?: string, scope?: Element): MotionDebugSnapshot {
  const entries: MotionDebugEntry[] = []
  for (const element of inspectionElements(targetNodeId, scope)) {
    const token = element.getAttribute('data-op-motion')
    const spec = token ? registry[token] : undefined
    if (!token || !spec) continue
    const controlledByTrack = controlled.get(element)
    const stoppedTracks = automaticStopped.get(element)
    const preparedByTrack = prepared.get(element)
    for (const track of spec.tracks) {
      const controlledItem = controlledByTrack?.get(track.id)
      const wasAutomaticallyStopped = stoppedTracks?.has(track.id) === true
      const automaticItem = automaticTrackFor(element, track)
      const cssAnimation =
        !controlledItem && !automaticItem && !wasAutomaticallyStopped
          ? cssAnimationFor(element, track)
          : undefined
      const preparedItem = preparedByTrack?.get(track.id)
      const animation =
        controlledItem?.animation ??
        automaticItem?.animation ??
        cssAnimation ??
        preparedItem?.animation
      const effectiveTrack = controlledItem?.track ?? automaticItem?.track ?? preparedItem?.track ?? track
      const source: MotionDebugSource = controlledItem
        ? 'controlled'
        : wasAutomaticallyStopped
          ? 'stopped'
          : automaticItem || cssAnimation
            ? 'automatic'
            : 'idle'
      entries.push(
        Object.freeze({
          nodeId: element.getAttribute('data-node-id') ?? '',
          token,
          reducedMotion: spec.reducedMotion,
          trackId: track.id,
          trigger: track.trigger,
          source,
          playState: safePlayState(animation),
          currentTime: safeCurrentTime(animation),
          progress: safeProgress(animation, effectiveTrack),
          timing: Object.freeze({ ...effectiveTrack.timing }),
          exit: track.exit,
          stopped: source === 'stopped'
        })
      )
    }
  }
  return Object.freeze({
    capturedAt: Date.now(),
    entries: Object.freeze(entries),
    activeAnimationCount: allAnimations.size
  })
}

function rememberControlledTrackProgress(element: Element, trackId: string, progress: number): number {
  const normalized = Math.min(1, Math.max(0, progress))
  const byTrack = controlledProgress.get(element) ?? new Map<string, number>()
  byTrack.set(trackId, normalized)
  controlledProgress.set(element, byTrack)
  return normalized
}

function forgetControlledTrackProgress(element: Element, trackId?: string): void {
  if (trackId === undefined) {
    controlledProgress.delete(element)
    return
  }
  const byTrack = controlledProgress.get(element)
  if (!byTrack) return
  byTrack.delete(trackId)
  if (byTrack.size === 0) controlledProgress.delete(element)
}

/** Restore a continuous driver at its last normalized input after the Motion
 * runtime swaps full/reduced WAAPI effects. The progress snapshot survives a
 * disabled policy (where no reduced effect exists) so returning to full motion
 * remains paused and controlled instead of replaying from zero. */
function restoreControlledTrackProgress(
  element: Element,
  trackId: string,
  progress: number
): void {
  const spec = specFor(element)
  const sourceTrack = spec?.tracks.find((track) => track.id === trackId)
  if (!spec || !sourceTrack) return
  const normalized = rememberControlledTrackProgress(element, trackId, progress)
  let item = controlled.get(element)?.get(trackId)
  if (!item) {
    playControlledElement(element, trackId, true)
    item = controlled.get(element)?.get(trackId)
  }
  if (!item) return
  item.animation.pause()
  item.animation.currentTime = normalized * item.track.timing.duration
  applyManualComposition(element, item.track, item.animation)
}

function playControlledElement(
  element: Element,
  trackId?: string,
  preserveDrivenProgress = false
): void {
  const spec = specFor(element)
  if (!spec) return
  const tracks = tracksFor(spec, trackId)
  if (tracks.length === 0) return
  if (!preserveDrivenProgress) forgetControlledTrackProgress(element, trackId)

  const automaticByTrack = prepareAutomaticAnimations(element, spec)
  stopAutomaticTracks(element, tracks)
  stopControlledElement(element, trackId)
  const byTrack = controlled.get(element) ?? new Map<string, ActiveTrack>()
  for (const sourceTrack of tracks) {
    const item = automaticByTrack.get(sourceTrack.id)
    if (!item) continue
    replayAnimation(element, item)
    byTrack.set(sourceTrack.id, item)
    item.animation.onfinish = () => finishControlledTrack(element, sourceTrack.id, item)
  }
  if (byTrack.size > 0) controlled.set(element, byTrack)
}

interface MotionSceneCuePlayback {
  readonly matchedElementCount: number
  readonly animations: readonly Animation[]
}

function detachAutomaticTrack(element: Element, trackId: string): void {
  const item = prepared.get(element)?.get(trackId)
  if (item) cancelAnimation(item.animation)
  const byTrigger = active.get(element)
  if (!byTrigger) return
  for (const [trigger, items] of byTrigger) {
    const retained = items.filter((candidate) => candidate.track.id !== trackId)
    if (retained.length > 0) byTrigger.set(trigger, retained)
    else byTrigger.delete(trigger)
  }
  if (byTrigger.size === 0) active.delete(element)
}

/** Start one scene cue with timing folded exactly like core's globalTrack(). */
function playMotionSceneCue(
  targetNodeId: string,
  trackId: string,
  startMs: number,
  timeScale: number,
  scope: ParentNode
): MotionSceneCuePlayback {
  if (
    !targetNodeId ||
    !trackId ||
    !Number.isFinite(startMs) ||
    startMs < 0 ||
    !Number.isFinite(timeScale) ||
    timeScale <= 0 ||
    timeScale > 100
  ) {
    return { matchedElementCount: 0, animations: [] }
  }
  let matchedElementCount = 0
  const animations: Animation[] = []
  for (const element of matchingElements(scope, targetNodeId)) {
    const spec = managedSpecFor(element)
    const sourceTrack = spec?.tracks.find((candidate) => candidate.id === trackId)
    if (!spec || !sourceTrack) continue
    matchedElementCount += 1
    forgetControlledTrackProgress(element, trackId)
    stopControlledElement(element, trackId)
    detachAutomaticTrack(element, trackId)
    suppressCssTrack(element, sourceTrack)
    const sceneTrack: MotionTrack = {
      ...sourceTrack,
      timing: {
        ...sourceTrack.timing,
        duration: sourceTrack.timing.duration / timeScale,
        delay: startMs + sourceTrack.timing.delay / timeScale
      }
    }
    const item = startAnimation(element, sceneTrack, spec.reducedMotion)
    if (item) animations.push(item.animation)
  }
  return { matchedElementCount, animations }
}

function play(targetNodeId: string, trackId?: string, scope?: Element): void {
  if (trackId !== undefined && (typeof trackId !== 'string' || trackId.length === 0)) return
  for (const element of elementsForNodeId(targetNodeId, scope)) {
    playControlledElement(element, trackId)
  }
}

function stop(targetNodeId: string, trackId?: string, scope?: Element): void {
  if (trackId !== undefined && (typeof trackId !== 'string' || trackId.length === 0)) return
  for (const element of elementsForNodeId(targetNodeId, scope)) {
    const spec = specFor(element)
    if (!spec) continue
    const tracks = tracksFor(spec, trackId)
    forgetControlledTrackProgress(element, trackId)
    stopControlledElement(element, trackId)
    stopAutomaticTracks(element, tracks)
  }
}

function controlledTrackIsActive(element: Element, trackId?: string): boolean {
  const byTrack = controlled.get(element)
  if (!byTrack) return false
  if (trackId !== undefined) return byTrack.has(trackId)
  return byTrack.size > 0
}

function toggle(targetNodeId: string, trackId?: string, scope?: Element): void {
  if (trackId !== undefined && (typeof trackId !== 'string' || trackId.length === 0)) return
  const elements = elementsForNodeId(targetNodeId, scope)
  const shouldStop = elements.some((element) => controlledTrackIsActive(element, trackId))
  if (shouldStop) stop(targetNodeId, trackId, scope)
  else play(targetNodeId, trackId, scope)
}

function animationsForWait(element: Element, trackId?: string): Animation[] {
  const spec = specFor(element)
  if (!spec) return []
  const animations: Animation[] = []
  for (const track of tracksFor(spec, trackId)) {
    const item =
      controlled.get(element)?.get(track.id) ??
      automaticTrackFor(element, track) ??
      prepared.get(element)?.get(track.id)
    const animation = item?.animation ?? cssAnimationFor(element, track)
    if (animation && !animations.includes(animation)) animations.push(animation)
  }
  return animations
}

interface MotionAnimationWait {
  readonly promise: Promise<'finished' | 'stopped'>
  cancel: () => void
}

function watchAnimation(animation: Animation): MotionAnimationWait {
  const state = safePlayState(animation)
  if (state === 'finished' || state === 'idle') {
    return {
      promise: Promise.resolve(state === 'finished' ? 'finished' : 'stopped'),
      cancel: () => {}
    }
  }
  let cancelWatch = () => {}
  const promise = new Promise<'finished' | 'stopped'>((resolve) => {
    let settled = false
    const finish = () => settle('finished')
    const cancel = () => settle('stopped')
    const cleanup = () => {
      animation.removeEventListener('finish', finish)
      animation.removeEventListener('cancel', cancel)
    }
    const settle = (status: 'finished' | 'stopped') => {
      if (settled) return
      settled = true
      cleanup()
      resolve(status)
    }
    // Explicit cancellation is a terminal stopped result as well. Resolving
    // here keeps timeout/dispose paths from retaining an unreachable pending
    // Promise after listeners have been removed.
    cancelWatch = () => settle('stopped')
    animation.addEventListener('finish', finish)
    animation.addEventListener('cancel', cancel)
  })
  return { promise, cancel: () => cancelWatch() }
}

async function wait(
  targetNodeId: string,
  trackId?: string,
  scope?: Element,
  options: MotionWaitOptions = {}
): Promise<MotionWaitResult> {
  if (
    typeof targetNodeId !== 'string' ||
    targetNodeId.length === 0 ||
    (trackId !== undefined && (typeof trackId !== 'string' || trackId.length === 0))
  ) {
    return { status: 'missing', targetNodeId, ...(trackId ? { trackId } : {}) }
  }
  const animations = elementsForNodeId(targetNodeId, scope, true).flatMap((element) =>
    animationsForWait(element, trackId)
  )
  if (animations.length === 0) {
    return { status: 'missing', targetNodeId, ...(trackId ? { trackId } : {}) }
  }
  const watches = animations.map(watchAnimation)
  const completion = Promise.all(watches.map((watch) => watch.promise)).then((statuses) =>
    statuses.some((status) => status === 'stopped') ? ('stopped' as const) : ('finished' as const)
  )
  const timeoutMs = options.timeoutMs
  let status: MotionWaitStatus
  if (timeoutMs === undefined) status = await completion
  else {
    let timeoutId: ReturnType<typeof setTimeout> | undefined
    const timeout = new Promise<'timeout'>((resolve) => {
      timeoutId = setTimeout(() => resolve('timeout'), Math.max(0, Math.min(120_000, timeoutMs)))
    })
    status = await Promise.race([completion, timeout])
    if (timeoutId !== undefined) clearTimeout(timeoutId)
  }
  for (const watch of watches) watch.cancel()
  if (status === 'timeout' && options.stopOnTimeout) stop(targetNodeId, trackId, scope)
  return { status, targetNodeId, ...(trackId ? { trackId } : {}) }
}

function finishTransientClick(element: Element, items: readonly ActiveTrack[]): void {
  const current = active.get(element)?.get('click')
  if (current !== items || items.some((item) => safePlayState(item.animation) === 'running')) return
  clearTransientTrigger(element, 'click')
}

function run(
  element: Element,
  trigger: MotionTrigger,
  preserveStopped = false
): ActiveTrack[] {
  const spec = specFor(element)
  if (!spec) return []
  const matchingTracks = spec.tracks.filter((track) => track.trigger === trigger)
  if (matchingTracks.length === 0) return []
  markTransientTrigger(element, trigger)
  const byTrack = prepareAutomaticAnimations(element, spec)
  const stopped = automaticStopped.get(element)
  const programmatic = controlled.get(element)
  const items: ActiveTrack[] = []
  for (const track of matchingTracks) {
    if (!preserveStopped) stopped?.delete(track.id)
    if (stopped?.has(track.id)) continue
    if (programmatic?.has(track.id)) continue
    const item = byTrack.get(track.id)
    if (!item) continue
    replayAnimation(element, item)
    items.push(item)
  }
  const byTrigger = active.get(element) ?? new Map<MotionTrigger, ActiveTrack[]>()
  if (items.length > 0) {
    byTrigger.set(trigger, items)
    if (trigger === 'click') {
      for (const item of items) item.animation.onfinish = () => finishTransientClick(element, items)
    }
  } else byTrigger.delete(trigger)
  if (byTrigger.size > 0) active.set(element, byTrigger)
  else active.delete(element)
  return items
}

function pageExitTimeoutMs(options: MotionPageExitOptions): number {
  const requested = options.timeoutMs
  return typeof requested === 'number' && Number.isFinite(requested)
    ? Math.max(0, Math.min(PAGE_EXIT_MAX_WAIT_MS, requested))
    : PAGE_EXIT_MAX_WAIT_MS
}

function cancelPageExitAnimations(records: readonly { element: Element; item: ActiveTrack }[]): void {
  const elements = new Set<Element>()
  for (const { element, item } of records) {
    elements.add(element)
    cancelAnimation(item.animation)
  }
  for (const element of elements) {
    const byTrigger = active.get(element)
    if (!byTrigger) continue
    byTrigger.delete('pageExit')
    if (byTrigger.size === 0) active.delete(element)
  }
}

async function runPageExit(options: MotionPageExitOptions): Promise<MotionPageExitResult> {
  if (!runtimeDocument) return { status: 'missing', trackCount: 0, animationCount: 0 }
  const records: Array<{ element: Element; item: ActiveTrack }> = []
  let trackCount = 0
  for (const element of managedMotionElements(runtimeDocument)) {
    const spec = managedSpecFor(element)
    if (!spec) continue
    const tracks = spec.tracks.filter((track) => track.trigger === 'pageExit')
    if (tracks.length === 0) continue
    trackCount += tracks.length
    for (const track of tracks) stopControlledElement(element, track.id)
    for (const item of run(element, 'pageExit')) records.push({ element, item })
  }
  if (trackCount === 0) return { status: 'missing', trackCount: 0, animationCount: 0 }
  if (records.length === 0) return { status: 'finished', trackCount, animationCount: 0 }

  const watches = records.map(({ item }) => watchAnimation(item.animation))
  const completion = Promise.all(watches.map((watch) => watch.promise)).then((statuses) =>
    statuses.some((status) => status === 'stopped') ? ('stopped' as const) : ('finished' as const)
  )
  let timeoutId: ReturnType<typeof setTimeout> | undefined
  const timeout = new Promise<'timeout'>((resolve) => {
    timeoutId = setTimeout(() => resolve('timeout'), pageExitTimeoutMs(options))
  })
  const status = await Promise.race([completion, timeout])
  if (timeoutId !== undefined) clearTimeout(timeoutId)
  for (const watch of watches) watch.cancel()
  if (status === 'timeout') cancelPageExitAnimations(records)
  return { status, trackCount, animationCount: records.length }
}

function pageExit(options: MotionPageExitOptions = {}): Promise<MotionPageExitResult> {
  if (pageExitInFlight) return pageExitInFlight
  const task = runPageExit(options).catch(
    (): MotionPageExitResult => ({ status: 'stopped', trackCount: 0, animationCount: 0 })
  )
  pageExitInFlight = task
  void task.then(
    () => {
      if (pageExitInFlight === task) pageExitInFlight = null
    },
    () => {
      if (pageExitInFlight === task) pageExitInFlight = null
    }
  )
  return task
}

function exit(element: Element, trigger: MotionTrigger): void {
  clearTransientTrigger(element, trigger)
  const items = active.get(element)?.get(trigger)
  if (!items) return
  const retained: ActiveTrack[] = []
  for (const item of items) {
    if (item.track.exit === 'none') {
      retained.push(item)
    } else if (item.track.exit === 'reverse') {
      trackAnimation(item.animation)
      item.animation.reverse()
      retained.push(item)
    } else {
      cancelAnimation(item.animation)
    }
  }
  const byTrigger = active.get(element)
  if (!byTrigger) return
  if (retained.length > 0) byTrigger.set(trigger, retained)
  else byTrigger.delete(trigger)
  if (byTrigger.size === 0) active.delete(element)
}

function movedWithin(element: Element, relatedTarget: EventTarget | null): boolean {
  return relatedTarget instanceof Node && element.contains(relatedTarget)
}

function releasePointerPress(pointerId: number): void {
  const elements = pointerPresses.get(pointerId)
  if (!elements) return
  pointerPresses.delete(pointerId)
  for (const element of elements) exit(element, 'press')
}

const listeners: Array<[string, EventListener]> = []
function listen(type: string, listener: EventListener): void {
  if (!runtimeDocument) return
  runtimeDocument.addEventListener(type, listener, true)
  listeners.push([type, listener])
}

listen('pointerover', ((event: PointerEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) run(element, 'hover')
  }
}) as EventListener)

listen('pointerout', ((event: PointerEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) exit(element, 'hover')
  }
}) as EventListener)

listen('pointerdown', ((event: PointerEvent) => {
  const elements = motionElements(event.target)
  if (elements.length === 0) return
  releasePointerPress(event.pointerId)
  pointerPresses.set(event.pointerId, elements)
  for (const element of elements) run(element, 'press')
}) as EventListener)

const finishPointerPress = ((event: PointerEvent) => {
  releasePointerPress(event.pointerId)
}) as EventListener
listen('pointerup', finishPointerPress)
listen('pointercancel', finishPointerPress)

listen('keydown', ((event: KeyboardEvent) => {
  if (event.repeat || (event.key !== 'Enter' && event.key !== ' ')) return
  for (const element of motionElements(event.target)) {
    keyboardPresses.add(element)
    run(element, 'press')
  }
}) as EventListener)

listen('keyup', ((event: KeyboardEvent) => {
  if (event.key !== 'Enter' && event.key !== ' ') return
  for (const pressed of keyboardPresses) exit(pressed, 'press')
  keyboardPresses.clear()
}) as EventListener)

listen('focusin', ((event: FocusEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) run(element, 'focus')
  }
}) as EventListener)

listen('focusout', ((event: FocusEvent) => {
  for (const element of motionElements(event.target)) {
    if (movedWithin(element, event.relatedTarget)) continue
    if (keyboardPresses.delete(element)) exit(element, 'press')
    exit(element, 'focus')
  }
}) as EventListener)

listen('click', ((event: MouseEvent) => {
  for (const element of motionElements(event.target)) run(element, 'click')
}) as EventListener)

const inViewObserver = !runtimeDocument || typeof IntersectionObserver === 'undefined'
  ? null
  : new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) run(entry.target, 'inView')
        else exit(entry.target, 'inView')
      }
    })

function scan(root: ParentNode): void {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  for (const element of elements) {
    const spec = managedSpecFor(element)
    if (!spec) continue
    for (const track of spec.tracks) {
      if (
        track.trigger !== 'mount' &&
        track.trigger !== 'pageEnter' &&
        track.trigger !== 'loop'
      ) {
        continue
      }
      suppressCssTrack(element, track)
    }
    prepareAutomaticAnimations(element, spec)
    if (spec.tracks.some((track) => track.trigger === 'inView')) inViewObserver?.observe(element)
  }
}

function cleanupElement(element: Element, preserveTransientState = false): void {
  stopControlledElement(element, undefined, false)
  cancelAutomaticAnimations(element)
  automaticStopped.delete(element)
  inViewObserver?.unobserve(element)
  if (!preserveTransientState) {
    transientTriggers.delete(element)
    for (const [pointerId, elements] of pointerPresses) {
      const remaining = elements.filter((candidate) => candidate !== element)
      if (remaining.length > 0) pointerPresses.set(pointerId, remaining)
      else pointerPresses.delete(pointerId)
    }
    keyboardPresses.delete(element)
  }
}

function cleanupTree(root: ParentNode): void {
  if (root instanceof Element) cleanupElement(root)
  for (const element of root.querySelectorAll('*')) cleanupElement(element)
}

function restoreCssTree(root: ParentNode): void {
  if (root instanceof Element && root.matches(selector)) restoreCssTracks(root)
  for (const element of root.querySelectorAll(selector)) restoreCssTracks(element)
}

function managedMotionElements(root: ParentNode): Element[] {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  return elements.filter((element) => managedSpecFor(element) !== undefined)
}

function refreshableMotionElements(root: ParentNode): Element[] {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  return elements.filter(
    (element) =>
      managedSpecFor(element) !== undefined ||
      controlled.has(element) ||
      controlledProgress.has(element)
  )
}

function refreshReducedMotion(): void {
  if (!runtimeDocument) return
  const snapshots = refreshableMotionElements(runtimeDocument)
    .filter((element) => specFor(element)?.reducedMotion !== 'allow')
    .map((element) => ({
      element,
      stoppedTrackIds: new Set(automaticStopped.get(element) ?? []),
      controlledTrackIds: new Set([
        ...(controlled.get(element)?.keys() ?? []),
        ...(controlledProgress.get(element)?.keys() ?? [])
      ]),
      controlledProgressByTrack: new Map(controlledProgress.get(element) ?? []),
      transientTriggerIds: [...(transientTriggers.get(element) ?? [])]
    }))
  for (const { element } of snapshots) cleanupElement(element, true)
  scan(runtimeDocument)
  for (const {
    element,
    stoppedTrackIds,
    controlledTrackIds,
    controlledProgressByTrack,
    transientTriggerIds
  } of snapshots) {
    const refreshedSpec = specFor(element)
    if (!refreshedSpec) continue
    if (stoppedTrackIds.size > 0) {
      stopAutomaticTracks(
        element,
        refreshedSpec.tracks.filter((track) => stoppedTrackIds.has(track.id))
      )
    }
    for (const trigger of transientTriggerIds) run(element, trigger, true)
    for (const trackId of controlledTrackIds) {
      const progress = controlledProgressByTrack.get(trackId)
      if (progress === undefined) playControlledElement(element, trackId)
      else restoreControlledTrackProgress(element, trackId, progress)
    }
  }
}

reducedMotionQuery?.addEventListener('change', refreshReducedMotion)
if (runtimeDocument) scan(runtimeDocument)
const mutationObserver =
  runtimeDocument && typeof MutationObserver !== 'undefined'
    ? new MutationObserver((records) => {
        for (const record of records) {
          if (record.type === 'attributes') cleanupElement(record.target as Element)
          for (const node of record.removedNodes) {
            if (node instanceof Element) cleanupTree(node)
          }
        }
        for (const record of records) {
          if (record.type === 'attributes') scan(record.target as Element)
          for (const node of record.addedNodes) {
            if (node instanceof Element) scan(node)
          }
        }
      })
    : null
if (mutationObserver && runtimeDocument) {
  mutationObserver.observe(runtimeDocument.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['data-op-motion']
  })
}

function dispose(): void {
  manualFrameLoop.dispose()
  reducedMotionQuery?.removeEventListener('change', refreshReducedMotion)
  if (runtimeDocument) {
    for (const [type, listener] of listeners) {
      runtimeDocument.removeEventListener(type, listener, true)
    }
    cleanupTree(runtimeDocument.documentElement)
    restoreCssTree(runtimeDocument.documentElement)
  }
  mutationObserver?.disconnect()
  inViewObserver?.disconnect()
  for (const animation of [...allAnimations]) cancelAnimation(animation)
  allAnimations.clear()
  pointerPresses.clear()
  keyboardPresses.clear()
  if (runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__ === runtimeHandle) {
    delete runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__
  }
}

const runtimeHandle: OpenPencilMotionRuntimeHandle = {
  dispose,
  inspect,
  pageExit,
  play,
  stop,
  toggle,
  wait
}
runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__ = runtimeHandle
const hot = (import.meta as ImportMeta & { hot?: { dispose: (callback: () => void) => void } }).hot
hot?.dispose(dispose)
`
}

function runtimeTrack(
  track: IRMotionTrack,
  token: string,
  index: number,
  motion: IRMotion
): unknown {
  const sourceIndex = track.composition?.sourceIndex ?? motion.tracks.indexOf(track)
  const composition =
    motion.version === 3
      ? {
          mode: track.composition?.mode ?? 'replace',
          weight: track.composition?.weight ?? 1,
          priority: track.composition?.priority ?? 0,
          sourceIndex,
          clock: motionCompositionClockVariableName(token, sourceIndex),
          weightVariable: motionCompositionWeightVariableName(token, sourceIndex),
          variables: Object.fromEntries(
            motionCompositionChannels(track).map((channel) => [
              channel,
              motionCompositionVariableName(token, sourceIndex, channel)
            ])
          ),
          sampling: {
            easing: track.timing.easing,
            keyframes: track.keyframes.map((frame) => ({
              offset: frame.offset,
              values: Object.fromEntries(
                motionCompositionChannels(track).flatMap((channel) =>
                  frame[channel] === undefined ? [] : [[channel, frame[channel]]]
                )
              ),
              ...(frame.easing ? { easing: frame.easing } : {})
            }))
          }
        }
      : undefined
  const advanced = runtimeAdvancedTrack(track, motion)
  return {
    id: track.id,
    trigger: track.trigger,
    exit: track.exit,
    keyframes: track.keyframes.map((frame) =>
      runtimeKeyframe(frame, track, motion, token, sourceIndex)
    ),
    timing: {
      duration: track.timing.durationMs,
      delay: track.timing.delayMs,
      easing: easingCss(track.timing.easing),
      iterations: track.timing.iterations,
      direction: track.timing.direction,
      fill: track.timing.fill
    },
    ...(composition ? { composition } : {}),
    ...(advanced ? { advanced } : {}),
    ...(motion.version !== 3 &&
    (track.trigger === 'mount' || track.trigger === 'pageEnter' || track.trigger === 'loop')
      ? {
          css: {
            variable: motionCssVariableName(token, index),
            animationNames: [
              motionCssAnimationName(token, index),
              motionCssAnimationName(token, index, true)
            ]
          }
        }
      : {})
  }
}

const ADVANCED_FRAME_KEYS = [
  'paints',
  'gradientStops',
  'effects',
  'cornerRadii',
  'textReveal',
  'fontAxes',
  'vectorMorph'
] as const

function runtimeAdvancedTrack(track: IRMotionTrack, motion: IRMotion): unknown {
  if (
    motion.version !== 3 ||
    !motion.target ||
    !track.keyframes.some((frame) => ADVANCED_FRAME_KEYS.some((key) => frame[key] !== undefined))
  ) {
    return undefined
  }
  return {
    target: motion.target,
    easing: track.timing.easing,
    keyframes: track.keyframes.map(runtimeAdvancedFrame)
  }
}

function runtimeAdvancedFrame(frame: IRMotionKeyframe): Record<string, unknown> {
  const result: Record<string, unknown> = { offset: frame.offset }
  for (const key of ADVANCED_FRAME_KEYS) {
    const value = frame[key]
    if (value === undefined) continue
    result[key] =
      key === 'vectorMorph' && frame.vectorMorph
        ? { topologyId: frame.vectorMorph.topologyId, paths: frame.vectorMorph.paths }
        : value
  }
  if (frame.easing) result.easing = frame.easing
  return result
}

function runtimeKeyframe(
  frame: IRMotionKeyframe,
  track: IRMotionTrack,
  motion: IRMotion,
  token: string,
  sourceIndex: number
): Record<string, string | number> {
  const hasPath = frame.pathProgress !== undefined && track.path !== undefined
  return {
    offset: frame.offset,
    ...(motion.version === 3
      ? runtimeStaticTransformFrame(frame, hasPath)
      : runtimeTransformFrame(frame, hasPath)),
    ...(motion.version === 3
      ? {
          [motionCompositionClockVariableName(token, sourceIndex)]: frame.offset,
          ...runtimeSampledPathCompositionFrame(frame, track, token, sourceIndex)
        }
      : {}),
    ...runtimePaintFrame(frame, motion),
    ...runtimePathFrame(frame, track, motion),
    ...runtimeLayoutFrame(frame),
    ...(frame.easing ? { easing: easingCss(frame.easing) } : {})
  }
}

function runtimeSampledPathCompositionFrame(
  frame: IRMotionKeyframe,
  track: IRMotionTrack,
  token: string,
  sourceIndex: number
): Record<string, number> {
  if (!track.sampledPath) return {}
  return Object.fromEntries(
    motionCompositionChannels(track).flatMap((channel) =>
      frame[channel] === undefined
        ? []
        : [[motionCompositionVariableName(token, sourceIndex, channel), frame[channel]]]
    )
  )
}

function runtimeStaticTransformFrame(
  frame: IRMotionKeyframe,
  pathOwnsTranslation: boolean
): Record<string, string | number> {
  const result = runtimeTransformFrame(frame, pathOwnsTranslation)
  delete result.opacity
  delete result.translate
  delete result.scale
  delete result.rotate
  return result
}

function runtimeTransformFrame(
  frame: IRMotionKeyframe,
  pathOwnsTranslation = false
): Record<string, string | number> {
  return {
    ...(frame.opacity !== undefined ? { opacity: frame.opacity } : {}),
    ...(!pathOwnsTranslation && (frame.x !== undefined || frame.y !== undefined)
      ? { translate: `${frame.x ?? 0}px ${frame.y ?? 0}px` }
      : {}),
    ...(frame.scaleX !== undefined || frame.scaleY !== undefined
      ? { scale: `${frame.scaleX ?? 1} ${frame.scaleY ?? 1}` }
      : {}),
    ...(frame.rotate !== undefined ? { rotate: `${frame.rotate}deg` } : {}),
    ...(frame.originX !== undefined || frame.originY !== undefined
      ? { transformOrigin: `${(frame.originX ?? 0.5) * 100}% ${(frame.originY ?? 0.5) * 100}%` }
      : {}),
    ...(frame.width !== undefined ? { width: `${frame.width}px` } : {}),
    ...(frame.height !== undefined ? { height: `${frame.height}px` } : {}),
    ...(frame.cornerRadius !== undefined ? { borderRadius: `${frame.cornerRadius}px` } : {})
  }
}

function runtimePaintFrame(frame: IRMotionKeyframe, motion: IRMotion): Record<string, string> {
  const kind = motionTargetKind(motion)
  const result: Record<string, string> = {}
  addRuntimePaintColors(result, frame, motion, kind)
  addRuntimeEffects(result, frame, kind)
  return result
}

function addRuntimePaintColors(
  result: Record<string, string>,
  frame: IRMotionKeyframe,
  motion: IRMotion,
  kind: ReturnType<typeof motionTargetKind>
): void {
  const target = motion.target
  if (frame.fillColor && target?.fillColor) {
    result[RUNTIME_FILL_PROPERTY[kind]] = colorToCSS(frame.fillColor)
  }
  if (frame.strokeColor && target?.strokeColor) {
    result[RUNTIME_STROKE_PROPERTY[kind]] = colorToCSS(frame.strokeColor)
  }
  if (frame.strokeWidth !== undefined && target?.strokeWidth !== undefined) {
    result[RUNTIME_STROKE_WIDTH_PROPERTY[kind]] =
      `${frame.strokeWidth}${kind === 'vector' ? '' : 'px'}`
  }
}

function addRuntimeEffects(
  result: Record<string, string>,
  frame: IRMotionKeyframe,
  kind: ReturnType<typeof motionTargetKind>
): void {
  const hasShadow = runtimeFrameHasShadow(frame)
  if (kind === 'vector') {
    const filters: string[] = []
    if (frame.blur !== undefined) filters.push(`blur(${frame.blur}px)`)
    if (hasShadow) filters.push(runtimeVectorDropShadow(frame))
    if (filters.length > 0) result.filter = filters.join(' ')
  } else if (frame.blur !== undefined) {
    result.filter = `blur(${frame.blur}px)`
  }
  if (hasShadow && kind === 'text') result.textShadow = runtimeTextShadow(frame)
  else if (hasShadow && kind === 'box') result.boxShadow = runtimeBoxShadow(frame)
}

function runtimeFrameHasShadow(frame: IRMotionKeyframe): boolean {
  return (
    frame.shadowX !== undefined ||
    frame.shadowY !== undefined ||
    frame.shadowBlur !== undefined ||
    frame.shadowSpread !== undefined ||
    frame.shadowColor !== undefined
  )
}

const RUNTIME_FILL_PROPERTY = {
  box: 'backgroundColor',
  text: 'color',
  vector: VECTOR_MOTION_FILL
} as const

const RUNTIME_STROKE_PROPERTY = {
  box: 'borderColor',
  text: 'WebkitTextStrokeColor',
  vector: VECTOR_MOTION_STROKE
} as const

const RUNTIME_STROKE_WIDTH_PROPERTY = {
  box: 'borderWidth',
  text: 'WebkitTextStrokeWidth',
  vector: VECTOR_MOTION_STROKE_WIDTH
} as const

function runtimePathFrame(
  frame: IRMotionKeyframe,
  track: IRMotionTrack,
  motion: IRMotion
): Record<string, string> {
  const result: Record<string, string> = {
    ...(frame.pathProgress !== undefined && track.path ? runtimeMotionPathFrame(frame, track) : {}),
    ...(motionTargetKind(motion) === 'vector' &&
    motion.target?.strokeColor &&
    (frame.trimStart !== undefined || frame.trimEnd !== undefined)
      ? {
          [VECTOR_MOTION_TRIM_VISIBLE]: String(
            Math.max(0, (frame.trimEnd ?? 1) - (frame.trimStart ?? 0))
          ),
          [VECTOR_MOTION_TRIM_HIDDEN]: String(
            1 - Math.max(0, (frame.trimEnd ?? 1) - (frame.trimStart ?? 0))
          ),
          [VECTOR_MOTION_TRIM_OFFSET]: String(-((frame.trimStart ?? 0) + (frame.trimOffset ?? 0)))
        }
      : {})
  }
  return result
}

function runtimeMotionPathFrame(
  frame: IRMotionKeyframe,
  track: IRMotionTrack
): Record<string, string> {
  const originX = frame.originX ?? 0.5
  const originY = frame.originY ?? 0.5
  const anchorX = (frame.width ?? 0) * originX + (frame.x ?? 0)
  const anchorY = (frame.height ?? 0) * originY + (frame.y ?? 0)
  return {
    offsetPath: runtimeOffsetPath(track.path?.points ?? [], anchorX, anchorY),
    offsetDistance: `${(frame.pathProgress ?? 0) * 100}%`,
    offsetAnchor: `${originX * 100}% ${originY * 100}%`,
    offsetRotate: track.path?.autoRotate ? 'auto' : '0deg'
  }
}

function runtimeBoxShadow(frame: IRMotionKeyframe): string {
  return `${frame.shadowX ?? 0}px ${frame.shadowY ?? 0}px ${frame.shadowBlur ?? 0}px ${frame.shadowSpread ?? 0}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)}`
}

function runtimeTextShadow(frame: IRMotionKeyframe): string {
  return `${frame.shadowX ?? 0}px ${frame.shadowY ?? 0}px ${runtimeSpreadlessShadowBlur(frame)}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)}`
}

function runtimeVectorDropShadow(frame: IRMotionKeyframe): string {
  return `drop-shadow(${frame.shadowX ?? 0}px ${frame.shadowY ?? 0}px ${runtimeSpreadlessShadowBlur(frame)}px ${colorToCSS(frame.shadowColor ?? TRANSPARENT)})`
}

function runtimeSpreadlessShadowBlur(frame: IRMotionKeyframe): number {
  return Math.max(0, (frame.shadowBlur ?? 0) + (frame.shadowSpread ?? 0))
}

function runtimeLayoutFrame(frame: IRMotionKeyframe): Record<string, string> {
  return {
    ...(frame.gap !== undefined ? { gap: `${frame.gap}px` } : {}),
    ...(frame.rowGap !== undefined ? { rowGap: `${frame.rowGap}px` } : {}),
    ...(frame.columnGap !== undefined ? { columnGap: `${frame.columnGap}px` } : {}),
    ...(frame.paddingTop !== undefined ? { paddingTop: `${frame.paddingTop}px` } : {}),
    ...(frame.paddingRight !== undefined ? { paddingRight: `${frame.paddingRight}px` } : {}),
    ...(frame.paddingBottom !== undefined ? { paddingBottom: `${frame.paddingBottom}px` } : {}),
    ...(frame.paddingLeft !== undefined ? { paddingLeft: `${frame.paddingLeft}px` } : {})
  }
}

function runtimeOffsetPath(
  points: NonNullable<IRMotionTrack['path']>['points'],
  anchorX: number,
  anchorY: number
): string {
  const [first, ...rest] = points
  return `path("${[
    `M ${first.x + anchorX} ${first.y + anchorY}`,
    ...rest.map((point) => `L ${point.x + anchorX} ${point.y + anchorY}`)
  ].join(' ')}")`
}
