import type { IRMotionTrack } from '#compiler/ir/motion'

import { easingCss } from './key'
import type { ReactMotionEntry } from './types'

const RUNTIME_TRIGGERS = new Set(['hover', 'press', 'focus', 'click', 'inView'])

/** Build the zero-dependency delegated WAAPI runtime. */
export function buildMotionRuntime(entries: readonly ReactMotionEntry[]): string | undefined {
  const registry = Object.fromEntries(
    entries.flatMap((entry) => {
      const tracks = entry.motion.tracks.filter((track) => RUNTIME_TRIGGERS.has(track.trigger))
      return tracks.length > 0
        ? [
            [
              entry.token,
              { reducedMotion: entry.motion.reducedMotion, tracks: tracks.map(runtimeTrack) }
            ]
          ]
        : []
    })
  )
  if (Object.keys(registry).length === 0) return undefined

  return `/* Generated by OpenPencil. */
type MotionTrigger = 'hover' | 'press' | 'focus' | 'click' | 'inView'
type MotionExit = 'none' | 'reverse' | 'reset'

interface MotionFrame {
  offset: number
  opacity?: number
  translate?: string
  scale?: string
  rotate?: string
  easing?: string
}

interface MotionTrack {
  trigger: MotionTrigger
  exit: MotionExit
  keyframes: MotionFrame[]
  timing: {
    duration: number
    delay: number
    easing: string
    iterations: number | 'infinite'
    direction: PlaybackDirection
    fill: FillMode
  }
}

interface MotionSpec {
  reducedMotion: 'reduce' | 'disable' | 'allow'
  tracks: MotionTrack[]
}

interface ActiveTrack {
  track: MotionTrack
  animation: Animation
}

const registry: Record<string, MotionSpec> = ${JSON.stringify(registry)}
const runtimeGlobal = globalThis as typeof globalThis & {
  __OPENPENCIL_MOTION_RUNTIME__?: { dispose: () => void }
}
runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__?.dispose()
const selector = '[data-op-motion]'
const active = new WeakMap<Element, Map<MotionTrigger, ActiveTrack[]>>()
const allAnimations = new Set<Animation>()
const observedAnimations = new WeakSet<Animation>()
const pointerPresses = new Map<number, Element[]>()
const keyboardPresses = new Set<Element>()

function specFor(element: Element): MotionSpec | undefined {
  const token = element.getAttribute('data-op-motion')
  return token ? registry[token] : undefined
}

function motionElements(target: EventTarget | null): Element[] {
  if (!(target instanceof Element)) return []
  const elements: Element[] = []
  for (let element: Element | null = target; element; element = element.parentElement) {
    if (element.matches(selector) && specFor(element)) elements.push(element)
  }
  return elements
}

function prefersReducedMotion(): boolean {
  return typeof window.matchMedia === 'function' && window.matchMedia('(prefers-reduced-motion: reduce)').matches
}

function playableTrack(track: MotionTrack, policy: MotionSpec['reducedMotion']): MotionTrack | null {
  if (!prefersReducedMotion() || policy === 'allow') return track
  if (policy === 'disable') return null
  const keyframes = track.keyframes.map(({ offset, opacity, easing }) => ({
    offset,
    ...(opacity === undefined ? {} : { opacity }),
    ...(easing === undefined ? {} : { easing })
  }))
  if (!keyframes.some((frame) => frame.opacity !== undefined)) return null
  return {
    ...track,
    keyframes,
    timing: { ...track.timing, duration: Math.min(track.timing.duration, 120), delay: 0 }
  }
}

function trackAnimation(animation: Animation): void {
  allAnimations.add(animation)
  if (observedAnimations.has(animation)) return
  observedAnimations.add(animation)
  const release = (event: Event) => allAnimations.delete(event.currentTarget as Animation)
  animation.addEventListener('cancel', release)
  animation.addEventListener('finish', release)
}

function cancelAnimation(animation: Animation): void {
  allAnimations.delete(animation)
  animation.cancel()
}

function run(element: Element, trigger: MotionTrigger): void {
  const spec = specFor(element)
  if (!spec) return
  const byTrigger = active.get(element) ?? new Map<MotionTrigger, ActiveTrack[]>()
  for (const item of byTrigger.get(trigger) ?? []) cancelAnimation(item.animation)
  const started: ActiveTrack[] = []
  for (const sourceTrack of spec.tracks) {
    if (sourceTrack.trigger !== trigger) continue
    const track = playableTrack(sourceTrack, spec.reducedMotion)
    if (!track) continue
    const animation = element.animate(track.keyframes as Keyframe[], {
      duration: track.timing.duration,
      delay: track.timing.delay,
      easing: track.timing.easing,
      iterations: track.timing.iterations === 'infinite' ? Infinity : track.timing.iterations,
      direction: track.timing.direction,
      fill: track.timing.fill
    })
    trackAnimation(animation)
    started.push({ track, animation })
  }
  if (started.length > 0) {
    byTrigger.set(trigger, started)
    active.set(element, byTrigger)
  } else {
    byTrigger.delete(trigger)
  }
}

function exit(element: Element, trigger: MotionTrigger): void {
  const items = active.get(element)?.get(trigger)
  if (!items) return
  const retained: ActiveTrack[] = []
  for (const item of items) {
    if (item.track.exit === 'none') {
      retained.push(item)
    } else if (item.track.exit === 'reverse') {
      trackAnimation(item.animation)
      item.animation.reverse()
      retained.push(item)
    } else {
      cancelAnimation(item.animation)
    }
  }
  const byTrigger = active.get(element)
  if (!byTrigger) return
  if (retained.length > 0) byTrigger.set(trigger, retained)
  else byTrigger.delete(trigger)
}

function movedWithin(element: Element, relatedTarget: EventTarget | null): boolean {
  return relatedTarget instanceof Node && element.contains(relatedTarget)
}

function releasePointerPress(pointerId: number): void {
  const elements = pointerPresses.get(pointerId)
  if (!elements) return
  pointerPresses.delete(pointerId)
  for (const element of elements) exit(element, 'press')
}

const listeners: Array<[string, EventListener]> = []
function listen(type: string, listener: EventListener): void {
  document.addEventListener(type, listener, true)
  listeners.push([type, listener])
}

listen('pointerover', ((event: PointerEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) run(element, 'hover')
  }
}) as EventListener)

listen('pointerout', ((event: PointerEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) exit(element, 'hover')
  }
}) as EventListener)

listen('pointerdown', ((event: PointerEvent) => {
  const elements = motionElements(event.target)
  if (elements.length === 0) return
  releasePointerPress(event.pointerId)
  pointerPresses.set(event.pointerId, elements)
  for (const element of elements) run(element, 'press')
}) as EventListener)

const finishPointerPress = ((event: PointerEvent) => {
  releasePointerPress(event.pointerId)
}) as EventListener
listen('pointerup', finishPointerPress)
listen('pointercancel', finishPointerPress)

listen('keydown', ((event: KeyboardEvent) => {
  if (event.repeat || (event.key !== 'Enter' && event.key !== ' ')) return
  for (const element of motionElements(event.target)) {
    keyboardPresses.add(element)
    run(element, 'press')
  }
}) as EventListener)

listen('keyup', ((event: KeyboardEvent) => {
  if (event.key !== 'Enter' && event.key !== ' ') return
  for (const pressed of keyboardPresses) exit(pressed, 'press')
  keyboardPresses.clear()
}) as EventListener)

listen('focusin', ((event: FocusEvent) => {
  for (const element of motionElements(event.target)) {
    if (!movedWithin(element, event.relatedTarget)) run(element, 'focus')
  }
}) as EventListener)

listen('focusout', ((event: FocusEvent) => {
  for (const element of motionElements(event.target)) {
    if (movedWithin(element, event.relatedTarget)) continue
    if (keyboardPresses.delete(element)) exit(element, 'press')
    exit(element, 'focus')
  }
}) as EventListener)

listen('click', ((event: MouseEvent) => {
  for (const element of motionElements(event.target)) run(element, 'click')
}) as EventListener)

const inViewObserver = typeof IntersectionObserver === 'undefined'
  ? null
  : new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) run(entry.target, 'inView')
        else exit(entry.target, 'inView')
      }
    })

function scan(root: ParentNode): void {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(selector)) elements.push(root)
  elements.push(...root.querySelectorAll(selector))
  for (const element of elements) {
    const spec = specFor(element)
    if (spec?.tracks.some((track) => track.trigger === 'inView')) inViewObserver?.observe(element)
  }
}

function cleanupElement(element: Element): void {
  const byTrigger = active.get(element)
  if (byTrigger) {
    for (const items of byTrigger.values()) {
      for (const item of items) cancelAnimation(item.animation)
    }
    active.delete(element)
  }
  inViewObserver?.unobserve(element)
  for (const [pointerId, elements] of pointerPresses) {
    const remaining = elements.filter((candidate) => candidate !== element)
    if (remaining.length > 0) pointerPresses.set(pointerId, remaining)
    else pointerPresses.delete(pointerId)
  }
  keyboardPresses.delete(element)
}

function cleanupTree(root: ParentNode): void {
  if (root instanceof Element) cleanupElement(root)
  for (const element of root.querySelectorAll('*')) cleanupElement(element)
}

scan(document)
const mutationObserver = new MutationObserver((records) => {
  for (const record of records) {
    if (record.type === 'attributes') cleanupElement(record.target as Element)
    for (const node of record.removedNodes) {
      if (node instanceof Element) cleanupTree(node)
    }
  }
  for (const record of records) {
    if (record.type === 'attributes') scan(record.target as Element)
    for (const node of record.addedNodes) {
      if (node instanceof Element) scan(node)
    }
  }
})
mutationObserver.observe(document.documentElement, {
  childList: true,
  subtree: true,
  attributes: true,
  attributeFilter: ['data-op-motion']
})

function dispose(): void {
  for (const [type, listener] of listeners) document.removeEventListener(type, listener, true)
  mutationObserver.disconnect()
  cleanupTree(document.documentElement)
  inViewObserver?.disconnect()
  for (const animation of [...allAnimations]) cancelAnimation(animation)
  allAnimations.clear()
  pointerPresses.clear()
  keyboardPresses.clear()
  if (runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__ === runtimeHandle) {
    delete runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__
  }
}

const runtimeHandle = { dispose }
runtimeGlobal.__OPENPENCIL_MOTION_RUNTIME__ = runtimeHandle
`
}

function runtimeTrack(track: IRMotionTrack): unknown {
  return {
    trigger: track.trigger,
    exit: track.exit,
    keyframes: track.keyframes.map((frame) => ({
      offset: frame.offset,
      ...(frame.opacity !== undefined ? { opacity: frame.opacity } : {}),
      ...(frame.x !== undefined || frame.y !== undefined
        ? { translate: `${frame.x ?? 0}px ${frame.y ?? 0}px` }
        : {}),
      ...(frame.scaleX !== undefined || frame.scaleY !== undefined
        ? { scale: `${frame.scaleX ?? 1} ${frame.scaleY ?? 1}` }
        : {}),
      ...(frame.rotate !== undefined ? { rotate: `${frame.rotate}deg` } : {}),
      ...(frame.easing ? { easing: easingCss(frame.easing) } : {})
    })),
    timing: {
      duration: track.timing.durationMs,
      delay: track.timing.delayMs,
      easing: easingCss(track.timing.easing),
      iterations: track.timing.iterations,
      direction: track.timing.direction,
      fill: track.timing.fill
    }
  }
}
