import { formatSupabaseManagedMarker } from '#compiler/backend/supabase/inspection'
import {
  qualified,
  quoteIdentifier,
  quoteLiteral
} from '#compiler/backend/supabase/migration-review/common'

import type { BackendApplicationSpecV2 } from '@open-pencil/lowcode/backend'

import {
  resolvedSupabaseBackfillV2,
  SUPABASE_BACKFILL_MAX_BATCH_RECEIPTS_V2,
  SUPABASE_BACKFILL_MAX_RECEIPTS_V2,
  SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2
} from './index'

/**
 * Emits catalog and row-summary queries only. Positional parameters in the third query are a Host
 * binding template: $1 is captured high water and $2 is the trusted prior receipt cursor.
 */
export function emitSupabaseBackfillReviewSQLV2(application: BackendApplicationSpecV2): string {
  const migration = resolvedSupabaseBackfillV2(application)
  const entity = application.dataModel.entities.at(0)
  if (!entity) throw new TypeError('Supabase backfill SQL requires one managed entity.')
  const targetField = entity.fields.find((field) => field.id === migration.transform.fieldId)
  if (!targetField) throw new TypeError('Supabase backfill SQL requires the resolved target field.')
  const targetEnum =
    targetField.type === 'enum'
      ? application.dataModel.enums.find((entry) => entry.id === targetField.enumId)
      : undefined
  if (targetField.type === 'enum' && !targetEnum) {
    throw new TypeError('Supabase backfill SQL requires the resolved target enum.')
  }
  const tablePath = qualified(migration.table)
  const cursorName = quoteIdentifier(migration.cursor.field)
  const targetName = quoteIdentifier(migration.transform.field)
  const desiredDefaultJSON = JSON.stringify(migration.transform.value)
  const expectedTypeKind = targetField.type === 'enum' ? 'e' : 'b'
  const enumMarkerAndLabelsSQL = targetEnum
    ? `COALESCE((SELECT "pg_catalog"."obj_description"("actual_type_oid", 'pg_type') = ${quoteLiteral(formatSupabaseManagedMarker('enum', targetEnum.id))} AND (SELECT COALESCE("pg_catalog"."jsonb_agg"("enum_entry"."enumlabel" ORDER BY "enum_entry"."enumsortorder"), '[]'::"pg_catalog"."jsonb") FROM "pg_catalog"."pg_enum" AS "enum_entry" WHERE "enum_entry"."enumtypid" = "target_column"."actual_type_oid") = ${quoteLiteral(JSON.stringify(targetEnum.values))}::"pg_catalog"."jsonb" FROM "target_column"), FALSE)`
    : 'TRUE'
  const matchedRows = migration.postconditions.find(
    (condition) => condition.kind === 'matched-row-count'
  )
  const requiredMatchedRowsSQL = matchedRows ? String(matchedRows.minimum) : 'NULL'
  const lines = [
    '-- OpenPencil Supabase receipt-driven backfill read-only review v1.',
    '-- REVIEW ONLY: no direct DML or DDL is emitted; this file is not execution authority.',
    '-- A trusted Host must enforce a database READ ONLY transaction because SELECT can invoke policy functions.',
    '-- Row reads additionally require one fixed role/search_path and row_security=off failure semantics.',
    '-- Statement 1 reports a partial catalog checklist; its generated text is not live evidence.',
    'WITH "managed_table" AS (',
    '  SELECT "table_class"."oid", "table_class"."relrowsecurity", "table_class"."relforcerowsecurity"',
    '  FROM "pg_catalog"."pg_class" AS "table_class"',
    '  JOIN "pg_catalog"."pg_namespace" AS "table_namespace"',
    '    ON "table_namespace"."oid" = "table_class"."relnamespace"',
    '  WHERE "table_namespace"."nspname" = \'public\'',
    `    AND "table_class"."relname" = ${quoteLiteral(migration.table)}`,
    '    AND "table_class"."relkind" = \'r\'',
    `    AND "pg_catalog"."obj_description"("table_class"."oid", 'pg_class') = ${quoteLiteral(formatSupabaseManagedMarker('entity', entity.id))}`,
    '),',
    '"cursor_column" AS (',
    '  SELECT "column_entry"."attrelid", "column_entry"."attnum", "column_entry"."attidentity"',
    '  FROM "pg_catalog"."pg_attribute" AS "column_entry"',
    '  JOIN "managed_table" ON "managed_table"."oid" = "column_entry"."attrelid"',
    `  WHERE "column_entry"."attname" = ${quoteLiteral(migration.cursor.field)}`,
    '    AND "column_entry"."attnum" > 0',
    '    AND NOT "column_entry"."attisdropped"',
    '    AND "column_entry"."attnotnull"',
    '    AND "column_entry"."atttypid" = "pg_catalog"."to_regtype"(\'pg_catalog.int8\')',
    `    AND "pg_catalog"."col_description"("column_entry"."attrelid", "column_entry"."attnum") = ${quoteLiteral(formatSupabaseManagedMarker('field', migration.cursor.fieldId))}`,
    '),',
    '"target_column" AS (',
    '  SELECT',
    '    "column_entry"."attrelid",',
    '    "column_entry"."attnum",',
    '    "column_entry"."atttypmod" AS "actual_type_modifier",',
    '    "column_entry"."attgenerated" AS "generated_kind",',
    '    NOT "column_entry"."attnotnull" AS "currently_nullable",',
    '    "column_entry"."atttypid" AS "actual_type_oid",',
    '    "type_namespace"."nspname" AS "actual_type_schema",',
    '    "type_entry"."typname" AS "actual_type_name",',
    '    "type_entry"."typtype" AS "actual_type_kind",',
    '    "column_default"."oid" IS NOT NULL AS "has_default_expression"',
    '  FROM "pg_catalog"."pg_attribute" AS "column_entry"',
    '  JOIN "managed_table" ON "managed_table"."oid" = "column_entry"."attrelid"',
    '  JOIN "pg_catalog"."pg_type" AS "type_entry"',
    '    ON "type_entry"."oid" = "column_entry"."atttypid"',
    '  JOIN "pg_catalog"."pg_namespace" AS "type_namespace"',
    '    ON "type_namespace"."oid" = "type_entry"."typnamespace"',
    '  LEFT JOIN "pg_catalog"."pg_attrdef" AS "column_default"',
    '    ON "column_default"."adrelid" = "column_entry"."attrelid"',
    '   AND "column_default"."adnum" = "column_entry"."attnum"',
    `  WHERE "column_entry"."attname" = ${quoteLiteral(migration.transform.field)}`,
    '    AND "column_entry"."attnum" > 0',
    '    AND NOT "column_entry"."attisdropped"',
    `    AND "pg_catalog"."col_description"("column_entry"."attrelid", "column_entry"."attnum") = ${quoteLiteral(formatSupabaseManagedMarker('field', migration.transform.fieldId))}`,
    '),',
    '"table_write_hazards" AS (',
    '  SELECT',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_constraint" AS "constraint_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "constraint_entry"."conrelid"',
    '      WHERE "constraint_entry"."contype" IN (\'u\', \'x\')) AS "non_primary_unique_or_exclusion_constraint_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_index" AS "index_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "index_entry"."indrelid"',
    '      WHERE NOT "index_entry"."indisprimary") AS "non_primary_index_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_index" AS "index_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "index_entry"."indrelid"',
    '      WHERE ("index_entry"."indpred" IS NOT NULL',
    '         OR "index_entry"."indexprs" IS NOT NULL)) AS "partial_or_expression_index_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_constraint" AS "constraint_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "constraint_entry"."conrelid"',
    '      WHERE "constraint_entry"."contype" = \'c\') AS "check_constraint_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_constraint" AS "constraint_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "constraint_entry"."conrelid"',
    '      WHERE "constraint_entry"."contype" = \'f\') AS "outbound_foreign_key_constraint_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_attribute" AS "generated_column"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "generated_column"."attrelid"',
    '      WHERE "generated_column"."attnum" > 0',
    '        AND NOT "generated_column"."attisdropped"',
    '        AND "generated_column"."attgenerated" <> \'\') AS "generated_column_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_inherits" AS "inheritance_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "inheritance_entry"."inhrelid"',
    '        OR "managed_table"."oid" = "inheritance_entry"."inhparent") AS "inheritance_relation_count"',
    '),',
    '"primary_key" AS (',
    '  SELECT "constraint_entry"."oid"',
    '  FROM "pg_catalog"."pg_constraint" AS "constraint_entry"',
    '  JOIN "managed_table" ON "managed_table"."oid" = "constraint_entry"."conrelid"',
    '  JOIN "cursor_column" ON "cursor_column"."attrelid" = "constraint_entry"."conrelid"',
    '  WHERE "constraint_entry"."contype" = \'p\'',
    '    AND "constraint_entry"."conkey" = ARRAY["cursor_column"."attnum"]::"pg_catalog"."int2"[]',
    `    AND "pg_catalog"."obj_description"("constraint_entry"."oid", 'pg_constraint') = ${quoteLiteral(formatSupabaseManagedMarker('primary-key', entity.id))}`,
    '),',
    '"identity_sequence" AS (',
    '  SELECT',
    '    "sequence_class"."oid",',
    '    "sequence_state"."seqincrement",',
    '    "sequence_state"."seqmin",',
    '    "sequence_state"."seqmax",',
    '    "sequence_state"."seqcache",',
    '    "sequence_state"."seqcycle",',
    '    "sequence_live"."last_value",',
    '    ("pg_catalog"."has_sequence_privilege"("sequence_class"."oid", \'SELECT\')',
    '      OR "pg_catalog"."has_sequence_privilege"("sequence_class"."oid", \'USAGE\')) AS "sequence_state_readable"',
    '  FROM "cursor_column"',
    '  JOIN "pg_catalog"."pg_depend" AS "sequence_dependency"',
    '    ON "sequence_dependency"."refobjid" = "cursor_column"."attrelid"',
    '   AND "sequence_dependency"."refobjsubid" = "cursor_column"."attnum"',
    '   AND "sequence_dependency"."deptype" = \'i\'',
    '   AND "sequence_dependency"."classid" = "pg_catalog"."to_regclass"(\'pg_catalog.pg_class\')',
    '   AND "sequence_dependency"."refclassid" = "pg_catalog"."to_regclass"(\'pg_catalog.pg_class\')',
    '  JOIN "pg_catalog"."pg_class" AS "sequence_class"',
    '    ON "sequence_class"."oid" = "sequence_dependency"."objid"',
    '   AND "sequence_class"."relkind" = \'S\'',
    '  JOIN "pg_catalog"."pg_namespace" AS "sequence_namespace"',
    '    ON "sequence_namespace"."oid" = "sequence_class"."relnamespace"',
    '  JOIN "pg_catalog"."pg_sequence" AS "sequence_state"',
    '    ON "sequence_state"."seqrelid" = "sequence_class"."oid"',
    '  LEFT JOIN "pg_catalog"."pg_sequences" AS "sequence_live"',
    '    ON "sequence_live"."schemaname" = "sequence_namespace"."nspname"',
    '   AND "sequence_live"."sequencename" = "sequence_class"."relname"',
    '),',
    '"user_behavior" AS (',
    '  SELECT',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_trigger" AS "trigger_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "trigger_entry"."tgrelid"',
    '      WHERE NOT "trigger_entry"."tgisinternal") AS "user_trigger_count",',
    '    (SELECT COUNT(*) FROM "pg_catalog"."pg_rewrite" AS "rule_entry"',
    '      JOIN "managed_table" ON "managed_table"."oid" = "rule_entry"."ev_class"',
    '      WHERE "rule_entry"."rulename" <> \'_RETURN\') AS "user_rule_count"',
    ')',
    'SELECT',
    '  (SELECT COUNT(*) FROM "managed_table") = 1 AS "entity_marker_matches",',
    '  (SELECT COUNT(*) FROM "cursor_column") = 1 AS "cursor_marker_type_and_nullability_match",',
    '  COALESCE((SELECT "attidentity" = \'a\' FROM "cursor_column"), FALSE) AS "identity_is_always",',
    '  (SELECT COUNT(*) FROM "primary_key") = 1 AS "primary_key_marker_and_shape_match",',
    '  COALESCE((SELECT "relrowsecurity" AND "relforcerowsecurity" FROM "managed_table"), FALSE) AS "rls_enabled_and_forced",',
    '  (SELECT COUNT(*) FROM "target_column") = 1 AS "target_marker_matches",',
    '  (SELECT "actual_type_schema" FROM "target_column") AS "target_actual_type_schema",',
    '  (SELECT "actual_type_name" FROM "target_column") AS "target_actual_type_name",',
    '  (SELECT "actual_type_kind" FROM "target_column") AS "target_actual_type_kind",',
    '  (SELECT "actual_type_modifier" FROM "target_column") AS "target_actual_type_modifier",',
    '  (SELECT "generated_kind" FROM "target_column") AS "target_generated_kind",',
    `  COALESCE((SELECT "actual_type_oid" = "pg_catalog"."to_regtype"(${quoteLiteral(migration.transform.expectedPostgresType)}) AND "actual_type_kind" = ${quoteLiteral(expectedTypeKind)} AND "actual_type_modifier" = -1 AND "generated_kind" = '' FROM "target_column"), FALSE) AS "target_type_shape_matches",`,
    `  ${enumMarkerAndLabelsSQL} AS "target_enum_marker_and_ordered_labels_match",`,
    '  COALESCE((SELECT "currently_nullable" FROM "target_column"), FALSE) AS "target_is_currently_nullable",',
    '  COALESCE((SELECT "has_default_expression" FROM "target_column"), FALSE) AS "target_has_default_expression",',
    `  ${quoteLiteral(desiredDefaultJSON)}::"pg_catalog"."jsonb" AS "target_expected_literal_json",`,
    '  FALSE AS "target_default_expression_equivalence_proven",',
    '  (SELECT "non_primary_unique_or_exclusion_constraint_count" FROM "table_write_hazards") AS "non_primary_unique_or_exclusion_constraint_count",',
    '  (SELECT "non_primary_index_count" FROM "table_write_hazards") AS "non_primary_index_count",',
    '  (SELECT "partial_or_expression_index_count" FROM "table_write_hazards") AS "partial_or_expression_index_count",',
    '  (SELECT "check_constraint_count" FROM "table_write_hazards") AS "check_constraint_count",',
    '  (SELECT "outbound_foreign_key_constraint_count" FROM "table_write_hazards") AS "outbound_foreign_key_constraint_count",',
    '  (SELECT "generated_column_count" FROM "table_write_hazards") AS "generated_column_count",',
    '  (SELECT "inheritance_relation_count" FROM "table_write_hazards") AS "inheritance_relation_count",',
    '  COALESCE((SELECT "non_primary_unique_or_exclusion_constraint_count" = 0 AND "non_primary_index_count" = 0 AND "partial_or_expression_index_count" = 0 AND "check_constraint_count" = 0 AND "outbound_foreign_key_constraint_count" = 0 AND "generated_column_count" = 0 AND "inheritance_relation_count" = 0 FROM "table_write_hazards"), FALSE) AS "table_has_no_backfill_write_hazards",',
    '  (SELECT "oid" FROM "managed_table") AS "managed_table_oid",',
    '  (SELECT "attnum" FROM "cursor_column") AS "cursor_attribute_number",',
    '  (SELECT "attnum" FROM "target_column") AS "target_attribute_number",',
    '  (SELECT COUNT(*) FROM "identity_sequence") = 1 AS "identity_sequence_owned_by_cursor",',
    '  (SELECT "oid" FROM "identity_sequence") AS "identity_sequence_oid",',
    '  NOT "pg_catalog"."pg_is_in_recovery"() AS "database_is_primary",',
    '  COALESCE((SELECT "sequence_state_readable" FROM "identity_sequence"), FALSE) AS "identity_sequence_state_readable",',
    `  COALESCE((SELECT "seqincrement" = 1 AND "seqmin" >= 0 AND "seqmax" <= ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2} AND "seqcache" = 1 AND NOT "seqcycle" FROM "identity_sequence"), FALSE) AS "identity_sequence_properties_safe",`,
    `  COALESCE((SELECT "sequence_state_readable" AND NOT "pg_catalog"."pg_is_in_recovery"() AND ("last_value" IS NULL OR "last_value" BETWEEN 0 AND ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2}) FROM "identity_sequence"), FALSE) AS "identity_sequence_current_value_safe",`,
    `  COALESCE((SELECT "sequence_state_readable" AND NOT "pg_catalog"."pg_is_in_recovery"() AND "last_value" IS NOT NULL AND "last_value" > COALESCE((SELECT MAX(${cursorName}) FROM ${tablePath}), -1) FROM "identity_sequence"), FALSE) AS "identity_sequence_next_value_definitely_above_cursor",`,
    '  FALSE AS "identity_sequence_next_value_and_is_called_proven",',
    '  CURRENT_USER::"pg_catalog"."text" AS "current_role",',
    '  SESSION_USER::"pg_catalog"."text" AS "session_role",',
    '  "pg_catalog"."current_setting"(\'row_security\') AS "row_security_setting",',
    '  "pg_catalog"."current_setting"(\'search_path\') AS "search_path_setting",',
    '  COALESCE((SELECT "pg_catalog"."row_security_active"("oid") FROM "managed_table"), TRUE) AS "row_security_active_for_table",',
    '  (SELECT "user_trigger_count" FROM "user_behavior") AS "user_trigger_count",',
    '  (SELECT "user_rule_count" FROM "user_behavior") AS "user_rule_count";',
    '',
    '-- Statement 2 observes a high-water candidate without a write barrier or lock.',
    '-- It is review evidence only and MUST NOT be used as a captured execution high water or receipt.',
    'WITH "row_summary" AS (',
    '  SELECT',
    `    MAX(${cursorName}) FILTER (WHERE ${cursorName} BETWEEN 0 AND ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2}) AS "observed_high_water_candidate",`,
    `    COUNT(*) FILTER (WHERE ${cursorName} BETWEEN 0 AND ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2}) AS "bounded_range_row_count",`,
    `    COUNT(*) FILTER (WHERE ${cursorName} BETWEEN 0 AND ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2} AND ${targetName} IS NULL) AS "eligible_row_count",`,
    `    COUNT(*) FILTER (WHERE ${cursorName} < 0 OR ${cursorName} > ${SUPABASE_BACKFILL_MAX_SAFE_CURSOR_V2}) AS "unsafe_cursor_row_count"`,
    `  FROM ${tablePath}`,
    ')',
    'SELECT',
    '  "observed_high_water_candidate",',
    '  "bounded_range_row_count",',
    '  "eligible_row_count",',
    '  "unsafe_cursor_row_count",',
    `  CEIL("eligible_row_count"::"pg_catalog"."numeric" / ${migration.batchSize})::"pg_catalog"."int8" AS "eligible_batch_count",`,
    `  CEIL("bounded_range_row_count"::"pg_catalog"."numeric" / ${migration.batchSize})::"pg_catalog"."int8" AS "cursor_range_batch_count",`,
    `  ${SUPABASE_BACKFILL_MAX_RECEIPTS_V2}::"pg_catalog"."int8" AS "maximum_total_receipt_count",`,
    `  ${SUPABASE_BACKFILL_MAX_BATCH_RECEIPTS_V2}::"pg_catalog"."int8" AS "maximum_batch_receipt_count",`,
    `  CEIL("bounded_range_row_count"::"pg_catalog"."numeric" / ${migration.batchSize}) <= ${SUPABASE_BACKFILL_MAX_BATCH_RECEIPTS_V2} AS "within_receipt_count_limit"`,
    'FROM "row_summary";',
    '',
    '-- Statement 3 previews one receipt-bounded scan. Host binds $1 high water and $2 prior cursor.',
    'WITH "trusted_input" AS (',
    '  SELECT',
    '    $1::"pg_catalog"."int8" AS "captured_high_water",',
    '    $2::"pg_catalog"."int8" AS "last_processed_key"',
    '),',
    '"bounded_batch" AS (',
    '  SELECT',
    `    "candidate".${cursorName} AS "cursor_value",`,
    `    "candidate".${targetName} IS NULL AS "matches_predicate"`,
    `  FROM ${tablePath} AS "candidate"`,
    '  CROSS JOIN "trusted_input"',
    '  WHERE "trusted_input"."captured_high_water" BETWEEN 0 AND 9007199254740991',
    '    AND ("trusted_input"."last_processed_key" IS NULL',
    '      OR "trusted_input"."last_processed_key" BETWEEN 0 AND "trusted_input"."captured_high_water")',
    `    AND "candidate".${cursorName} > COALESCE("trusted_input"."last_processed_key", -1)`,
    `    AND "candidate".${cursorName} <= "trusted_input"."captured_high_water"`,
    `  ORDER BY "candidate".${cursorName} ASC`,
    `  LIMIT ${migration.batchSize}`,
    ')',
    'SELECT',
    '  MIN("cursor_value") AS "first_scanned_key",',
    '  MAX("cursor_value") AS "last_scanned_key",',
    '  COUNT(*) AS "scanned_row_count",',
    '  COUNT(*) FILTER (WHERE "matches_predicate") AS "matched_row_count",',
    `  COUNT(*) <= ${migration.batchSize} AS "batch_size_respected"`,
    'FROM "bounded_batch";',
    '',
    '-- Statement 4 reports the field postcondition; receipt counts remain Host-bound evidence.',
    'SELECT',
    `  COUNT(*) FILTER (WHERE ${targetName} IS NULL) AS "remaining_null_row_count",`,
    `  COUNT(*) FILTER (WHERE ${targetName} IS NULL) = 0 AS "field_not_null_postcondition",`,
    `  ${requiredMatchedRowsSQL}::"pg_catalog"."int8" AS "required_matched_row_count_from_receipts"`,
    `FROM ${tablePath};`,
    ''
  ]
  return lines.join('\n')
}
