const english = {
  install: 'Create single-item checkout example',
  installHint:
    'Adds editable products, orders, atomic commands and login pages in one undo step. Uses the local Keycloak sign-in example, which you can change in HTTP API & Login. This action does not add database rows or start services.',
  blocked:
    'Use a new document without a Backend declaration or an existing sign-in flow for this example.',
  commands: 'Atomic commands',
  command: 'Backend command',
  recoveryAction: 'Recover backend command',
  recoveryEnabled: 'Allow recovery after refresh',
  recoveryStorage:
    'Saves this command’s request parameters on this device for the signed-in account. Tokens and full results are not saved.',
  recoveryOperation: 'Recovery operation',
  inspect: 'View saved attempt',
  retry: 'Retry saved request',
  acknowledge: 'Acknowledge handled attempt',
  recoveryKey: 'Saved attempt key expression',
  recoveryTitle: 'Saved attempt on this device',
  recoveryUninspected: 'Sign in and view the saved attempt.',
  recoveryEmpty: 'No saved attempt for this account.',
  recoveryIncompatible:
    'This saved attempt belongs to a different command version. Check the result before clearing it; retry is unavailable.',
  recoveryConfirm:
    'Have you checked My orders and confirmed this attempt is handled? Clearing this saved attempt cannot undo an order. Continue to start a new attempt?',
  savedSku: 'Saved product ID',
  savedOrder: 'Saved order ID',
  savedKey: 'Saved attempt key',
  parameters: 'Parameters',
  steps: 'Transaction steps',
  returns: 'Returns',
  entities: 'Affected entities',
  access: 'Access',
  authenticated: 'Signed-in users',
  commandHint:
    'The server applies each command in one transaction. Failed commands roll back. A retry with the same attempt key returns the original result; a changed request must use a new key.',
  empty:
    'No commands declared. Create the checkout example in a new document to inspect its commands.',
  keyState: 'Attempt key state',
  keyHint:
    'Choose an empty, non-persistent string document state. With browser recovery enabled, acknowledge the saved attempt before starting another; do not clear the key directly.',
  resultState: 'Result state',
  errorState: 'Error state',
  valueExpression: 'Value expression',
  shop: 'Products',
  orders: 'My orders',
  login: 'Shop sign in',
  admin: 'Catalog manager',
  signIn: 'Sign in',
  signOut: 'Sign out',
  choose: 'Choose product',
  quantity: 'Quantity (1–99)',
  quantityLabel: 'Quantity',
  unitPrice: 'Unit price',
  total: 'Total',
  orderLabel: 'Order',
  checkout: 'Place order',
  submitting: 'Submitting…',
  newOrder: 'Start new order',
  retryHint:
    'This device saves the original request. After refresh, sign in again and view the saved attempt. Retry uses its saved product, quantity and key, even if the form differs.',
  cancel: 'Cancel order',
  chooseOrder: 'Choose order to cancel',
  newCancellation: 'Start new cancellation',
  cancelHint:
    'After refresh, sign in and view the saved cancellation. Retry uses the saved order ID and key. Inventory is released only once.',
  first: 'First page',
  next: 'Next page',
  title: 'Product title',
  price: 'Unit price (minor units)',
  stock: 'Stock',
  active: 'Available for sale',
  saveProduct: 'Create product',
  newProduct: 'New product',
  editProduct: 'Edit product',
  saveChanges: 'Save changes',
  discardDraft: 'Discard draft',
  productCreated: 'Product created. It is now selected for editing.',
  productUpdated: 'Product changes saved.',
  catalogAll: 'All products',
  catalogHint: 'Includes available and unavailable products. Search starts from the first page.',
  chooseToManage: 'Choose a product to edit, or select New product.',
  draftHint:
    'Changes are saved only when you submit. Other managers can overwrite these fields with a later save.',
  initialStock: 'Initial stock',
  currentStock: 'Stock when selected',
  stockEditHint:
    'Stock is read-only here. Use Restock product to add inventory without overwriting purchases.',
  titleInvalid: 'Enter a non-blank product title, up to 16,384 characters.',
  nonnegativeInteger: 'Enter a whole number from 0 to 2,147,483,647.',
  published: 'Available',
  unpublished: 'Unavailable',
  markUnavailable: 'Mark unavailable',
  markAvailable: 'Mark available',
  restockTitle: 'Restock product',
  restockQuantity: 'Restock quantity (1–100000)',
  restockInvalid: 'Enter a whole restock quantity from 1 to 100,000.',
  restockHint:
    'Select an existing product first. Stock is added in one server transaction. Inspect and retry a saved request after refresh; the original key adds stock only once.',
  restockConfirm: 'Add this quantity to the selected product?',
  confirmRestock: 'Confirm restock',
  restocked:
    'Restock confirmed. Stock shown is the original transaction result, not the current inventory.',
  newRestock: 'Start new restock',
  restockAcknowledge:
    'Have you verified the saved restock request is handled? Current inventory alone does not prove whether it ran. Clearing the record cannot undo a restock. Continue to start another attempt?',
  adminHint:
    'Requires the catalog-manager role in the verified token. Prices use integer minor units; initial stock must be non-negative. No payment is collected.',
  productHint:
    'Choose a product, enter a quantity, then place an order. The server calculates the final amount.',
  search: 'Search products',
  searchPlaceholder: 'Search by product title',
  searchHint: 'Products are sorted by price, lowest first. Search starts from the first page.',
  soldOut: 'Sold out',
  review: 'Review your order',
  chooseFirst: 'Choose an available product to review your order.',
  estimatedTotal: 'Estimated total (minor units)',
  amountUnit: 'Amounts use integer minor units.',
  quantityInvalid: 'Enter a whole quantity from 1 to 99, within the displayed stock.',
  priceNotice:
    'Price and availability are checked again by the server. The final total may change. No payment is collected.',
  checkoutConfirm: 'Place this order?',
  confirmCheckout: 'Confirm order',
  keepEditing: 'Keep editing',
  placed: 'Order placed',
  pendingStatus: 'Pending',
  cancelledStatus: 'Cancelled',
  unknownStatus: 'Unknown status',
  createdAt: 'Ordered at (UTC)',
  selectedOrder: 'Selected order',
  cancelConfirm: 'Cancel this order and release its reserved stock?',
  confirmCancellation: 'Confirm cancellation',
  keepOrder: 'Keep order',
  cancelled: 'Order cancelled. Reserved stock has been released.',
  loginHint: 'Sign in to place an order or view your orders.',
  created: 'Checkout example created.'
}
const chinese: typeof english = {
  install: '生成单商品下单示例',
  installHint:
    '一次撤销可移除新增的商品、订单、原子命令和登录页面。使用本地 Keycloak 登录示例，可在“HTTP API 与登录”中修改。此操作不会添加数据库商品或启动服务。',
  blocked: '请在没有后端声明和登录流程的新文档中使用此示例。',
  commands: '原子命令',
  command: '后端命令',
  recoveryAction: '恢复后端命令',
  recoveryEnabled: '允许刷新后恢复',
  recoveryStorage: '在此设备保存当前账号的请求参数，不保存令牌或完整结果。',
  recoveryOperation: '恢复操作',
  inspect: '查看已保存尝试',
  retry: '重试已保存请求',
  acknowledge: '确认尝试已处理',
  recoveryKey: '已保存尝试标识表达式',
  recoveryTitle: '此设备保存的尝试',
  recoveryUninspected: '登录后查看上次尝试。',
  recoveryEmpty: '当前账号没有已保存的尝试。',
  recoveryIncompatible: '保存的尝试使用了其他命令版本，无法直接重试。请核对处理结果后再清除。',
  recoveryConfirm:
    '是否已查看“我的订单”并确认本次尝试已处理？清除保存记录不会撤销订单。确认后开始新尝试？',
  savedSku: '已保存商品 ID',
  savedOrder: '已保存订单 ID',
  savedKey: '已保存尝试标识',
  parameters: '参数',
  steps: '事务步骤',
  returns: '返回字段',
  entities: '作用实体',
  access: '权限',
  authenticated: '已登录用户',
  commandHint:
    '服务器在一个事务中执行命令，失败会整体回滚。使用相同尝试标识重试会返回原结果；请求内容改变时应开始新的尝试。',
  empty: '尚未声明命令。可在新文档中生成下单示例并查看命令。',
  keyState: '尝试标识状态',
  keyHint:
    '选择初始为空且不持久化的字符串文档状态。启用刷新恢复时，应确认保存的尝试已处理后再开始新的尝试，不要直接清空标识。',
  resultState: '结果状态',
  errorState: '错误状态',
  valueExpression: '值表达式',
  shop: '商品',
  orders: '我的订单',
  login: '商城登录',
  admin: '商品管理',
  signIn: '登录',
  signOut: '退出登录',
  choose: '选择商品',
  quantity: '数量（1–99）',
  quantityLabel: '数量',
  unitPrice: '单价',
  total: '总额',
  orderLabel: '订单',
  checkout: '提交订单',
  submitting: '正在提交…',
  newOrder: '开始新订单',
  retryHint:
    '此设备会保存原请求。刷新后请重新登录并查看保存的尝试。重试使用保存的商品、数量和标识，与当前表单内容无关。',
  cancel: '取消订单',
  chooseOrder: '选择待取消订单',
  newCancellation: '开始新的取消尝试',
  cancelHint:
    '刷新后重新登录并查看保存的取消尝试。重试使用保存的订单 ID 和标识，每笔订单只释放一次库存。',
  first: '第一页',
  next: '下一页',
  title: '商品名称',
  price: '单价（最小货币单位）',
  stock: '库存',
  active: '允许购买',
  saveProduct: '创建商品',
  newProduct: '新建商品',
  editProduct: '编辑商品',
  saveChanges: '保存修改',
  discardDraft: '放弃草稿',
  productCreated: '商品已创建，现可继续编辑。',
  productUpdated: '商品修改已保存。',
  catalogAll: '全部商品',
  catalogHint: '包括已上架和已下架商品；搜索会回到第一页。',
  chooseToManage: '选择商品进行编辑，或点击“新建商品”。',
  draftHint: '提交后才会保存修改；其他管理员后续保存可能覆盖这些字段。',
  initialStock: '初始库存',
  currentStock: '选中时的库存',
  stockEditHint: '此处库存只读。请通过“商品补货”增加库存，避免覆盖正在发生的下单。',
  titleInvalid: '请输入非空白商品名称，最多 16,384 个字符。',
  nonnegativeInteger: '请输入 0–2,147,483,647 的整数。',
  published: '已上架',
  unpublished: '已下架',
  markUnavailable: '设为下架',
  markAvailable: '设为上架',
  restockTitle: '商品补货',
  restockQuantity: '补货数量（1–100000）',
  restockInvalid: '请输入 1–100,000 的整数补货数量。',
  restockHint:
    '请先选择已有商品。服务器通过一个事务增加库存；刷新后可查看并重试已保存请求，相同标识只补货一次。',
  restockConfirm: '确认向选中的商品增加以下数量？',
  confirmRestock: '确认补货',
  restocked: '补货已确认，展示库存为原事务执行后的结果，不代表当前库存。',
  newRestock: '开始新补货',
  restockAcknowledge:
    '是否已核对保存的补货请求已处理？仅查看当前库存不能证明该请求是否执行。清除记录不会撤销补货，确认后开始新的尝试？',
  adminHint:
    '已验证令牌需要 catalog-manager 角色。金额使用整数最小货币单位，初始库存须为非负数。此示例不收款。',
  productHint: '选择商品、输入数量后提交订单，最终金额由服务器计算。',
  search: '搜索商品',
  searchPlaceholder: '按商品名称搜索',
  searchHint: '商品按价格从低到高排列；搜索会回到第一页。',
  soldOut: '已售罄',
  review: '核对订单',
  chooseFirst: '请选择有库存的商品，再核对订单。',
  estimatedTotal: '预计总额（最小货币单位）',
  amountUnit: '金额均为整数最小货币单位。',
  quantityInvalid: '请输入 1–99 的整数数量，且不超过展示库存。',
  priceNotice: '服务器会重新核对价格和库存，最终总额可能变化。此示例不收款。',
  checkoutConfirm: '确认提交以下订单？',
  confirmCheckout: '确认下单',
  keepEditing: '继续修改',
  placed: '下单成功',
  pendingStatus: '待处理',
  cancelledStatus: '已取消',
  unknownStatus: '未知状态',
  createdAt: '下单时间（UTC）',
  selectedOrder: '选中的订单',
  cancelConfirm: '确认取消以下订单并释放预留库存？',
  confirmCancellation: '确认取消订单',
  keepOrder: '保留订单',
  cancelled: '订单已取消，预留库存已释放。',
  loginHint: '登录后可下单或查看自己的订单。',
  created: '下单示例已生成。'
}
export function commerceCopy(locale: string): typeof english {
  return locale.startsWith('zh') ? chinese : english
}
