import { ACCORDION_MODULE_TYPE, ACCORDION_PLUGIN_ID } from '@open-pencil/core/plugins'

import { REACT_MODULE_POSITIONED_HOST_SOURCE } from './runtime-source'
import type { ReactModuleAdapter } from './types'

const ACCORDION_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
  type HTMLAttributes,
  type KeyboardEvent
} from 'react'

export interface OpenPencilAccordionItem {
  id: string
  title: string
  content: string
}

export interface OpenPencilAccordionConfig {
  label: string
  items: readonly OpenPencilAccordionItem[]
  allowMultiple: boolean
  initialOpenIds: readonly string[]
  showDividers: boolean
  backgroundColor: string
  textColor: string
  accentColor: string
  fontSize: number
}

export interface OpenPencilAccordionProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilAccordionConfig
}

export default function OpenPencilAccordion({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilAccordionProps) {
  const instanceId = useId().replace(/:/g, '')
  const buttonRefs = useRef<Array<HTMLButtonElement | null>>([])
  const identityKey = useMemo(
    () => config.items.map((item) => item.id).join('\\u0000'),
    [config.items]
  )
  const initialKey = config.initialOpenIds.join('\\u0000')
  const [openIds, setOpenIds] = useState(() => new Set(config.initialOpenIds))
${REACT_MODULE_POSITIONED_HOST_SOURCE}

  useEffect(() => {
    const available = new Set(config.items.map((item) => item.id))
    const requested = config.initialOpenIds.filter((id) => available.has(id))
    setOpenIds(new Set(config.allowMultiple ? requested : requested.slice(0, 1)))
  }, [config.allowMultiple, identityKey, initialKey])

  function toggle(id: string): void {
    setOpenIds((current) => {
      if (!config.allowMultiple) return current.has(id) ? new Set() : new Set([id])
      const next = new Set(current)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  function onHeaderKeyDown(event: KeyboardEvent<HTMLButtonElement>, index: number): void {
    let target: number | null = null
    if (event.key === 'ArrowUp') target = index - 1
    if (event.key === 'ArrowDown') target = index + 1
    if (event.key === 'Home') target = 0
    if (event.key === 'End') target = config.items.length - 1
    if (target === null || config.items.length === 0) return
    event.preventDefault()
    const next = ((target % config.items.length) + config.items.length) % config.items.length
    buttonRefs.current[next]?.focus()
  }

  return (
    <div
      {...hostProps}
      aria-label={config.label}
      className={className}
      data-openpencil-accordion=""
      role="region"
      style={{ ...hostStyle, background: config.backgroundColor, color: config.textColor, overflow: 'auto' }}
    >
      {config.items.map((item, index) => {
        const open = openIds.has(item.id)
        const headerId = instanceId + '-header-' + item.id
        const panelId = instanceId + '-panel-' + item.id
        return (
          <section
            key={item.id}
            style={{ borderBottom: config.showDividers ? '1px solid ' + config.accentColor + '44' : undefined }}
          >
            <h3 style={{ margin: 0 }}>
              <button
                aria-controls={panelId}
                aria-expanded={open}
                id={headerId}
                onClick={() => toggle(item.id)}
                onKeyDown={(event) => onHeaderKeyDown(event, index)}
                ref={(element) => { buttonRefs.current[index] = element }}
                style={{
                  alignItems: 'center',
                  background: 'transparent',
                  border: 0,
                  color: config.textColor,
                  cursor: 'pointer',
                  display: 'flex',
                  font: '600 ' + config.fontSize + 'px/1.4 system-ui, sans-serif',
                  gap: 12,
                  justifyContent: 'space-between',
                  padding: '12px 16px',
                  textAlign: 'start',
                  width: '100%'
                }}
                type="button"
              >
                <span>{item.title}</span>
                <span aria-hidden="true" style={{ color: config.accentColor }}>
                  {open ? '−' : '+'}
                </span>
              </button>
            </h3>
            <div
              aria-labelledby={headerId}
              hidden={!open}
              id={panelId}
              role="region"
              style={{ font: config.fontSize + 'px/1.6 system-ui, sans-serif', padding: '0 16px 16px' }}
            >
              {item.content}
            </div>
          </section>
        )
      })}
      {children}
    </div>
  )
}
`

export function buildOpenPencilAccordionComponent(): string {
  return ACCORDION_RUNTIME
}

export const ACCORDION_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: ACCORDION_PLUGIN_ID,
  moduleType: ACCORDION_MODULE_TYPE,
  componentName: 'OpenPencilAccordion',
  runtimePath: 'src/__openpencil_accordion.tsx',
  rootImportPath: './__openpencil_accordion',
  nestedImportPath: '../__openpencil_accordion',
  buildRuntime: buildOpenPencilAccordionComponent
})
