import { AUDIO_PLAYER_MODULE_TYPE, AUDIO_PLAYER_PLUGIN_ID } from '@open-pencil/core/plugins'

import { REACT_MODULE_POSITIONED_HOST_SOURCE } from './runtime-source'
import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

export function buildOpenPencilAudioPlayerComponent(options: ReactModuleRuntimeOptions): string {
  const stateImport = options.devMode ? ', useState' : ''
  const activationState = options.devMode
    ? `  const [authorizedSource, setAuthorizedSource] = useState('')
  const activeSource = authorizedSource === config.src ? config.src : ''

  useEffect(() => {
    setAuthorizedSource('')
  }, [config.src])`
    : `  const activeSource = config.src`
  const activationButton = options.devMode
    ? `
      {config.src && activeSource === '' ? (
        <button
          data-openpencil-audio-load=""
          onClick={() => setAuthorizedSource(config.src)}
          style={{ background: config.accentColor, border: 0, borderRadius: 6, color: config.backgroundColor, cursor: 'pointer', font: '600 12px system-ui, sans-serif', padding: '8px 12px' }}
          type="button"
        >
          Load audio preview
        </button>
      ) : null}`
    : ''

  return `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import { useEffect, useRef${stateImport}, type HTMLAttributes } from 'react'

export interface OpenPencilAudioPlayerConfig {
  src: string
  title: string
  artist: string
  controls: boolean
  autoplay: boolean
  loop: boolean
  muted: boolean
  preload: 'none' | 'metadata'
  volume: number
  playbackRate: number
  backgroundColor: string
  textColor: string
  accentColor: string
}

export interface OpenPencilAudioPlayerProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilAudioPlayerConfig
}

export default function OpenPencilAudioPlayer({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilAudioPlayerProps) {
  const audioRef = useRef<HTMLAudioElement | null>(null)
${activationState}
${REACT_MODULE_POSITIONED_HOST_SOURCE}

  useEffect(() => {
    const audio = audioRef.current
    if (!audio) return
    audio.volume = config.volume
    audio.playbackRate = config.playbackRate
  }, [config.playbackRate, config.volume])

  useEffect(() => {
    const audio = audioRef.current
    return () => {
      if (!audio) return
      audio.pause()
      audio.removeAttribute('src')
      audio.load()
    }
  }, [activeSource])

  return (
    <div
      {...hostProps}
      aria-label={config.title}
      className={className}
      data-openpencil-audio-player=""
      role="region"
      style={{ ...hostStyle, alignItems: 'center', background: config.backgroundColor, color: config.textColor, display: 'flex', gap: 14, overflow: 'hidden', padding: 12 }}
    >
      <div aria-hidden="true" style={{ alignItems: 'center', background: config.accentColor, borderRadius: 8, color: config.backgroundColor, display: 'flex', flex: '0 0 42px', font: '700 20px system-ui, sans-serif', height: 42, justifyContent: 'center' }}>♪</div>
      <div style={{ flex: '1 1 120px', minWidth: 0 }}>
        <strong style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{config.title}</strong>
        {config.artist ? <span style={{ display: 'block', font: '12px system-ui, sans-serif', opacity: 0.7 }}>{config.artist}</span> : null}
      </div>
      {activeSource ? (
        <audio
          autoPlay={config.autoplay}
          controls={config.controls}
          loop={config.loop}
          muted={config.muted}
          preload={config.preload}
          ref={audioRef}
          src={activeSource}
          style={{ accentColor: config.accentColor, maxWidth: '55%', minWidth: 180 }}
        />
      ) : (
        <span style={{ font: '12px system-ui, sans-serif', opacity: 0.72 }}>
          {config.src ? 'Preview requires confirmation.' : 'Choose an audio source.'}
        </span>
      )}${activationButton}
      {children}
    </div>
  )
}
`
}

export const AUDIO_PLAYER_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: AUDIO_PLAYER_PLUGIN_ID,
  moduleType: AUDIO_PLAYER_MODULE_TYPE,
  componentName: 'OpenPencilAudioPlayer',
  runtimePath: 'src/__openpencil_audio_player.tsx',
  rootImportPath: './__openpencil_audio_player',
  nestedImportPath: '../__openpencil_audio_player',
  buildRuntime: buildOpenPencilAudioPlayerComponent
})
