import { CAROUSEL_MODULE_TYPE, CAROUSEL_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

const CAROUSEL_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useCallback,
  useEffect,
  useState,
  type FocusEvent as ReactFocusEvent,
  type HTMLAttributes,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent
} from 'react'

export interface OpenPencilCarouselSlide {
  title: string
  description: string
  imageUrl: string
  alt: string
  href: string
}

export interface OpenPencilCarouselConfig {
  label: string
  slides: readonly OpenPencilCarouselSlide[]
  initialIndex: number
  transition: 'slide' | 'fade'
  autoplay: boolean
  intervalMs: number
  loop: boolean
  showArrows: boolean
  showDots: boolean
  pauseOnHover: boolean
  backgroundColor: string
  textColor: string
  accentColor: string
}

export interface OpenPencilCarouselProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilCarouselConfig
}

const REMOTE_MEDIA_ENABLED_BY_DEFAULT = __OPENPENCIL_REMOTE_MEDIA_ENABLED__

function clampIndex(index: number, length: number): number {
  return Math.min(Math.max(0, index), Math.max(0, length - 1))
}

export default function OpenPencilCarousel({
  config,
  children,
  className,
  onBlur,
  onFocus,
  onKeyDown,
  onPointerEnter,
  onPointerLeave,
  style,
  tabIndex,
  ...hostProps
}: OpenPencilCarouselProps) {
  const [activeIndex, setActiveIndex] = useState(() =>
    clampIndex(config.initialIndex, config.slides.length)
  )
  const [hovered, setHovered] = useState(false)
  const [focusWithin, setFocusWithin] = useState(false)
  const [userPaused, setUserPaused] = useState(false)
  const [pageHidden, setPageHidden] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const [announcement, setAnnouncement] = useState('')
  const [authorizedRemoteMediaUrls, setAuthorizedRemoteMediaUrls] = useState<ReadonlySet<string>>(
    () => new Set()
  )

  useEffect(() => {
    setActiveIndex(clampIndex(config.initialIndex, config.slides.length))
  }, [config.initialIndex, config.slides.length])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [])

  useEffect(() => {
    if (typeof document === 'undefined') return
    const sync = () => setPageHidden(document.hidden)
    sync()
    document.addEventListener('visibilitychange', sync)
    return () => document.removeEventListener('visibilitychange', sync)
  }, [])

  const selectSlide = useCallback(
    (requested: number, announce: boolean) => {
      setActiveIndex((current) => {
        let next = requested
        if (config.loop && config.slides.length > 0) {
          next = (requested + config.slides.length) % config.slides.length
        } else {
          next = clampIndex(requested, config.slides.length)
        }
        if (announce && next !== current) {
          const title = config.slides[next]?.title ?? ''
          setAnnouncement('Slide ' + (next + 1) + ' of ' + config.slides.length + ': ' + title)
        }
        return next
      })
    },
    [config.loop, config.slides]
  )

  const paused =
    userPaused ||
    pageHidden ||
    reducedMotion ||
    (config.pauseOnHover && hovered) ||
    focusWithin

  useEffect(() => {
    if (!config.autoplay || paused || config.slides.length < 2) return
    const timer = window.setInterval(() => {
      setActiveIndex((current) => {
        if (!config.loop && current >= config.slides.length - 1) return current
        return (current + 1) % config.slides.length
      })
    }, config.intervalMs)
    return () => window.clearInterval(timer)
  }, [config.autoplay, config.intervalMs, config.loop, config.slides.length, paused])

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    onKeyDown?.(event)
    if (event.defaultPrevented) return
    if (event.target !== event.currentTarget) return
    if (event.key === 'ArrowLeft') {
      event.preventDefault()
      selectSlide(activeIndex - 1, true)
    } else if (event.key === 'ArrowRight') {
      event.preventDefault()
      selectSlide(activeIndex + 1, true)
    } else if (event.key === 'Home') {
      event.preventDefault()
      selectSlide(0, true)
    } else if (event.key === 'End') {
      event.preventDefault()
      selectSlide(config.slides.length - 1, true)
    }
  }

  const handlePointerEnter = (event: ReactPointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event)
    if (!event.defaultPrevented) setHovered(true)
  }
  const handlePointerLeave = (event: ReactPointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event)
    if (!event.defaultPrevented) setHovered(false)
  }
  const handleFocus = (event: ReactFocusEvent<HTMLDivElement>) => {
    onFocus?.(event)
    if (!event.defaultPrevented) setFocusWithin(true)
  }
  const handleBlur = (event: ReactFocusEvent<HTMLDivElement>) => {
    onBlur?.(event)
    if (
      !event.defaultPrevented &&
      !(event.relatedTarget instanceof Node && event.currentTarget.contains(event.relatedTarget))
    ) {
      setFocusWithin(false)
    }
  }

  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle = {
    ...(positionedByClass || positionedByStyle ? style : { ...style, position: 'relative' as const }),
    background: config.backgroundColor,
    color: config.textColor,
    overflow: 'hidden'
  }
  const transition = reducedMotion
    ? 'none'
    : config.transition === 'fade'
      ? 'opacity 300ms ease'
      : 'transform 300ms ease, opacity 300ms ease'

  return (
    <div
      {...hostProps}
      aria-label={config.label}
      aria-roledescription="carousel"
      className={className}
      data-openpencil-carousel=""
      onBlur={handleBlur}
      onFocus={handleFocus}
      onKeyDown={handleKeyDown}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      role="region"
      style={hostStyle}
      tabIndex={tabIndex ?? 0}
    >
      <div data-openpencil-carousel-track="" style={{ height: '100%', position: 'relative' }}>
        {config.slides.map((slide, index) => {
          const active = index === activeIndex
          const remoteMediaEnabled =
            REMOTE_MEDIA_ENABLED_BY_DEFAULT || authorizedRemoteMediaUrls.has(slide.imageUrl)
          const media = slide.imageUrl ? (
            remoteMediaEnabled ? (
              <img
                alt={slide.alt}
                loading="lazy"
                src={slide.imageUrl}
                style={{ height: '100%', objectFit: 'cover', width: '100%' }}
              />
            ) : active ? (
              <button
                onClick={() =>
                  setAuthorizedRemoteMediaUrls((current) => {
                    const next = new Set(current)
                    next.add(slide.imageUrl)
                    return next
                  })
                }
                style={{ inset: 0, position: 'absolute' }}
                type="button"
              >
                Load remote slide media
              </button>
            ) : null
          ) : null
          const content = (
            <>
              {media ? (
                <div data-openpencil-carousel-media="" style={{ height: '58%', position: 'relative' }}>
                  {media}
                </div>
              ) : null}
              <div style={{ padding: 20 }}>
                <h2>
                  {slide.href ? (
                    <a
                      href={slide.href}
                      style={{ color: 'inherit' }}
                      tabIndex={active ? undefined : -1}
                    >
                      {slide.title}
                    </a>
                  ) : (
                    slide.title
                  )}
                </h2>
                {slide.description ? <p>{slide.description}</p> : null}
              </div>
            </>
          )
          return (
            <section
              aria-hidden={!active}
              aria-label={(index + 1) + ' of ' + config.slides.length + ': ' + slide.title}
              aria-roledescription="slide"
              data-active={active || undefined}
              data-openpencil-carousel-slide=""
              key={index}
              role="group"
              style={{
                inset: 0,
                opacity: active ? 1 : 0,
                pointerEvents: active ? 'auto' : 'none',
                position: 'absolute',
                transform:
                  config.transition === 'slide'
                    ? 'translateX(' + (index - activeIndex) * 100 + '%)'
                    : undefined,
                transition
              }}
            >
              {content}
            </section>
          )
        })}
      </div>

      {config.showArrows && config.slides.length > 1 ? (
        <div data-openpencil-carousel-arrows="">
          <button
            aria-label="Previous slide"
            disabled={!config.loop && activeIndex === 0}
            onClick={() => selectSlide(activeIndex - 1, true)}
            type="button"
          >
            Previous
          </button>
          <button
            aria-label="Next slide"
            disabled={!config.loop && activeIndex === config.slides.length - 1}
            onClick={() => selectSlide(activeIndex + 1, true)}
            type="button"
          >
            Next
          </button>
        </div>
      ) : null}

      {config.showDots && config.slides.length > 1 ? (
        <div aria-label="Choose slide" data-openpencil-carousel-dots="" role="group">
          {config.slides.map((slide, index) => (
            <button
              aria-current={index === activeIndex ? 'true' : undefined}
              aria-label={'Show slide ' + (index + 1) + ': ' + slide.title}
              key={index}
              onClick={() => selectSlide(index, true)}
              style={{ color: index === activeIndex ? config.accentColor : undefined }}
              type="button"
            >
              {index + 1}
            </button>
          ))}
        </div>
      ) : null}

      {config.autoplay && config.slides.length > 1 ? (
        <button
          aria-label={userPaused ? 'Resume carousel' : 'Pause carousel'}
          data-openpencil-carousel-autoplay=""
          onClick={() => setUserPaused((value) => !value)}
          type="button"
        >
          {userPaused ? 'Play' : 'Pause'}
        </button>
      ) : null}
      <span
        aria-live="polite"
        style={{ height: 1, overflow: 'hidden', position: 'absolute', width: 1 }}
      >
        {announcement}
      </span>
      {children}
    </div>
  )
}
`

export function buildOpenPencilCarouselComponent(options: ReactModuleRuntimeOptions): string {
  return CAROUSEL_RUNTIME.replace(
    '__OPENPENCIL_REMOTE_MEDIA_ENABLED__',
    options.devMode ? 'false' : 'true'
  )
}

export const CAROUSEL_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: CAROUSEL_PLUGIN_ID,
  moduleType: CAROUSEL_MODULE_TYPE,
  componentName: 'OpenPencilCarousel',
  runtimePath: 'src/__openpencil_carousel.tsx',
  rootImportPath: './__openpencil_carousel',
  nestedImportPath: '../__openpencil_carousel',
  buildRuntime: buildOpenPencilCarouselComponent
})
