/* eslint-disable max-lines -- the generated accessible runtime stays beside its adapter contract */
import { DROPDOWN_MENU_MODULE_TYPE, DROPDOWN_MENU_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter } from './types'

const DROPDOWN_MENU_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent
} from 'react'
import { createPortal } from 'react-dom'

export type OpenPencilDropdownPlacement =
  | 'bottomLeft' | 'bottom' | 'bottomRight'
  | 'topLeft' | 'top' | 'topRight'
  | 'leftTop' | 'left' | 'leftBottom'
  | 'rightTop' | 'right' | 'rightBottom'

export type OpenPencilDropdownEntry =
  | {
      type: 'item'
      label: string
      href: string
      disabled: boolean
      danger: boolean
      shortcut: string
    }
  | { type: 'separator' }

export interface OpenPencilDropdownMenuConfig {
  triggerLabel: string
  showTriggerLabel: boolean
  showTriggerChevron: boolean
  triggerMode: 'click' | 'hover'
  placement: OpenPencilDropdownPlacement
  closeOnSelect: boolean
  closeOnEscape: boolean
  closeOnOutsidePress: boolean
  menuWidth: number
  triggerBackground: string
  triggerTextColor: string
  menuBackground: string
  itemTextColor: string
  accentColor: string
  dangerColor: string
  items: readonly OpenPencilDropdownEntry[]
}

export interface OpenPencilDropdownMenuProps
  extends Omit<
    ButtonHTMLAttributes<HTMLButtonElement>,
    'onClick' | 'onKeyDown' | 'onMouseEnter' | 'onMouseLeave' | 'type'
  > {
  config: OpenPencilDropdownMenuConfig
  onClick?: (event: ReactMouseEvent<HTMLButtonElement>) => void
  onKeyDown?: (event: ReactKeyboardEvent<HTMLButtonElement>) => void
  onMouseEnter?: (event: ReactMouseEvent<HTMLButtonElement>) => void
  onMouseLeave?: (event: ReactMouseEvent<HTMLButtonElement>) => void
}

const VIEWPORT_INSET = 8
const PLACEMENT_GAP = 8
const TRANSITION_MS = 140
const HOVER_CLOSE_MS = 140
const DOCUMENT_TAB_STOP_SELECTOR = [
  'a[href]',
  'area[href]',
  'button',
  'input:not([type="hidden"])',
  'select',
  'textarea',
  'iframe',
  'object',
  'embed',
  '[contenteditable]:not([contenteditable="false"])',
  '[tabindex]'
].join(',')
const TRIGGER_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  border: 0,
  borderRadius: 8,
  boxSizing: 'border-box',
  cursor: 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: '0 12px',
  textAlign: 'center',
  touchAction: 'manipulation'
}
const AUTHORED_CONTENT_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'inline-flex',
  justifyContent: 'center',
  maxWidth: '100%',
  minWidth: 0,
  pointerEvents: 'none'
}
const AUTHORED_BUTTON_STYLE: CSSProperties = {
  appearance: 'none',
  background: 'transparent',
  border: 0,
  color: 'inherit',
  cursor: 'pointer',
  inset: 0,
  outlineOffset: 2,
  padding: 0,
  position: 'absolute',
  touchAction: 'manipulation',
  zIndex: 1
}
const LABEL_STYLE: CSSProperties = {
  color: 'inherit',
  lineHeight: 1.2,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
}
const CHEVRON_STYLE: CSSProperties = {
  display: 'inline-flex',
  flexShrink: 0,
  height: 16,
  width: 16
}
const ITEM_BASE_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  background: 'transparent',
  border: 0,
  borderRadius: 7,
  boxSizing: 'border-box',
  display: 'flex',
  font: 'inherit',
  gap: 16,
  justifyContent: 'space-between',
  minHeight: 44,
  outlineOffset: -2,
  padding: '9px 12px',
  textAlign: 'left',
  textDecoration: 'none',
  width: '100%'
}

interface OpenDropdownEntry {
  token: symbol
  menu: HTMLElement
  trigger: HTMLButtonElement
  restoreFocus: HTMLElement | null
}

const openDropdowns: OpenDropdownEntry[] = []

function addOpenDropdown(entry: OpenDropdownEntry): void {
  const previous = openDropdowns.findIndex((candidate) => candidate.token === entry.token)
  if (previous >= 0) openDropdowns.splice(previous, 1)
  openDropdowns.push(entry)
}

function removeOpenDropdown(token: symbol): { wasTop: boolean; next?: OpenDropdownEntry } {
  const index = openDropdowns.findIndex((entry) => entry.token === token)
  const wasTop = index >= 0 && index === openDropdowns.length - 1
  if (index >= 0) openDropdowns.splice(index, 1)
  return { wasTop, next: openDropdowns[openDropdowns.length - 1] }
}

function isTopDropdown(token: symbol): boolean {
  return openDropdowns[openDropdowns.length - 1]?.token === token
}

function runtimeSafeHref(value: string): string | undefined {
  if (!value || value.includes('\\\\') || /[\\u0000-\\u001F\\u007F]/.test(value)) return undefined
  if (value.startsWith('/') && !value.startsWith('//')) return value
  if (value.startsWith('#') && value.length > 1) return value
  try {
    const url = new URL(value)
    const hostname = url.hostname.toLowerCase()
    const localHostname =
      hostname.endsWith('.') ||
      ['localhost', 'localdomain', 'home.arpa'].includes(hostname) ||
      ['.localhost', '.local', '.localdomain', '.home.arpa'].some((suffix) =>
        hostname.endsWith(suffix)
      )
    const ipv4 = /^(?:\\d{1,3}\\.){3}\\d{1,3}$/.test(hostname)
    const ipv6 = hostname.startsWith('[') && hostname.endsWith(']')
    if (
      url.protocol === 'https:' &&
      url.username === '' &&
      url.password === '' &&
      url.hash === '' &&
      (url.port === '' || url.port === '443') &&
      !localHostname &&
      !ipv4 &&
      !ipv6 &&
      url.href === value
    ) return value
  } catch {
    // Invalid absolute URLs are not navigable menu targets.
  }
  return undefined
}

function hasHiddenOrInertAncestor(element: HTMLElement): boolean {
  let current: HTMLElement | null = element
  while (current) {
    if (
      current.hidden ||
      current.hasAttribute('inert') ||
      current.getAttribute('aria-hidden') === 'true'
    ) return true
    const style = window.getComputedStyle(current)
    if (style.display === 'none' || style.visibility === 'hidden' || style.visibility === 'collapse') {
      return true
    }
    current = current.parentElement
  }
  return false
}

function isDocumentTabStop(element: HTMLElement): boolean {
  return (
    element.isConnected &&
    element.tabIndex >= 0 &&
    !element.matches(':disabled') &&
    !hasHiddenOrInertAncestor(element) &&
    element.getClientRects().length > 0
  )
}

function adjacentDocumentTabStop(
  trigger: HTMLButtonElement,
  backwards: boolean
): HTMLElement | undefined {
  const elements = Array.from(
    document.querySelectorAll<HTMLElement>(DOCUMENT_TAB_STOP_SELECTOR)
  ).filter((element) => {
    if (element === trigger) return true
    if (element.closest('[data-openpencil-dropdown-menu]')) return false
    return isDocumentTabStop(element)
  })
  if (!elements.includes(trigger)) elements.push(trigger)
  const ordered = elements
    .map((element, order) => ({
      element,
      order,
      tabIndex: element === trigger && element.tabIndex < 0 ? 0 : element.tabIndex
    }))
    .sort((left, right) => {
      const leftPositive = left.tabIndex > 0
      const rightPositive = right.tabIndex > 0
      if (leftPositive !== rightPositive) return leftPositive ? -1 : 1
      if (leftPositive && left.tabIndex !== right.tabIndex) return left.tabIndex - right.tabIndex
      return left.order - right.order
    })
  const triggerIndex = ordered.findIndex(({ element }) => element === trigger)
  if (triggerIndex < 0) return undefined
  return ordered[triggerIndex + (backwards ? -1 : 1)]?.element
}

function enabledIndexes(items: readonly OpenPencilDropdownEntry[]): number[] {
  const result: number[] = []
  for (let index = 0; index < items.length; index += 1) {
    const item = items[index]
    if (item.type === 'item' && !item.disabled) result.push(index)
  }
  return result
}

function clamped(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(value, maximum))
}

function idealPosition(
  placement: OpenPencilDropdownPlacement,
  trigger: DOMRect,
  menu: { width: number; height: number }
): { left: number; top: number } {
  const centeredX = trigger.left + (trigger.width - menu.width) / 2
  const centeredY = trigger.top + (trigger.height - menu.height) / 2
  if (placement === 'bottomLeft') return { left: trigger.left, top: trigger.bottom + PLACEMENT_GAP }
  if (placement === 'bottom') return { left: centeredX, top: trigger.bottom + PLACEMENT_GAP }
  if (placement === 'bottomRight') return { left: trigger.right - menu.width, top: trigger.bottom + PLACEMENT_GAP }
  if (placement === 'topLeft') return { left: trigger.left, top: trigger.top - menu.height - PLACEMENT_GAP }
  if (placement === 'top') return { left: centeredX, top: trigger.top - menu.height - PLACEMENT_GAP }
  if (placement === 'topRight') return { left: trigger.right - menu.width, top: trigger.top - menu.height - PLACEMENT_GAP }
  if (placement === 'leftTop') return { left: trigger.left - menu.width - PLACEMENT_GAP, top: trigger.top }
  if (placement === 'left') return { left: trigger.left - menu.width - PLACEMENT_GAP, top: centeredY }
  if (placement === 'leftBottom') return { left: trigger.left - menu.width - PLACEMENT_GAP, top: trigger.bottom - menu.height }
  if (placement === 'rightTop') return { left: trigger.right + PLACEMENT_GAP, top: trigger.top }
  if (placement === 'right') return { left: trigger.right + PLACEMENT_GAP, top: centeredY }
  return { left: trigger.right + PLACEMENT_GAP, top: trigger.bottom - menu.height }
}

export default function OpenPencilDropdownMenu({
  config,
  className,
  children,
  onClick,
  onKeyDown,
  onMouseEnter,
  onMouseLeave,
  style,
  tabIndex,
  ...hostProps
}: OpenPencilDropdownMenuProps) {
  const triggerRef = useRef<HTMLButtonElement>(null)
  const menuRef = useRef<HTMLDivElement>(null)
  const tokenRef = useRef(Symbol('open-pencil-dropdown-menu'))
  const closeTimerRef = useRef<number | null>(null)
  const hoverTimerRef = useRef<number | null>(null)
  const openFrameRef = useRef<number | null>(null)
  const tabFocusFrameRef = useRef<number | null>(null)
  const desiredFocusRef = useRef<'first' | 'last' | 'none'>('first')
  const restoreFocusRef = useRef(true)
  const [mounted, setMounted] = useState(false)
  const [visible, setVisible] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const [activeIndex, setActiveIndex] = useState(-1)
  const [position, setPosition] = useState({ left: -10000, top: -10000 })
  const baseId = useId().replaceAll(':', '')
  const menuId = baseId + '-menu'

  const clearTimers = useCallback(() => {
    if (closeTimerRef.current !== null) window.clearTimeout(closeTimerRef.current)
    if (hoverTimerRef.current !== null) window.clearTimeout(hoverTimerRef.current)
    if (openFrameRef.current !== null) window.cancelAnimationFrame(openFrameRef.current)
    if (tabFocusFrameRef.current !== null) window.cancelAnimationFrame(tabFocusFrameRef.current)
    closeTimerRef.current = null
    hoverTimerRef.current = null
    openFrameRef.current = null
    tabFocusFrameRef.current = null
  }, [])

  const focusItem = useCallback((index: number) => {
    const menu = menuRef.current
    if (!menu) return
    setActiveIndex(index)
    window.requestAnimationFrame(() => {
      menu.querySelector<HTMLElement>('[data-openpencil-dropdown-item-index="' + index + '"]')
        ?.focus({ preventScroll: true })
    })
  }, [])

  const openMenu = useCallback((focus: 'first' | 'last' | 'none' = 'first') => {
    clearTimers()
    restoreFocusRef.current = true
    desiredFocusRef.current = focus
    if (focus === 'none') setActiveIndex(-1)
    if (!mounted) {
      setMounted(true)
      return
    }
    setVisible(true)
    if (focus === 'none') return
    const indexes = enabledIndexes(config.items)
    const initial = focus === 'last' ? indexes.at(-1) : indexes[0]
    if (initial !== undefined) focusItem(initial)
    else menuRef.current?.focus({ preventScroll: true })
  }, [clearTimers, config.items, focusItem, mounted])

  const closeMenu = useCallback((restoreFocus = true) => {
    clearTimers()
    restoreFocusRef.current = restoreFocus
    setVisible(false)
    if (reducedMotion) {
      setMounted(false)
      return
    }
    closeTimerRef.current = window.setTimeout(() => {
      closeTimerRef.current = null
      setMounted(false)
    }, TRANSITION_MS)
  }, [clearTimers, reducedMotion])

  const closeMenuForTab = useCallback((backwards: boolean) => {
    const trigger = triggerRef.current
    clearTimers()
    restoreFocusRef.current = false
    setVisible(false)
    setMounted(false)
    tabFocusFrameRef.current = window.requestAnimationFrame(() => {
      tabFocusFrameRef.current = null
      if (!trigger?.isConnected) return
      const target = adjacentDocumentTabStop(trigger, backwards)
      if (target && isDocumentTabStop(target)) target.focus({ preventScroll: true })
      else trigger.focus({ preventScroll: true })
    })
  }, [clearTimers])

  const scheduleHoverClose = useCallback(() => {
    if (config.triggerMode !== 'hover' || desiredFocusRef.current !== 'none') return
    if (hoverTimerRef.current !== null) window.clearTimeout(hoverTimerRef.current)
    hoverTimerRef.current = window.setTimeout(() => {
      hoverTimerRef.current = null
      if (desiredFocusRef.current === 'none' && isTopDropdown(tokenRef.current)) {
        closeMenu(false)
      }
    }, HOVER_CLOSE_MS)
  }, [closeMenu, config.triggerMode])

  const cancelHoverClose = useCallback(() => {
    if (hoverTimerRef.current !== null) window.clearTimeout(hoverTimerRef.current)
    hoverTimerRef.current = null
  }, [])

  const reposition = useCallback(() => {
    const trigger = triggerRef.current
    const menu = menuRef.current
    if (!trigger || !menu) return
    const triggerRect = trigger.getBoundingClientRect()
    const menuSize = { width: menu.offsetWidth, height: menu.offsetHeight }
    const ideal = idealPosition(config.placement, triggerRect, menuSize)
    setPosition({
      left: clamped(ideal.left, VIEWPORT_INSET, Math.max(VIEWPORT_INSET, window.innerWidth - menuSize.width - VIEWPORT_INSET)),
      top: clamped(ideal.top, VIEWPORT_INSET, Math.max(VIEWPORT_INSET, window.innerHeight - menuSize.height - VIEWPORT_INSET))
    })
  }, [config.placement])

  useEffect(() => {
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [])

  useEffect(() => {
    if (!mounted) return
    const trigger = triggerRef.current
    const menu = menuRef.current
    if (!trigger || !menu) return
    const entry: OpenDropdownEntry = {
      token: tokenRef.current,
      menu,
      trigger,
      restoreFocus: document.activeElement instanceof HTMLElement ? document.activeElement : null
    }
    addOpenDropdown(entry)
    const desiredFocus = desiredFocusRef.current
    const indexes = enabledIndexes(config.items)
    const initial = desiredFocus === 'last' ? indexes.at(-1) : indexes[0]
    reposition()
    openFrameRef.current = window.requestAnimationFrame(() => {
      openFrameRef.current = null
      reposition()
      setVisible(true)
      if (desiredFocus === 'none') return
      if (initial !== undefined) focusItem(initial)
      else menu.focus({ preventScroll: true })
    })
    const refreshPosition = () => reposition()
    window.addEventListener('resize', refreshPosition)
    window.addEventListener('scroll', refreshPosition, true)
    return () => {
      window.removeEventListener('resize', refreshPosition)
      window.removeEventListener('scroll', refreshPosition, true)
      const { wasTop, next } = removeOpenDropdown(entry.token)
      if (!wasTop || !restoreFocusRef.current) return
      if (next?.menu.isConnected) next.menu.focus({ preventScroll: true })
      else if (entry.restoreFocus?.isConnected) entry.restoreFocus.focus({ preventScroll: true })
      else if (trigger.isConnected) trigger.focus({ preventScroll: true })
    }
  }, [config.items, focusItem, mounted, reposition])

  useEffect(() => {
    if (!mounted) return
    const onPointerDown = (event: PointerEvent) => {
      if (!config.closeOnOutsidePress || !isTopDropdown(tokenRef.current)) return
      const target = event.target
      if (!(target instanceof Node)) return
      if (menuRef.current?.contains(target) || triggerRef.current?.contains(target)) return
      closeMenu(false)
    }
    const onDocumentKeyDown = (event: KeyboardEvent) => {
      if (
        event.key !== 'Escape' ||
        event.defaultPrevented ||
        !config.closeOnEscape ||
        !isTopDropdown(tokenRef.current)
      ) return
      event.preventDefault()
      closeMenu()
    }
    document.addEventListener('pointerdown', onPointerDown, true)
    document.addEventListener('keydown', onDocumentKeyDown)
    return () => {
      document.removeEventListener('pointerdown', onPointerDown, true)
      document.removeEventListener('keydown', onDocumentKeyDown)
    }
  }, [closeMenu, config.closeOnEscape, config.closeOnOutsidePress, mounted])

  useEffect(() => clearTimers, [clearTimers])

  const handleTriggerClick = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onClick?.(event)
    if (event.defaultPrevented) return
    if (mounted && visible) closeMenu()
    else openMenu('first')
  }

  const handleTriggerKeyDown = (event: ReactKeyboardEvent<HTMLButtonElement>) => {
    onKeyDown?.(event)
    if (event.defaultPrevented) return
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      openMenu(event.key === 'ArrowUp' ? 'last' : 'first')
    }
  }

  const handleTriggerMouseEnter = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onMouseEnter?.(event)
    cancelHoverClose()
    if (!event.defaultPrevented && config.triggerMode === 'hover') openMenu('none')
  }

  const handleTriggerMouseLeave = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onMouseLeave?.(event)
    scheduleHoverClose()
  }

  const handleMenuKeyDown = (event: ReactKeyboardEvent<HTMLDivElement>) => {
    if (!isTopDropdown(tokenRef.current)) return
    const indexes = enabledIndexes(config.items)
    if (event.key === 'Escape') {
      if (!config.closeOnEscape) return
      event.preventDefault()
      closeMenu()
      return
    }
    if (event.key === 'Tab') {
      event.preventDefault()
      closeMenuForTab(event.shiftKey)
      return
    }
    if (indexes.length === 0) return
    const current = indexes.indexOf(activeIndex)
    let next: number | undefined
    if (event.key === 'ArrowDown') next = indexes[(current + 1 + indexes.length) % indexes.length]
    else if (event.key === 'ArrowUp') next = indexes[(current - 1 + indexes.length) % indexes.length]
    else if (event.key === 'Home') next = indexes[0]
    else if (event.key === 'End') next = indexes[indexes.length - 1]
    else if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      menuRef.current
        ?.querySelector<HTMLElement>('[data-openpencil-dropdown-item-index="' + activeIndex + '"]')
        ?.click()
      return
    } else return
    event.preventDefault()
    if (next !== undefined) focusItem(next)
  }

  const hasAuthoredTrigger = children !== undefined && children !== null
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle = positionedByClass || positionedByStyle ? style : { ...style, position: 'relative' as const }
  const triggerStyle: CSSProperties = {
    ...hostStyle,
    ...TRIGGER_STYLE,
    background: config.triggerBackground,
    color: config.triggerTextColor,
    gap: !hasAuthoredTrigger && config.showTriggerLabel && config.showTriggerChevron ? 8 : 0
  }
  const accessibleLabel = config.triggerLabel || 'Open menu'
  const sharedTriggerProps = {
    ...hostProps,
    'aria-controls': menuId,
    'aria-expanded': mounted && visible,
    'aria-haspopup': 'menu' as const,
    'aria-label': accessibleLabel,
    'data-openpencil-dropdown-owner': menuId,
    'data-openpencil-dropdown-trigger': '',
    onClick: handleTriggerClick,
    onKeyDown: handleTriggerKeyDown,
    onMouseEnter: handleTriggerMouseEnter,
    onMouseLeave: handleTriggerMouseLeave,
    ref: triggerRef,
    tabIndex: tabIndex ?? 0,
    type: 'button' as const
  }
  const ownerSelector = '[data-openpencil-dropdown-owner="' + menuId + '"]'
  const focusCss =
    ownerSelector + '[data-openpencil-dropdown-trigger]:focus-visible{' +
    'outline:2px solid ' + config.accentColor + '}' +
    ownerSelector + '[data-openpencil-dropdown-item]:focus-visible{' +
    'background:' + config.accentColor + '1F;outline:2px solid ' + config.accentColor + '}' +
    ownerSelector + '[data-openpencil-dropdown-item]:not([aria-disabled="true"]):hover{' +
    'background:' + config.accentColor + '1F}'

  const portal = mounted
    ? createPortal(
        <>
          <style>{focusCss}</style>
          <div
            aria-label={accessibleLabel}
            data-openpencil-dropdown-menu=""
            data-placement={config.placement}
            data-state={visible ? 'open' : 'closed'}
            id={menuId}
            onKeyDown={handleMenuKeyDown}
            onMouseEnter={cancelHoverClose}
            onMouseLeave={scheduleHoverClose}
            ref={menuRef}
            role="menu"
            style={{
              background: config.menuBackground,
              border: '1px solid #0000001A',
              borderRadius: 10,
              boxShadow: '0 16px 40px #0000002E',
              boxSizing: 'border-box',
              color: config.itemTextColor,
              left: position.left,
              maxHeight: 'calc(100vh - 16px)',
              opacity: visible ? 1 : 0,
              overflowX: 'hidden',
              overflowY: 'auto',
              padding: 6,
              pointerEvents: visible ? 'auto' : 'none',
              position: 'fixed',
              top: position.top,
              transform: visible ? 'scale(1)' : 'scale(0.98)',
              transformOrigin: 'center',
              transition: reducedMotion
                ? 'none'
                : 'opacity ' + TRANSITION_MS + 'ms ease, transform ' + TRANSITION_MS + 'ms ease',
              width: 'min(' + config.menuWidth + 'px, calc(100vw - 16px))',
              zIndex: 2147483647
            }}
            tabIndex={-1}
          >
            {config.items.map((entry, index) => {
              if (entry.type === 'separator') {
                return (
                  <div
                    data-openpencil-dropdown-separator=""
                    key={'separator-' + index}
                    role="separator"
                    style={{ background: '#0000001F', height: 1, margin: '5px 8px' }}
                  />
                )
              }
              const href = runtimeSafeHref(entry.href)
              const itemStyle: CSSProperties = {
                ...ITEM_BASE_STYLE,
                color: entry.disabled
                  ? config.itemTextColor + '66'
                  : entry.danger
                    ? config.dangerColor
                    : config.itemTextColor,
                cursor: entry.disabled ? 'not-allowed' : 'pointer'
              }
              const itemProps = {
                'aria-disabled': entry.disabled || undefined,
                'data-danger': !entry.disabled && entry.danger ? 'true' : undefined,
                'data-openpencil-dropdown-item': '',
                'data-openpencil-dropdown-item-index': index,
                'data-openpencil-dropdown-owner': menuId,
                onClick: (event: ReactMouseEvent<HTMLElement>) => {
                  if (entry.disabled) {
                    event.preventDefault()
                    return
                  }
                  if (config.closeOnSelect) closeMenu(!href)
                },
                onFocus: () => {
                  desiredFocusRef.current = 'first'
                  setActiveIndex(index)
                },
                role: 'menuitem' as const,
                style: itemStyle,
                tabIndex: !entry.disabled && index === activeIndex ? 0 : -1
              }
              const content = (
                <>
                  <span style={{ minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {entry.label}
                  </span>
                  {entry.shortcut ? (
                    <span aria-hidden="true" data-openpencil-dropdown-shortcut="" style={{ flexShrink: 0, fontSize: '0.85em', opacity: 0.65 }}>
                      {entry.shortcut}
                    </span>
                  ) : null}
                </>
              )
              return href && !entry.disabled ? (
                <a {...itemProps} href={href} key={'item-' + index}>{content}</a>
              ) : (
                <button {...itemProps} disabled={entry.disabled} key={'item-' + index} type="button">{content}</button>
              )
            })}
          </div>
        </>,
        document.body
      )
    : null

  return (
    <>
      {hasAuthoredTrigger ? (
        <div className={className} data-openpencil-dropdown-trigger-host="" style={triggerStyle}>
          <div aria-hidden="true" data-openpencil-dropdown-trigger-authored="" inert style={AUTHORED_CONTENT_STYLE}>
            {children}
          </div>
          <button {...sharedTriggerProps} style={AUTHORED_BUTTON_STYLE} />
        </div>
      ) : (
        <button {...sharedTriggerProps} className={className} style={triggerStyle}>
          {config.showTriggerLabel ? (
            <span data-openpencil-dropdown-trigger-label="" style={LABEL_STYLE}>{config.triggerLabel}</span>
          ) : null}
          {config.showTriggerChevron ? (
            <svg aria-hidden="true" data-openpencil-dropdown-trigger-chevron="" focusable="false" style={CHEVRON_STYLE} viewBox="0 0 24 24">
              <path d="M6 9L12 15L18 9" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" />
            </svg>
          ) : null}
        </button>
      )}
      {portal}
    </>
  )
}
`

export function buildOpenPencilDropdownMenuComponent(): string {
  return DROPDOWN_MENU_RUNTIME
}

export const DROPDOWN_MENU_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: DROPDOWN_MENU_PLUGIN_ID,
  moduleType: DROPDOWN_MENU_MODULE_TYPE,
  componentName: 'OpenPencilDropdownMenu',
  runtimePath: 'src/__openpencil_dropdown_menu.tsx',
  rootImportPath: './__openpencil_dropdown_menu',
  nestedImportPath: '../__openpencil_dropdown_menu',
  buildRuntime: buildOpenPencilDropdownMenuComponent
})
