import {
  HTML_MODULE_SANDBOX_CSP,
  HTML_MODULE_TYPE,
  HTML_PLUGIN_ID
} from '@open-pencil/core/plugins'

import type { ReactModuleAdapter } from './types'

export function buildOpenPencilHTMLComponent(): string {
  const sandboxCsp = JSON.stringify(HTML_MODULE_SANDBOX_CSP)
  return `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import type { HTMLAttributes } from 'react'

export interface OpenPencilHtmlConfig {
  html: string
}

export interface OpenPencilHtmlProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilHtmlConfig
}

// This policy is copied from the compiler's trusted HTML-module contract. The generated
// runtime stays dependency-free while preserving the exact security boundary.
export const OPENPENCIL_HTML_SANDBOX_CSP = ${sandboxCsp}

function escapeAttribute(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;')
}

function buildSandboxDocument(html: string): string {
  const policy = escapeAttribute(OPENPENCIL_HTML_SANDBOX_CSP)
  return '<!doctype html><meta http-equiv="Content-Security-Policy" content="' + policy + '">' + html
}

export default function OpenPencilHtml({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilHtmlProps) {
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle =
    positionedByClass || positionedByStyle
      ? style
      : { ...style, position: 'relative' as const }

  return (
    <div {...hostProps} className={className} data-openpencil-html-preview="" style={hostStyle}>
      <iframe
        aria-label="HTML preview"
        referrerPolicy="no-referrer"
        sandbox=""
        srcDoc={buildSandboxDocument(config.html)}
        style={{
          border: 0,
          height: '100%',
          inset: 0,
          pointerEvents: 'none',
          position: 'absolute',
          width: '100%'
        }}
        tabIndex={-1}
        title="HTML preview"
      />
      {children}
    </div>
  )
}
`
}

export const HTML_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: HTML_PLUGIN_ID,
  moduleType: HTML_MODULE_TYPE,
  componentName: 'OpenPencilHtml',
  runtimePath: 'src/__openpencil_html.tsx',
  rootImportPath: './__openpencil_html',
  nestedImportPath: '../__openpencil_html',
  buildRuntime: buildOpenPencilHTMLComponent
})
