import { MARKDOWN_MODULE_TYPE, MARKDOWN_PLUGIN_ID } from '@open-pencil/core/plugins'

import { REACT_MODULE_POSITIONED_HOST_SOURCE } from './runtime-source'
import type { ReactModuleAdapter } from './types'

export const REACT_MARKDOWN_VERSION = '10.1.0'
export const REMARK_GFM_VERSION = '4.0.1'

const MARKDOWN_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import type { HTMLAttributes, ReactNode } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

export interface OpenPencilMarkdownConfig {
  source: string
  flavor: 'commonmark' | 'gfm'
  linkTarget: 'same-tab' | 'new-tab'
  backgroundColor: string
  textColor: string
  headingColor: string
  accentColor: string
  fontSize: number
  lineHeight: number
}

export interface OpenPencilMarkdownProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilMarkdownConfig
}

function safeHref(value: string): string {
  if (value === '' || value.trim() !== value || /[\\u0000-\\u001F\\u007F\\\\]/.test(value)) return ''
  if (value.startsWith('#')) return /^#[A-Za-z0-9._:-]*$/.test(value) ? value : ''
  if (value.startsWith('/')) {
    if (value.startsWith('//')) return ''
    try {
      const decoded = decodeURIComponent(value).toLowerCase()
      if (decoded.split('/').some((part) => part === '.' || part === '..')) return ''
    } catch {
      return ''
    }
    return value
  }
  let parsed: URL
  try {
    parsed = new URL(value)
  } catch {
    return ''
  }
  const hostname = parsed.hostname.toLowerCase()
  const local =
    hostname === 'localhost' || hostname.endsWith('.localhost') || hostname.endsWith('.local')
  const ipLiteral = /^(?:\\d{1,3}\\.){3}\\d{1,3}$/.test(hostname) || hostname.includes(':')
  return parsed.protocol === 'https:' && parsed.username === '' && parsed.password === '' &&
    (parsed.port === '' || parsed.port === '443') && !local && !ipLiteral && parsed.href === value
    ? value
    : ''
}

function SafeLink({
  accentColor,
  children,
  href,
  target
}: {
  accentColor: string
  children: ReactNode
  href?: string
  target: 'same-tab' | 'new-tab'
}) {
  const safe = safeHref(href ?? '')
  if (!safe) return <span>{children}</span>
  const newTab = target === 'new-tab'
  return (
    <a
      href={safe}
      rel={newTab ? 'nofollow noopener noreferrer' : undefined}
      style={{ color: accentColor, textDecoration: 'underline' }}
      target={newTab ? '_blank' : undefined}
    >
      {children}
    </a>
  )
}

function InertImage({ alt }: { alt?: string }) {
  const label = alt?.trim() || 'Markdown image'
  return (
    <span aria-label={label} data-openpencil-markdown-image="" role="img">
      {'[' + label + ']'}
    </span>
  )
}

export default function OpenPencilMarkdown({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilMarkdownProps) {
${REACT_MODULE_POSITIONED_HOST_SOURCE}
  const headingStyle = { color: config.headingColor, lineHeight: 1.25 }

  return (
    <div
      {...hostProps}
      className={className}
      data-openpencil-markdown=""
      style={{
        ...hostStyle,
        background: config.backgroundColor,
        color: config.textColor,
        font: config.fontSize + 'px/' + config.lineHeight + ' system-ui, sans-serif',
        overflow: 'auto',
        padding: 16
      }}
    >
      <ReactMarkdown
        components={{
          a: ({ children: linkChildren, href }) => (
            <SafeLink accentColor={config.accentColor} href={href} target={config.linkTarget}>
              {linkChildren}
            </SafeLink>
          ),
          blockquote: ({ children: quoteChildren }) => (
            <blockquote style={{ borderInlineStart: '3px solid ' + config.accentColor, marginInline: 0, paddingInlineStart: 12 }}>
              {quoteChildren}
            </blockquote>
          ),
          code: ({ children: codeChildren }) => (
            <code style={{ background: config.accentColor + '16', borderRadius: 4, padding: '0.1em 0.3em' }}>
              {codeChildren}
            </code>
          ),
          h1: ({ children: heading }) => <h1 style={headingStyle}>{heading}</h1>,
          h2: ({ children: heading }) => <h2 style={headingStyle}>{heading}</h2>,
          h3: ({ children: heading }) => <h3 style={headingStyle}>{heading}</h3>,
          img: ({ alt }) => <InertImage alt={alt} />,
          table: ({ children: tableChildren }) => (
            <div style={{ overflowX: 'auto' }}><table style={{ borderCollapse: 'collapse', width: '100%' }}>{tableChildren}</table></div>
          ),
          td: ({ children: cell }) => <td style={{ border: '1px solid ' + config.accentColor + '44', padding: 6 }}>{cell}</td>,
          th: ({ children: cell }) => <th scope="col" style={{ border: '1px solid ' + config.accentColor + '66', padding: 6, textAlign: 'start' }}>{cell}</th>
        }}
        remarkPlugins={config.flavor === 'gfm' ? [remarkGfm] : []}
        skipHtml
        urlTransform={safeHref}
      >
        {config.source}
      </ReactMarkdown>
      {children}
    </div>
  )
}
`

export function buildOpenPencilMarkdownComponent(): string {
  return MARKDOWN_RUNTIME
}

export const MARKDOWN_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: MARKDOWN_PLUGIN_ID,
  moduleType: MARKDOWN_MODULE_TYPE,
  componentName: 'OpenPencilMarkdown',
  runtimePath: 'src/__openpencil_markdown.tsx',
  rootImportPath: './__openpencil_markdown',
  nestedImportPath: '../__openpencil_markdown',
  dependencies: Object.freeze({
    'react-markdown': REACT_MARKDOWN_VERSION,
    'remark-gfm': REMARK_GFM_VERSION
  }),
  optimizeDeps: Object.freeze(['react-markdown', 'remark-gfm']),
  buildRuntime: buildOpenPencilMarkdownComponent
})
