import { MODAL_MODULE_TYPE, MODAL_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

const MODAL_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent
} from 'react'
import { createPortal } from 'react-dom'

export interface OpenPencilModalConfig {
  triggerLabel: string
  showTriggerIcon: boolean
  showTriggerLabel: boolean
  title: string
  content: string
  showCloseButton: boolean
  closeOnBackdrop: boolean
  closeOnEscape: boolean
  showCancelButton: boolean
  cancelLabel: string
  showConfirmButton: boolean
  confirmLabel: string
  panelWidth: number
  footerAlign: 'left' | 'center' | 'right'
  panelBackground: string
  textColor: string
  accentColor: string
  overlayOpacity: number
}

export interface OpenPencilModalProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, 'onClick' | 'onKeyDown' | 'type'> {
  config: OpenPencilModalConfig
  onClick?: (event: ReactMouseEvent<HTMLButtonElement>) => void
  onKeyDown?: (event: ReactKeyboardEvent<HTMLButtonElement>) => void
}

const TRANSITION_MS = 180
const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])'
].join(',')
const TRIGGER_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  boxSizing: 'border-box',
  color: '#FFFFFF',
  cursor: 'pointer',
  display: 'flex',
  font: 'inherit',
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: '0 12px',
  textAlign: 'center',
  touchAction: 'manipulation'
}
const AUTHORED_CONTENT_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'inline-flex',
  justifyContent: 'center',
  maxWidth: '100%',
  minWidth: 0,
  pointerEvents: 'none'
}
const AUTHORED_BUTTON_STYLE: CSSProperties = {
  appearance: 'none',
  background: 'transparent',
  border: 0,
  color: 'inherit',
  cursor: 'pointer',
  inset: 0,
  outlineOffset: 2,
  padding: 0,
  position: 'absolute',
  touchAction: 'manipulation',
  zIndex: 1
}
const LABEL_STYLE: CSSProperties = {
  color: 'inherit',
  lineHeight: 1.2,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
}
const ICON_STYLE: CSSProperties = {
  display: 'inline-flex',
  flexShrink: 0,
  height: 18,
  width: 18
}
const CLOSE_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  background: 'transparent',
  border: 0,
  borderRadius: 8,
  color: 'inherit',
  cursor: 'pointer',
  display: 'inline-flex',
  height: 44,
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: 10,
  width: 44
}
const ACTION_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  borderRadius: 8,
  cursor: 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  fontWeight: 600,
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 88,
  outlineOffset: 2,
  padding: '10px 16px'
}

interface OpenModalEntry {
  token: symbol
  dialog: HTMLDialogElement
  restoreFocus: HTMLElement | null
}

const openModals: OpenModalEntry[] = []
let bodyLockCount = 0
let bodyOverflowBeforeLock: string | null = null

function addOpenModal(entry: OpenModalEntry): void {
  const previous = openModals.findIndex((candidate) => candidate.token === entry.token)
  if (previous >= 0) openModals.splice(previous, 1)
  openModals.push(entry)
}

function removeOpenModal(token: symbol): { wasTop: boolean; nextTop?: OpenModalEntry } {
  const index = openModals.findIndex((entry) => entry.token === token)
  const wasTop = index >= 0 && index === openModals.length - 1
  if (index >= 0) openModals.splice(index, 1)
  return { wasTop, nextTop: openModals[openModals.length - 1] }
}

function isTopModal(token: symbol): boolean {
  return openModals[openModals.length - 1]?.token === token
}

function lockBody(): () => void {
  if (bodyLockCount === 0) {
    bodyOverflowBeforeLock = document.body.style.overflow
    document.body.style.overflow = 'hidden'
  }
  bodyLockCount += 1
  let released = false
  return () => {
    if (released) return
    released = true
    bodyLockCount = Math.max(0, bodyLockCount - 1)
    if (bodyLockCount > 0) return
    document.body.style.overflow = bodyOverflowBeforeLock ?? ''
    bodyOverflowBeforeLock = null
  }
}

function focusableElements(dialog: HTMLDialogElement): HTMLElement[] {
  return [...dialog.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)].filter(
    (element) => !element.hasAttribute('disabled') && element.getAttribute('aria-hidden') !== 'true'
  )
}

function focusDialog(dialog: HTMLDialogElement): void {
  dialog.focus({ preventScroll: true })
}

function trapTab(event: ReactKeyboardEvent<HTMLDialogElement>): void {
  if (event.key !== 'Tab') return
  const dialog = event.currentTarget
  const focusable = focusableElements(dialog)
  if (focusable.length === 0) {
    event.preventDefault()
    focusDialog(dialog)
    return
  }
  const first = focusable[0]
  const last = focusable[focusable.length - 1]
  const active = document.activeElement
  if (event.shiftKey && (active === first || active === dialog || !dialog.contains(active))) {
    event.preventDefault()
    last.focus({ preventScroll: true })
  } else if (!event.shiftKey && (active === last || !dialog.contains(active))) {
    event.preventDefault()
    first.focus({ preventScroll: true })
  }
}

function footerJustify(align: OpenPencilModalConfig['footerAlign']): CSSProperties['justifyContent'] {
  if (align === 'left') return 'flex-start'
  if (align === 'center') return 'center'
  return 'flex-end'
}

export default function OpenPencilModal({
  config,
  className,
  children,
  onClick,
  onKeyDown,
  style,
  tabIndex,
  ...hostProps
}: OpenPencilModalProps) {
  const triggerRef = useRef<HTMLButtonElement>(null)
  const dialogRef = useRef<HTMLDialogElement>(null)
  const closeTimerRef = useRef<number | null>(null)
  const openFrameRef = useRef<number | null>(null)
  const tokenRef = useRef(Symbol('open-pencil-modal'))
  const backdropPressRef = useRef(false)
  const [mounted, setMounted] = useState(false)
  const [visible, setVisible] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const baseId = useId().replaceAll(':', '')
  const titleId = baseId + '-title'
  const contentId = baseId + '-content'
  const panelId = baseId + '-panel'

  const clearTimers = useCallback(() => {
    if (closeTimerRef.current !== null) window.clearTimeout(closeTimerRef.current)
    if (openFrameRef.current !== null) window.cancelAnimationFrame(openFrameRef.current)
    closeTimerRef.current = null
    openFrameRef.current = null
  }, [])

  const openModal = useCallback(() => {
    clearTimers()
    if (mounted) setVisible(true)
    else setMounted(true)
  }, [clearTimers, mounted])

  const closeModal = useCallback(() => {
    clearTimers()
    setVisible(false)
    if (reducedMotion) {
      setMounted(false)
      return
    }
    closeTimerRef.current = window.setTimeout(() => {
      closeTimerRef.current = null
      setMounted(false)
    }, TRANSITION_MS)
  }, [clearTimers, reducedMotion])

  useEffect(() => {
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [])

  useEffect(() => {
    if (!mounted) return
    const dialog = dialogRef.current
    if (!dialog) return
    const entry: OpenModalEntry = {
      token: tokenRef.current,
      dialog,
      restoreFocus: document.activeElement instanceof HTMLElement ? document.activeElement : null
    }
    dialog.showModal()
    addOpenModal(entry)
    const releaseBody = lockBody()
    openFrameRef.current = window.requestAnimationFrame(() => {
      openFrameRef.current = null
      setVisible(true)
      focusDialog(dialog)
    })
    return () => {
      clearTimers()
      if (dialog.open) dialog.close()
      const { wasTop, nextTop } = removeOpenModal(entry.token)
      releaseBody()
      if (!wasTop) return
      if (nextTop?.dialog.open) focusDialog(nextTop.dialog)
      else if (entry.restoreFocus?.isConnected) entry.restoreFocus.focus({ preventScroll: true })
      else triggerRef.current?.focus({ preventScroll: true })
    }
  }, [clearTimers, mounted])

  useEffect(() => clearTimers, [clearTimers])

  const handleTriggerClick = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onClick?.(event)
    if (!event.defaultPrevented) openModal()
  }
  const accessibleLabel = config.triggerLabel || 'Open modal'
  const hasAuthoredTrigger = children !== undefined && children !== null
  const showIcon = config.showTriggerIcon
  const showLabel = config.showTriggerLabel
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle = positionedByClass || positionedByStyle ? style : { ...style, position: 'relative' as const }
  const triggerStyle: CSSProperties = {
    ...hostStyle,
    ...TRIGGER_STYLE,
    color: hostStyle?.color ?? TRIGGER_STYLE.color,
    gap: !hasAuthoredTrigger && showIcon && showLabel ? 8 : 0
  }
  const overlayCss =
    '[data-openpencil-modal-panel="' + baseId + '"]::backdrop{' +
    'background:#000000;' +
    'opacity:' + (visible ? config.overlayOpacity : '0') + ';' +
    'transition:' + (reducedMotion ? 'none' : 'opacity ' + TRANSITION_MS + 'ms ease') + '}' +
    '[data-openpencil-modal-close]:focus-visible,[data-openpencil-modal-action]:focus-visible{' +
    'outline:2px solid currentColor}'

  const portal = mounted
    ? createPortal(
        <>
          <style>{overlayCss}</style>
          <dialog
            aria-describedby={config.content ? contentId : undefined}
            aria-label={config.title ? undefined : accessibleLabel}
            aria-labelledby={config.title ? titleId : undefined}
            aria-modal="true"
            data-openpencil-modal-panel={baseId}
            data-state={visible ? 'open' : 'closed'}
            id={panelId}
            onCancel={(event) => {
              event.preventDefault()
              if (config.closeOnEscape && isTopModal(tokenRef.current)) closeModal()
            }}
            onClick={(event) => {
              if (
                backdropPressRef.current &&
                event.target === event.currentTarget &&
                config.closeOnBackdrop &&
                isTopModal(tokenRef.current)
              ) closeModal()
              backdropPressRef.current = false
            }}
            onKeyDown={trapTab}
            onMouseDown={(event) => {
              backdropPressRef.current = event.target === event.currentTarget
            }}
            ref={dialogRef}
            role="dialog"
            style={{
              background: config.panelBackground,
              border: 0,
              borderRadius: 12,
              boxShadow: '0 24px 80px #00000040',
              boxSizing: 'border-box',
              color: config.textColor,
              maxHeight: 'calc(100vh - 32px)',
              maxWidth: 'calc(100vw - 32px)',
              opacity: visible ? 1 : 0,
              overflow: 'hidden',
              padding: 0,
              transform: visible ? 'translateY(0) scale(1)' : 'translateY(12px) scale(0.98)',
              transition: reducedMotion
                ? 'none'
                : 'opacity ' + TRANSITION_MS + 'ms ease, transform ' + TRANSITION_MS + 'ms ease',
              width: 'min(' + config.panelWidth + 'px, calc(100vw - 32px))'
            }}
            tabIndex={-1}
          >
            <div
              data-openpencil-modal-layout=""
              style={{ display: 'flex', flexDirection: 'column', maxHeight: 'calc(100vh - 32px)', minWidth: 0 }}
            >
              {config.title || config.showCloseButton ? (
                <header
                  data-openpencil-modal-header=""
                  style={{
                    alignItems: 'start',
                    columnGap: 16,
                    display: 'grid',
                    gridTemplateColumns: 'minmax(0, 1fr) auto',
                    padding: '20px 20px 0 24px'
                  }}
                >
                  <div style={{ minWidth: 0, overflowWrap: 'anywhere' }}>
                    {config.title ? <h2 id={titleId} style={{ margin: 0 }}>{config.title}</h2> : null}
                  </div>
                  {config.showCloseButton ? (
                    <button
                      aria-label="Close modal"
                      data-openpencil-modal-close=""
                      onClick={closeModal}
                      style={CLOSE_STYLE}
                      type="button"
                    >
                      <svg aria-hidden="true" focusable="false" height="20" viewBox="0 0 24 24" width="20">
                        <path
                          d="M6 6L18 18M18 6L6 18"
                          fill="none"
                          stroke="currentColor"
                          strokeLinecap="round"
                          strokeWidth="2"
                        />
                      </svg>
                    </button>
                  ) : null}
                </header>
              ) : null}
              {config.content ? (
                <div
                  data-openpencil-modal-content=""
                  id={contentId}
                  style={{
                    minWidth: 0,
                    overflowWrap: 'anywhere',
                    overflowY: 'auto',
                    padding: '16px 24px 24px',
                    whiteSpace: 'pre-wrap'
                  }}
                >
                  {config.content}
                </div>
              ) : null}
              {config.showCancelButton || config.showConfirmButton ? (
                <footer
                  data-openpencil-modal-footer=""
                  style={{
                    borderTop: '1px solid #0000001F',
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: 12,
                    justifyContent: footerJustify(config.footerAlign),
                    padding: '16px 24px'
                  }}
                >
                  {config.showCancelButton ? (
                    <button
                      data-openpencil-modal-action="cancel"
                      onClick={closeModal}
                      style={{ ...ACTION_STYLE, background: 'transparent', border: '1px solid currentColor', color: 'inherit' }}
                      type="button"
                    >
                      {config.cancelLabel}
                    </button>
                  ) : null}
                  {config.showConfirmButton ? (
                    <button
                      data-openpencil-modal-action="confirm"
                      onClick={closeModal}
                      style={{ ...ACTION_STYLE, background: config.accentColor, border: 0, color: '#FFFFFF' }}
                      type="button"
                    >
                      {config.confirmLabel}
                    </button>
                  ) : null}
                </footer>
              ) : null}
            </div>
          </dialog>
        </>,
        document.body
      )
    : null

  return (
    <>
      {hasAuthoredTrigger ? (
        <div className={className} data-openpencil-modal-trigger-host="" style={triggerStyle}>
          <div aria-hidden="true" data-openpencil-modal-trigger-authored="" inert style={AUTHORED_CONTENT_STYLE}>
            {children}
          </div>
          <button
            {...hostProps}
            aria-controls={panelId}
            aria-expanded={mounted && visible}
            aria-haspopup="dialog"
            aria-label={accessibleLabel}
            data-openpencil-modal-trigger=""
            onClick={handleTriggerClick}
            onKeyDown={onKeyDown}
            ref={triggerRef}
            style={AUTHORED_BUTTON_STYLE}
            tabIndex={tabIndex ?? 0}
            type="button"
          />
        </div>
      ) : (
        <button
          {...hostProps}
          aria-controls={panelId}
          aria-expanded={mounted && visible}
          aria-haspopup="dialog"
          aria-label={accessibleLabel}
          className={className}
          data-openpencil-modal-trigger=""
          onClick={handleTriggerClick}
          onKeyDown={onKeyDown}
          ref={triggerRef}
          style={triggerStyle}
          tabIndex={tabIndex ?? 0}
          type="button"
        >
          {showIcon ? (
            <svg
              aria-hidden="true"
              data-openpencil-modal-trigger-icon=""
              focusable="false"
              style={ICON_STYLE}
              viewBox="0 0 24 24"
            >
              <rect fill="none" height="16" rx="2" stroke="currentColor" strokeWidth="2" width="18" x="3" y="4" />
              <path d="M3 9H21" fill="none" stroke="currentColor" strokeWidth="2" />
            </svg>
          ) : null}
          {showLabel ? <span data-openpencil-modal-trigger-label="" style={LABEL_STYLE}>{config.triggerLabel}</span> : null}
        </button>
      )}
      {portal}
    </>
  )
}
`

export function buildOpenPencilModalComponent(options?: ReactModuleRuntimeOptions): string {
  if (!options?.microfrontend) return MODAL_RUNTIME
  return MODAL_RUNTIME.replace(
    "import { createPortal } from 'react-dom'",
    "import { createPortal } from 'react-dom'\nimport { microfrontendPortalTarget } from './__microfrontend-context'"
  ).replace(
    '        document.body\n      )',
    '        microfrontendPortalTarget() ?? document.body\n      )'
  )
}

export const MODAL_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: MODAL_PLUGIN_ID,
  moduleType: MODAL_MODULE_TYPE,
  componentName: 'OpenPencilModal',
  runtimePath: 'src/__openpencil_modal.tsx',
  rootImportPath: './__openpencil_modal',
  nestedImportPath: '../__openpencil_modal',
  buildRuntime: buildOpenPencilModalComponent
})
