import { PDF_VIEWER_MODULE_TYPE, PDF_VIEWER_PLUGIN_ID } from '@open-pencil/core/plugins'

import { REACT_MODULE_POSITIONED_HOST_SOURCE } from './runtime-source'
import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

export function buildOpenPencilPDFViewerComponent(options: ReactModuleRuntimeOptions): string {
  const stateImport = options.devMode
    ? "import { useEffect, useState, type HTMLAttributes } from 'react'"
    : "import type { HTMLAttributes } from 'react'"
  const activationState = options.devMode
    ? `  const [authorizedSource, setAuthorizedSource] = useState('')
  const activeSource = authorizedSource === config.sourceUrl ? config.sourceUrl : ''

  useEffect(() => {
    setAuthorizedSource('')
  }, [config.sourceUrl])`
    : `  const activeSource = config.sourceUrl`
  const activationButton = options.devMode
    ? `
      {config.sourceUrl && activeSource === '' ? (
        <button
          data-openpencil-pdf-load=""
          onClick={() => setAuthorizedSource(config.sourceUrl)}
          style={{ background: config.accentColor, border: 0, borderRadius: 6, color: '#FFFFFF', cursor: 'pointer', font: '600 13px system-ui, sans-serif', padding: '10px 14px' }}
          type="button"
        >
          Load PDF preview
        </button>
      ) : null}`
    : ''

  return `// Auto-generated by OpenPencil compiler. Do not edit by hand.
${stateImport}

export interface OpenPencilPdfViewerConfig {
  sourceUrl: string
  title: string
  initialPage: number
  pageCountHint: number
  fit: 'width' | 'page'
  showToolbar: boolean
  allowDownload: boolean
  backgroundColor: string
  accentColor: string
}

export interface OpenPencilPdfViewerProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilPdfViewerConfig
}

function viewerSource(source: string, config: OpenPencilPdfViewerConfig): string {
  if (!source) return ''
  const view = config.fit === 'width' ? 'FitH' : 'Fit'
  return source + '#page=' + config.initialPage + '&view=' + view + '&toolbar=' + (config.showToolbar ? '1' : '0')
}

export default function OpenPencilPdfViewer({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilPdfViewerProps) {
${activationState}
  const src = viewerSource(activeSource, config)
${REACT_MODULE_POSITIONED_HOST_SOURCE}

  return (
    <div
      {...hostProps}
      aria-label={config.title}
      className={className}
      data-openpencil-pdf-viewer=""
      role="region"
      style={{ ...hostStyle, alignItems: 'center', background: config.backgroundColor, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}
    >
      {config.showToolbar ? (
        <div style={{ alignItems: 'center', background: config.accentColor, color: '#FFFFFF', display: 'flex', flex: '0 0 auto', gap: 12, justifyContent: 'space-between', padding: '8px 12px', width: '100%' }}>
          <strong style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{config.title}</strong>
          <span style={{ font: '12px system-ui, sans-serif' }}>
            Page {config.initialPage}{config.pageCountHint > 0 ? ' / ' + config.pageCountHint : ''}
          </span>
          {config.allowDownload && activeSource ? (
            <a href={activeSource} rel="noopener noreferrer" style={{ color: '#FFFFFF' }} target="_blank">Download</a>
          ) : null}
        </div>
      ) : null}
      {src ? (
        <iframe
          referrerPolicy="no-referrer"
          sandbox=""
          src={src}
          style={{ border: 0, flex: '1 1 auto', minHeight: 0, width: '100%' }}
          title={config.title}
        />
      ) : (
        <div style={{ alignItems: 'center', display: 'flex', flex: '1 1 auto', flexDirection: 'column', gap: 10, justifyContent: 'center', padding: 20, textAlign: 'center' }}>
          <strong>{config.title}</strong>
          <span style={{ font: '12px system-ui, sans-serif', opacity: 0.72 }}>
            {config.sourceUrl ? 'Preview loading requires confirmation.' : 'Choose a PDF source in OpenPencil.'}
          </span>${activationButton}
        </div>
      )}
      {children}
    </div>
  )
}
`
}

export const PDF_VIEWER_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: PDF_VIEWER_PLUGIN_ID,
  moduleType: PDF_VIEWER_MODULE_TYPE,
  componentName: 'OpenPencilPdfViewer',
  runtimePath: 'src/__openpencil_pdf_viewer.tsx',
  rootImportPath: './__openpencil_pdf_viewer',
  nestedImportPath: '../__openpencil_pdf_viewer',
  buildRuntime: buildOpenPencilPDFViewerComponent
})
