import { QR_BARCODE_MODULE_TYPE, QR_BARCODE_PLUGIN_ID } from '@open-pencil/core/plugins'

import { REACT_MODULE_POSITIONED_HOST_SOURCE } from './runtime-source'
import type { ReactModuleAdapter } from './types'

export const QRCODE_VERSION = '1.5.4'
export const JSBARCODE_VERSION = '3.12.3'

const QR_BARCODE_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import { useEffect, useRef, useState, type HTMLAttributes } from 'react'
// @ts-ignore -- generated source relies on the package's browser entry.
import QRCode from 'qrcode'
import JsBarcode from 'jsbarcode'

export interface OpenPencilQrBarcodeConfig {
  format: 'qr' | 'code128'
  value: string
  caption: string
  showCaption: boolean
  errorCorrection: 'low' | 'medium' | 'quartile' | 'high'
  quietZone: number
  foregroundColor: string
  backgroundColor: string
}

export interface OpenPencilQrBarcodeProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilQrBarcodeConfig
}

const ERROR_LEVEL = { low: 'L', medium: 'M', quartile: 'Q', high: 'H' } as const

export default function OpenPencilQrBarcode({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilQrBarcodeProps) {
  const barcodeRef = useRef<SVGSVGElement | null>(null)
  const [qrDataUrl, setQrDataUrl] = useState('')
  const [error, setError] = useState('')
${REACT_MODULE_POSITIONED_HOST_SOURCE}

  useEffect(() => {
    let cancelled = false
    setError('')
    setQrDataUrl('')
    if (config.format === 'qr') {
      void QRCode.toDataURL(config.value, {
        color: { dark: config.foregroundColor, light: config.backgroundColor },
        errorCorrectionLevel: ERROR_LEVEL[config.errorCorrection],
        margin: Math.max(0, Math.round(config.quietZone / 4)),
        width: 1024
      }).then(
        (url: string) => {
          if (!cancelled) setQrDataUrl(url)
        },
        (cause: unknown) => {
          if (!cancelled) setError(cause instanceof Error ? cause.message : String(cause))
        }
      )
    } else if (barcodeRef.current) {
      try {
        JsBarcode(barcodeRef.current, config.value, {
          background: config.backgroundColor,
          displayValue: false,
          format: 'CODE128',
          height: 160,
          lineColor: config.foregroundColor,
          margin: config.quietZone,
          width: 3
        })
      } catch (cause) {
        setError(cause instanceof Error ? cause.message : String(cause))
      }
    }
    return () => { cancelled = true }
  }, [
    config.backgroundColor,
    config.errorCorrection,
    config.foregroundColor,
    config.format,
    config.quietZone,
    config.value
  ])

  return (
    <div
      {...hostProps}
      className={className}
      data-openpencil-qr-barcode=""
      style={{
        ...hostStyle,
        alignItems: 'center',
        background: config.backgroundColor,
        color: config.foregroundColor,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        overflow: 'hidden',
        padding: Math.min(config.quietZone, 32)
      }}
    >
      {error ? (
        <p role="alert" style={{ font: '12px/1.4 system-ui, sans-serif', margin: 12 }}>
          Unable to generate code: {error}
        </p>
      ) : config.format === 'qr' ? (
        qrDataUrl ? (
          <img
            alt={config.caption || 'QR code'}
            draggable={false}
            src={qrDataUrl}
            style={{ height: 'min(80%, 100%)', imageRendering: 'pixelated', maxWidth: '100%', objectFit: 'contain' }}
          />
        ) : (
          <span aria-live="polite" style={{ font: '12px system-ui, sans-serif' }}>Generating QR code…</span>
        )
      ) : (
        <svg
          aria-label={config.caption || 'Code 128 barcode'}
          ref={barcodeRef}
          role="img"
          style={{ height: 'min(75%, 180px)', maxWidth: '100%', width: '100%' }}
        />
      )}
      {config.showCaption && config.caption ? (
        <p style={{ font: '600 13px/1.3 system-ui, sans-serif', margin: '8px 0 0', textAlign: 'center' }}>
          {config.caption}
        </p>
      ) : null}
      {children}
    </div>
  )
}
`

export function buildOpenPencilQrBarcodeComponent(): string {
  return QR_BARCODE_RUNTIME
}

export const QR_BARCODE_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: QR_BARCODE_PLUGIN_ID,
  moduleType: QR_BARCODE_MODULE_TYPE,
  componentName: 'OpenPencilQrBarcode',
  runtimePath: 'src/__openpencil_qr_barcode.tsx',
  rootImportPath: './__openpencil_qr_barcode',
  nestedImportPath: '../__openpencil_qr_barcode',
  dependencies: Object.freeze({ jsbarcode: JSBARCODE_VERSION, qrcode: QRCODE_VERSION }),
  optimizeDeps: Object.freeze(['jsbarcode', 'qrcode']),
  buildRuntime: buildOpenPencilQrBarcodeComponent
})
