import { RICH_TEXT_MODULE_TYPE, RICH_TEXT_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter } from './types'

const RICH_TEXT_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import { useId, useLayoutEffect, useRef } from 'react'
import type {
  CSSProperties,
  DragEvent,
  HTMLAttributes,
  MouseEvent,
  ReactNode,
  SyntheticEvent
} from 'react'

type RichTextAlign = 'left' | 'center' | 'right'
type RichTextMark =
  | { type: 'bold' | 'italic' | 'underline' | 'strike' | 'code' }
  | { type: 'link'; href: string }

interface RichTextInline {
  type: 'text'
  text: string
  marks: readonly RichTextMark[]
}

type RichTextBlock =
  | { type: 'paragraph'; align: RichTextAlign; children: readonly RichTextInline[] }
  | { type: 'heading'; level: 1 | 2 | 3; align: RichTextAlign; children: readonly RichTextInline[] }
  | { type: 'blockquote'; children: readonly RichTextInline[] }
  | { type: 'codeBlock'; language: string; text: string }
  | {
      type: 'bulletList' | 'orderedList'
      items: readonly { children: readonly RichTextInline[] }[]
    }

export interface OpenPencilRichTextDocument {
  type: 'doc'
  blocks: readonly RichTextBlock[]
}

export interface OpenPencilRichTextConfig {
  content: OpenPencilRichTextDocument
  textColor: string
  linkColor: string
  fontSize: number
  lineHeight: number
}

export interface OpenPencilRichTextProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilRichTextConfig
  name?: string
  onDocumentChange?: (document: OpenPencilRichTextDocument) => void
}

const LIMITS = {
  blocks: 64,
  codeBlockText: 8000,
  inlines: 256,
  inlinesPerBlock: 64,
  listItems: 128,
  listItemsPerBlock: 32,
  marks: 256,
  marksPerInline: 4,
  textPerInline: 2000,
  totalText: 24000
} as const

const SIMPLE_MARK_ORDER = ['bold', 'italic', 'underline', 'strike', 'code'] as const
type SimpleMark = (typeof SIMPLE_MARK_ORDER)[number]

interface ParseBudget {
  inlines: number
  listItems: number
  marks: number
  totalText: number
  truncated: boolean
}

function safeHref(value: string): string | null {
  if (value.length === 0 || value.length > 2048 || value.trim() !== value) return null
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index)
    if (code <= 31 || code === 127) return null
  }
  if (value.startsWith('/') && !value.startsWith('//')) return value
  if (value.startsWith('#') || value.startsWith('?')) return value
  return /^(?:https?:|mailto:|tel:)/i.test(value) ? value : null
}

function appendInlineElement(
  parent: HTMLElement,
  inline: RichTextInline,
  linkColor: string
): void {
  let content: Node = document.createTextNode(inline.text)
  for (const mark of inline.marks) {
    let wrapper: HTMLElement
    if (mark.type === 'link') {
      const href = safeHref(mark.href)
      if (!href) continue
      const anchor = document.createElement('a')
      anchor.href = href
      anchor.rel = 'noopener noreferrer'
      anchor.style.color = linkColor
      wrapper = anchor
    } else {
      const tag =
        mark.type === 'bold'
          ? 'strong'
          : mark.type === 'italic'
            ? 'em'
            : mark.type === 'underline'
              ? 'u'
              : mark.type === 'strike'
                ? 's'
                : 'code'
      wrapper = document.createElement(tag)
    }
    wrapper.append(content)
    content = wrapper
  }
  parent.append(content)
}

function appendInlines(
  parent: HTMLElement,
  children: readonly RichTextInline[],
  linkColor: string
): void {
  for (const child of children) appendInlineElement(parent, child, linkColor)
}

function createBlockElement(block: RichTextBlock, linkColor: string): HTMLElement {
  if (block.type === 'paragraph') {
    const paragraph = document.createElement('p')
    paragraph.style.margin = '0'
    paragraph.style.textAlign = block.align
    appendInlines(paragraph, block.children, linkColor)
    return paragraph
  }
  if (block.type === 'heading') {
    const heading = document.createElement('h' + block.level)
    heading.style.margin = '0'
    heading.style.textAlign = block.align
    appendInlines(heading, block.children, linkColor)
    return heading
  }
  if (block.type === 'blockquote') {
    const quote = document.createElement('blockquote')
    quote.style.borderInlineStart = '3px solid currentColor'
    quote.style.margin = '0'
    quote.style.paddingInlineStart = '1em'
    appendInlines(quote, block.children, linkColor)
    return quote
  }
  if (block.type === 'codeBlock') {
    const pre = document.createElement('pre')
    const code = document.createElement('code')
    pre.style.margin = '0'
    pre.style.overflowX = 'auto'
    pre.style.whiteSpace = 'pre-wrap'
    code.dataset.language = block.language
    code.append(document.createTextNode(block.text))
    pre.append(code)
    return pre
  }
  const list = document.createElement(block.type === 'orderedList' ? 'ol' : 'ul')
  list.style.margin = '0'
  list.style.paddingInlineStart = '1.5em'
  for (const item of block.items) {
    const listItem = document.createElement('li')
    appendInlines(listItem, item.children, linkColor)
    list.append(listItem)
  }
  return list
}

function mountDocument(
  editor: HTMLElement,
  value: OpenPencilRichTextDocument,
  linkColor: string
): void {
  const fragment = document.createDocumentFragment()
  for (const block of value.blocks) fragment.append(createBlockElement(block, linkColor))
  if (value.blocks.length === 0) fragment.append(createBlockElement(
    { type: 'paragraph', align: 'left', children: [] },
    linkColor
  ))
  editor.replaceChildren(fragment)
}

function sameMarks(left: readonly RichTextMark[], right: readonly RichTextMark[]): boolean {
  if (left.length !== right.length) return false
  return left.every((mark, index) => {
    const candidate = right[index]
    return (
      candidate?.type === mark.type &&
      (mark.type !== 'link' || (candidate.type === 'link' && candidate.href === mark.href))
    )
  })
}

function normalizeMarks(marks: readonly RichTextMark[]): RichTextMark[] {
  const simple = new Map<SimpleMark, RichTextMark>()
  let link: RichTextMark | undefined
  for (const mark of marks) {
    if (mark.type === 'link') {
      const href = safeHref(mark.href)
      if (href) link = { type: 'link', href }
    } else if (!simple.has(mark.type)) {
      simple.set(mark.type, { type: mark.type })
    }
  }
  const normalized = SIMPLE_MARK_ORDER.flatMap((type) => {
    const mark = simple.get(type)
    return mark ? [mark] : []
  })
  if (link) normalized.splice(Math.min(3, normalized.length), 0, link)
  return normalized.slice(0, LIMITS.marksPerInline)
}

function marksForElement(element: HTMLElement, inherited: readonly RichTextMark[]): RichTextMark[] {
  const marks = [...inherited]
  const tag = element.tagName.toLowerCase()
  if (tag === 'b' || tag === 'strong') marks.push({ type: 'bold' })
  if (tag === 'i' || tag === 'em') marks.push({ type: 'italic' })
  if (tag === 'u') marks.push({ type: 'underline' })
  if (tag === 's' || tag === 'strike') marks.push({ type: 'strike' })
  if (tag === 'code') marks.push({ type: 'code' })
  if (tag === 'a') {
    const href = safeHref(element.getAttribute('href') ?? '')
    if (href) marks.push({ type: 'link', href })
  }

  const weight = element.style.fontWeight
  if (weight === 'bold' || Number.parseInt(weight, 10) >= 600) marks.push({ type: 'bold' })
  if (element.style.fontStyle === 'italic') marks.push({ type: 'italic' })
  const decoration = element.style.textDecorationLine || element.style.textDecoration
  if (decoration.includes('underline')) marks.push({ type: 'underline' })
  if (decoration.includes('line-through')) marks.push({ type: 'strike' })
  return normalizeMarks(marks)
}

function appendInline(
  inlines: RichTextInline[],
  text: string,
  marks: readonly RichTextMark[],
  budget: ParseBudget
): void {
  if (text.length === 0) return
  const remainingTotal = Math.max(0, LIMITS.totalText - budget.totalText)
  const clipped = text.slice(0, Math.min(LIMITS.textPerInline, remainingTotal))
  if (clipped.length !== text.length) budget.truncated = true
  if (clipped.length === 0) return

  const normalizedMarks = normalizeMarks(marks)
  const previous = inlines.at(-1)
  if (
    previous &&
    sameMarks(previous.marks, normalizedMarks) &&
    previous.text.length + clipped.length <= LIMITS.textPerInline
  ) {
    inlines[inlines.length - 1] = { ...previous, text: previous.text + clipped }
    budget.totalText += clipped.length
    return
  }
  if (inlines.length >= LIMITS.inlinesPerBlock || budget.inlines >= LIMITS.inlines) {
    budget.truncated = true
    return
  }
  const remainingMarks = Math.max(0, LIMITS.marks - budget.marks)
  const boundedMarks = normalizedMarks.slice(0, remainingMarks)
  if (boundedMarks.length !== normalizedMarks.length) budget.truncated = true
  inlines.push({ type: 'text', text: clipped, marks: boundedMarks })
  budget.inlines += 1
  budget.marks += boundedMarks.length
  budget.totalText += clipped.length
}

function readInlineNodes(
  nodes: Iterable<ChildNode>,
  inherited: readonly RichTextMark[],
  budget: ParseBudget,
  result: RichTextInline[] = []
): RichTextInline[] {
  for (const node of nodes) {
    if (node.nodeType === Node.TEXT_NODE) {
      appendInline(result, node.textContent ?? '', inherited, budget)
      continue
    }
    if (!(node instanceof HTMLElement)) continue
    if (node.tagName.toLowerCase() === 'br') {
      appendInline(result, '\\n', inherited, budget)
      continue
    }
    readInlineNodes(node.childNodes, marksForElement(node, inherited), budget, result)
  }
  return result
}

function readAlignment(element: HTMLElement): RichTextAlign {
  const alignment = element.style.textAlign || element.getAttribute('align') || ''
  return alignment === 'center' || alignment === 'right' ? alignment : 'left'
}

function readTextBlock(
  element: HTMLElement,
  budget: ParseBudget,
  type: 'paragraph' | 'blockquote' | 'heading',
  level?: 1 | 2 | 3
): RichTextBlock {
  const children = readInlineNodes(element.childNodes, [], budget)
  if (type === 'blockquote') return { type, children }
  if (type === 'heading' && level) {
    return { type, level, align: readAlignment(element), children }
  }
  return { type: 'paragraph', align: readAlignment(element), children }
}

function readListBlock(
  element: HTMLElement,
  budget: ParseBudget,
  type: 'bulletList' | 'orderedList'
): RichTextBlock {
  const items: { children: readonly RichTextInline[] }[] = []
  for (const child of element.children) {
    if (!(child instanceof HTMLElement) || child.tagName.toLowerCase() !== 'li') continue
    if (items.length >= LIMITS.listItemsPerBlock || budget.listItems >= LIMITS.listItems) {
      budget.truncated = true
      break
    }
    items.push({ children: readInlineNodes(child.childNodes, [], budget) })
    budget.listItems += 1
  }
  return { type, items }
}

function readBlock(node: ChildNode, budget: ParseBudget): RichTextBlock | null {
  if (node.nodeType === Node.TEXT_NODE) {
    const children: RichTextInline[] = []
    appendInline(children, node.textContent ?? '', [], budget)
    return children.length > 0 ? { type: 'paragraph', align: 'left', children } : null
  }
  if (!(node instanceof HTMLElement)) return null
  const tag = node.tagName.toLowerCase()
  if (tag === 'h1' || tag === 'h2' || tag === 'h3') {
    return readTextBlock(node, budget, 'heading', Number(tag[1]) as 1 | 2 | 3)
  }
  if (tag === 'blockquote') return readTextBlock(node, budget, 'blockquote')
  if (tag === 'pre') {
    const remaining = Math.max(0, LIMITS.totalText - budget.totalText)
    const source = node.textContent ?? ''
    const text = source.slice(0, Math.min(LIMITS.codeBlockText, remaining))
    if (text.length !== source.length) budget.truncated = true
    budget.totalText += text.length
    const language = node.querySelector('code')?.getAttribute('data-language') ?? ''
    return { type: 'codeBlock', language: /^[A-Za-z0-9_+#.-]{0,32}$/.test(language) ? language : '', text }
  }
  if (tag === 'ol' || tag === 'ul') {
    return readListBlock(node, budget, tag === 'ol' ? 'orderedList' : 'bulletList')
  }
  return readTextBlock(node, budget, 'paragraph')
}

function readDocument(editor: HTMLElement): {
  document: OpenPencilRichTextDocument
  truncated: boolean
} {
  const budget: ParseBudget = {
    inlines: 0,
    listItems: 0,
    marks: 0,
    totalText: 0,
    truncated: false
  }
  const blocks: RichTextBlock[] = []
  for (const node of editor.childNodes) {
    if (blocks.length >= LIMITS.blocks) {
      budget.truncated = true
      break
    }
    const block = readBlock(node, budget)
    if (block) blocks.push(block)
  }
  if (blocks.length === 0) {
    blocks.push({ type: 'paragraph', align: 'left', children: [] })
  }
  return { document: { type: 'doc', blocks }, truncated: budget.truncated }
}

const TOOLBAR_STYLE: CSSProperties = {
  alignItems: 'center',
  background: '#FFFFFF',
  borderBottom: '1px solid #D1D5DB',
  boxSizing: 'border-box',
  color: '#374151',
  display: 'flex',
  flexWrap: 'wrap',
  gap: 6,
  padding: '10px 12px'
}

const TOOL_BUTTON_STYLE: CSSProperties = {
  alignItems: 'center',
  background: '#FFFFFF',
  border: '1px solid transparent',
  borderRadius: 5,
  color: '#374151',
  cursor: 'pointer',
  display: 'inline-flex',
  fontFamily: 'ui-sans-serif, system-ui, sans-serif',
  fontSize: 15,
  fontWeight: 600,
  height: 32,
  justifyContent: 'center',
  minWidth: 32,
  padding: '0 8px'
}

const SELECT_STYLE: CSSProperties = {
  ...TOOL_BUTTON_STYLE,
  borderColor: '#D1D5DB',
  fontWeight: 500,
  minWidth: 112
}

function ToolbarButton({
  children,
  label,
  onRun
}: {
  children: ReactNode
  label: string
  onRun: () => void
}) {
  return (
    <button
      aria-label={label}
      onClick={onRun}
      onMouseDown={(event) => event.preventDefault()}
      style={TOOL_BUTTON_STYLE}
      title={label}
      type="button"
    >
      {children}
    </button>
  )
}

export default function OpenPencilRichText({
  config,
  children,
  name,
  onDocumentChange,
  style,
  ...hostProps
}: OpenPencilRichTextProps) {
  const generatedId = useId()
  const editorId = 'openpencil-rich-text-' + generatedId.replace(/:/g, '')
  const hostRef = useRef<HTMLDivElement>(null)
  const editorRef = useRef<HTMLElement>(null)
  const hiddenInputRef = useRef<HTMLInputElement>(null)
  const mountedRef = useRef(false)
  const selectionRef = useRef<Range | null>(null)
  const documentRef = useRef<OpenPencilRichTextDocument>(config.content)
  const statusRef = useRef<HTMLSpanElement>(null)

  useLayoutEffect(() => {
    const editor = editorRef.current
    if (!editor || mountedRef.current) return
    mountDocument(editor, documentRef.current, config.linkColor)
    mountedRef.current = true
  }, [])

  function captureSelection(): void {
    const editor = editorRef.current
    const selection = window.getSelection()
    if (!editor || !selection || selection.rangeCount === 0) return
    const range = selection.getRangeAt(0)
    const container =
      range.commonAncestorContainer.nodeType === Node.ELEMENT_NODE
        ? range.commonAncestorContainer
        : range.commonAncestorContainer.parentNode
    if (container && editor.contains(container)) selectionRef.current = range.cloneRange()
  }

  function restoreSelection(): void {
    const range = selectionRef.current
    if (!range) return
    const selection = window.getSelection()
    if (!selection) return
    selection.removeAllRanges()
    selection.addRange(range)
  }

  function setStatus(message: string): void {
    if (statusRef.current) statusRef.current.textContent = message
  }

  function syncDocument(): void {
    const editor = editorRef.current
    if (!editor) return
    const next = readDocument(editor)
    documentRef.current = next.document
    if (hiddenInputRef.current) hiddenInputRef.current.value = JSON.stringify(next.document)
    onDocumentChange?.(next.document)
    hostRef.current?.dispatchEvent(
      new CustomEvent('openpencil:rich-text-change', {
        bubbles: true,
        detail: next.document
      })
    )
    setStatus(next.truncated ? 'Content limit reached' : 'Changes ready')
  }

  function runCommand(command: string, value?: string): void {
    const editor = editorRef.current
    if (!editor) return
    editor.focus({ preventScroll: true })
    restoreSelection()
    try {
      document.execCommand('styleWithCSS', false, 'false')
      document.execCommand(command, false, value)
    } finally {
      captureSelection()
      syncDocument()
    }
  }

  function applyLink(): void {
    const requested = window.prompt('Enter a safe URL (https, mailto, tel, /, #, or ?):')
    if (requested === null) return
    const href = safeHref(requested)
    if (!href) {
      setStatus('Link rejected: unsupported or unsafe URL')
      return
    }
    runCommand('createLink', href)
  }

  function toggleInlineCode(): void {
    const editor = editorRef.current
    if (!editor) return
    editor.focus({ preventScroll: true })
    restoreSelection()
    const selection = window.getSelection()
    if (!selection || selection.rangeCount === 0) return
    const range = selection.getRangeAt(0)
    const startElement =
      range.startContainer instanceof Element
        ? range.startContainer
        : range.startContainer.parentElement
    const existing = startElement?.closest('code')
    if (existing && editor.contains(existing) && existing.parentElement?.tagName !== 'PRE') {
      const parent = existing.parentNode
      if (!parent) return
      while (existing.firstChild) parent.insertBefore(existing.firstChild, existing)
      parent.removeChild(existing)
      parent.normalize()
      syncDocument()
      return
    }

    const code = document.createElement('code')
    if (range.collapsed) {
      range.insertNode(code)
      range.setStart(code, 0)
      range.collapse(true)
    } else {
      try {
        range.surroundContents(code)
      } catch {
        code.append(range.extractContents())
        range.insertNode(code)
      }
      range.selectNodeContents(code)
    }
    selection.removeAllRanges()
    selection.addRange(range)
    captureSelection()
    syncDocument()
  }

  function insertPlainText(text: string): void {
    const editor = editorRef.current
    if (!editor) return
    editor.focus({ preventScroll: true })
    restoreSelection()
    const available = Math.max(0, LIMITS.totalText - (editor.textContent?.length ?? 0))
    const bounded = text.slice(0, available)
    if (bounded.length !== text.length) setStatus('Content limit reached')
    if (document.execCommand('insertText', false, bounded)) return
    const selection = window.getSelection()
    if (!selection || selection.rangeCount === 0) return
    const range = selection.getRangeAt(0)
    range.deleteContents()
    const textNode = document.createTextNode(bounded)
    range.insertNode(textNode)
    range.setStartAfter(textNode)
    range.collapse(true)
    selection.removeAllRanges()
    selection.addRange(range)
  }

  function handlePaste(event: SyntheticEvent<HTMLElement, ClipboardEvent>): void {
    event.preventDefault()
    insertPlainText(event.nativeEvent.clipboardData?.getData('text/plain') ?? '')
    captureSelection()
    syncDocument()
  }

  function handleDrop(event: DragEvent<HTMLElement>): void {
    event.preventDefault()
    insertPlainText(event.dataTransfer.getData('text/plain'))
    captureSelection()
    syncDocument()
  }

  function preventLinkNavigation(event: MouseEvent<HTMLElement>): void {
    if (event.target instanceof Element && event.target.closest('a')) event.preventDefault()
  }

  const hostStyle: CSSProperties = {
    ...style,
    color: config.textColor,
    fontSize: config.fontSize,
    lineHeight: config.lineHeight,
    overflow: style?.overflow ?? 'hidden'
  }
  return (
    <div {...hostProps} ref={hostRef} style={hostStyle}>
      <div
        data-openpencil-rich-text-editor=""
        onClick={(event) => event.stopPropagation()}
        onKeyDown={(event) => event.stopPropagation()}
        onPointerDown={(event) => event.stopPropagation()}
        style={{ background: '#FFFFFF', display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0, width: '100%' }}
      >
        <div aria-controls={editorId} aria-label="Rich text formatting" role="toolbar" style={TOOLBAR_STYLE}>
          <select
            aria-label="Block style"
            defaultValue=""
            onChange={(event) => {
              if (event.currentTarget.value) runCommand('formatBlock', event.currentTarget.value)
              event.currentTarget.value = ''
            }}
            onMouseDown={captureSelection}
            style={SELECT_STYLE}
          >
            <option value="">Block style</option>
            <option value="p">Normal</option>
            <option value="h1">Heading 1</option>
            <option value="h2">Heading 2</option>
            <option value="h3">Heading 3</option>
            <option value="blockquote">Quote</option>
            <option value="pre">Code block</option>
          </select>
          <ToolbarButton label="Bold" onRun={() => runCommand('bold')}><strong>B</strong></ToolbarButton>
          <ToolbarButton label="Italic" onRun={() => runCommand('italic')}><em>I</em></ToolbarButton>
          <ToolbarButton label="Underline" onRun={() => runCommand('underline')}><u>U</u></ToolbarButton>
          <ToolbarButton label="Strikethrough" onRun={() => runCommand('strikeThrough')}><s>S</s></ToolbarButton>
          <ToolbarButton label="Inline code" onRun={toggleInlineCode}>{'{ }'}</ToolbarButton>
          <ToolbarButton label="Ordered list" onRun={() => runCommand('insertOrderedList')}>1.</ToolbarButton>
          <ToolbarButton label="Bullet list" onRun={() => runCommand('insertUnorderedList')}>•</ToolbarButton>
          <ToolbarButton label="Align left" onRun={() => runCommand('justifyLeft')}>≡</ToolbarButton>
          <ToolbarButton label="Align center" onRun={() => runCommand('justifyCenter')}>≣</ToolbarButton>
          <ToolbarButton label="Align right" onRun={() => runCommand('justifyRight')}>≡</ToolbarButton>
          <ToolbarButton label="Link" onRun={applyLink}>↗</ToolbarButton>
          <ToolbarButton label="Remove link" onRun={() => runCommand('unlink')}>⊘</ToolbarButton>
          <ToolbarButton label="Clear formatting" onRun={() => runCommand('removeFormat')}>Tx</ToolbarButton>
          <ToolbarButton label="Undo" onRun={() => runCommand('undo')}>↶</ToolbarButton>
          <ToolbarButton label="Redo" onRun={() => runCommand('redo')}>↷</ToolbarButton>
        </div>
        <article
          aria-label="Rich text editor"
          aria-multiline="true"
          contentEditable
          data-openpencil-rich-text=""
          id={editorId}
          onBlur={() => {
            captureSelection()
            syncDocument()
          }}
          onClickCapture={preventLinkNavigation}
          onDrop={handleDrop}
          onFocus={() => {
            try { document.execCommand('defaultParagraphSeparator', false, 'p') } catch { /* Browser fallback. */ }
          }}
          onInput={syncDocument}
          onKeyUp={captureSelection}
          onMouseUp={captureSelection}
          onPaste={handlePaste}
          ref={editorRef}
          role="textbox"
          spellCheck
          style={{
            boxSizing: 'border-box',
            color: config.textColor,
            display: 'grid',
            flex: 1,
            gap: '0.65em',
            minHeight: 0,
            outline: 'none',
            overflow: 'auto',
            padding: '1em',
            whiteSpace: 'pre-wrap',
            width: '100%'
          }}
          suppressContentEditableWarning
          tabIndex={0}
        />
        <input
          defaultValue={JSON.stringify(documentRef.current)}
          name={name ?? 'openpencil.richText.' + generatedId.replace(/:/g, '')}
          ref={hiddenInputRef}
          type="hidden"
        />
        <span aria-live="polite" ref={statusRef} style={{ height: 1, overflow: 'hidden', position: 'absolute', width: 1 }} />
      </div>
      {children}
    </div>
  )
}
`

export function buildOpenPencilRichTextComponent(): string {
  return RICH_TEXT_RUNTIME
}

export const RICH_TEXT_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: RICH_TEXT_PLUGIN_ID,
  moduleType: RICH_TEXT_MODULE_TYPE,
  componentName: 'OpenPencilRichText',
  runtimePath: 'src/__openpencil_rich_text.tsx',
  rootImportPath: './__openpencil_rich_text',
  nestedImportPath: '../__openpencil_rich_text',
  buildRuntime: buildOpenPencilRichTextComponent
})
