import { SLIDE_MENU_MODULE_TYPE, SLIDE_MENU_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

const SLIDE_MENU_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type CSSProperties,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent
} from 'react'
import { createPortal } from 'react-dom'

export interface OpenPencilSlideMenuItem {
  label: string
  href: string
}

export interface OpenPencilSlideMenuConfig {
  presentation: 'menu' | 'dialog'
  direction: 'left' | 'right' | 'top' | 'bottom'
  triggerLabel: string
  showTriggerIcon?: boolean
  showTriggerLabel?: boolean
  title: string
  description: string
  items: readonly OpenPencilSlideMenuItem[]
  closeOnBackdrop: boolean
  showCloseButton: boolean
  panelSize: number
  panelBackground: string
  textColor: string
  overlayOpacity: number
}

export interface OpenPencilSlideMenuProps
  extends Omit<
    ButtonHTMLAttributes<HTMLButtonElement>,
    'onClick' | 'onKeyDown' | 'type'
  > {
  config: OpenPencilSlideMenuConfig
  onClick?: (event: ReactMouseEvent<HTMLButtonElement>) => void
  onKeyDown?: (event: ReactKeyboardEvent<HTMLButtonElement>) => void
}

const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])'
].join(',')
const TRANSITION_MS = 220
const TRIGGER_BUTTON_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  boxSizing: 'border-box',
  color: '#FFFFFF',
  cursor: 'pointer',
  display: 'flex',
  font: 'inherit',
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: '0 12px',
  textAlign: 'center',
  touchAction: 'manipulation'
}
const TRIGGER_ICON_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'inline-flex',
  flexDirection: 'column',
  flexShrink: 0,
  height: 14,
  justifyContent: 'space-between',
  width: 18
}
const TRIGGER_ICON_BAR_STYLE: CSSProperties = {
  background: 'currentColor',
  display: 'block',
  height: 2,
  width: 18
}
const TRIGGER_LABEL_STYLE: CSSProperties = {
  color: 'inherit',
  lineHeight: 1.2,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
}
const TRIGGER_AUTHORED_CONTENT_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'inline-flex',
  justifyContent: 'center',
  maxWidth: '100%',
  minWidth: 0,
  pointerEvents: 'none'
}
const TRIGGER_AUTHORED_BUTTON_STYLE: CSSProperties = {
  appearance: 'none',
  background: 'transparent',
  border: 0,
  color: 'inherit',
  cursor: 'pointer',
  inset: 0,
  outlineOffset: 2,
  padding: 0,
  position: 'absolute',
  touchAction: 'manipulation',
  zIndex: 1
}
const PANEL_HEADER_STYLE: CSSProperties = {
  columnGap: 16,
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 1fr) auto',
  marginBottom: 16
}
const PANEL_HEADER_COPY_STYLE: CSSProperties = {
  minWidth: 0,
  overflowWrap: 'anywhere'
}
const PANEL_TITLE_STYLE: CSSProperties = { margin: '0 0 8px' }
const PANEL_DESCRIPTION_STYLE: CSSProperties = { margin: 0 }
const CLOSE_BUTTON_STYLE: CSSProperties = {
  ...TRIGGER_BUTTON_STYLE,
  background: 'transparent',
  border: 0,
  borderRadius: 8,
  color: 'inherit',
  height: 44,
  padding: 10,
  width: 44
}
let bodyScrollLockCount = 0
let previousBodyOverflow: string | null = null

interface OpenSlideMenuEntry {
  token: symbol
  panel: HTMLElement
  restoreFocus: HTMLElement | null
}

const openSlideMenus: OpenSlideMenuEntry[] = []

function pushOpenSlideMenu(entry: OpenSlideMenuEntry): void {
  const existingIndex = openSlideMenus.findIndex((candidate) => candidate.token === entry.token)
  if (existingIndex >= 0) openSlideMenus.splice(existingIndex, 1)
  openSlideMenus.push(entry)
}

function removeOpenSlideMenu(token: symbol): {
  wasTop: boolean
  nextTop: OpenSlideMenuEntry | undefined
} {
  const index = openSlideMenus.findIndex((entry) => entry.token === token)
  const wasTop = index >= 0 && index === openSlideMenus.length - 1
  if (index >= 0) openSlideMenus.splice(index, 1)
  return { wasTop, nextTop: openSlideMenus[openSlideMenus.length - 1] }
}

function isTopOpenSlideMenu(token: symbol): boolean {
  return openSlideMenus[openSlideMenus.length - 1]?.token === token
}

function lockBodyScroll(): () => void {
  if (bodyScrollLockCount === 0) {
    previousBodyOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
  }
  bodyScrollLockCount += 1
  let released = false
  return () => {
    if (released) return
    released = true
    bodyScrollLockCount = Math.max(0, bodyScrollLockCount - 1)
    if (bodyScrollLockCount !== 0) return
    document.body.style.overflow = previousBodyOverflow ?? ''
    previousBodyOverflow = null
  }
}

function focusableElements(panel: HTMLElement): HTMLElement[] {
  return [...panel.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)].filter(
    (element) => !element.hasAttribute('disabled') && element.getAttribute('aria-hidden') !== 'true'
  )
}

function focusPanel(panel: HTMLElement): void {
  ;(focusableElements(panel)[0] ?? panel).focus({ preventScroll: true })
}

function menuPlacement(config: OpenPencilSlideMenuConfig): CSSProperties {
  const size = config.panelSize + 'px'
  const width = 'min(' + size + ', calc(100vw - 16px))'
  const height = 'min(' + size + ', calc(100vh - 16px))'
  const base: CSSProperties = { position: 'absolute' }
  if (config.direction === 'left') return { ...base, height: '100%', left: 0, top: 0, width }
  if (config.direction === 'right') return { ...base, height: '100%', right: 0, top: 0, width }
  if (config.direction === 'top') return { ...base, height, left: 0, top: 0, width: '100%' }
  return { ...base, bottom: 0, height, left: 0, width: '100%' }
}

function dialogPlacement(config: OpenPencilSlideMenuConfig): CSSProperties {
  return {
    left: '50%',
    maxHeight: 'calc(100vh - 32px)',
    position: 'absolute',
    top: '50%',
    width: 'min(' + config.panelSize + 'px, calc(100vw - 32px))'
  }
}

function closedTransform(config: OpenPencilSlideMenuConfig): string {
  if (config.presentation === 'menu') {
    if (config.direction === 'left') return 'translate3d(-100%, 0, 0)'
    if (config.direction === 'right') return 'translate3d(100%, 0, 0)'
    if (config.direction === 'top') return 'translate3d(0, -100%, 0)'
    return 'translate3d(0, 100%, 0)'
  }
  if (config.direction === 'left') return 'translate(calc(-50% - 48px), -50%)'
  if (config.direction === 'right') return 'translate(calc(-50% + 48px), -50%)'
  if (config.direction === 'top') return 'translate(-50%, calc(-50% - 48px))'
  return 'translate(-50%, calc(-50% + 48px))'
}

function openTransform(config: OpenPencilSlideMenuConfig): string {
  return config.presentation === 'dialog' ? 'translate(-50%, -50%)' : 'translate3d(0, 0, 0)'
}

function panelStyle(
  config: OpenPencilSlideMenuConfig,
  visible: boolean,
  reducedMotion: boolean
): CSSProperties {
  return {
    ...(config.presentation === 'dialog' ? dialogPlacement(config) : menuPlacement(config)),
    background: config.panelBackground,
    boxSizing: 'border-box',
    boxShadow: '0 24px 80px #00000040',
    color: config.textColor,
    opacity: visible ? 1 : 0,
    overflowY: 'auto',
    padding: 24,
    transform: visible ? openTransform(config) : closedTransform(config),
    transition: reducedMotion
      ? 'none'
      : 'transform ' + TRANSITION_MS + 'ms ease, opacity ' + TRANSITION_MS + 'ms ease',
    zIndex: 1
  }
}

export default function OpenPencilSlideMenu({
  config,
  className,
  children,
  onClick,
  onKeyDown,
  style,
  tabIndex,
  ...hostProps
}: OpenPencilSlideMenuProps) {
  const triggerRef = useRef<HTMLButtonElement>(null)
  const panelRef = useRef<HTMLElement>(null)
  const closeTimerRef = useRef<number | null>(null)
  const openFrameRef = useRef<number | null>(null)
  const modalTokenRef = useRef(Symbol('open-pencil-slide-menu'))
  const [mounted, setMounted] = useState(false)
  const [visible, setVisible] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const baseId = useId().replaceAll(':', '')
  const panelId = baseId + '-panel'
  const titleId = baseId + '-title'
  const descriptionId = baseId + '-description'

  const clearCloseTimer = useCallback(() => {
    if (closeTimerRef.current === null) return
    window.clearTimeout(closeTimerRef.current)
    closeTimerRef.current = null
  }, [])

  const clearOpenFrame = useCallback(() => {
    if (openFrameRef.current === null) return
    window.cancelAnimationFrame(openFrameRef.current)
    openFrameRef.current = null
  }, [])

  const openPanel = useCallback(() => {
    clearCloseTimer()
    if (mounted) setVisible(true)
    else setMounted(true)
  }, [clearCloseTimer, mounted])

  const closePanel = useCallback(() => {
    clearCloseTimer()
    clearOpenFrame()
    setVisible(false)
    if (reducedMotion) {
      setMounted(false)
      return
    }
    closeTimerRef.current = window.setTimeout(() => {
      closeTimerRef.current = null
      setMounted(false)
    }, TRANSITION_MS)
  }, [clearCloseTimer, clearOpenFrame, reducedMotion])

  useEffect(() => {
    if (typeof window === 'undefined') return
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [])

  useEffect(() => {
    if (!mounted) return
    clearOpenFrame()
    openFrameRef.current = window.requestAnimationFrame(() => {
      openFrameRef.current = null
      setVisible(true)
    })
    return clearOpenFrame
  }, [clearOpenFrame, mounted])

  useEffect(() => {
    if (!mounted) return
    const panel = panelRef.current
    if (!panel) return
    const entry: OpenSlideMenuEntry = {
      token: modalTokenRef.current,
      panel,
      restoreFocus:
        document.activeElement instanceof HTMLElement ? document.activeElement : null
    }
    pushOpenSlideMenu(entry)
    const releaseBodyScroll = lockBodyScroll()
    const frame = window.requestAnimationFrame(() => focusPanel(panel))
    return () => {
      window.cancelAnimationFrame(frame)
      const { wasTop, nextTop } = removeOpenSlideMenu(entry.token)
      releaseBodyScroll()
      if (!wasTop) return
      if (nextTop) {
        if (
          entry.restoreFocus?.isConnected &&
          nextTop.panel.contains(entry.restoreFocus)
        ) {
          entry.restoreFocus.focus({ preventScroll: true })
        } else {
          focusPanel(nextTop.panel)
        }
        return
      }
      triggerRef.current?.focus({ preventScroll: true })
    }
  }, [mounted])

  useEffect(() => {
    if (!mounted) return
    const handleKeyDown = (event: KeyboardEvent) => {
      if (!isTopOpenSlideMenu(modalTokenRef.current)) return
      if (event.key === 'Escape') {
        event.preventDefault()
        closePanel()
        return
      }
      if (event.key !== 'Tab') return
      const panel = panelRef.current
      if (!panel) return
      const focusable = focusableElements(panel)
      if (focusable.length === 0) {
        event.preventDefault()
        panel.focus({ preventScroll: true })
        return
      }
      const first = focusable[0]
      const last = focusable[focusable.length - 1]
      const active = document.activeElement
      if (event.shiftKey && (active === first || !panel.contains(active))) {
        event.preventDefault()
        last.focus({ preventScroll: true })
      } else if (!event.shiftKey && (active === last || !panel.contains(active))) {
        event.preventDefault()
        first.focus({ preventScroll: true })
      }
    }
    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [closePanel, mounted])

  useEffect(
    () => () => {
      clearCloseTimer()
      clearOpenFrame()
    },
    [clearCloseTimer, clearOpenFrame]
  )

  const handleTriggerClick = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onClick?.(event)
    if (!event.defaultPrevented) openPanel()
  }
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle =
    positionedByClass || positionedByStyle
      ? style
      : { ...style, position: 'relative' as const }
  const hasAuthoredTrigger = children !== undefined && children !== null
  const showTriggerIcon = config.showTriggerIcon !== false
  const showTriggerLabel = config.showTriggerLabel !== false
  const triggerStyle: CSSProperties = {
    ...hostStyle,
    ...TRIGGER_BUTTON_STYLE,
    color: hostStyle?.color ?? TRIGGER_BUTTON_STYLE.color,
    gap: !hasAuthoredTrigger && showTriggerIcon && showTriggerLabel ? 8 : 0
  }
  const accessibleLabel = config.triggerLabel || 'Open slide menu'

  const portal =
    mounted && typeof document !== 'undefined'
      ? createPortal(
          <div
            data-openpencil-slide-menu-overlay=""
            style={{ inset: 0, pointerEvents: visible ? 'auto' : 'none', position: 'fixed', zIndex: 2147483647 }}
          >
            <style>{'[data-openpencil-slide-menu-close]:focus-visible{outline:2px solid currentColor}'}</style>
            <div
              data-openpencil-slide-menu-backdrop=""
              onMouseDown={() => {
                if (config.closeOnBackdrop) closePanel()
              }}
              style={{
                background: '#000000',
                inset: 0,
                opacity: visible ? config.overlayOpacity : 0,
                position: 'absolute',
                transition: reducedMotion ? 'none' : 'opacity ' + TRANSITION_MS + 'ms ease'
              }}
            />
            <section
              aria-describedby={config.description ? descriptionId : undefined}
              aria-label={config.title ? undefined : accessibleLabel}
              aria-labelledby={config.title ? titleId : undefined}
              aria-modal="true"
              data-direction={config.direction}
              data-openpencil-slide-menu-panel=""
              data-presentation={config.presentation}
              data-state={visible ? 'open' : 'closed'}
              id={panelId}
              ref={panelRef}
              role="dialog"
              style={panelStyle(config, visible, reducedMotion)}
              tabIndex={-1}
            >
              {config.title || config.description || config.showCloseButton ? (
                <header data-openpencil-slide-menu-header="" style={PANEL_HEADER_STYLE}>
                  <div style={PANEL_HEADER_COPY_STYLE}>
                    {config.title ? <h2 id={titleId} style={PANEL_TITLE_STYLE}>{config.title}</h2> : null}
                    {config.description ? (
                      <p id={descriptionId} style={PANEL_DESCRIPTION_STYLE}>{config.description}</p>
                    ) : null}
                  </div>
                  {config.showCloseButton ? (
                    <button
                      aria-label="Close"
                      data-openpencil-slide-menu-close=""
                      onClick={closePanel}
                      style={CLOSE_BUTTON_STYLE}
                      type="button"
                    >
                      <svg
                        aria-hidden="true"
                        data-openpencil-slide-menu-close-icon=""
                        focusable="false"
                        height="20"
                        viewBox="0 0 24 24"
                        width="20"
                      >
                        <path
                          d="M6 6L18 18M18 6L6 18"
                          fill="none"
                          stroke="currentColor"
                          strokeLinecap="round"
                          strokeWidth="2"
                        />
                      </svg>
                    </button>
                  ) : null}
                </header>
              ) : null}
              <nav aria-label={config.title || accessibleLabel}>
                <ul>
                  {config.items.map((item, index) => (
                    <li key={item.href + '-' + index}>
                      <a href={item.href} onClick={closePanel}>{item.label}</a>
                    </li>
                  ))}
                </ul>
              </nav>
            </section>
          </div>,
          document.body
        )
      : null

  return (
    <>
      {hasAuthoredTrigger ? (
        <div
          className={className}
          data-openpencil-slide-menu-trigger-host=""
          style={triggerStyle}
        >
          <div
            aria-hidden="true"
            data-openpencil-slide-menu-trigger-authored=""
            inert
            style={TRIGGER_AUTHORED_CONTENT_STYLE}
          >
            {children}
          </div>
          <button
            {...hostProps}
            aria-controls={panelId}
            aria-expanded={mounted && visible}
            aria-haspopup="dialog"
            aria-label={accessibleLabel}
            data-openpencil-slide-menu-trigger=""
            onClick={handleTriggerClick}
            onKeyDown={onKeyDown}
            ref={triggerRef}
            style={TRIGGER_AUTHORED_BUTTON_STYLE}
            tabIndex={tabIndex ?? 0}
            type="button"
          />
        </div>
      ) : (
        <button
          {...hostProps}
          aria-controls={panelId}
          aria-expanded={mounted && visible}
          aria-haspopup="dialog"
          aria-label={accessibleLabel}
          className={className}
          data-openpencil-slide-menu-trigger=""
          onClick={handleTriggerClick}
          onKeyDown={onKeyDown}
          ref={triggerRef}
          style={triggerStyle}
          tabIndex={tabIndex ?? 0}
          type="button"
        >
          <>
            {showTriggerIcon ? (
              <span aria-hidden="true" data-openpencil-slide-menu-trigger-icon="" style={TRIGGER_ICON_STYLE}>
                <span data-openpencil-slide-menu-trigger-icon-bar="" style={TRIGGER_ICON_BAR_STYLE} />
                <span data-openpencil-slide-menu-trigger-icon-bar="" style={TRIGGER_ICON_BAR_STYLE} />
                <span data-openpencil-slide-menu-trigger-icon-bar="" style={TRIGGER_ICON_BAR_STYLE} />
              </span>
            ) : null}
            {showTriggerLabel ? (
              <span data-openpencil-slide-menu-trigger-label="" style={TRIGGER_LABEL_STYLE}>
                {config.triggerLabel}
              </span>
            ) : null}
          </>
        </button>
      )}
      {portal}
    </>
  )
}
`

export function buildOpenPencilSlideMenuComponent(options?: ReactModuleRuntimeOptions): string {
  if (!options?.microfrontend) return SLIDE_MENU_RUNTIME
  return SLIDE_MENU_RUNTIME.replace(
    "import { createPortal } from 'react-dom'",
    "import { createPortal } from 'react-dom'\nimport { microfrontendPortalTarget } from './__microfrontend-context'"
  ).replace(
    '          document.body\n        )',
    '          microfrontendPortalTarget() ?? document.body\n        )'
  )
}

export const SLIDE_MENU_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: SLIDE_MENU_PLUGIN_ID,
  moduleType: SLIDE_MENU_MODULE_TYPE,
  componentName: 'OpenPencilSlideMenu',
  runtimePath: 'src/__openpencil_slide_menu.tsx',
  rootImportPath: './__openpencil_slide_menu',
  nestedImportPath: '../__openpencil_slide_menu',
  buildRuntime: buildOpenPencilSlideMenuComponent
})
