import { TABLE_MODULE_TYPE, TABLE_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter } from './types'

const TABLE_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import type { HTMLAttributes } from 'react'

export interface OpenPencilTableData {
  columns: readonly string[]
  rows: readonly (readonly string[])[]
}

export interface OpenPencilTableConfig {
  table: OpenPencilTableData
  showHeader: boolean
  striped: boolean
  borderColor: string
  headerBackground: string
  textColor: string
  fontSize: number
}

export interface OpenPencilTableProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilTableConfig
}

export default function OpenPencilTable({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilTableProps) {
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle =
    positionedByClass || positionedByStyle
      ? style
      : { ...style, position: 'relative' as const }
  const cellStyle = {
    border: '1px solid ' + config.borderColor,
    height: 'max(22px, 1.4em)',
    lineHeight: 1.4,
    padding: '0 0.7em',
    textAlign: 'start' as const,
    verticalAlign: 'top' as const
  }

  return (
    <div {...hostProps} className={className} data-openpencil-table="" style={hostStyle}>
      <div
        aria-label="Table scroll area"
        data-openpencil-table-scroll=""
        role="region"
        style={{ height: '100%', inset: 0, overflow: 'auto', position: 'absolute', width: '100%' }}
        tabIndex={0}
      >
        <table
          style={{
            borderCollapse: 'collapse',
            color: config.textColor,
            fontSize: config.fontSize,
            minWidth: '100%',
            width: 'max-content'
          }}
        >
          {config.showHeader ? (
            <thead style={{ background: config.headerBackground, position: 'sticky', top: 0, zIndex: 1 }}>
              <tr>
                {config.table.columns.map((column, columnIndex) => (
                  <th key={columnIndex} scope="col" style={cellStyle}>{column}</th>
                ))}
              </tr>
            </thead>
          ) : null}
          <tbody>
            {config.table.rows.map((row, rowIndex) => (
              <tr
                key={rowIndex}
                style={{
                  background:
                    config.striped && rowIndex % 2 === 1
                      ? '#F9FAFB'
                      : undefined
                }}
              >
                {config.table.columns.map((_, columnIndex) => (
                  <td key={columnIndex} style={cellStyle}>{row[columnIndex] ?? ''}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {children}
    </div>
  )
}
`

export function buildOpenPencilTableComponent(): string {
  return TABLE_RUNTIME
}

export const TABLE_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: TABLE_PLUGIN_ID,
  moduleType: TABLE_MODULE_TYPE,
  componentName: 'OpenPencilTable',
  runtimePath: 'src/__openpencil_table.tsx',
  rootImportPath: './__openpencil_table',
  nestedImportPath: '../__openpencil_table',
  buildRuntime: buildOpenPencilTableComponent
})
