/* eslint-disable max-lines -- the generated local-file runtime stays beside its adapter contract */
import { UPLOAD_BUTTON_MODULE_TYPE, UPLOAD_BUTTON_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

const UPLOAD_BUTTON_RUNTIME = `// Auto-generated by OpenPencil compiler. Do not edit by hand.
import {
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type ChangeEvent,
  type CSSProperties,
  type DragEvent as ReactDragEvent,
  type KeyboardEvent as ReactKeyboardEvent,
  type MouseEvent as ReactMouseEvent
} from 'react'
import { createPortal } from 'react-dom'

export interface OpenPencilUploadButtonConfig {
  triggerLabel: string
  showTriggerIcon: boolean
  showTriggerLabel: boolean
  accept: readonly string[]
  multiple: boolean
  maxFiles: number
  maxFileBytes: number
  allowDrop: boolean
  showFileList: boolean
  helperText: string
  buttonBackground: string
  buttonTextColor: string
  accentColor: string
  errorColor: string
}

export interface OpenPencilUploadButtonProps
  extends Omit<
    ButtonHTMLAttributes<HTMLButtonElement>,
    'onClick' | 'onKeyDown' | 'type'
  > {
  config: OpenPencilUploadButtonConfig
  onClick?: (event: ReactMouseEvent<HTMLButtonElement>) => void
  onKeyDown?: (event: ReactKeyboardEvent<HTMLButtonElement>) => void
}

interface SelectedLocalFile {
  id: number
  file: File
}

interface DropFiles {
  files: File[]
  ignoredItems: number
  rejectedDirectory: boolean
  rejectedNonFile: boolean
}

interface DetailsPosition {
  left: number
  ready: boolean
  top: number
  width: number
}

const VIEWPORT_INSET = 8
const DETAILS_GAP = 8
const MAX_INCOMING_FILES = 100
const MAX_ERROR_MESSAGES = 4
const MAX_DISPLAY_NAME_CODE_POINTS = 157

const ROOT_STYLE: CSSProperties = {
  background: 'transparent',
  border: 0,
  boxSizing: 'border-box',
  display: 'inline-block',
  minHeight: 44,
  minWidth: 44,
  overflow: 'visible',
  padding: 0
}
const TRIGGER_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  border: 0,
  borderRadius: 8,
  boxSizing: 'border-box',
  cursor: 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  gap: 8,
  height: '100%',
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: '0 14px',
  textAlign: 'center',
  touchAction: 'manipulation',
  width: '100%'
}
const AUTHORED_CONTENT_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'flex',
  inset: 0,
  justifyContent: 'center',
  overflow: 'hidden',
  pointerEvents: 'none',
  position: 'absolute'
}
const AUTHORED_BUTTON_STYLE: CSSProperties = {
  appearance: 'none',
  background: 'transparent',
  border: 0,
  color: 'inherit',
  cursor: 'pointer',
  inset: 0,
  outlineOffset: 2,
  padding: 0,
  position: 'absolute',
  touchAction: 'manipulation',
  zIndex: 1
}
const ICON_STYLE: CSSProperties = {
  display: 'inline-flex',
  flexShrink: 0,
  height: 18,
  width: 18
}
const LABEL_STYLE: CSSProperties = {
  color: 'inherit',
  lineHeight: 1.2,
  minWidth: 0,
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap'
}
const HIDDEN_INPUT_STYLE: CSSProperties = {
  clip: 'rect(0 0 0 0)',
  clipPath: 'inset(50%)',
  height: 1,
  margin: -1,
  overflow: 'hidden',
  padding: 0,
  position: 'absolute',
  whiteSpace: 'nowrap',
  width: 1
}
const DETAILS_STYLE: CSSProperties = {
  background: '#FFFFFF',
  border: '1px solid',
  borderRadius: 8,
  boxShadow: '0 8px 24px #0F172424',
  boxSizing: 'border-box',
  color: '#111827',
  display: 'grid',
  fontFamily: 'inherit',
  fontSize: 13,
  gap: 8,
  maxHeight: 'calc(100vh - 16px)',
  minWidth: 0,
  overflowY: 'auto',
  padding: 10,
  position: 'fixed',
  zIndex: 10
}
const FILE_LIST_STYLE: CSSProperties = {
  display: 'grid',
  gap: 6,
  listStyle: 'none',
  margin: 0,
  padding: 0
}
const FILE_ROW_STYLE: CSSProperties = {
  alignItems: 'center',
  display: 'grid',
  gap: 8,
  gridTemplateColumns: 'minmax(0, 1fr) auto auto',
  minHeight: 44
}
const REMOVE_STYLE: CSSProperties = {
  alignItems: 'center',
  appearance: 'none',
  background: 'transparent',
  border: '1px solid currentColor',
  borderRadius: 6,
  cursor: 'pointer',
  display: 'inline-flex',
  font: 'inherit',
  justifyContent: 'center',
  minHeight: 44,
  minWidth: 44,
  outlineOffset: 2,
  padding: '0 8px'
}

function fileNameTail(value: string): string {
  const boundedTail = value.slice(Math.max(0, value.length - 512))
  const separator = Math.max(boundedTail.lastIndexOf('/'), boundedTail.lastIndexOf('\\\\'))
  return boundedTail.slice(separator + 1) || 'Unnamed file'
}

function displayFileName(value: string): string {
  let result = ''
  let length = 0
  for (const character of fileNameTail(value)) {
    if (length >= MAX_DISPLAY_NAME_CODE_POINTS) return result + '...'
    const point = character.codePointAt(0) ?? 0
    const unsafe =
      point < 32 ||
      (point >= 127 && point <= 159) ||
      point === 0x061c ||
      point === 0x200e ||
      point === 0x200f ||
      (point >= 0x2028 && point <= 0x202e) ||
      (point >= 0x2066 && point <= 0x2069)
    result += unsafe ? '�' : character
    length += 1
  }
  return result
}

function formatBytes(value: number): string {
  if (value < 1024) return value + ' B'
  if (value < 1024 * 1024) return (value / 1024).toFixed(value < 10 * 1024 ? 1 : 0) + ' KB'
  return (value / (1024 * 1024)).toFixed(value < 10 * 1024 * 1024 ? 1 : 0) + ' MB'
}

function clamp(value: number, minimum: number, maximum: number): number {
  return Math.max(minimum, Math.min(value, maximum))
}

function matchesAccept(file: File, accept: readonly string[]): boolean {
  if (accept.length === 0) return true
  const name = fileNameTail(file.name)
  const mime = file.type.length <= 127 ? file.type.trim().toLowerCase() : ''
  return accept.some((rawToken) => {
    const token = rawToken.trim().toLowerCase()
    if (token.startsWith('.')) return name.slice(-token.length).toLowerCase() === token
    if (token.endsWith('/*')) return mime !== '' && mime.startsWith(token.slice(0, -1))
    return mime !== '' && mime === token
  })
}

function filesFromDrop(dataTransfer: DataTransfer): DropFiles {
  const result: DropFiles = {
    files: [],
    ignoredItems: 0,
    rejectedDirectory: false,
    rejectedNonFile: false
  }
  if (dataTransfer.items.length === 0) {
    const count = Math.min(dataTransfer.files.length, MAX_INCOMING_FILES)
    for (let index = 0; index < count; index += 1) {
      const file = dataTransfer.files[index]
      if (file) result.files.push(file)
    }
    result.ignoredItems = Math.max(0, dataTransfer.files.length - count)
    return result
  }
  const count = Math.min(dataTransfer.items.length, MAX_INCOMING_FILES)
  result.ignoredItems = Math.max(0, dataTransfer.items.length - count)
  for (let index = 0; index < count; index += 1) {
    const item = dataTransfer.items[index]
    if (!item) continue
    if (item.kind !== 'file') {
      result.rejectedNonFile = true
      continue
    }
    const candidate = item as DataTransferItem & {
      webkitGetAsEntry?: () => { isDirectory: boolean; isFile: boolean } | null
    }
    const entry = candidate.webkitGetAsEntry?.()
    if (entry?.isDirectory) {
      result.rejectedDirectory = true
      continue
    }
    const file = item.getAsFile()
    if (!file || (entry && !entry.isFile)) {
      result.rejectedNonFile = true
      continue
    }
    result.files.push(file)
  }
  return result
}

export default function OpenPencilUploadButton({
  config,
  children,
  className,
  disabled,
  onClick,
  onKeyDown,
  style,
  tabIndex,
  ...hostProps
}: OpenPencilUploadButtonProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const detailsRef = useRef<HTMLDivElement>(null)
  const removeRefs = useRef(new Map<number, HTMLButtonElement>())
  const dragDepthRef = useRef(0)
  const focusAfterSelectionRef = useRef<number | 'trigger' | null>(null)
  const nextFileIdRef = useRef(1)
  const selectedRef = useRef<SelectedLocalFile[]>([])
  const [selected, setSelected] = useState<SelectedLocalFile[]>([])
  const [error, setError] = useState('')
  const [dragging, setDragging] = useState(false)
  const [detailsPosition, setDetailsPosition] = useState<DetailsPosition>({
    left: -10000,
    ready: false,
    top: -10000,
    width: 220
  })
  const [portalReady, setPortalReady] = useState(false)
  const [reducedMotion, setReducedMotion] = useState(false)
  const baseId = useId().replaceAll(':', '')
  const helperId = baseId + '-helper'
  const statusId = baseId + '-status'
  const errorId = baseId + '-error'
  const authoredLabelId = baseId + '-authored-label'
  const authoredFallbackId = baseId + '-authored-fallback'
  const hasAuthoredTrigger = children !== undefined && children !== null
  const hasDetails = config.helperText !== '' || selected.length > 0 || error !== ''

  useEffect(() => {
    setPortalReady(true)
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const sync = () => setReducedMotion(query.matches)
    sync()
    query.addEventListener('change', sync)
    return () => query.removeEventListener('change', sync)
  }, [])

  useLayoutEffect(() => {
    const target = focusAfterSelectionRef.current
    if (target === null) return
    focusAfterSelectionRef.current = null
    if (target === 'trigger') {
      triggerRef.current?.focus({ preventScroll: true })
      return
    }
    const remove = removeRefs.current.get(target)
    if (remove) remove.focus({ preventScroll: true })
    else triggerRef.current?.focus({ preventScroll: true })
  }, [selected])

  const processFiles = useCallback((
    files: ArrayLike<File>,
    dropMessages: readonly string[] = [],
    additionalUnchecked = 0
  ) => {
    const accepted: File[] = []
    const messages = dropMessages.slice(0, MAX_ERROR_MESSAGES)
    let suppressedRejections = Math.max(0, dropMessages.length - messages.length)
    const addRejection = (message: string) => {
      if (messages.length < MAX_ERROR_MESSAGES) messages.push(message)
      else suppressedRejections += 1
    }
    const candidateCount = Math.min(files.length, MAX_INCOMING_FILES)
    for (let index = 0; index < candidateCount; index += 1) {
      const file = files[index]
      if (!file) continue
      const name = displayFileName(file.name)
      if (!matchesAccept(file, config.accept)) {
        addRejection('“' + name + '” is not an accepted file type.')
      } else if (file.size > config.maxFileBytes) {
        addRejection(
          '“' + name + '” exceeds the ' + formatBytes(config.maxFileBytes) + ' limit.'
        )
      } else {
        accepted.push(file)
      }
    }
    const summaries: string[] = []
    const current = selectedRef.current
    let next = current
    if (!config.multiple) {
      if (accepted.length > 1) summaries.push('Choose one file at a time.')
      const first = accepted[0]
      if (first) next = [{ id: nextFileIdRef.current++, file: first }]
    } else {
      const available = Math.max(0, config.maxFiles - current.length)
      if (accepted.length > available) {
        summaries.push('You can select up to ' + config.maxFiles + ' files.')
      }
      next = [
        ...current,
        ...accepted.slice(0, available).map((file) => ({
          id: nextFileIdRef.current++,
          file
        }))
      ]
    }
    if (suppressedRejections > 0) {
      summaries.push(suppressedRejections + ' more files were rejected.')
    }
    const unchecked = Math.max(0, files.length - candidateCount) + additionalUnchecked
    if (unchecked > 0) summaries.push(unchecked + ' additional files were not checked.')
    selectedRef.current = next
    setSelected(next)
    setError([...messages, ...summaries].join(' '))
  }, [config.accept, config.maxFileBytes, config.maxFiles, config.multiple])

  const openPicker = () => {
    if (disabled) return
    setError('')
    const input = inputRef.current
    if (!input) return
    input.value = ''
    input.click()
  }

  const handleClick = (event: ReactMouseEvent<HTMLButtonElement>) => {
    onClick?.(event)
    if (!event.defaultPrevented) openPicker()
  }

  const handleKeyDown = (event: ReactKeyboardEvent<HTMLButtonElement>) => {
    onKeyDown?.(event)
  }

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    processFiles(event.currentTarget.files ?? [])
    event.currentTarget.value = ''
    window.requestAnimationFrame(() => triggerRef.current?.focus({ preventScroll: true }))
  }

  const isFileDrag = (event: ReactDragEvent<HTMLDivElement>): boolean =>
    event.dataTransfer.types.includes('Files')

  const canProcessFileDrop = (event: ReactDragEvent<HTMLDivElement>): boolean =>
    isFileDrag(event) && config.allowDrop && !disabled

  const handleDragEnter = (event: ReactDragEvent<HTMLDivElement>) => {
    if (!isFileDrag(event)) return
    event.preventDefault()
    if (!canProcessFileDrop(event)) return
    dragDepthRef.current += 1
    setDragging(true)
  }

  const handleDragOver = (event: ReactDragEvent<HTMLDivElement>) => {
    if (!isFileDrag(event)) return
    event.preventDefault()
    event.dataTransfer.dropEffect = canProcessFileDrop(event) ? 'copy' : 'none'
  }

  const handleDragLeave = (event: ReactDragEvent<HTMLDivElement>) => {
    if (!isFileDrag(event)) return
    event.preventDefault()
    if (!canProcessFileDrop(event)) return
    dragDepthRef.current = Math.max(0, dragDepthRef.current - 1)
    if (dragDepthRef.current === 0) setDragging(false)
  }

  const handleDrop = (event: ReactDragEvent<HTMLDivElement>) => {
    if (!isFileDrag(event)) return
    event.preventDefault()
    dragDepthRef.current = 0
    setDragging(false)
    if (!canProcessFileDrop(event)) return
    const dropped = filesFromDrop(event.dataTransfer)
    const messages: string[] = []
    if (dropped.rejectedDirectory) messages.push('Folders are not supported.')
    if (dropped.rejectedNonFile) messages.push('Only local files can be selected.')
    if (dropped.files.length === 0 && messages.length === 0) messages.push('No local files were found.')
    processFiles(dropped.files, messages, dropped.ignoredItems)
    window.requestAnimationFrame(() => triggerRef.current?.focus({ preventScroll: true }))
  }

  const removeFile = (id: number) => {
    setError('')
    const current = selectedRef.current
    const index = current.findIndex((entry) => entry.id === id)
    if (index < 0) return
    const remaining = current.filter((entry) => entry.id !== id)
    selectedRef.current = remaining
    const focusId = remaining[Math.min(index, Math.max(0, remaining.length - 1))]?.id
    focusAfterSelectionRef.current = focusId ?? 'trigger'
    setSelected(remaining)
  }

  const clearLocalSelection = () => {
    selectedRef.current = []
    focusAfterSelectionRef.current = 'trigger'
    setSelected([])
    setError('')
  }

  const positionDetails = useCallback(() => {
    const trigger = triggerRef.current
    const details = detailsRef.current
    if (!trigger || !details) return
    const triggerRect = trigger.getBoundingClientRect()
    const availableWidth = Math.max(1, window.innerWidth - VIEWPORT_INSET * 2)
    const width = Math.min(Math.max(triggerRect.width, 220), availableWidth)
    details.style.width = width + 'px'
    const height = details.offsetHeight
    const below = triggerRect.bottom + DETAILS_GAP
    const above = triggerRect.top - DETAILS_GAP - height
    const idealTop = below + height <= window.innerHeight - VIEWPORT_INSET ? below : above
    setDetailsPosition({
      left: clamp(
        triggerRect.left,
        VIEWPORT_INSET,
        Math.max(VIEWPORT_INSET, window.innerWidth - width - VIEWPORT_INSET)
      ),
      ready: true,
      top: clamp(
        idealTop,
        VIEWPORT_INSET,
        Math.max(VIEWPORT_INSET, window.innerHeight - height - VIEWPORT_INSET)
      ),
      width
    })
  }, [])

  useLayoutEffect(() => {
    if (!portalReady) return
    if (!hasDetails) {
      setDetailsPosition((position) =>
        position.ready ? { ...position, ready: false } : position
      )
      return
    }
    positionDetails()
  }, [error, hasDetails, portalReady, positionDetails, selected])

  useEffect(() => {
    if (!portalReady || !hasDetails) return
    window.addEventListener('resize', positionDetails)
    window.addEventListener('scroll', positionDetails, true)
    return () => {
      window.removeEventListener('resize', positionDetails)
      window.removeEventListener('scroll', positionDetails, true)
    }
  }, [hasDetails, portalReady, positionDetails])

  const describedBy = [config.helperText ? helperId : '', selected.length > 0 ? statusId : '', error ? errorId : '']
    .filter(Boolean)
    .join(' ') || undefined
  const rootStyle: CSSProperties = { ...ROOT_STYLE, ...style }
  const triggerStyle: CSSProperties = {
    ...TRIGGER_STYLE,
    background: config.buttonBackground,
    boxShadow: dragging ? '0 0 0 3px ' + config.accentColor + '55' : undefined,
    color: config.buttonTextColor,
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.55 : 1,
    transition: reducedMotion ? 'none' : 'box-shadow 140ms ease, opacity 140ms ease'
  }
  const sharedTriggerProps = {
    'aria-describedby': describedBy,
    'aria-label': config.triggerLabel,
    'data-openpencil-upload-trigger': '',
    disabled,
    onClick: handleClick,
    onKeyDown: handleKeyDown,
    ref: triggerRef,
    tabIndex,
    type: 'button' as const
  }

  return (
    <div
      {...hostProps}
      className={className}
      data-dragging={dragging ? 'true' : 'false'}
      data-openpencil-upload-owner={baseId}
      data-openpencil-upload-root=""
      onDragEnter={handleDragEnter}
      onDragLeave={handleDragLeave}
      onDragOver={handleDragOver}
      onDrop={handleDrop}
      style={rootStyle}
    >
      <div data-openpencil-upload-anchor="" style={{ height: '100%', position: 'relative', width: '100%' }}>
        <input
          accept={config.accept.length > 0 ? config.accept.join(',') : undefined}
          aria-hidden="true"
          data-openpencil-upload-input=""
          disabled={disabled}
          multiple={config.multiple}
          onChange={handleChange}
          ref={inputRef}
          style={HIDDEN_INPUT_STYLE}
          tabIndex={-1}
          type="file"
        />
        {hasAuthoredTrigger ? (
          <div data-openpencil-upload-authored-host="" style={{ ...triggerStyle, position: 'relative' }}>
            <div aria-hidden="true" data-openpencil-upload-trigger-authored="" id={authoredLabelId} inert style={AUTHORED_CONTENT_STYLE}>
              {children}
            </div>
            <span id={authoredFallbackId} style={HIDDEN_INPUT_STYLE}>{config.triggerLabel}</span>
            <button
              {...sharedTriggerProps}
              aria-labelledby={authoredLabelId + ' ' + authoredFallbackId}
              style={AUTHORED_BUTTON_STYLE}
            />
          </div>
        ) : (
          <button {...sharedTriggerProps} style={triggerStyle}>
            {config.showTriggerIcon ? (
              <svg aria-hidden="true" data-openpencil-upload-trigger-icon="" focusable="false" style={ICON_STYLE} viewBox="0 0 24 24">
                <path d="M12 16V4M7 9l5-5 5 5M5 15v4h14v-4" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" />
              </svg>
            ) : null}
            {config.showTriggerLabel ? (
              <span data-openpencil-upload-trigger-label="" style={LABEL_STYLE}>{config.triggerLabel}</span>
            ) : null}
          </button>
        )}
        {portalReady && hasDetails ? createPortal(
          <div
            data-openpencil-upload-details=""
            data-openpencil-upload-owner={baseId}
            ref={detailsRef}
            style={{
              ...DETAILS_STYLE,
              borderColor: error ? config.errorColor : config.accentColor,
              left: detailsPosition.left,
              top: detailsPosition.top,
              visibility: detailsPosition.ready ? 'visible' : 'hidden',
              width: detailsPosition.width
            }}
          >
            {config.helperText ? <div id={helperId}>{config.helperText}</div> : null}
            {selected.length > 0 ? (
              <div aria-atomic="true" aria-live="polite" data-openpencil-upload-status="" id={statusId} role="status">
                {selected.length} {selected.length === 1 ? 'file' : 'files'} selected locally — not uploaded.
              </div>
            ) : null}
            {error ? (
              <div aria-atomic="true" aria-live="assertive" data-openpencil-upload-error="" id={errorId} role="alert" style={{ color: config.errorColor }}>
                {error}
              </div>
            ) : null}
            {config.showFileList && selected.length > 0 ? (
              <ul aria-label="Files selected locally" data-openpencil-upload-file-list="" style={FILE_LIST_STYLE}>
                {selected.map((entry) => {
                  const name = displayFileName(entry.file.name)
                  return (
                    <li data-openpencil-upload-file="" key={entry.id} style={FILE_ROW_STYLE}>
                      <span style={{ minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={name}>{name}</span>
                      <span aria-label={formatBytes(entry.file.size)}>{formatBytes(entry.file.size)}</span>
                      <button
                        aria-label={'Remove ' + name + ' from local selection'}
                        data-openpencil-upload-remove=""
                        onClick={() => removeFile(entry.id)}
                        ref={(element) => {
                          if (element) removeRefs.current.set(entry.id, element)
                          else removeRefs.current.delete(entry.id)
                        }}
                        style={{ ...REMOVE_STYLE, color: config.errorColor }}
                        type="button"
                      >
                        Remove
                      </button>
                    </li>
                  )
                })}
              </ul>
            ) : null}
            {!config.showFileList && selected.length > 0 ? (
              <button
                data-openpencil-upload-clear=""
                onClick={clearLocalSelection}
                style={{ ...REMOVE_STYLE, color: config.accentColor, width: '100%' }}
                type="button"
              >
                Clear local selection
              </button>
            ) : null}
          </div>,
          document.body
        ) : null}
      </div>
    </div>
  )
}
`

export function buildOpenPencilUploadButtonComponent(options?: ReactModuleRuntimeOptions): string {
  if (!options?.microfrontend) return UPLOAD_BUTTON_RUNTIME
  return UPLOAD_BUTTON_RUNTIME.replace(
    "import { createPortal } from 'react-dom'",
    "import { createPortal } from 'react-dom'\nimport { microfrontendPortalTarget } from './__microfrontend-context'"
  ).replace(
    '          document.body\n        )',
    '          microfrontendPortalTarget() ?? document.body\n        )'
  )
}

export const UPLOAD_BUTTON_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: UPLOAD_BUTTON_PLUGIN_ID,
  moduleType: UPLOAD_BUTTON_MODULE_TYPE,
  componentName: 'OpenPencilUploadButton',
  runtimePath: 'src/__openpencil_upload_button.tsx',
  rootImportPath: './__openpencil_upload_button',
  nestedImportPath: '../__openpencil_upload_button',
  buildRuntime: buildOpenPencilUploadButtonComponent
})
