import { VIDEO_MODULE_TYPE, VIDEO_PLUGIN_ID } from '@open-pencil/core/plugins'

import type { ReactModuleAdapter, ReactModuleRuntimeOptions } from './types'

export function buildOpenPencilVideoComponent(options: ReactModuleRuntimeOptions): string {
  const previewStateImport = options.devMode ? "import { useState } from 'react'\n" : ''
  const networkActivation = options.devMode
    ? '  const [networkActivated, setNetworkActivated] = useState(false)\n'
    : ''
  const preloadCalculation = options.devMode
    ? `  const preload =
    !networkActivated || config.src === '' ? 'none' : config.autoplay ? 'auto' : 'metadata'`
    : `  const preload = config.src === '' ? 'none' : config.autoplay ? 'auto' : 'metadata'`
  const autoplayExpression = options.devMode
    ? 'networkActivated && config.autoplay'
    : 'config.autoplay'
  const posterExpression = options.devMode
    ? 'networkActivated ? config.poster || undefined : undefined'
    : 'config.poster || undefined'
  const sourceExpression = options.devMode
    ? 'networkActivated ? config.src || undefined : undefined'
    : 'config.src || undefined'
  const previewActivationButton = options.devMode
    ? `
      {!networkActivated && (config.src !== '' || config.poster !== '') ? (
        <button
          data-openpencil-video-load=""
          onClick={() => setNetworkActivated(true)}
          style={{
            background: '#0F172AE0',
            border: '1px solid #FFFFFFB8',
            borderRadius: 6,
            color: '#FFFFFF',
            cursor: 'pointer',
            font: '600 14px/1 system-ui, sans-serif',
            left: '50%',
            padding: '10px 14px',
            position: 'absolute',
            top: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 2147483647
          }}
          type="button"
        >
          Load video preview
        </button>
      ) : null}`
    : ''

  return `// Auto-generated by OpenPencil compiler. Do not edit by hand.
${previewStateImport}import type { HTMLAttributes } from 'react'

export interface OpenPencilVideoConfig {
  src: string
  poster: string
  controls: boolean
  autoplay: boolean
  muted: boolean
  loop: boolean
  fit: 'contain' | 'cover' | 'fill'
}

export interface OpenPencilVideoProps extends HTMLAttributes<HTMLDivElement> {
  config: OpenPencilVideoConfig
}

export default function OpenPencilVideo({
  config,
  className,
  children,
  style,
  ...hostProps
}: OpenPencilVideoProps) {
  const positionedByClass = className
    ?.split(' ')
    .some((token) => ['absolute', 'fixed', 'relative', 'sticky'].includes(token))
  const positionedByStyle = style?.position !== undefined && style.position !== 'static'
  const hostStyle =
    positionedByClass || positionedByStyle
      ? style
      : { ...style, position: 'relative' as const }
${networkActivation}${preloadCalculation}

  return (
    <div {...hostProps} className={className} data-openpencil-video="" style={hostStyle}>
      <video
        aria-label="Video"
        autoPlay={${autoplayExpression}}
        controls={config.controls}
        loop={config.loop}
        muted={config.muted}
        playsInline
        poster={${posterExpression}}
        preload={preload}
        src={${sourceExpression}}
        style={{
          height: '100%',
          inset: 0,
          objectFit: config.fit,
          position: 'absolute',
          width: '100%'
        }}
      />
      {children}
${previewActivationButton}
    </div>
  )
}
`
}

export const VIDEO_REACT_MODULE_ADAPTER: ReactModuleAdapter = Object.freeze({
  pluginId: VIDEO_PLUGIN_ID,
  moduleType: VIDEO_MODULE_TYPE,
  componentName: 'OpenPencilVideo',
  runtimePath: 'src/__openpencil_video.tsx',
  rootImportPath: './__openpencil_video',
  nestedImportPath: '../__openpencil_video',
  buildRuntime: buildOpenPencilVideoComponent
})
