/* eslint-disable max-lines -- the one-shot DDL and exact catalog postconditions form one review boundary */
import {
  BACKEND_AUTOMATION_OUTBOX_MAX_PUBLISH_ATTEMPTS,
  BACKEND_AUTOMATION_OUTBOX_MAX_REVISION,
  BACKEND_AUTOMATION_OUTBOX_MAX_ROW_VERSION
} from '@open-pencil/lowcode/backend'

const OUTBOX_MARKER_FORMAT = 'openpencil.supabase-automation-transactional-outbox.v1'
const BINDINGS_TABLE = 'outbox_bindings'
const REVISIONS_TABLE = 'outbox_revisions'
const HEADS_TABLE = 'outbox_heads'
const ATTEMPT_VALIDATOR_FUNCTION = 'outbox_attempt_ids_are_valid'
const MUTATION_GUARD_FUNCTION = 'reject_outbox_immutable_mutation'
const BINDINGS_MUTATION_GUARD_TRIGGER = 'outbox_bindings_immutable'
const REVISIONS_MUTATION_GUARD_TRIGGER = 'outbox_revisions_immutable'

const BINDING_CONSTRAINTS = Object.freeze([
  ['outbox_bindings_pkey', 'p'],
  ['outbox_bindings_transaction_key', 'u'],
  ['outbox_bindings_identifiers_check', 'c'],
  ['outbox_bindings_digests_check', 'c'],
  ['outbox_bindings_row_message_check', 'c']
] as const)

const REVISION_CONSTRAINTS = Object.freeze([
  ['outbox_revisions_pkey', 'p'],
  ['outbox_revisions_head_key', 'u'],
  ['outbox_revisions_binding_fkey', 'f'],
  ['outbox_revisions_previous_fkey', 'f'],
  ['outbox_revisions_identifiers_check', 'c'],
  ['outbox_revisions_digests_check', 'c'],
  ['outbox_revisions_chain_check', 'c'],
  ['outbox_revisions_attempts_check', 'c'],
  ['outbox_revisions_state_evidence_check', 'c'],
  ['outbox_revisions_transition_check', 'c'],
  ['outbox_revisions_timestamp_check', 'c']
] as const)

const HEAD_CONSTRAINTS = Object.freeze([
  ['outbox_heads_pkey', 'p'],
  ['outbox_heads_binding_fkey', 'f'],
  ['outbox_heads_revision_fkey', 'f'],
  ['outbox_heads_identifier_check', 'c'],
  ['outbox_heads_digests_check', 'c'],
  ['outbox_heads_revision_attempt_check', 'c'],
  ['outbox_heads_transition_check', 'c'],
  ['outbox_heads_timestamp_check', 'c']
] as const)

const INDEXES = Object.freeze([
  ['outbox_bindings_pkey', BINDINGS_TABLE, true, true, [1]],
  ['outbox_bindings_transaction_key', BINDINGS_TABLE, false, true, [1, 3, 12, 13]],
  ['outbox_bindings_event_idx', BINDINGS_TABLE, false, false, [9, 7, 1]],
  ['outbox_revisions_pkey', REVISIONS_TABLE, true, true, [1, 2]],
  [
    'outbox_revisions_head_key',
    REVISIONS_TABLE,
    false,
    true,
    [1, 2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 34, 35, 36, 37]
  ],
  ['outbox_revisions_transition_evidence_uidx', REVISIONS_TABLE, false, true, [1, 25]],
  ['outbox_heads_pkey', HEADS_TABLE, true, true, [1]],
  ['outbox_heads_state_idx', HEADS_TABLE, false, false, [10, 11, 1]]
] as const)

const IDENTIFIER_PATTERN = '^[A-Za-z0-9][A-Za-z0-9._:/@-]{0,255}$'
const DIGEST_PATTERN = '^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$'
// Preserve nanosecond ordering as a validated Supabase text projection; this is not evidence that
// an upstream variable-fraction timestamp had byte-identical source spelling.
const TIMESTAMP_PATTERN =
  '^[0-9]{4}-(0[1-9]|1[0-2])-([0-2][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\\.[0-9]{9}Z$'

function literal(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

function generatedIdentifier(value: string, path: string): string {
  if (!/^[a-z][a-z0-9_-]{0,60}$/u.test(value)) {
    throw new TypeError(`${path} is not a bounded generated PostgreSQL identifier.`)
  }
  return value
}

function identifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`
}

function qualified(schemaName: string, objectName: string): string {
  return `${identifier(schemaName)}.${identifier(objectName)}`
}

function markerPrefix(applicationObjectKey: string): string {
  return `${OUTBOX_MARKER_FORMAT};application=${applicationObjectKey};`
}

function marker(applicationObjectKey: string, object: string): string {
  return `${markerPrefix(applicationObjectKey)}object=${object}`
}

export function supabaseAutomationTransactionalOutboxSchemaNameV2(
  applicationObjectKey: string
): string {
  return generatedIdentifier(
    `op_automation_outbox_${applicationObjectKey}`,
    '$.supabaseAutomations.transactionalOutbox.schemaName'
  )
}

function inventoryPreflight(applicationObjectKey: string, schemaName: string): readonly string[] {
  const prefix = markerPrefix(applicationObjectKey)
  return [
    'DO $openpencil_transactional_outbox_inventory$',
    'BEGIN',
    `  IF "pg_catalog"."to_regnamespace"(${literal(identifier(schemaName))}) IS NOT NULL THEN`,
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil refuses to adopt or replace a pre-existing transactional outbox schema.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_description" AS "prior_outbox_marker"',
    `    WHERE LEFT("prior_outbox_marker"."description", ${prefix.length}) = ${literal(prefix)}`,
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil found a previously generated transactional outbox; retirement or replacement requires explicit approval and a fresh inspected inventory.';",
    '  END IF;',
    'END',
    '$openpencil_transactional_outbox_inventory$;'
  ]
}

function attemptValidatorDDL(schemaName: string): readonly string[] {
  const validator = qualified(schemaName, ATTEMPT_VALIDATOR_FUNCTION)
  return [
    `CREATE FUNCTION ${validator}("attempt_ids" text[])`,
    'RETURNS boolean',
    'LANGUAGE plpgsql',
    'IMMUTABLE',
    'STRICT',
    'PARALLEL SAFE',
    'SECURITY INVOKER',
    'SET search_path = pg_catalog',
    'AS $openpencil_outbox_attempt_validator$',
    'DECLARE',
    '  candidate text;',
    '  seen_attempt_ids text[] := ARRAY[]::text[];',
    'BEGIN',
    '  IF "pg_catalog"."array_ndims"("attempt_ids") IS DISTINCT FROM 1',
    '    OR "pg_catalog"."array_lower"("attempt_ids", 1) IS DISTINCT FROM 1',
    '    OR "pg_catalog"."cardinality"("attempt_ids") NOT BETWEEN 1 AND ' +
      BACKEND_AUTOMATION_OUTBOX_MAX_PUBLISH_ATTEMPTS,
    '  THEN',
    '    RETURN FALSE;',
    '  END IF;',
    '  FOREACH candidate IN ARRAY "attempt_ids" LOOP',
    `    IF candidate IS NULL OR candidate !~ ${literal(IDENTIFIER_PATTERN)}`,
    '      OR candidate = ANY(seen_attempt_ids) THEN',
    '      RETURN FALSE;',
    '    END IF;',
    '    seen_attempt_ids := "pg_catalog"."array_append"(seen_attempt_ids, candidate);',
    '  END LOOP;',
    '  RETURN TRUE;',
    'END',
    '$openpencil_outbox_attempt_validator$;'
  ]
}

function bindingsTableDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  return [
    `CREATE TABLE ${bindings} (`,
    '  "outbox_id" text NOT NULL,',
    '  "business_transaction_id" text NOT NULL,',
    '  "business_transaction_digest" text NOT NULL,',
    '  "entity_id" text NOT NULL,',
    '  "row_id_digest" text NOT NULL,',
    '  "row_version" bigint NOT NULL,',
    '  "event_id" text NOT NULL,',
    '  "event_digest" text NOT NULL,',
    '  "queue_id" text NOT NULL,',
    '  "message_envelope_digest" text NOT NULL,',
    '  "idempotency_key_digest" text NOT NULL,',
    '  "message_enqueued_at" text NOT NULL,',
    '  "message_retention_deadline" text NOT NULL,',
    '  CONSTRAINT "outbox_bindings_pkey" PRIMARY KEY ("outbox_id"),',
    '  CONSTRAINT "outbox_bindings_transaction_key"',
    '    UNIQUE (',
    '      "outbox_id", "business_transaction_digest",',
    '      "message_enqueued_at", "message_retention_deadline"',
    '    ),',
    '  CONSTRAINT "outbox_bindings_identifiers_check" CHECK (',
    `    "outbox_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    `    AND "business_transaction_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    `    AND "entity_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    `    AND "event_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    `    AND "queue_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    '  ),',
    '  CONSTRAINT "outbox_bindings_digests_check" CHECK (',
    `    "business_transaction_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "row_id_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "event_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "message_envelope_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "idempotency_key_digest" ~ ${literal(DIGEST_PATTERN)}`,
    '  ),',
    '  CONSTRAINT "outbox_bindings_row_message_check" CHECK (',
    `    "row_version" BETWEEN 0 AND ${BACKEND_AUTOMATION_OUTBOX_MAX_ROW_VERSION}`,
    `    AND "message_enqueued_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("message_enqueued_at"::timestamptz)',
    `    AND "message_retention_deadline" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("message_retention_deadline"::timestamptz)',
    '    AND "message_retention_deadline" > "message_enqueued_at"',
    '  )',
    ') USING heap;'
  ]
}

function revisionsTableDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const validator = qualified(schemaName, ATTEMPT_VALIDATOR_FUNCTION)
  return [
    `CREATE TABLE ${revisions} (`,
    '  "outbox_id" text NOT NULL,',
    '  "revision" bigint NOT NULL,',
    '  "expected_revision" bigint,',
    '  "expected_head_digest" text,',
    '  "previous_record_digest" text,',
    '  "expected_publish_attempt_ids" text[],',
    '  "expected_current_publish_attempt_id" text,',
    '  "expected_publish_attempt_ordinal" smallint,',
    '  "expected_state" text,',
    '  "expected_recorded_at" text,',
    '  "expected_transition_evidence_digest" text,',
    '  "expected_publish_confirmation_evidence_digest" text,',
    '  "expected_known_not_published_evidence_digest" text,',
    '  "expected_delivery_evidence_digest" text,',
    '  "expected_reconciliation_evidence_digest" text,',
    '  "record_digest" text NOT NULL,',
    '  "business_transaction_digest" text NOT NULL,',
    '  "message_enqueued_at" text NOT NULL,',
    '  "message_retention_deadline" text NOT NULL,',
    '  "publish_attempt_ids" text[] NOT NULL,',
    '  "current_publish_attempt_id" text NOT NULL,',
    '  "publish_attempt_ordinal" smallint NOT NULL,',
    '  "state" text NOT NULL,',
    '  "recorded_at" text NOT NULL,',
    '  "transition_evidence_digest" text NOT NULL,',
    '  "publish_confirmation_evidence_digest" text,',
    '  "known_not_published_evidence_digest" text,',
    '  "delivery_evidence_digest" text,',
    '  "reconciliation_evidence_digest" text,',
    '  "expected_publish_confirmation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("expected_publish_confirmation_evidence_digest", \'-\')) STORED,',
    '  "expected_known_not_published_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("expected_known_not_published_evidence_digest", \'-\')) STORED,',
    '  "expected_delivery_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("expected_delivery_evidence_digest", \'-\')) STORED,',
    '  "expected_reconciliation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("expected_reconciliation_evidence_digest", \'-\')) STORED,',
    '  "publish_confirmation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("publish_confirmation_evidence_digest", \'-\')) STORED,',
    '  "known_not_published_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("known_not_published_evidence_digest", \'-\')) STORED,',
    '  "delivery_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("delivery_evidence_digest", \'-\')) STORED,',
    '  "reconciliation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("reconciliation_evidence_digest", \'-\')) STORED,',
    '  CONSTRAINT "outbox_revisions_pkey" PRIMARY KEY ("outbox_id", "revision"),',
    '  CONSTRAINT "outbox_revisions_head_key" UNIQUE (',
    '    "outbox_id", "revision", "record_digest",',
    '    "business_transaction_digest", "message_enqueued_at",',
    '    "message_retention_deadline", "publish_attempt_ids",',
    '    "current_publish_attempt_id", "publish_attempt_ordinal",',
    '    "state", "recorded_at", "transition_evidence_digest",',
    '    "publish_confirmation_evidence_token", "known_not_published_evidence_token",',
    '    "delivery_evidence_token", "reconciliation_evidence_token"',
    '  ),',
    '  CONSTRAINT "outbox_revisions_binding_fkey" FOREIGN KEY (',
    '    "outbox_id", "business_transaction_digest",',
    '    "message_enqueued_at", "message_retention_deadline"',
    `  ) REFERENCES ${bindings} (`,
    '    "outbox_id", "business_transaction_digest",',
    '    "message_enqueued_at", "message_retention_deadline"',
    '  ) MATCH FULL DEFERRABLE INITIALLY DEFERRED,',
    '  CONSTRAINT "outbox_revisions_previous_fkey" FOREIGN KEY (',
    '    "outbox_id", "expected_revision", "expected_head_digest",',
    '    "business_transaction_digest", "message_enqueued_at",',
    '    "message_retention_deadline",',
    '    "expected_publish_attempt_ids", "expected_current_publish_attempt_id",',
    '    "expected_publish_attempt_ordinal",',
    '    "expected_state", "expected_recorded_at", "expected_transition_evidence_digest",',
    '    "expected_publish_confirmation_evidence_token",',
    '    "expected_known_not_published_evidence_token",',
    '    "expected_delivery_evidence_token", "expected_reconciliation_evidence_token"',
    `  ) REFERENCES ${revisions} (`,
    '    "outbox_id", "revision", "record_digest",',
    '    "business_transaction_digest", "message_enqueued_at",',
    '    "message_retention_deadline", "publish_attempt_ids",',
    '    "current_publish_attempt_id", "publish_attempt_ordinal",',
    '    "state", "recorded_at", "transition_evidence_digest",',
    '    "publish_confirmation_evidence_token", "known_not_published_evidence_token",',
    '    "delivery_evidence_token", "reconciliation_evidence_token"',
    '  ) MATCH SIMPLE DEFERRABLE INITIALLY DEFERRED,',
    '  CONSTRAINT "outbox_revisions_identifiers_check" CHECK (',
    `    "current_publish_attempt_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    '    AND ("expected_current_publish_attempt_id" IS NULL',
    `      OR "expected_current_publish_attempt_id" ~ ${literal(IDENTIFIER_PATTERN)})`,
    '  ),',
    '  CONSTRAINT "outbox_revisions_digests_check" CHECK (',
    `    "record_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "business_transaction_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "transition_evidence_digest" ~ ${literal(DIGEST_PATTERN)}`,
    '    AND ("expected_head_digest" IS NULL',
    `      OR "expected_head_digest" ~ ${literal(DIGEST_PATTERN)})`,
    '    AND ("previous_record_digest" IS NULL',
    `      OR "previous_record_digest" ~ ${literal(DIGEST_PATTERN)})`,
    '    AND ("expected_transition_evidence_digest" IS NULL',
    `      OR "expected_transition_evidence_digest" ~ ${literal(DIGEST_PATTERN)})`,
    ...[
      'expected_publish_confirmation_evidence_digest',
      'expected_known_not_published_evidence_digest',
      'expected_delivery_evidence_digest',
      'expected_reconciliation_evidence_digest',
      'publish_confirmation_evidence_digest',
      'known_not_published_evidence_digest',
      'delivery_evidence_digest',
      'reconciliation_evidence_digest'
    ].flatMap((column, index, columns) => [
      `    AND ("${column}" IS NULL`,
      `      OR "${column}" ~ ${literal(DIGEST_PATTERN)})${index + 1 === columns.length ? '' : ''}`
    ]),
    '  ),',
    '  CONSTRAINT "outbox_revisions_chain_check" CHECK (',
    '    (',
    '      "revision" = 0',
    '      AND "expected_revision" IS NULL',
    '      AND "expected_head_digest" IS NULL',
    '      AND "previous_record_digest" IS NULL',
    '      AND "expected_publish_attempt_ids" IS NULL',
    '      AND "expected_current_publish_attempt_id" IS NULL',
    '      AND "expected_publish_attempt_ordinal" IS NULL',
    '      AND "expected_state" IS NULL',
    '      AND "expected_recorded_at" IS NULL',
    '      AND "expected_transition_evidence_digest" IS NULL',
    '      AND "expected_publish_confirmation_evidence_digest" IS NULL',
    '      AND "expected_known_not_published_evidence_digest" IS NULL',
    '      AND "expected_delivery_evidence_digest" IS NULL',
    '      AND "expected_reconciliation_evidence_digest" IS NULL',
    '      AND "state" = \'pending\'',
    '      AND "publish_attempt_ordinal" = 1',
    '      AND "transition_evidence_digest" = "business_transaction_digest"',
    '      AND "recorded_at" <= "message_enqueued_at"',
    '    ) OR (',
    `      "revision" BETWEEN 1 AND ${BACKEND_AUTOMATION_OUTBOX_MAX_REVISION}`,
    '      AND "expected_revision" IS NOT NULL',
    '      AND "expected_revision" = "revision" - 1',
    '      AND "expected_head_digest" IS NOT NULL',
    '      AND "previous_record_digest" IS NOT NULL',
    '      AND "previous_record_digest" = "expected_head_digest"',
    '      AND "expected_publish_attempt_ids" IS NOT NULL',
    '      AND "expected_current_publish_attempt_id" IS NOT NULL',
    '      AND "expected_publish_attempt_ordinal" IS NOT NULL',
    '      AND "expected_state" IS NOT NULL',
    '      AND "expected_recorded_at" IS NOT NULL',
    '      AND "expected_transition_evidence_digest" IS NOT NULL',
    '      AND "recorded_at" > "expected_recorded_at"',
    '      AND "transition_evidence_digest" IS DISTINCT FROM "expected_transition_evidence_digest"',
    '    )',
    '  ),',
    '  CONSTRAINT "outbox_revisions_attempts_check" CHECK (',
    `    ${validator}("publish_attempt_ids")`,
    '    AND "publish_attempt_ordinal" = "pg_catalog"."cardinality"("publish_attempt_ids")',
    '    AND "current_publish_attempt_id" =',
    '      "publish_attempt_ids"["pg_catalog"."array_upper"("publish_attempt_ids", 1)]',
    '    AND (',
    '      "expected_publish_attempt_ids" IS NULL',
    '      OR (',
    `        ${validator}("expected_publish_attempt_ids")`,
    '        AND "expected_publish_attempt_ordinal" =',
    '          "pg_catalog"."cardinality"("expected_publish_attempt_ids")',
    '        AND "expected_current_publish_attempt_id" =',
    '          "expected_publish_attempt_ids"[',
    '            "pg_catalog"."array_upper"("expected_publish_attempt_ids", 1)',
    '          ]',
    '      )',
    '    )',
    '  ),',
    '  CONSTRAINT "outbox_revisions_state_evidence_check" CHECK (',
    '    (',
    "      \"state\" IN ('pending', 'pre-publish-outcome-unknown')",
    '      AND "publish_confirmation_evidence_digest" IS NULL',
    '      AND "known_not_published_evidence_digest" IS NULL',
    '      AND "delivery_evidence_digest" IS NULL',
    '      AND "reconciliation_evidence_digest" IS NULL',
    '    ) OR (',
    '      "state" = \'outcome-unknown\'',
    '      AND "publish_confirmation_evidence_digest" IS NULL',
    '      AND "known_not_published_evidence_digest" IS NULL',
    '      AND "delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "state" = \'known-not-published\'',
    '      AND "publish_confirmation_evidence_digest" IS NULL',
    '      AND "known_not_published_evidence_digest" IS NOT NULL',
    '      AND "delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "state" = \'published\'',
    '      AND "publish_confirmation_evidence_digest" IS NOT NULL',
    '      AND "known_not_published_evidence_digest" IS NULL',
    '      AND "delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "state" = \'delivered\'',
    '      AND "publish_confirmation_evidence_digest" IS NOT NULL',
    '      AND "known_not_published_evidence_digest" IS NULL',
    '      AND "delivery_evidence_digest" IS NOT NULL',
    '      AND "delivery_evidence_digest" IS DISTINCT FROM',
    '        "publish_confirmation_evidence_digest"',
    '    )',
    '  ),',
    '  CONSTRAINT "outbox_revisions_transition_check" CHECK (',
    '    "revision" = 0',
    '    OR (',
    `      "revision" BETWEEN 1 AND ${BACKEND_AUTOMATION_OUTBOX_MAX_REVISION}`,
    '      AND (',
    '        (',
    '          "expected_state" = \'pending\'',
    '          AND "state" = \'pre-publish-outcome-unknown\'',
    '          AND "publish_attempt_ids" IS NOT DISTINCT FROM "expected_publish_attempt_ids"',
    '          AND "current_publish_attempt_id" = "expected_current_publish_attempt_id"',
    '          AND "publish_attempt_ordinal" = "expected_publish_attempt_ordinal"',
    '          AND "recorded_at" < "message_retention_deadline"',
    '        ) OR (',
    '          "expected_state" = \'pre-publish-outcome-unknown\'',
    "          AND \"state\" IN ('published', 'outcome-unknown', 'known-not-published')",
    '          AND "publish_attempt_ids" IS NOT DISTINCT FROM "expected_publish_attempt_ids"',
    '          AND "current_publish_attempt_id" = "expected_current_publish_attempt_id"',
    '          AND "publish_attempt_ordinal" = "expected_publish_attempt_ordinal"',
    '          AND (',
    '            ("state" = \'outcome-unknown\'',
    '              AND "reconciliation_evidence_digest" IS NULL)',
    '            OR ("state" = \'published\'',
    '              AND "reconciliation_evidence_digest" IS NULL',
    '              AND "publish_confirmation_evidence_digest" IS NOT DISTINCT FROM',
    '                "transition_evidence_digest"',
    '              AND "publish_confirmation_evidence_digest" IS DISTINCT FROM',
    '                "expected_transition_evidence_digest")',
    '            OR ("state" = \'known-not-published\'',
    '              AND "reconciliation_evidence_digest" IS NULL',
    '              AND "known_not_published_evidence_digest" IS DISTINCT FROM',
    '                "expected_transition_evidence_digest")',
    '          )',
    '        ) OR (',
    '          "expected_state" = \'outcome-unknown\'',
    "          AND \"state\" IN ('published', 'outcome-unknown', 'known-not-published')",
    '          AND "publish_attempt_ids" IS NOT DISTINCT FROM "expected_publish_attempt_ids"',
    '          AND "current_publish_attempt_id" = "expected_current_publish_attempt_id"',
    '          AND "publish_attempt_ordinal" = "expected_publish_attempt_ordinal"',
    '          AND "reconciliation_evidence_digest" IS NOT NULL',
    '          AND "reconciliation_evidence_digest" IS DISTINCT FROM',
    '            "expected_transition_evidence_digest"',
    '          AND "reconciliation_evidence_digest" IS DISTINCT FROM',
    '            "expected_reconciliation_evidence_digest"',
    '          AND (',
    '            "state" = \'outcome-unknown\'',
    '            OR ("state" = \'published\'',
    '              AND "publish_confirmation_evidence_digest" IS NOT DISTINCT FROM',
    '                "transition_evidence_digest"',
    '              AND "publish_confirmation_evidence_digest" IS DISTINCT FROM',
    '                "expected_transition_evidence_digest"',
    '              AND "publish_confirmation_evidence_digest" IS DISTINCT FROM',
    '                "expected_reconciliation_evidence_digest")',
    '            OR ("state" = \'known-not-published\'',
    '              AND "known_not_published_evidence_digest" IS DISTINCT FROM',
    '                "expected_transition_evidence_digest")',
    '          )',
    '        ) OR (',
    '          "expected_state" = \'known-not-published\'',
    '          AND "state" = \'pre-publish-outcome-unknown\'',
    `          AND "expected_publish_attempt_ordinal" BETWEEN 1 AND ${BACKEND_AUTOMATION_OUTBOX_MAX_PUBLISH_ATTEMPTS - 1}`,
    '          AND "publish_attempt_ordinal" = "expected_publish_attempt_ordinal" + 1',
    '          AND "current_publish_attempt_id" IS DISTINCT FROM',
    '            "expected_current_publish_attempt_id"',
    '          AND "publish_attempt_ids"[1:"expected_publish_attempt_ordinal"]',
    '            IS NOT DISTINCT FROM "expected_publish_attempt_ids"',
    '          AND "recorded_at" < "message_retention_deadline"',
    '        ) OR (',
    '          "expected_state" = \'published\'',
    '          AND "state" = \'delivered\'',
    '          AND "publish_attempt_ids" IS NOT DISTINCT FROM "expected_publish_attempt_ids"',
    '          AND "current_publish_attempt_id" = "expected_current_publish_attempt_id"',
    '          AND "publish_attempt_ordinal" = "expected_publish_attempt_ordinal"',
    '          AND "publish_confirmation_evidence_digest" IS NOT DISTINCT FROM',
    '            "expected_publish_confirmation_evidence_digest"',
    '          AND "reconciliation_evidence_digest" IS NOT DISTINCT FROM',
    '            "expected_reconciliation_evidence_digest"',
    '          AND "delivery_evidence_digest" IS NOT DISTINCT FROM',
    '            "transition_evidence_digest"',
    '          AND "delivery_evidence_digest" IS DISTINCT FROM',
    '            "expected_transition_evidence_digest"',
    '          AND "delivery_evidence_digest" IS DISTINCT FROM',
    '            "expected_reconciliation_evidence_digest"',
    '        )',
    '      )',
    '    )',
    '  ),',
    '  CONSTRAINT "outbox_revisions_timestamp_check" CHECK (',
    `    "recorded_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("recorded_at"::timestamptz)',
    `    AND "message_enqueued_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("message_enqueued_at"::timestamptz)',
    `    AND "message_retention_deadline" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("message_retention_deadline"::timestamptz)',
    '    AND "message_retention_deadline" > "message_enqueued_at"',
    '    AND ("expected_recorded_at" IS NULL OR (',
    `      "expected_recorded_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '      AND "pg_catalog"."isfinite"("expected_recorded_at"::timestamptz)',
    '    ))',
    '  )',
    ') USING heap;'
  ]
}

function headsTableDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const validator = qualified(schemaName, ATTEMPT_VALIDATOR_FUNCTION)
  return [
    `CREATE TABLE ${qualified(schemaName, HEADS_TABLE)} (`,
    '  "outbox_id" text NOT NULL,',
    '  "current_revision" bigint NOT NULL,',
    '  "current_head_digest" text NOT NULL,',
    '  "current_business_transaction_digest" text NOT NULL,',
    '  "current_message_enqueued_at" text NOT NULL,',
    '  "current_message_retention_deadline" text NOT NULL,',
    '  "current_publish_attempt_ids" text[] NOT NULL,',
    '  "current_publish_attempt_id" text NOT NULL,',
    '  "current_publish_attempt_ordinal" smallint NOT NULL,',
    '  "current_state" text NOT NULL,',
    '  "current_recorded_at" text NOT NULL,',
    '  "current_transition_evidence_digest" text NOT NULL,',
    '  "current_publish_confirmation_evidence_digest" text,',
    '  "current_known_not_published_evidence_digest" text,',
    '  "current_delivery_evidence_digest" text,',
    '  "current_reconciliation_evidence_digest" text,',
    '  "current_publish_confirmation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("current_publish_confirmation_evidence_digest", \'-\')) STORED,',
    '  "current_known_not_published_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("current_known_not_published_evidence_digest", \'-\')) STORED,',
    '  "current_delivery_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("current_delivery_evidence_digest", \'-\')) STORED,',
    '  "current_reconciliation_evidence_token" text',
    '    GENERATED ALWAYS AS (COALESCE("current_reconciliation_evidence_digest", \'-\')) STORED,',
    '  CONSTRAINT "outbox_heads_pkey" PRIMARY KEY ("outbox_id"),',
    '  CONSTRAINT "outbox_heads_binding_fkey" FOREIGN KEY (',
    '    "outbox_id", "current_business_transaction_digest",',
    '    "current_message_enqueued_at", "current_message_retention_deadline"',
    `  ) REFERENCES ${bindings} (`,
    '    "outbox_id", "business_transaction_digest",',
    '    "message_enqueued_at", "message_retention_deadline"',
    '  ) MATCH FULL DEFERRABLE INITIALLY DEFERRED,',
    '  CONSTRAINT "outbox_heads_revision_fkey" FOREIGN KEY (',
    '    "outbox_id", "current_revision", "current_head_digest",',
    '    "current_business_transaction_digest", "current_message_enqueued_at",',
    '    "current_message_retention_deadline",',
    '    "current_publish_attempt_ids", "current_publish_attempt_id",',
    '    "current_publish_attempt_ordinal",',
    '    "current_state", "current_recorded_at", "current_transition_evidence_digest",',
    '    "current_publish_confirmation_evidence_token",',
    '    "current_known_not_published_evidence_token",',
    '    "current_delivery_evidence_token", "current_reconciliation_evidence_token"',
    `  ) REFERENCES ${revisions} (`,
    '    "outbox_id", "revision", "record_digest",',
    '    "business_transaction_digest", "message_enqueued_at",',
    '    "message_retention_deadline", "publish_attempt_ids",',
    '    "current_publish_attempt_id", "publish_attempt_ordinal",',
    '    "state", "recorded_at", "transition_evidence_digest",',
    '    "publish_confirmation_evidence_token", "known_not_published_evidence_token",',
    '    "delivery_evidence_token", "reconciliation_evidence_token"',
    '  ) MATCH FULL DEFERRABLE INITIALLY DEFERRED,',
    '  CONSTRAINT "outbox_heads_identifier_check" CHECK (',
    `    "current_publish_attempt_id" ~ ${literal(IDENTIFIER_PATTERN)}`,
    '  ),',
    '  CONSTRAINT "outbox_heads_digests_check" CHECK (',
    `    "current_head_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "current_business_transaction_digest" ~ ${literal(DIGEST_PATTERN)}`,
    `    AND "current_transition_evidence_digest" ~ ${literal(DIGEST_PATTERN)}`,
    ...[
      'current_publish_confirmation_evidence_digest',
      'current_known_not_published_evidence_digest',
      'current_delivery_evidence_digest',
      'current_reconciliation_evidence_digest'
    ].flatMap((column) => [
      `    AND ("${column}" IS NULL`,
      `      OR "${column}" ~ ${literal(DIGEST_PATTERN)})`
    ]),
    '  ),',
    '  CONSTRAINT "outbox_heads_revision_attempt_check" CHECK (',
    `    "current_revision" BETWEEN 0 AND ${BACKEND_AUTOMATION_OUTBOX_MAX_REVISION}`,
    `    AND ${validator}("current_publish_attempt_ids")`,
    '    AND "current_publish_attempt_ordinal" =',
    '      "pg_catalog"."cardinality"("current_publish_attempt_ids")',
    '    AND "current_publish_attempt_id" =',
    '      "current_publish_attempt_ids"[',
    '        "pg_catalog"."array_upper"("current_publish_attempt_ids", 1)',
    '      ]',
    '  ),',
    '  CONSTRAINT "outbox_heads_transition_check" CHECK (',
    '    (',
    "      \"current_state\" IN ('pending', 'pre-publish-outcome-unknown')",
    '      AND "current_publish_confirmation_evidence_digest" IS NULL',
    '      AND "current_known_not_published_evidence_digest" IS NULL',
    '      AND "current_delivery_evidence_digest" IS NULL',
    '      AND "current_reconciliation_evidence_digest" IS NULL',
    '    ) OR (',
    '      "current_state" = \'outcome-unknown\'',
    '      AND "current_publish_confirmation_evidence_digest" IS NULL',
    '      AND "current_known_not_published_evidence_digest" IS NULL',
    '      AND "current_delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "current_state" = \'known-not-published\'',
    '      AND "current_publish_confirmation_evidence_digest" IS NULL',
    '      AND "current_known_not_published_evidence_digest" IS NOT NULL',
    '      AND "current_delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "current_state" = \'published\'',
    '      AND "current_publish_confirmation_evidence_digest" IS NOT NULL',
    '      AND "current_known_not_published_evidence_digest" IS NULL',
    '      AND "current_delivery_evidence_digest" IS NULL',
    '    ) OR (',
    '      "current_state" = \'delivered\'',
    '      AND "current_publish_confirmation_evidence_digest" IS NOT NULL',
    '      AND "current_known_not_published_evidence_digest" IS NULL',
    '      AND "current_delivery_evidence_digest" IS NOT NULL',
    '      AND "current_delivery_evidence_digest" IS DISTINCT FROM',
    '        "current_publish_confirmation_evidence_digest"',
    '    )',
    '  ),',
    '  CONSTRAINT "outbox_heads_timestamp_check" CHECK (',
    `    "current_recorded_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("current_recorded_at"::timestamptz)',
    `    AND "current_message_enqueued_at" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("current_message_enqueued_at"::timestamptz)',
    `    AND "current_message_retention_deadline" ~ ${literal(TIMESTAMP_PATTERN)}`,
    '    AND "pg_catalog"."isfinite"("current_message_retention_deadline"::timestamptz)',
    '    AND "current_message_retention_deadline" > "current_message_enqueued_at"',
    '  )',
    ') USING heap;'
  ]
}

function mutationGuardDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const guard = qualified(schemaName, MUTATION_GUARD_FUNCTION)
  return [
    `CREATE FUNCTION ${guard}()`,
    'RETURNS "pg_catalog"."trigger"',
    'LANGUAGE plpgsql',
    'SECURITY INVOKER',
    'SET search_path = pg_catalog',
    'AS $openpencil_outbox_mutation_guard$',
    'BEGIN',
    "  RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox bindings and revisions are immutable; mutation and retirement require explicit approval.';",
    'END',
    '$openpencil_outbox_mutation_guard$;',
    `CREATE TRIGGER ${identifier(BINDINGS_MUTATION_GUARD_TRIGGER)}`,
    `BEFORE UPDATE OR DELETE OR TRUNCATE ON ${bindings}`,
    'FOR EACH STATEMENT',
    `EXECUTE FUNCTION ${guard}();`,
    `CREATE TRIGGER ${identifier(REVISIONS_MUTATION_GUARD_TRIGGER)}`,
    `BEFORE UPDATE OR DELETE OR TRUNCATE ON ${revisions}`,
    'FOR EACH STATEMENT',
    `EXECUTE FUNCTION ${guard}();`
  ]
}

function indexDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const heads = qualified(schemaName, HEADS_TABLE)
  return [
    `CREATE INDEX ${identifier('outbox_bindings_event_idx')}`,
    `ON ${bindings} ("queue_id", "event_id", "outbox_id");`,
    `CREATE UNIQUE INDEX ${identifier('outbox_revisions_transition_evidence_uidx')}`,
    `ON ${revisions} ("outbox_id", "transition_evidence_digest");`,
    `CREATE INDEX ${identifier('outbox_heads_state_idx')}`,
    `ON ${heads} ("current_state", "current_recorded_at", "outbox_id");`
  ]
}

function comments(applicationObjectKey: string, schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const heads = qualified(schemaName, HEADS_TABLE)
  const validator = qualified(schemaName, ATTEMPT_VALIDATOR_FUNCTION)
  const guard = qualified(schemaName, MUTATION_GUARD_FUNCTION)
  return [
    `COMMENT ON SCHEMA ${identifier(schemaName)} IS ${literal(marker(applicationObjectKey, 'schema'))};`,
    `COMMENT ON TABLE ${bindings} IS ${literal(marker(applicationObjectKey, 'table:outbox-bindings'))};`,
    `COMMENT ON TABLE ${revisions} IS ${literal(marker(applicationObjectKey, 'table:outbox-revisions'))};`,
    `COMMENT ON TABLE ${heads} IS ${literal(marker(applicationObjectKey, 'table:outbox-heads'))};`,
    `COMMENT ON FUNCTION ${validator}(text[]) IS ${literal(marker(applicationObjectKey, 'function:attempt-validator'))};`,
    `COMMENT ON FUNCTION ${guard}() IS ${literal(marker(applicationObjectKey, 'function:immutable-mutation-guard'))};`,
    `COMMENT ON TRIGGER ${identifier(BINDINGS_MUTATION_GUARD_TRIGGER)} ON ${bindings} IS ${literal(marker(applicationObjectKey, 'trigger:bindings-immutability'))};`,
    `COMMENT ON TRIGGER ${identifier(REVISIONS_MUTATION_GUARD_TRIGGER)} ON ${revisions} IS ${literal(marker(applicationObjectKey, 'trigger:revisions-immutability'))};`,
    ...BINDING_CONSTRAINTS.map(
      ([constraintName]) =>
        `COMMENT ON CONSTRAINT ${identifier(constraintName)} ON ${bindings} IS ${literal(marker(applicationObjectKey, `constraint:${constraintName}`))};`
    ),
    ...REVISION_CONSTRAINTS.map(
      ([constraintName]) =>
        `COMMENT ON CONSTRAINT ${identifier(constraintName)} ON ${revisions} IS ${literal(marker(applicationObjectKey, `constraint:${constraintName}`))};`
    ),
    ...HEAD_CONSTRAINTS.map(
      ([constraintName]) =>
        `COMMENT ON CONSTRAINT ${identifier(constraintName)} ON ${heads} IS ${literal(marker(applicationObjectKey, `constraint:${constraintName}`))};`
    ),
    ...INDEXES.map(
      ([indexName]) =>
        `COMMENT ON INDEX ${qualified(schemaName, indexName)} IS ${literal(marker(applicationObjectKey, `index:${indexName}`))};`
    )
  ]
}

function revokeDDL(schemaName: string): readonly string[] {
  const bindings = qualified(schemaName, BINDINGS_TABLE)
  const revisions = qualified(schemaName, REVISIONS_TABLE)
  const heads = qualified(schemaName, HEADS_TABLE)
  const validator = qualified(schemaName, ATTEMPT_VALIDATOR_FUNCTION)
  const guard = qualified(schemaName, MUTATION_GUARD_FUNCTION)
  return [
    `REVOKE ALL PRIVILEGES ON SCHEMA ${identifier(schemaName)} FROM PUBLIC, "anon", "authenticated", "authenticator";`,
    `REVOKE ALL PRIVILEGES ON TABLE ${bindings}, ${revisions}, ${heads} FROM PUBLIC, "anon", "authenticated", "authenticator";`,
    `REVOKE ALL PRIVILEGES ON FUNCTION ${validator}(text[]), ${guard}() FROM PUBLIC, "anon", "authenticated", "authenticator";`,
    'DO $openpencil_transactional_outbox_api_role_revoke$',
    'DECLARE',
    `  schema_identifier CONSTANT text := ${literal(identifier(schemaName))};`,
    `  tables_identifier CONSTANT text := ${literal(`${bindings}, ${revisions}, ${heads}`)};`,
    `  functions_identifier CONSTANT text := ${literal(`${validator}(text[]), ${guard}()`)};`,
    '  api_role_identifier CONSTANT text := "pg_catalog"."quote_ident"(\'service\' || \'_role\');',
    'BEGIN',
    "  EXECUTE 'REVOKE ALL PRIVILEGES ON SCHEMA ' || schema_identifier || ' FROM ' || api_role_identifier;",
    "  EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE ' || tables_identifier || ' FROM ' || api_role_identifier;",
    "  EXECUTE 'REVOKE ALL PRIVILEGES ON FUNCTION ' || functions_identifier || ' FROM ' || api_role_identifier;",
    'END',
    '$openpencil_transactional_outbox_api_role_revoke$;'
  ]
}

function expectedColumnRows(): readonly string[] {
  const rows = [
    [BINDINGS_TABLE, 1, 'outbox_id', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 2, 'business_transaction_id', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 3, 'business_transaction_digest', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 4, 'entity_id', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 5, 'row_id_digest', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 6, 'row_version', 'pg_catalog.int8', true, false, ''],
    [BINDINGS_TABLE, 7, 'event_id', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 8, 'event_digest', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 9, 'queue_id', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 10, 'message_envelope_digest', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 11, 'idempotency_key_digest', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 12, 'message_enqueued_at', 'pg_catalog.text', true, false, ''],
    [BINDINGS_TABLE, 13, 'message_retention_deadline', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 1, 'outbox_id', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 2, 'revision', 'pg_catalog.int8', true, false, ''],
    [REVISIONS_TABLE, 3, 'expected_revision', 'pg_catalog.int8', false, false, ''],
    [REVISIONS_TABLE, 4, 'expected_head_digest', 'pg_catalog.text', false, false, ''],
    [REVISIONS_TABLE, 5, 'previous_record_digest', 'pg_catalog.text', false, false, ''],
    [REVISIONS_TABLE, 6, 'expected_publish_attempt_ids', 'pg_catalog.text[]', false, false, ''],
    [
      REVISIONS_TABLE,
      7,
      'expected_current_publish_attempt_id',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [REVISIONS_TABLE, 8, 'expected_publish_attempt_ordinal', 'pg_catalog.int2', false, false, ''],
    [REVISIONS_TABLE, 9, 'expected_state', 'pg_catalog.text', false, false, ''],
    [REVISIONS_TABLE, 10, 'expected_recorded_at', 'pg_catalog.text', false, false, ''],
    [
      REVISIONS_TABLE,
      11,
      'expected_transition_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [
      REVISIONS_TABLE,
      12,
      'expected_publish_confirmation_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [
      REVISIONS_TABLE,
      13,
      'expected_known_not_published_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [REVISIONS_TABLE, 14, 'expected_delivery_evidence_digest', 'pg_catalog.text', false, false, ''],
    [
      REVISIONS_TABLE,
      15,
      'expected_reconciliation_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [REVISIONS_TABLE, 16, 'record_digest', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 17, 'business_transaction_digest', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 18, 'message_enqueued_at', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 19, 'message_retention_deadline', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 20, 'publish_attempt_ids', 'pg_catalog.text[]', true, false, ''],
    [REVISIONS_TABLE, 21, 'current_publish_attempt_id', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 22, 'publish_attempt_ordinal', 'pg_catalog.int2', true, false, ''],
    [REVISIONS_TABLE, 23, 'state', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 24, 'recorded_at', 'pg_catalog.text', true, false, ''],
    [REVISIONS_TABLE, 25, 'transition_evidence_digest', 'pg_catalog.text', true, false, ''],
    [
      REVISIONS_TABLE,
      26,
      'publish_confirmation_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [
      REVISIONS_TABLE,
      27,
      'known_not_published_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [REVISIONS_TABLE, 28, 'delivery_evidence_digest', 'pg_catalog.text', false, false, ''],
    [REVISIONS_TABLE, 29, 'reconciliation_evidence_digest', 'pg_catalog.text', false, false, ''],
    [
      REVISIONS_TABLE,
      30,
      'expected_publish_confirmation_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [
      REVISIONS_TABLE,
      31,
      'expected_known_not_published_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [REVISIONS_TABLE, 32, 'expected_delivery_evidence_token', 'pg_catalog.text', false, true, 's'],
    [
      REVISIONS_TABLE,
      33,
      'expected_reconciliation_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [
      REVISIONS_TABLE,
      34,
      'publish_confirmation_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [
      REVISIONS_TABLE,
      35,
      'known_not_published_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [REVISIONS_TABLE, 36, 'delivery_evidence_token', 'pg_catalog.text', false, true, 's'],
    [REVISIONS_TABLE, 37, 'reconciliation_evidence_token', 'pg_catalog.text', false, true, 's'],
    [HEADS_TABLE, 1, 'outbox_id', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 2, 'current_revision', 'pg_catalog.int8', true, false, ''],
    [HEADS_TABLE, 3, 'current_head_digest', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 4, 'current_business_transaction_digest', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 5, 'current_message_enqueued_at', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 6, 'current_message_retention_deadline', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 7, 'current_publish_attempt_ids', 'pg_catalog.text[]', true, false, ''],
    [HEADS_TABLE, 8, 'current_publish_attempt_id', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 9, 'current_publish_attempt_ordinal', 'pg_catalog.int2', true, false, ''],
    [HEADS_TABLE, 10, 'current_state', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 11, 'current_recorded_at', 'pg_catalog.text', true, false, ''],
    [HEADS_TABLE, 12, 'current_transition_evidence_digest', 'pg_catalog.text', true, false, ''],
    [
      HEADS_TABLE,
      13,
      'current_publish_confirmation_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [
      HEADS_TABLE,
      14,
      'current_known_not_published_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [HEADS_TABLE, 15, 'current_delivery_evidence_digest', 'pg_catalog.text', false, false, ''],
    [
      HEADS_TABLE,
      16,
      'current_reconciliation_evidence_digest',
      'pg_catalog.text',
      false,
      false,
      ''
    ],
    [
      HEADS_TABLE,
      17,
      'current_publish_confirmation_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [
      HEADS_TABLE,
      18,
      'current_known_not_published_evidence_token',
      'pg_catalog.text',
      false,
      true,
      's'
    ],
    [HEADS_TABLE, 19, 'current_delivery_evidence_token', 'pg_catalog.text', false, true, 's'],
    [HEADS_TABLE, 20, 'current_reconciliation_evidence_token', 'pg_catalog.text', false, true, 's']
  ] as const
  return rows.map(
    ([tableName, ordinal, columnName, typeName, notNull, hasDefault, generatedKind]) =>
      `      (${literal(tableName)}, ${ordinal}, ${literal(columnName)}, "pg_catalog"."to_regtype"(${literal(typeName)}), ${notNull ? 'TRUE' : 'FALSE'}, ${hasDefault ? 'TRUE' : 'FALSE'}, ${literal(generatedKind)})`
  )
}

function expectedConstraintRows(applicationObjectKey: string): readonly string[] {
  return [
    ...BINDING_CONSTRAINTS.map((entry) => [BINDINGS_TABLE, ...entry] as const),
    ...REVISION_CONSTRAINTS.map((entry) => [REVISIONS_TABLE, ...entry] as const),
    ...HEAD_CONSTRAINTS.map((entry) => [HEADS_TABLE, ...entry] as const)
  ].map(
    ([tableName, constraintName, constraintType]) =>
      `      (${literal(tableName)}, ${literal(constraintName)}, ${literal(constraintType)}, ${literal(marker(applicationObjectKey, `constraint:${constraintName}`))})`
  )
}

function expectedIndexRows(applicationObjectKey: string): readonly string[] {
  return INDEXES.map(
    ([indexName, tableName, primary, unique, columns]) =>
      `      (${literal(indexName)}, ${literal(tableName)}, ${primary ? 'TRUE' : 'FALSE'}, ${unique ? 'TRUE' : 'FALSE'}, ARRAY[${columns.join(', ')}]::smallint[], NULL, ${literal(marker(applicationObjectKey, `index:${indexName}`))})`
  )
}

function catalogPostcondition(applicationObjectKey: string, schemaName: string): readonly string[] {
  const schemaMarker = literal(marker(applicationObjectKey, 'schema'))
  const bindingMarker = literal(marker(applicationObjectKey, 'table:outbox-bindings'))
  const revisionMarker = literal(marker(applicationObjectKey, 'table:outbox-revisions'))
  const headMarker = literal(marker(applicationObjectKey, 'table:outbox-heads'))
  const validatorMarker = literal(marker(applicationObjectKey, 'function:attempt-validator'))
  const guardMarker = literal(marker(applicationObjectKey, 'function:immutable-mutation-guard'))
  const bindingTriggerMarker = literal(
    marker(applicationObjectKey, 'trigger:bindings-immutability')
  )
  const revisionTriggerMarker = literal(
    marker(applicationObjectKey, 'trigger:revisions-immutability')
  )
  const schemaLiteral = literal(schemaName)
  const bindingsRegclass = literal(identifier(schemaName) + '.' + identifier(BINDINGS_TABLE))
  const revisionsRegclass = literal(identifier(schemaName) + '.' + identifier(REVISIONS_TABLE))
  const headsRegclass = literal(identifier(schemaName) + '.' + identifier(HEADS_TABLE))
  const validatorRegprocedure = literal(
    identifier(schemaName) + '.' + identifier(ATTEMPT_VALIDATOR_FUNCTION) + '(text[])'
  )
  const guardRegprocedure = literal(
    identifier(schemaName) + '.' + identifier(MUTATION_GUARD_FUNCTION) + '()'
  )
  return [
    'DO $openpencil_transactional_outbox_postcondition$',
    'DECLARE',
    '  expected_owner oid := (',
    '    SELECT "database_role"."oid"',
    '    FROM "pg_catalog"."pg_roles" AS "database_role"',
    '    WHERE "database_role"."rolname" = CURRENT_USER',
    '  );',
    `  outbox_namespace oid := "pg_catalog"."to_regnamespace"(${literal(identifier(schemaName))});`,
    `  bindings_table regclass := "pg_catalog"."to_regclass"(${bindingsRegclass});`,
    `  revisions_table regclass := "pg_catalog"."to_regclass"(${revisionsRegclass});`,
    `  heads_table regclass := "pg_catalog"."to_regclass"(${headsRegclass});`,
    `  validator_function regprocedure := "pg_catalog"."to_regprocedure"(${validatorRegprocedure});`,
    `  guard_function regprocedure := "pg_catalog"."to_regprocedure"(${guardRegprocedure});`,
    'BEGIN',
    '  IF outbox_namespace IS NULL OR bindings_table IS NULL OR revisions_table IS NULL',
    '    OR heads_table IS NULL OR validator_function IS NULL OR guard_function IS NULL THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox object resolution postcondition failed.';",
    '  END IF;',
    '  IF NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_namespace" AS "outbox_schema"',
    '    WHERE "outbox_schema"."oid" = outbox_namespace',
    `      AND "outbox_schema"."nspname" = ${schemaLiteral}`,
    '      AND "outbox_schema"."nspowner" = expected_owner',
    `      AND "pg_catalog"."obj_description"("outbox_schema"."oid", 'pg_namespace') = ${schemaMarker}`,
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox schema ownership/marker postcondition failed.';",
    '  END IF;',
    '  IF (',
    '    SELECT "pg_catalog"."count"(*)',
    '    FROM "pg_catalog"."pg_class" AS "outbox_relation"',
    '    WHERE "outbox_relation"."relnamespace" = outbox_namespace',
    `  ) <> ${3 + INDEXES.length} OR EXISTS (`,
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_class" AS "outbox_relation"',
    '    WHERE "outbox_relation"."relnamespace" = outbox_namespace',
    '      AND (',
    `        ("outbox_relation"."relkind" = 'r' AND "outbox_relation"."relname" NOT IN (${[BINDINGS_TABLE, REVISIONS_TABLE, HEADS_TABLE].map(literal).join(', ')}))`,
    `        OR ("outbox_relation"."relkind" = 'i' AND "outbox_relation"."relname" NOT IN (${INDEXES.map(([name]) => literal(name)).join(', ')}))`,
    `        OR "outbox_relation"."relkind" NOT IN ('r', 'i')`,
    '        OR "outbox_relation"."relowner" <> expected_owner',
    '      )',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox relation inventory postcondition failed.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM (VALUES',
    ...expectedColumnRows().map(
      (row, index, rows) => `${row}${index + 1 === rows.length ? '' : ','}`
    ),
    '    ) AS "expected_column"(',
    '      "table_name", "ordinal", "column_name", "type_oid", "not_null", "has_default",',
    '      "generated_kind"',
    '    )',
    '    FULL OUTER JOIN (',
    '      SELECT',
    '        "table_relation"."relname" AS "table_name",',
    '        "table_column"."attnum"::integer AS "ordinal",',
    '        "table_column"."attname" AS "column_name",',
    '        "table_column"."atttypid" AS "type_oid",',
    '        "table_column"."attnotnull" AS "not_null",',
    '        "table_column"."atthasdef" AS "has_default",',
    '        "table_column"."attidentity" AS "identity_kind",',
    '        "table_column"."attgenerated" AS "generated_kind"',
    '      FROM "pg_catalog"."pg_attribute" AS "table_column"',
    '      INNER JOIN "pg_catalog"."pg_class" AS "table_relation"',
    '        ON "table_relation"."oid" = "table_column"."attrelid"',
    '      WHERE "table_relation"."oid" IN (bindings_table, revisions_table, heads_table)',
    '        AND "table_column"."attnum" > 0',
    '        AND NOT "table_column"."attisdropped"',
    '    ) AS "actual_column"',
    '      ON "actual_column"."table_name" = "expected_column"."table_name"',
    '      AND "actual_column"."ordinal" = "expected_column"."ordinal"',
    '    WHERE "expected_column"."table_name" IS NULL',
    '      OR "actual_column"."table_name" IS NULL',
    '      OR "actual_column"."column_name" <> "expected_column"."column_name"',
    '      OR "actual_column"."type_oid" <> "expected_column"."type_oid"',
    '      OR "actual_column"."not_null" <> "expected_column"."not_null"',
    '      OR "actual_column"."has_default" <> "expected_column"."has_default"',
    '      OR "actual_column"."identity_kind" <> \'\'',
    '      OR "actual_column"."generated_kind" <> "expected_column"."generated_kind"',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox column catalog postcondition failed.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM (VALUES',
    ...expectedConstraintRows(applicationObjectKey).map(
      (row, index, rows) => `${row}${index + 1 === rows.length ? '' : ','}`
    ),
    '    ) AS "expected_constraint"("table_name", "constraint_name", "constraint_type", "marker")',
    '    FULL OUTER JOIN (',
    '      SELECT',
    '        "constraint_table"."relname" AS "table_name",',
    '        "table_constraint"."conname" AS "constraint_name",',
    '        "table_constraint"."contype"::text AS "constraint_type",',
    '        "pg_catalog"."obj_description"("table_constraint"."oid", \'pg_constraint\') AS "marker",',
    '        "table_constraint"."convalidated" AS "validated",',
    '        "table_constraint"."connoinherit" AS "no_inherit"',
    '      FROM "pg_catalog"."pg_constraint" AS "table_constraint"',
    '      INNER JOIN "pg_catalog"."pg_class" AS "constraint_table"',
    '        ON "constraint_table"."oid" = "table_constraint"."conrelid"',
    '      WHERE "constraint_table"."oid" IN (bindings_table, revisions_table, heads_table)',
    '    ) AS "actual_constraint"',
    '      ON "actual_constraint"."table_name" = "expected_constraint"."table_name"',
    '      AND "actual_constraint"."constraint_name" = "expected_constraint"."constraint_name"',
    '    WHERE "expected_constraint"."table_name" IS NULL',
    '      OR "actual_constraint"."table_name" IS NULL',
    '      OR "actual_constraint"."constraint_type" IS DISTINCT FROM',
    '        "expected_constraint"."constraint_type"',
    '      OR "actual_constraint"."marker" IS DISTINCT FROM "expected_constraint"."marker"',
    '      OR NOT "actual_constraint"."validated"',
    '      OR "actual_constraint"."no_inherit"',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox constraint catalog postcondition failed.';",
    '  END IF;',
    '  IF NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_constraint" AS "binding_constraint"',
    '    WHERE "binding_constraint"."conrelid" = revisions_table',
    `      AND "binding_constraint"."conname" = 'outbox_revisions_binding_fkey'`,
    '      AND "binding_constraint"."confrelid" = bindings_table',
    '      AND "binding_constraint"."conkey" = ARRAY[1, 17, 18, 19]::smallint[]',
    '      AND "binding_constraint"."confkey" = ARRAY[1, 3, 12, 13]::smallint[]',
    '      AND "binding_constraint"."condeferrable"',
    '      AND "binding_constraint"."condeferred"',
    `      AND "binding_constraint"."confmatchtype" = 'f'`,
    `      AND "binding_constraint"."confupdtype" = 'a'`,
    `      AND "binding_constraint"."confdeltype" = 'a'`,
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_constraint" AS "previous_constraint"',
    '    WHERE "previous_constraint"."conrelid" = revisions_table',
    `      AND "previous_constraint"."conname" = 'outbox_revisions_previous_fkey'`,
    '      AND "previous_constraint"."confrelid" = revisions_table',
    '      AND "previous_constraint"."conkey" =',
    '        ARRAY[1, 3, 4, 17, 18, 19, 6, 7, 8, 9, 10, 11, 30, 31, 32, 33]::smallint[]',
    '      AND "previous_constraint"."confkey" =',
    '        ARRAY[1, 2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 34, 35, 36, 37]::smallint[]',
    '      AND "previous_constraint"."condeferrable"',
    '      AND "previous_constraint"."condeferred"',
    `      AND "previous_constraint"."confmatchtype" = 's'`,
    `      AND "previous_constraint"."confupdtype" = 'a'`,
    `      AND "previous_constraint"."confdeltype" = 'a'`,
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_constraint" AS "head_constraint"',
    '    WHERE "head_constraint"."conrelid" = heads_table',
    `      AND "head_constraint"."conname" = 'outbox_heads_pkey'`,
    '      AND "head_constraint"."conkey" = ARRAY[1]::smallint[]',
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_constraint" AS "head_binding_constraint"',
    '    WHERE "head_binding_constraint"."conrelid" = heads_table',
    `      AND "head_binding_constraint"."conname" = 'outbox_heads_binding_fkey'`,
    '      AND "head_binding_constraint"."confrelid" = bindings_table',
    '      AND "head_binding_constraint"."conkey" = ARRAY[1, 4, 5, 6]::smallint[]',
    '      AND "head_binding_constraint"."confkey" = ARRAY[1, 3, 12, 13]::smallint[]',
    '      AND "head_binding_constraint"."condeferrable"',
    '      AND "head_binding_constraint"."condeferred"',
    `      AND "head_binding_constraint"."confmatchtype" = 'f'`,
    `      AND "head_binding_constraint"."confupdtype" = 'a'`,
    `      AND "head_binding_constraint"."confdeltype" = 'a'`,
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_constraint" AS "head_constraint"',
    '    WHERE "head_constraint"."conrelid" = heads_table',
    `      AND "head_constraint"."conname" = 'outbox_heads_revision_fkey'`,
    '      AND "head_constraint"."confrelid" = revisions_table',
    '      AND "head_constraint"."conkey" =',
    '        ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 19, 20]::smallint[]',
    '      AND "head_constraint"."confkey" =',
    '        ARRAY[1, 2, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 34, 35, 36, 37]::smallint[]',
    '      AND "head_constraint"."condeferrable"',
    '      AND "head_constraint"."condeferred"',
    `      AND "head_constraint"."confmatchtype" = 'f'`,
    `      AND "head_constraint"."confupdtype" = 'a'`,
    `      AND "head_constraint"."confdeltype" = 'a'`,
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox binding/CAS foreign-key postcondition failed.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM (VALUES',
    ...expectedIndexRows(applicationObjectKey).map(
      (row, index, rows) => `${row}${index + 1 === rows.length ? '' : ','}`
    ),
    '    ) AS "expected_index"(',
    '      "index_name", "table_name", "primary", "unique_index", "key_columns", "predicate", "marker"',
    '    )',
    '    FULL OUTER JOIN (',
    '      SELECT',
    '        "index_relation"."relname" AS "index_name",',
    '        "table_relation"."relname" AS "table_name",',
    '        "table_index"."indisprimary" AS "primary",',
    '        "table_index"."indisunique" AS "unique_index",',
    '        ARRAY(',
    '          SELECT ("table_index"."indkey"::smallint[])["index_key"."ordinal"]',
    '          FROM "pg_catalog"."generate_subscripts"(',
    '            "table_index"."indkey"::smallint[], 1',
    '          ) AS "index_key"("ordinal")',
    '          ORDER BY "index_key"."ordinal"',
    '        )::smallint[] AS "key_columns",',
    '        "pg_catalog"."pg_get_expr"(',
    '          "table_index"."indpred", "table_index"."indrelid"',
    '        ) AS "predicate",',
    '        "pg_catalog"."obj_description"("index_relation"."oid", \'pg_class\') AS "marker",',
    '        "table_index"."indisvalid" AS "valid",',
    '        "table_index"."indisready" AS "ready",',
    '        "table_index"."indislive" AS "live"',
    '      FROM "pg_catalog"."pg_index" AS "table_index"',
    '      INNER JOIN "pg_catalog"."pg_class" AS "index_relation"',
    '        ON "index_relation"."oid" = "table_index"."indexrelid"',
    '      INNER JOIN "pg_catalog"."pg_class" AS "table_relation"',
    '        ON "table_relation"."oid" = "table_index"."indrelid"',
    '      WHERE "table_index"."indrelid" IN (bindings_table, revisions_table, heads_table)',
    '    ) AS "actual_index"',
    '      ON "actual_index"."index_name" = "expected_index"."index_name"',
    '      AND "actual_index"."table_name" = "expected_index"."table_name"',
    '    WHERE "expected_index"."index_name" IS NULL',
    '      OR "actual_index"."index_name" IS NULL',
    '      OR "actual_index"."primary" IS DISTINCT FROM "expected_index"."primary"',
    '      OR "actual_index"."unique_index" IS DISTINCT FROM "expected_index"."unique_index"',
    '      OR "actual_index"."key_columns" IS DISTINCT FROM "expected_index"."key_columns"',
    '      OR "actual_index"."predicate" IS DISTINCT FROM "expected_index"."predicate"',
    '      OR "actual_index"."marker" IS DISTINCT FROM "expected_index"."marker"',
    '      OR NOT "actual_index"."valid"',
    '      OR NOT "actual_index"."ready"',
    '      OR NOT "actual_index"."live"',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox index catalog postcondition failed.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_class" AS "outbox_table"',
    '    INNER JOIN "pg_catalog"."pg_am" AS "table_access_method"',
    '      ON "table_access_method"."oid" = "outbox_table"."relam"',
    '    WHERE "outbox_table"."oid" IN (bindings_table, revisions_table, heads_table)',
    '      AND (',
    `        "outbox_table"."relkind" <> 'r'`,
    `        OR "outbox_table"."relpersistence" <> 'p'`,
    '        OR "outbox_table"."relispartition"',
    '        OR "outbox_table"."relowner" <> expected_owner',
    '        OR "outbox_table"."relrowsecurity"',
    '        OR "outbox_table"."relforcerowsecurity"',
    `        OR "outbox_table"."relreplident" <> 'd'`,
    `        OR "table_access_method"."amname" <> 'heap'`,
    '      )',
    `  ) OR "pg_catalog"."obj_description"(bindings_table, 'pg_class') IS DISTINCT FROM ${bindingMarker}`,
    `    OR "pg_catalog"."obj_description"(revisions_table, 'pg_class') IS DISTINCT FROM ${revisionMarker}`,
    `    OR "pg_catalog"."obj_description"(heads_table, 'pg_class') IS DISTINCT FROM ${headMarker}`,
    '    OR EXISTS (',
    '      SELECT 1',
    '      FROM "pg_catalog"."pg_policy" AS "outbox_policy"',
    '      WHERE "outbox_policy"."polrelid" IN (bindings_table, revisions_table, heads_table)',
    '    )',
    '  THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox table shape/ownership/marker postcondition failed.';",
    '  END IF;',
    '  IF (',
    '    SELECT "pg_catalog"."count"(*)',
    '    FROM "pg_catalog"."pg_proc" AS "outbox_function"',
    '    WHERE "outbox_function"."pronamespace" = outbox_namespace',
    '  ) <> 2 OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_proc" AS "validator_proc"',
    '    INNER JOIN "pg_catalog"."pg_language" AS "function_language"',
    '      ON "function_language"."oid" = "validator_proc"."prolang"',
    '    WHERE "validator_proc"."oid" = validator_function',
    '      AND "validator_proc"."pronamespace" = outbox_namespace',
    '      AND "validator_proc"."proowner" = expected_owner',
    '      AND NOT "validator_proc"."prosecdef"',
    '      AND NOT "validator_proc"."proleakproof"',
    '      AND "validator_proc"."proisstrict"',
    '      AND NOT "validator_proc"."proretset"',
    `      AND "validator_proc"."prokind" = 'f'`,
    `      AND "validator_proc"."provolatile" = 'i'`,
    `      AND "validator_proc"."proparallel" = 's'`,
    `      AND "validator_proc"."prorettype" = "pg_catalog"."to_regtype"('pg_catalog.bool')`,
    '      AND "validator_proc"."pronargs" = 1',
    '      AND "validator_proc"."pronargdefaults" = 0',
    `      AND "validator_proc"."proconfig" = ARRAY['search_path=pg_catalog']::text[]`,
    `      AND "function_language"."lanname" = 'plpgsql'`,
    `      AND "pg_catalog"."obj_description"("validator_proc"."oid", 'pg_proc') = ${validatorMarker}`,
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_proc" AS "guard_proc"',
    '    INNER JOIN "pg_catalog"."pg_language" AS "function_language"',
    '      ON "function_language"."oid" = "guard_proc"."prolang"',
    '    WHERE "guard_proc"."oid" = guard_function',
    '      AND "guard_proc"."pronamespace" = outbox_namespace',
    '      AND "guard_proc"."proowner" = expected_owner',
    '      AND NOT "guard_proc"."prosecdef"',
    '      AND NOT "guard_proc"."proleakproof"',
    '      AND NOT "guard_proc"."proisstrict"',
    '      AND NOT "guard_proc"."proretset"',
    `      AND "guard_proc"."prokind" = 'f'`,
    `      AND "guard_proc"."provolatile" = 'v'`,
    `      AND "guard_proc"."proparallel" = 'u'`,
    `      AND "guard_proc"."prorettype" = "pg_catalog"."to_regtype"('pg_catalog.trigger')`,
    '      AND "guard_proc"."pronargs" = 0',
    '      AND "guard_proc"."pronargdefaults" = 0',
    `      AND "guard_proc"."proconfig" = ARRAY['search_path=pg_catalog']::text[]`,
    `      AND "function_language"."lanname" = 'plpgsql'`,
    `      AND "pg_catalog"."obj_description"("guard_proc"."oid", 'pg_proc') = ${guardMarker}`,
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox function catalog postcondition failed.';",
    '  END IF;',
    '  IF (',
    '    SELECT "pg_catalog"."count"(*)',
    '    FROM "pg_catalog"."pg_trigger" AS "outbox_trigger"',
    '    WHERE "outbox_trigger"."tgrelid" IN (bindings_table, revisions_table, heads_table)',
    '      AND NOT "outbox_trigger"."tgisinternal"',
    '  ) <> 2 OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_trigger" AS "binding_trigger"',
    '    WHERE "binding_trigger"."tgrelid" = bindings_table',
    `      AND "binding_trigger"."tgname" = ${literal(BINDINGS_MUTATION_GUARD_TRIGGER)}`,
    '      AND NOT "binding_trigger"."tgisinternal"',
    `      AND "binding_trigger"."tgenabled" = 'O'`,
    '      AND "binding_trigger"."tgtype" = 58',
    '      AND "binding_trigger"."tgfoid" = guard_function',
    `      AND "pg_catalog"."obj_description"("binding_trigger"."oid", 'pg_trigger') = ${bindingTriggerMarker}`,
    '  ) OR NOT EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_trigger" AS "revision_trigger"',
    '    WHERE "revision_trigger"."tgrelid" = revisions_table',
    `      AND "revision_trigger"."tgname" = ${literal(REVISIONS_MUTATION_GUARD_TRIGGER)}`,
    '      AND NOT "revision_trigger"."tgisinternal"',
    `      AND "revision_trigger"."tgenabled" = 'O'`,
    '      AND "revision_trigger"."tgtype" = 58',
    '      AND "revision_trigger"."tgfoid" = guard_function',
    `      AND "pg_catalog"."obj_description"("revision_trigger"."oid", 'pg_trigger') = ${revisionTriggerMarker}`,
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'OpenPencil transactional outbox immutability guard postcondition failed.';",
    '  END IF;',
    '  IF EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_namespace" AS "outbox_schema"',
    '    CROSS JOIN LATERAL "pg_catalog"."aclexplode"(',
    `      COALESCE("outbox_schema"."nspacl", "pg_catalog"."acldefault"('n', "outbox_schema"."nspowner"))`,
    '    ) AS "schema_acl"',
    '    WHERE "outbox_schema"."oid" = outbox_namespace',
    '      AND "schema_acl"."grantee" <> "outbox_schema"."nspowner"',
    '  ) OR EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_class" AS "outbox_table"',
    '    CROSS JOIN LATERAL "pg_catalog"."aclexplode"(',
    `      COALESCE("outbox_table"."relacl", "pg_catalog"."acldefault"('r', "outbox_table"."relowner"))`,
    '    ) AS "table_acl"',
    '    WHERE "outbox_table"."oid" IN (bindings_table, revisions_table, heads_table)',
    '      AND "table_acl"."grantee" <> "outbox_table"."relowner"',
    '  ) OR EXISTS (',
    '    SELECT 1',
    '    FROM "pg_catalog"."pg_proc" AS "outbox_function"',
    '    CROSS JOIN LATERAL "pg_catalog"."aclexplode"(',
    `      COALESCE("outbox_function"."proacl", "pg_catalog"."acldefault"('f', "outbox_function"."proowner"))`,
    '    ) AS "function_acl"',
    '    WHERE "outbox_function"."oid" IN (validator_function, guard_function)',
    '      AND "function_acl"."grantee" <> "outbox_function"."proowner"',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'A non-owner retains a direct privilege on an OpenPencil transactional outbox object.';",
    '  END IF;',
    '  IF EXISTS (',
    `    SELECT 1 FROM (VALUES ('anon'), ('authenticated'), ('authenticator'), ('service' || '_role')) AS "known_role"("role_name")`,
    '    WHERE "pg_catalog"."has_schema_privilege"(',
    `      "known_role"."role_name", outbox_namespace, 'USAGE'`,
    '    ) OR "pg_catalog"."has_schema_privilege"(',
    `      "known_role"."role_name", outbox_namespace, 'CREATE'`,
    '    )',
    '  ) OR EXISTS (',
    `    SELECT 1 FROM (VALUES ('anon'), ('authenticated'), ('authenticator'), ('service' || '_role')) AS "known_role"("role_name")`,
    `    CROSS JOIN (VALUES ('SELECT'), ('INSERT'), ('UPDATE'), ('DELETE'), ('TRUNCATE'), ('REFERENCES'), ('TRIGGER')) AS "table_privilege"("privilege_name")`,
    '    CROSS JOIN (VALUES (bindings_table), (revisions_table), (heads_table))',
    '      AS "outbox_table"("table_oid")',
    '    WHERE "pg_catalog"."has_table_privilege"(',
    '      "known_role"."role_name", "outbox_table"."table_oid",',
    '      "table_privilege"."privilege_name"',
    '    )',
    '  ) OR EXISTS (',
    `    SELECT 1 FROM (VALUES ('anon'), ('authenticated'), ('authenticator'), ('service' || '_role')) AS "known_role"("role_name")`,
    '    CROSS JOIN (VALUES (validator_function), (guard_function))',
    '      AS "outbox_function"("function_oid")',
    '    WHERE "pg_catalog"."has_function_privilege"(',
    `      "known_role"."role_name", "outbox_function"."function_oid", 'EXECUTE'`,
    '    )',
    '  ) THEN',
    "    RAISE EXCEPTION USING ERRCODE = '55000', MESSAGE = 'A known Supabase API role retains effective access to an OpenPencil transactional outbox object.';",
    '  END IF;',
    'END',
    '$openpencil_transactional_outbox_postcondition$;'
  ]
}

/**
 * Deterministic application-scoped outbox DDL for review. It creates no DML writer, queue
 * worker, network client, credential, Apply path, or Deploy path.
 */
export function emitSupabaseAutomationTransactionalOutboxReviewSQLV2(
  applicationObjectKey: string
): readonly string[] {
  const schemaName = supabaseAutomationTransactionalOutboxSchemaNameV2(applicationObjectKey)
  return [
    ...inventoryPreflight(applicationObjectKey, schemaName),
    `CREATE SCHEMA ${identifier(schemaName)} AUTHORIZATION CURRENT_USER;`,
    ...attemptValidatorDDL(schemaName),
    ...bindingsTableDDL(schemaName),
    ...revisionsTableDDL(schemaName),
    ...headsTableDDL(schemaName),
    ...mutationGuardDDL(schemaName),
    ...indexDDL(schemaName),
    ...comments(applicationObjectKey, schemaName),
    ...revokeDDL(schemaName),
    ...catalogPostcondition(applicationObjectKey, schemaName)
  ]
}
