const english = {
  title: 'NestJS backend',
  description: 'Manage the backend for your live preview.',
  close: 'Close backend panel',
  managed: 'Managed backend',
  external: 'External backend',
  ready: 'Ready to start',
  unconfigured: 'Not configured',
  stopped: 'Stopped',
  running: 'Running',
  busy: 'Working…',
  reviewPending: 'Review required',
  blocked: 'Manual migration required',
  failed: 'Needs attention',
  prepare: 'Prepare',
  start: 'Start preview',
  open: 'Open in browser',
  stop: 'Stop',
  connect: 'Connect',
  disconnect: 'Disconnect',
  connecting: 'Connecting…',
  managedDescription:
    'A dedicated local backend and database. Stopping preserves your preview data.',
  prepareHint: 'Complete the sign-in settings below, then prepare your backend.',
  runningHint: 'Frontend changes update automatically in your browser.',
  readyHint: 'Your backend is prepared. Start it to preview your app.',
  stoppedHint: 'Your preview data is retained. Prepare again to continue.',
  externalDescription:
    'Connect a backend already running from your current export with npm run local:up.',
  externalData: 'Use a dedicated preview database. Actions save real data.',
  externalHint: 'Disconnect closes this preview. Your backend and database keep running.',
  apiPort: 'API port · 127.0.0.1',
  previewAddress: 'Preview address',
  settings: 'Connection & sign-in',
  configured: 'Configured',
  required: 'Setup required',
  issuer: 'Document issuer',
  clientId: 'Public client ID',
  authenticationRequired: 'Configure the document NestJS backend and login pages first.',
  audience: 'Server audience',
  jwks: 'HTTPS JWKS URL',
  advanced: 'Advanced settings',
  ca: 'Trusted CA file (optional)',
  caRequired: 'Trusted CA file (required for local Keycloak)',
  caHint: 'Select the public CA certificate used by your local HTTPS identity service.',
  chooseCA: 'Choose file',
  chooseCATitle: 'Choose the trusted public CA certificate',
  chooseCAFailed: 'Could not select the certificate. Enter its absolute path instead.',
  callback: 'Allowed redirect URI',
  origin: 'Allowed web origin',
  browserHint:
    'Add these values to your identity client. Sign-in and data stay in your browser; a full reload requires signing in again.',
  serviceDetails: 'Service details',
  api: 'Backend API',
  database: 'Preview database',
  log: 'Progress log',
  viewLogs: 'View logs',
  noLogs: 'Progress appears here after you prepare the backend.',
  review: 'Review changes',
  initialTitle: 'Initialize preview database',
  updateTitle: 'Backend changes need review',
  reviewDescription: 'Review the exact changes before applying them to your preview database.',
  reviewClose: 'Close change review',
  reviewSQL: 'SQL to execute',
  noSQL: 'No database SQL changes.',
  blockedHint: 'A manual migration is required. Your preview database will not be reset.',
  initialConfirm: 'Install dependencies & initialize DB',
  updateConfirm: 'Apply reviewed update & rebuild',
  cancel: 'Back',
  copy: 'Copy',
  copied: 'Copied',
  copyFailed: 'Copy failed. Select and copy the value manually.',
  presets: 'Common configurations',
  presetHint:
    'Presets fill empty fields only. They do not install an identity service or change your document.',
  presetLabel: 'Configuration preset',
  applyPreset: 'Apply preset',
  presetApplied: 'Preset applied. Complete the remaining fields below.',
  presetReady: 'Preset applied. You can prepare the backend.',
  localPreset: 'Local Keycloak · personal notes',
  httpsPreset: 'Self-hosted HTTPS Keycloak',
  oidcPreset: 'Generic OIDC',
  localPresetHint:
    'For the local OpenPencil Keycloak service. Select its trusted CA certificate after applying.',
  httpsPresetHint: 'Derives the signing-key URL from your document’s HTTPS Keycloak realm.',
  oidcPresetHint:
    'Keeps your existing identity provider. Enter its published HTTPS signing-key URL.',
  presetDocumentRequired: 'Configure document sign-in before applying a preset.',
  presetLocalRequired:
    'This preset needs document issuer http://127.0.0.1:18080/realms/openpencil.',
  presetHTTPSRequired:
    'This preset needs a document HTTPS Keycloak issuer ending in /realms/<realm>.',
  presetJWKSInvalid: 'Enter a valid HTTPS signing-key URL.',
  presetCAInvalid: 'Enter an absolute certificate path.',
  presetAudienceInvalid: 'Enter a valid server audience.',
  oidcRequirements: 'Requires RS256 or ES256 signed JWT access tokens and a UUID subject.',
  missingFields: 'Complete these fields',
  identityClient: 'Keycloak client configuration',
  identityClientHint:
    'Import as a new client in the matching realm. For an existing client, add these redirects and audience mapper while preserving its current settings.',
  clientJSON: 'Public client JSON'
}

const chinese: typeof english = {
  title: 'NestJS 后端',
  description: '管理实时预览使用的后端服务。',
  close: '关闭后端面板',
  managed: '本地托管',
  external: '外部连接',
  ready: '可以启动',
  unconfigured: '尚未配置',
  stopped: '已停止',
  running: '运行中',
  busy: '处理中…',
  reviewPending: '等待确认',
  blocked: '需要手动迁移',
  failed: '需要处理',
  prepare: '配置并检查',
  start: '启动预览',
  open: '打开预览',
  stop: '停止',
  connect: '连接后端',
  disconnect: '断开连接',
  connecting: '连接中…',
  managedDescription: '使用独立的本地后端和数据库。停止服务会保留预览数据。',
  prepareHint: '先完善下方登录设置，再检查并准备后端。',
  runningHint: '前端修改会自动更新到浏览器中。',
  readyHint: '后端已准备就绪，可以启动并预览应用。',
  stoppedHint: '预览数据已保留。重新检查配置后即可继续。',
  externalDescription: '连接已运行的后端。请先在当前导出项目中执行 npm run local:up。',
  externalData: '请使用独立的预览数据库，页面操作会保存真实数据。',
  externalHint: '断开连接会关闭此次预览，后端和数据库继续运行。',
  apiPort: 'API 端口 · 127.0.0.1',
  previewAddress: '预览地址',
  settings: '连接与登录设置',
  configured: '已配置',
  required: '待配置',
  issuer: '文档 Issuer',
  clientId: '公开 Client ID',
  authenticationRequired: '请先配置文档的 NestJS 后端和登录页面。',
  audience: '服务端 Audience',
  jwks: 'HTTPS JWKS 地址',
  advanced: '高级设置',
  ca: '受信任 CA 文件（可选）',
  caRequired: '受信任 CA 文件（本地 Keycloak 必填）',
  caHint: '选择本地 HTTPS 身份服务使用的公开 CA 证书。',
  chooseCA: '选择文件',
  chooseCATitle: '选择受信任的公开 CA 证书',
  chooseCAFailed: '无法选择证书，请手动填写其绝对路径。',
  callback: '允许的回调地址',
  origin: '允许的网页来源',
  browserHint:
    '将这两项添加到身份服务的客户端配置。登录和数据留在浏览器中，完整刷新后需要重新登录。',
  serviceDetails: '服务详情',
  api: '后端 API',
  database: '预览数据库',
  log: '运行日志',
  viewLogs: '查看日志',
  noLogs: '检查并准备后端后，这里会显示运行进度。',
  review: '审核变更',
  initialTitle: '初始化预览数据库',
  updateTitle: '后端变更等待审核',
  reviewDescription: '确认以下精确变更后，再应用到预览数据库。',
  reviewClose: '关闭变更审核',
  reviewSQL: '将执行的 SQL',
  noSQL: '没有数据库 SQL 变更。',
  blockedHint: '此变更需要手动迁移，预览数据库不会被重置。',
  initialConfirm: '安装依赖并初始化数据库',
  updateConfirm: '应用已审核变更并重新构建',
  cancel: '返回',
  copy: '复制',
  copied: '已复制',
  copyFailed: '复制失败，请选中内容后手动复制。',
  presets: '常用配置',
  presetHint: '预设只补全空字段，不安装身份服务，也不会修改文档。',
  presetLabel: '配置方案',
  applyPreset: '应用预设',
  presetApplied: '已应用预设，请完善下方剩余字段。',
  presetReady: '已应用预设，可以检查并准备后端。',
  localPreset: '本地 Keycloak · 个人笔记',
  httpsPreset: '自建 HTTPS Keycloak',
  oidcPreset: '通用 OIDC',
  localPresetHint: '适用于本地 OpenPencil Keycloak 服务，应用后请选择其受信任 CA 证书。',
  httpsPresetHint: '根据文档中的 HTTPS Keycloak Realm 补全签名密钥地址。',
  oidcPresetHint: '使用现有身份服务，填写它公开的 HTTPS 签名密钥地址。',
  presetDocumentRequired: '请先配置文档登录，再应用预设。',
  presetLocalRequired: '此预设要求文档 Issuer 为 http://127.0.0.1:18080/realms/openpencil。',
  presetHTTPSRequired: '此预设要求文档使用以 /realms/<realm> 结尾的 HTTPS Keycloak Issuer。',
  presetJWKSInvalid: '请填写有效的 HTTPS 签名密钥地址。',
  presetCAInvalid: '请填写证书的绝对路径。',
  presetAudienceInvalid: '请填写有效的服务端 Audience。',
  oidcRequirements: '访问令牌需为 RS256 或 ES256 签名的 JWT，且用户标识 sub 为 UUID。',
  missingFields: '还需填写',
  identityClient: 'Keycloak 客户端配置',
  identityClientHint:
    '可在对应 Realm 中导入为新客户端。已有客户端请追加这些回调地址和 Audience 映射，保留现有设置。',
  clientJSON: '公开客户端 JSON'
}

export function backendPreviewCopy(locale: string) {
  return locale === 'zh-CN' ? chinese : english
}
