/**
 * Phase 3 §2: scaffold for `src/_lowcode_supabase.ts`, the lowcode runtime
 * that wraps `@supabase/supabase-js`. Step 2 reserves the module + pins the
 * supabase-js version so the preview-resolvable test can prove the dev-server
 * can resolve the bare `@supabase/supabase-js` import from the monorepo's
 * hoisted `node_modules`. Step 3 fills in `buildLowcodeSupabaseRuntime`:
 *
 *   getSupabaseClient()           — module-scope singleton (decision #h).
 *   useSupabaseAuth()             — React hook, returns { user, signIn, signOut }.
 *
 * On module load the runtime bootstraps `$currentUser` from
 * `supabase.auth.getSession()` and then keeps it in sync via
 * `onAuthStateChange`. Any page that reads `$currentUser` via
 * `useDocState('$currentUser')` therefore sees a valid auth snapshot
 * (decisions #e + #h).
 */
import type { IRSupabaseConfig } from '#compiler/ir/types'

/** supabase-js pin for emitted projects. Same `^2.x` shape the package.json
 *  devDependency uses so the preview-resolvable copy and the exported-project
 *  copy never diverge. */
export const SUPABASE_JS_VERSION = '^2.100.0'

/**
 * Build the contents of `src/_lowcode_supabase.ts`. Caller asserts that
 * `config` is the same object the root SceneNode carries; `url` and
 * `anonKey` are spliced verbatim via `JSON.stringify` so quotes and
 * backslashes survive into the emitted module unchanged.
 */
export function buildLowcodeSupabaseRuntime(config: IRSupabaseConfig): string {
  const url = JSON.stringify(config.url)
  const anonKey = JSON.stringify(config.anonKey)
  return `// Auto-generated by OpenPencil compiler (Phase 3 §2). Do not edit by hand.
import { createClient, type Session } from '@supabase/supabase-js'

import { setDocState, useDocState } from './_lowcode_state'

let _client: ReturnType<typeof createClient> | null = null
export function getSupabaseClient() {
  if (!_client) _client = createClient(${url}, ${anonKey})
  return _client
}

const supabase = getSupabaseClient()

function toCurrentUser(session: Session | null): Record<string, unknown> {
  return {
    id: session?.user.id ?? null,
    email: session?.user.email ?? null,
    signedIn: !!session
  }
}

void supabase.auth.getSession().then(({ data: { session } }) => {
  setDocState('$currentUser', toCurrentUser(session))
})
supabase.auth.onAuthStateChange((_event, session) => {
  setDocState('$currentUser', toCurrentUser(session))
})

export function useSupabaseAuth() {
  const user = useDocState('$currentUser')
  return {
    user,
    signIn: (email: string, password: string) =>
      supabase.auth.signInWithPassword({ email, password }),
    signOut: () => supabase.auth.signOut()
  }
}
`
}
