/**
 * Phase 2 §2: scaffold `src/_lowcode_state.ts`, the lowcode runtime that
 * backs document-level state ("Document State"). zustand sits underneath,
 * but the emitted module only exports our three-function API so generated
 * page code never touches zustand symbols directly.
 *
 *   useDocState(name)            — Hook, subscribes the component.
 *   setDocState(name, value|fn)  — Plain function, supports React-style
 *                                  functional updater `(prev) => …`.
 *   getDocStateSnapshot(name)    — Plain function, non-subscribing read.
 *
 * The file is emitted only when `IRTree.docStates.length > 0`; pages that
 * never bind a doc-state ref or fire setVariable don't import from it.
 */
import type { IRDocStateDecl } from '#compiler/ir/types'

/** zustand pin for emitted projects. ^5.x targets React 18+, which matches
 *  the Phase 0 / Phase 1 React floor (18.3.1 and 19.2.0 are both supported). */
export const ZUSTAND_VERSION = '^5.0.0'

const TS_TYPE_BY_STATE_VALUE_TYPE: Record<IRDocStateDecl['type'], string> = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  array: 'unknown[]',
  object: 'Record<string, unknown>'
}

/**
 * Build the contents of `src/_lowcode_state.ts`. Caller asserts that
 * `decls.length > 0` — passing an empty list returns the empty string,
 * which the caller treats as "do not emit".
 */
export function buildLowcodeStateRuntime(decls: readonly IRDocStateDecl[]): string {
  if (decls.length === 0) return ''
  // Stable order so two compiles of the same scene graph produce identical
  // output. Names are validated upstream (`collectDocStates` rejects empty
  // or duplicate names), so a simple string sort is enough.
  const sorted = [...decls].sort((a, b) => a.name.localeCompare(b.name))
  const typeFields = sorted
    .map((d) => `  ${d.name}: ${TS_TYPE_BY_STATE_VALUE_TYPE[d.type]}`)
    .join('\n')
  const initialFields = sorted
    .map((d) => `  ${d.name}: ${JSON.stringify(d.defaultValue)}`)
    .join(',\n')
  return `// Auto-generated by OpenPencil compiler (Phase 2 §2). Do not edit by hand.
import { useStore } from 'zustand'
import { createStore } from 'zustand/vanilla'

type DocState = {
${typeFields}
}

const initial: DocState = {
${initialFields}
}

const store = createStore<DocState>(() => initial)

export function useDocState<K extends keyof DocState>(name: K): DocState[K] {
  return useStore(store, (s) => s[name])
}

export function setDocState<K extends keyof DocState>(
  name: K,
  value: DocState[K] | ((prev: DocState[K]) => DocState[K])
): void {
  store.setState((s) => {
    const next =
      typeof value === 'function'
        ? (value as (prev: DocState[K]) => DocState[K])(s[name])
        : value
    return { [name]: next } as Partial<DocState>
  })
}

export function getDocStateSnapshot<K extends keyof DocState>(name: K): DocState[K] {
  return store.getState()[name]
}
`
}
