/**
 * Phase 3 §2: scaffold for `src/_lowcode_supabase.ts`, the lowcode runtime
 * that wraps `@supabase/supabase-js`. Step 2 reserves the module + pins the
 * supabase-js version so the preview-resolvable test can prove the dev-server
 * can resolve the bare `@supabase/supabase-js` import from the monorepo's
 * hoisted `node_modules`. Step 3 fills in `buildLowcodeSupabaseRuntime`:
 *
 *   getSupabaseClient()           — module-scope singleton (decision #h).
 *   useSupabaseAuth()             — React hook, returns { user, signIn, signOut }.
 *
 * On module load the runtime bootstraps `$currentUser` from
 * `supabase.auth.getSession()` and then keeps it in sync via
 * `onAuthStateChange`. Any page that reads `$currentUser` via
 * `useDocState('$currentUser')` therefore sees a valid auth snapshot
 * (decisions #e + #h).
 */
import type { IRSupabaseConfig } from '#compiler/ir/types'

/** supabase-js pin for emitted projects. Same `^2.x` shape the package.json
 *  devDependency uses so the preview-resolvable copy and the exported-project
 *  copy never diverge. */
export const SUPABASE_JS_VERSION = '^2.100.0'

/**
 * Build the contents of `src/_lowcode_supabase.ts`. Caller asserts that
 * `config` is the same object the root SceneNode carries; `url` and
 * `anonKey` are spliced verbatim via `JSON.stringify` so quotes and
 * backslashes survive into the emitted module unchanged.
 *
 * Phase 3 §5: the connection reads `import.meta.env.VITE_SUPABASE_URL` /
 * `VITE_SUPABASE_ANON_KEY` with the design-time values as a baked fallback, so
 * the same build deploys per-environment (set the env vars to override; unset
 * falls back to the design-time project). The anon key is public by design, so
 * baking it as the fallback is safe.
 */
export function buildLowcodeSupabaseRuntime(config: IRSupabaseConfig): string {
  const url = JSON.stringify(config.url)
  const anonKey = JSON.stringify(config.anonKey)
  return `// Auto-generated by OpenPencil compiler (Phase 3 §2). Do not edit by hand.
import { createClient, type Session } from '@supabase/supabase-js'

import { setDocState, useDocState } from './_lowcode_state'

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? ${url}
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? ${anonKey}

let _client: ReturnType<typeof createClient> | null = null
export function getSupabaseClient() {
  if (!_client) _client = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)
  return _client
}

const supabase = getSupabaseClient()

function toCurrentUser(session: Session | null): Record<string, unknown> {
  return {
    id: session?.user.id ?? null,
    email: session?.user.email ?? null,
    signedIn: !!session
  }
}

void supabase.auth.getSession().then(({ data: { session } }) => {
  setDocState('$currentUser', toCurrentUser(session))
})
supabase.auth.onAuthStateChange((_event, session) => {
  setDocState('$currentUser', toCurrentUser(session))
})

export function useSupabaseAuth() {
  const user = useDocState('$currentUser')
  return {
    user,
    signIn: (email: string, password: string) =>
      supabase.auth.signInWithPassword({ email, password }),
    signOut: () => supabase.auth.signOut()
  }
}
`
}

/**
 * `src/vite-env.d.ts` — pulls in Vite's `import.meta.env` typing so the
 * standalone export's `tsc --noEmit && vite build` accepts the
 * `import.meta.env.VITE_SUPABASE_*` reads in the runtime above. Only emitted
 * when a Supabase config is present (the only place we read import.meta.env).
 */
export function buildViteEnvDts(): string {
  return `/// <reference types="vite/client" />\n`
}

/**
 * `.env.example` — a copy-to-`.env` template documenting the per-environment
 * Supabase overrides. Pre-filled with the design-time values (the public anon
 * key); editing `.env` and rebuilding points the app at another project.
 */
export function buildSupabaseEnvExample(config: IRSupabaseConfig): string {
  return `# Supabase connection for the deployed app.
# Copy this file to .env and edit per environment (preview / staging / prod).
# Unset values fall back to the design-time project baked into the build.
VITE_SUPABASE_URL=${config.url}
VITE_SUPABASE_ANON_KEY=${config.anonKey}
`
}
