// The contents of `src/__preview-bridge.ts` that the React adapter writes
// into a dev-mode preview project. The file is a plain template literal —
// the compiler is Bun/Node-only, but the runtime it emits ships to the
// in-iframe preview build and gets compiled by Vite there.
//
// Contract with PreviewPane.vue (docs/lowcode-phase-0.md §5.4):
//
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'select', id }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'select', id }
//
// `id` is `null` when nothing is selected; otherwise the SceneNode id that
// the React adapter emitted as `data-node-id`. The iframe runtime only
// surrenders a click to the editor when the user is holding Alt/Option —
// plain clicks still flow to the user's onClick handlers so the live
// preview keeps working as an app, not just a static highlight target.

export function buildPreviewBridge(): string {
  return `// Auto-generated by @open-pencil/compiler — canvas↔preview selection bridge.
// Only emitted when CompilerOptions.devMode is true.

const INBOUND_SOURCE = 'op-lowcode-editor'
const OUTBOUND_SOURCE = 'op-lowcode-preview'

declare global {
  interface Window {
    __openPencilPreviewBridge?: boolean
  }
}

interface InboundSelect {
  source: typeof INBOUND_SOURCE
  type: 'select'
  id: string | null
}

if (typeof window !== 'undefined' && !window.__openPencilPreviewBridge) {
  window.__openPencilPreviewBridge = true

  const overlay = document.createElement('div')
  overlay.setAttribute('data-op-preview-overlay', '')
  overlay.style.position = 'fixed'
  overlay.style.left = '0px'
  overlay.style.top = '0px'
  overlay.style.width = '0px'
  overlay.style.height = '0px'
  overlay.style.pointerEvents = 'none'
  overlay.style.border = '2px solid #4c8bf5'
  overlay.style.background = '#4c8bf514'
  overlay.style.boxSizing = 'border-box'
  overlay.style.zIndex = '2147483647'
  overlay.style.display = 'none'
  overlay.style.transition = 'all 80ms linear'
  document.documentElement.appendChild(overlay)

  let currentId: string | null = null

  function updateOverlay(): void {
    if (!currentId) {
      overlay.style.display = 'none'
      return
    }
    const el = document.querySelector(
      \`[data-node-id="\${CSS.escape(currentId)}"]\`
    ) as HTMLElement | null
    if (!el) {
      overlay.style.display = 'none'
      return
    }
    const r = el.getBoundingClientRect()
    overlay.style.display = 'block'
    overlay.style.left = \`\${r.left}px\`
    overlay.style.top = \`\${r.top}px\`
    overlay.style.width = \`\${r.width}px\`
    overlay.style.height = \`\${r.height}px\`
  }

  window.addEventListener('message', (event: MessageEvent) => {
    const data = event.data as Partial<InboundSelect> | null
    if (!data || data.source !== INBOUND_SOURCE || data.type !== 'select') return
    currentId = typeof data.id === 'string' ? data.id : null
    updateOverlay()
  })

  // Alt/Option-click is the "select in canvas" affordance — plain clicks pass
  // through so the user's onClick handlers still fire as in any real app.
  document.addEventListener(
    'click',
    (event) => {
      if (!event.altKey) return
      const target = event.target as Element | null
      const host = target?.closest('[data-node-id]') as HTMLElement | null
      const id = host?.dataset.nodeId
      if (!id) return
      event.preventDefault()
      event.stopPropagation()
      window.parent?.postMessage({ source: OUTBOUND_SOURCE, type: 'select', id }, '*')
    },
    true
  )

  window.addEventListener('scroll', updateOverlay, true)
  window.addEventListener('resize', updateOverlay)

  // Re-derive the overlay rect every frame while highlighted so HMR-induced
  // layout shifts don't strand the box on stale coordinates.
  function tick(): void {
    if (currentId) updateOverlay()
    requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

export {}
`
}
