// The contents of `src/__preview-bridge.ts` that the React adapter writes
// into a dev-mode preview project. The file is a plain template literal —
// the compiler is Bun/Node-only, but the runtime it emits ships to the
// in-iframe preview build and gets compiled by Vite there.
//
// Contract with PreviewPane.vue (docs/lowcode-phase-0.md §5.4 + Phase 2 §7):
//
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'select',   id }
//   editor → iframe   { source: 'op-lowcode-editor',   type: 'navigate', route }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'select',   id }
//   iframe → editor   { source: 'op-lowcode-preview',  type: 'navigate', route }
//
// `id` is `null` when nothing is selected; otherwise the SceneNode id that
// the React adapter emitted as `data-node-id`. The iframe runtime only
// surrenders a click to the editor when the user is holding Alt/Option —
// plain clicks still flow to the user's onClick handlers so the live
// preview keeps working as an app, not just a static highlight target.
//
// Phase 2 §7: `navigate` rides the same channel so the editor and the
// iframe's react-router-dom stay in sync. Inbound `navigate` drives
// `history.pushState` + a synthetic `popstate` (the way to programmatically
// route in any history-API router from outside React). Outbound `navigate`
// fires from a `history.pushState` monkeypatch (react-router-dom's nav goes
// through pushState without firing popstate) plus a `popstate` listener
// (back/forward). A `suppressOutbound` flag breaks the echo loop on inbound.

export function buildPreviewBridge(): string {
  return `// Auto-generated by @open-pencil/compiler — canvas↔preview bridge.
// Only emitted when CompilerOptions.devMode is true.

const INBOUND_SOURCE = 'op-lowcode-editor'
const OUTBOUND_SOURCE = 'op-lowcode-preview'
// Editor-only preview selection chrome. Keep these fixed, high-contrast colors
// independent from generated app theme tokens so the canvas↔preview bridge is
// readable even when the user design overrides runtime CSS variables.
const PREVIEW_SELECTION_OVERLAY_BORDER = '2px solid #4c8bf5'
const PREVIEW_SELECTION_OVERLAY_BACKGROUND = '#4c8bf514'

interface DocStore {
  getState: () => Record<string, unknown>
  setState: (partial: Record<string, unknown>) => void
  subscribe: (
    listener: (state: Record<string, unknown>, prev: Record<string, unknown>) => void
  ) => () => void
}

declare global {
  interface Window {
    __openPencilPreviewBridge?: boolean
    // Phase 3 §4.6 — the lowcode docState zustand store, exposed by
    // _lowcode_state.ts so the bridge can mirror runtime state across peers.
    __opDocStore?: DocStore
  }
}

interface InboundSelect {
  source: typeof INBOUND_SOURCE
  type: 'select'
  id: string | null
}
interface InboundNavigate {
  source: typeof INBOUND_SOURCE
  type: 'navigate'
  route: string
}
interface InboundDocState {
  source: typeof INBOUND_SOURCE
  type: 'docState'
  name: string
  value: unknown
}
type Inbound = InboundSelect | InboundNavigate | InboundDocState

if (typeof window !== 'undefined' && !window.__openPencilPreviewBridge) {
  window.__openPencilPreviewBridge = true

  const overlay = document.createElement('div')
  overlay.setAttribute('data-op-preview-overlay', '')
  overlay.style.position = 'fixed'
  overlay.style.left = '0px'
  overlay.style.top = '0px'
  overlay.style.width = '0px'
  overlay.style.height = '0px'
  overlay.style.pointerEvents = 'none'
  overlay.style.border = PREVIEW_SELECTION_OVERLAY_BORDER
  overlay.style.background = PREVIEW_SELECTION_OVERLAY_BACKGROUND
  overlay.style.boxSizing = 'border-box'
  overlay.style.zIndex = '2147483647'
  overlay.style.display = 'none'
  overlay.style.transition = 'all 80ms linear'
  document.documentElement.appendChild(overlay)

  let currentId: string | null = null
  // §7 decision #f: suppress outbound navigate while replaying an inbound
  // navigate, so the editor→iframe→editor echo loop never fires.
  let suppressOutbound = false

  // Alias the real pushState BEFORE patching, so the patch can forward
  // calls (including our own replay) without re-entering itself.
  const nativePushState = history.pushState.bind(history)

  function updateOverlay(): void {
    if (!currentId) {
      overlay.style.display = 'none'
      return
    }
    const el = document.querySelector(
      \`[data-node-id="\${CSS.escape(currentId)}"]\`
    ) as HTMLElement | null
    if (!el) {
      overlay.style.display = 'none'
      return
    }
    const r = el.getBoundingClientRect()
    overlay.style.display = 'block'
    overlay.style.left = \`\${r.left}px\`
    overlay.style.top = \`\${r.top}px\`
    overlay.style.width = \`\${r.width}px\`
    overlay.style.height = \`\${r.height}px\`
  }

  function postOutboundNavigate(route: string): void {
    if (suppressOutbound) return
    window.parent?.postMessage(
      { source: OUTBOUND_SOURCE, type: 'navigate', route },
      '*'
    )
  }

  // react-router-dom's internal navigate() calls history.pushState directly
  // and does NOT dispatch popstate; patching pushState is the only way to
  // catch in-app nav from outside the React tree.
  history.pushState = function (
    this: History,
    ...args: Parameters<typeof history.pushState>
  ): void {
    nativePushState(...args)
    postOutboundNavigate(location.pathname)
  } as typeof history.pushState

  // popstate covers browser back/forward + our own synthetic dispatch.
  window.addEventListener('popstate', () => {
    postOutboundNavigate(location.pathname)
  })

  // Phase 3 §4.6 — runtime docState collaboration. Mirror the lowcode zustand
  // store's per-key changes across peers. suppressDocStateOutbound breaks the
  // remote→setState→subscribe→outbound echo, mirroring suppressOutbound above.
  let suppressDocStateOutbound = false

  function wireDocStore(store: DocStore): void {
    store.subscribe((state, prev) => {
      if (suppressDocStateOutbound) return
      for (const name of Object.keys(state)) {
        if (state[name] !== prev[name]) {
          window.parent?.postMessage(
            { source: OUTBOUND_SOURCE, type: 'docState', name: name, value: state[name] },
            '*'
          )
        }
      }
    })
  }

  // _lowcode_state.ts may evaluate before or after this bridge; cover both —
  // wire now if the store is already up, else wait for its ready event.
  if (window.__opDocStore) {
    wireDocStore(window.__opDocStore)
  } else {
    window.addEventListener(
      'op-docstore-ready',
      () => {
        if (window.__opDocStore) wireDocStore(window.__opDocStore)
      },
      { once: true }
    )
  }

  window.addEventListener('message', (event: MessageEvent) => {
    const data = event.data as Partial<Inbound> | null
    if (!data || data.source !== INBOUND_SOURCE) return
    if (data.type === 'select') {
      currentId = typeof data.id === 'string' ? data.id : null
      updateOverlay()
      return
    }
    if (data.type === 'navigate') {
      const route = typeof data.route === 'string' ? data.route : null
      if (!route) return
      // No-op if the iframe is already at this route — avoids stray
      // outbound traffic on init or on duplicate page-id watcher fires.
      if (location.pathname === route) return
      suppressOutbound = true
      try {
        nativePushState(null, '', route)
        window.dispatchEvent(new PopStateEvent('popstate'))
      } finally {
        suppressOutbound = false
      }
      return
    }
    if (data.type === 'docState') {
      const store = window.__opDocStore
      if (!store || typeof data.name !== 'string') return
      // Apply the remote value without re-broadcasting it back out.
      suppressDocStateOutbound = true
      try {
        store.setState({ [data.name]: data.value })
      } finally {
        suppressDocStateOutbound = false
      }
    }
  })

  // Alt/Option-click is the "select in canvas" affordance — plain clicks pass
  // through so the user's onClick handlers still fire as in any real app.
  document.addEventListener(
    'click',
    (event) => {
      if (!event.altKey) return
      const target = event.target as Element | null
      const host = target?.closest('[data-node-id]') as HTMLElement | null
      const id = host?.dataset.nodeId
      if (!id) return
      event.preventDefault()
      event.stopPropagation()
      window.parent?.postMessage({ source: OUTBOUND_SOURCE, type: 'select', id }, '*')
    },
    true
  )

  window.addEventListener('scroll', updateOverlay, true)
  window.addEventListener('resize', updateOverlay)

  // Re-derive the overlay rect every frame while highlighted so HMR-induced
  // layout shifts don't strand the box on stale coordinates.
  function tick(): void {
    if (currentId) updateOverlay()
    requestAnimationFrame(tick)
  }
  requestAnimationFrame(tick)
}

export {}
`
}
