const english = {
  shop: 'Commerce shop',
  cart: 'Shopping cart',
  checkout: 'Checkout',
  purchases: 'My purchases',
  orders: 'Delivery and refunds',
  merchantOrders: 'Merchant fulfillment',
  settlements: 'Merchant settlements',
  operator: 'Platform bookkeeping',
  stores: 'Store directory',
  myStore: 'My store',
  login: 'Commerce sign in',
  admin: 'Catalog manager',
  select: 'Select',
  selected: 'Selected record',
  add: 'Save cart quantity',
  remove: 'Remove from cart',
  quantity: 'Quantity',
  review: 'Review this cart',
  recipient: 'Recipient',
  phone: 'Phone',
  address: 'Delivery address',
  place: 'Place purchase',
  pay: 'Simulate successful payment',
  failPayment: 'Simulate failed payment',
  cancel: 'Cancel unpaid purchase',
  reason: 'Refund reason',
  unknownPayment: 'Simulate unknown result',
  simulate: 'Run payment simulation',
  paymentChoice: 'Selected simulation outcome',
  refund: 'Request refund',
  carrier: 'Carrier',
  tracking: 'Tracking number',
  ship: 'Record shipment',
  deliver: 'Confirm delivery',
  reference: 'External record reference',
  approve: 'Approve refund',
  reject: 'Reject refund',
  settle: 'Record settlement',
  items: 'Order items',
  shipments: 'Shipments',
  refunds: 'Refund requests',
  title: 'Store title',
  createStore: 'Open my store',
  manage: 'Manage products',
  search: 'Search products',
  reset: 'Show all products',
  visit: 'Browse this store',
  first: 'First page',
  next: 'Next page',
  signIn: 'Sign in',
  signOut: 'Sign out',
  inspect: 'Inspect saved request',
  retry: 'Retry saved request',
  acknowledge: 'Finish reviewed request',
  recovery:
    'A saved request is kept until you review its result. Retry uses the original parameters.',
  acknowledgeHint:
    'I have checked the server result. Finish this saved request and allow another action?',
  confirm: 'Confirm this action?',
  result: 'Server result',
  none: 'Choose a record to continue.',
  cartHint:
    'Your cart is saved to your account. Saving a quantity replaces that SKU quantity. Prices and stock are checked again at checkout.',
  checkoutHint:
    'Review the current cart before submitting. One purchase is split into one order per store. All amounts are integer minor currency units.',
  paymentHint:
    'DEMO ONLY: explicitly enable simulation in the exported local application; managed editor preview leaves it disabled. Production rejects simulation and no money is collected. Failure cancels the purchase and releases stock; shop and check out again. An unknown result keeps payment pending.',
  deliveryHint:
    'Tracking is entered manually; no carrier service is connected. Confirm delivery only after receiving the goods. Voluntary refunds cover the whole paid store order before shipment; shipped or settled orders cannot use this refund flow.',
  merchantHint:
    'Requires merchant and ownership of the store. Select a paid order, verify its items and address, then record the actual shipment.',
  settlementHint:
    'Amounts and eligibility are calculated by the server after delivery and the settlement delay. Recorded means bookkeeping confirmation, not a bank transfer.',
  operatorHint:
    'Requires commerce-operator. Review refund and settlement records before confirming. These controls record decisions; they do not transfer money.',
  storeHint:
    'The identity service must grant merchant before opening a store. Each account owns at most one store.',
  singleHint: 'This edition permits one store for the entire application.',
  created: 'Store created. Select it above to manage products.',
  loginHint: 'Sign in to use your saved cart, purchases and permitted merchant operations.',
  busy: 'Request in progress…',
  invalid: 'Complete the required fields with valid values.',
  summary: 'Cart summary',
  status: 'Status',
  subtotal: 'Subtotal',
  total: 'Total',
  stock: 'Stock',
  currency: 'Amounts are shown in integer minor currency units.',
  purchaseChildren: 'Store orders for the selected purchase',
  details: 'Items and shipment details',
  success: 'Recorded',
  empty: 'No saved request',
  unavailable: 'Saved request is incompatible',
  saved: 'Saved request',
  notInspected: 'Inspect after signing in to recover an earlier attempt.'
}
type OperationsCopy = { [Key in keyof typeof english]: string }
const chinese: OperationsCopy = {
  shop: '电商商城',
  cart: '购物车',
  checkout: '确认结账',
  purchases: '我的采购单',
  orders: '收货与退款',
  merchantOrders: '商家发货',
  settlements: '商家结算',
  operator: '平台账务',
  stores: '店铺目录',
  myStore: '我的店铺',
  login: '电商登录',
  admin: '商品管理',
  select: '选择',
  selected: '当前选择',
  add: '保存购物车数量',
  remove: '从购物车移除',
  quantity: '数量',
  review: '核对本次购物车',
  recipient: '收件人',
  phone: '联系电话',
  address: '收货地址',
  place: '提交采购单',
  pay: '模拟支付成功',
  failPayment: '模拟支付失败',
  cancel: '取消未支付采购单',
  reason: '退款原因',
  unknownPayment: '模拟支付结果未知',
  simulate: '执行支付模拟',
  paymentChoice: '当前模拟结果',
  refund: '申请退款',
  carrier: '承运公司',
  tracking: '运单号',
  ship: '记录发货',
  deliver: '确认收货',
  reference: '外部记录凭证',
  approve: '同意退款',
  reject: '拒绝退款',
  settle: '记录结算',
  items: '订单商品',
  shipments: '物流记录',
  refunds: '退款申请',
  title: '店铺名称',
  createStore: '开设我的店铺',
  manage: '管理商品',
  search: '搜索商品',
  reset: '查看全部商品',
  visit: '浏览本店商品',
  first: '首页',
  next: '下一页',
  signIn: '登录',
  signOut: '退出登录',
  inspect: '检查已保存请求',
  retry: '重试已保存请求',
  acknowledge: '结束已核对请求',
  recovery: '核对服务器结果前保留已保存请求；重试使用原始参数。',
  acknowledgeHint: '已核对服务器结果，结束此次已保存请求并允许下一次操作？',
  confirm: '确认执行此操作？',
  result: '服务器结果',
  none: '请选择记录后继续。',
  cartHint: '购物车保存在你的账号中。保存数量会替换该商品的数量；结账时服务器重新核对价格和库存。',
  checkoutHint:
    '提交前请核对当前购物车。一个采购单按店铺拆成多个订单；金额均为最小货币单位的整数。',
  paymentHint:
    '仅供演示：需在导出的本地应用中显式开启模拟，编辑器托管预览默认不启用，生产环境禁用且不会收款。模拟失败会取消采购单并释放库存，请重新购物结账；结果未知时保持待付款。',
  deliveryHint:
    '运单由商家手动登记，未接入快递服务。收到货后再确认收货；主动退款仅支持已付款、未发货的整份店铺订单，已发货或已结算订单不适用。',
  merchantHint:
    '需要 merchant 角色和店铺所有权。选择已付款订单，核对商品与收货地址后登记实际发货信息。',
  settlementHint:
    '服务器在收货及结算等待期后计算金额和资格。已记录表示账务确认，不代表完成银行转账。',
  operatorHint:
    '需要 commerce-operator 角色。核对退款及结算记录后再确认；这些操作登记处理结果，不执行资金转账。',
  storeHint: '身份服务先授予 merchant，用户才能开店；每个账号最多一家店铺。',
  singleHint: '此版本整个应用只允许创建一家店铺。',
  created: '店铺已创建，请在上方选择店铺管理商品。',
  loginHint: '登录后使用已保存购物车、采购单和获准的商家操作。',
  busy: '正在处理请求…',
  invalid: '请填写必填项并检查输入值。',
  summary: '购物车汇总',
  status: '状态',
  subtotal: '小计',
  total: '合计',
  stock: '库存',
  currency: '金额以最小货币单位的整数显示。',
  purchaseChildren: '当前采购单的店铺订单',
  details: '商品及物流详情',
  success: '已记录',
  empty: '没有已保存请求',
  unavailable: '已保存请求与当前版本不兼容',
  saved: '已保存请求',
  notInspected: '重新登录后可检查并恢复之前的请求。'
}
export function commerceOperationsCopy(locale: string): OperationsCopy {
  return locale.toLowerCase().startsWith('zh') ? chinese : english
}
