import type { CompilerOptions } from '#compiler/types'

import {
  TARO_BABEL_REACT_PRESET_VERSION,
  TARO_BABEL_VERSION,
  TARO_REACT_VERSION,
  TARO_TYPESCRIPT_VERSION,
  TARO_VERSION
} from './constants'

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

export function buildTaroPackageJSON(options: CompilerOptions): string {
  return json({
    name: options.packageName,
    version: '0.1.0',
    private: true,
    description: `${options.productName ?? options.packageName} — generated by OpenPencil`,
    scripts: {
      build: 'taro build --type weapp',
      'build:weapp': 'taro build --type weapp',
      'dev:weapp': 'taro build --type weapp --watch',
      typecheck: 'tsc --noEmit'
    },
    dependencies: {
      '@babel/runtime': TARO_BABEL_VERSION,
      '@tarojs/components': TARO_VERSION,
      '@tarojs/helper': TARO_VERSION,
      '@tarojs/plugin-framework-react': TARO_VERSION,
      '@tarojs/plugin-platform-weapp': TARO_VERSION,
      '@tarojs/react': TARO_VERSION,
      '@tarojs/runtime': TARO_VERSION,
      '@tarojs/shared': TARO_VERSION,
      '@tarojs/taro': TARO_VERSION,
      react: TARO_REACT_VERSION
    },
    devDependencies: {
      '@babel/core': TARO_BABEL_VERSION,
      '@babel/preset-react': TARO_BABEL_REACT_PRESET_VERSION,
      '@tarojs/cli': TARO_VERSION,
      '@tarojs/taro-loader': TARO_VERSION,
      '@tarojs/webpack5-runner': TARO_VERSION,
      '@types/react': '18.3.20',
      '@types/webpack-env': '1.18.8',
      'babel-preset-taro': TARO_VERSION,
      sass: '1.90.0',
      typescript: TARO_TYPESCRIPT_VERSION,
      webpack: '5.101.3'
    },
    engines: { node: '>=22.13.0' }
  })
}

export function buildTaroBabelConfig(): string {
  return `module.exports = {
  presets: [['taro', { framework: 'react', ts: true }]]
}
`
}

export function buildTaroConfig(projectName: string): string {
  return `import { defineConfig, type UserConfigExport } from '@tarojs/cli'

export default defineConfig<'webpack5'>(async (merge) => {
  const base: UserConfigExport<'webpack5'> = {
    projectName: ${JSON.stringify(projectName)},
    date: '2026-08-19',
    designWidth: 750,
    deviceRatio: { 375: 2, 640: 1.17, 750: 1, 828: 0.905 },
    sourceRoot: 'src',
    outputRoot: 'dist',
    framework: 'react',
    compiler: 'webpack5',
    cache: { enable: false },
    mini: {
      postcss: {
        pxtransform: { enable: true },
        url: { enable: true, config: { limit: 0 } },
        cssModules: { enable: false }
      }
    }
  }
  return merge({}, base)
})
`
}

export function buildTaroTsConfig(): string {
  return json({
    compilerOptions: {
      target: 'ES2017',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      allowJs: false,
      allowSyntheticDefaultImports: true,
      esModuleInterop: true,
      forceConsistentCasingInFileNames: true,
      jsx: 'react-jsx',
      noEmit: true,
      resolveJsonModule: true,
      skipLibCheck: true,
      strict: true,
      types: ['@tarojs/taro', '@types/webpack-env']
    },
    include: ['config/**/*.ts', 'src/**/*.ts', 'src/**/*.tsx'],
    exclude: ['dist', 'node_modules']
  })
}

export function buildTaroProjectConfig(projectName: string): string {
  return json({
    description: 'OpenPencil generated Taro WeChat Mini Program source project',
    miniprogramRoot: 'dist/',
    compileType: 'miniprogram',
    projectname: projectName,
    setting: {
      es6: true,
      minified: true,
      postcss: true,
      urlCheck: true
    }
  })
}

export function buildTaroAppConfig(pagePaths: readonly string[], productName: string): string {
  return `export default defineAppConfig({
  pages: ${JSON.stringify(pagePaths, null, 2)},
  window: {
    navigationBarTitleText: ${JSON.stringify(productName)},
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTextStyle: 'black',
    backgroundColor: '#ffffff'
  }
})
`
}

export function buildTaroAppSource(): string {
  return `import type { PropsWithChildren } from 'react'

import './app.scss'

export default function App({ children }: PropsWithChildren) {
  return children
}
`
}

export function buildTaroAppStyle(): string {
  return `page {
  box-sizing: border-box;
  min-height: 100%;
  background: #ffffff;
  color: #111827;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

view, text, image, button, input, textarea, picker, switch {
  box-sizing: border-box;
}
`
}

export function buildTaroPageConfig(title: string): string {
  return `export default definePageConfig({
  navigationBarTitleText: ${JSON.stringify(title)}
})
`
}

export function buildTaroGitignore(): string {
  return `node_modules/
dist/
project.private.config.json
.DS_Store
`
}

export function buildTaroReadme(productName: string): string {
  return `# ${productName}

This source-only Taro React project was generated by OpenPencil for the WeChat Mini Program target.

## Run

1. Install the exact dependencies pinned in \`package.json\`.
2. Run \`npm run build:weapp\`.
3. Open this directory in WeChat DevTools. The generated \`project.config.json\` points to \`dist/\`.
4. Configure the AppID in \`project.private.config.json\` or WeChat DevTools. OpenPencil never exports an AppID, AppSecret, credential, or local source path.

Review \`EXPORT_WARNINGS.md\` when present. Unsupported authored runtime behavior is reported there and is never replaced with network code or embedded secrets.
`
}
