import { describe, expect, test } from 'bun:test'

import { FIGMA_RAW_NODE_FIELD_KEYS } from '@open-pencil/fig/node-change'

const RAW_FIELD_COVERAGE = {
  rendered: [
    'backgroundColor',
    'borderBottomWeight',
    'borderLeftWeight',
    'borderRightWeight',
    'borderStrokeWeightsIndependent',
    'borderTopWeight',
    'derivedTextData',
    'backgroundPaints',
    'effects',
    'fillGeometry',
    'fillPaints',
    'fontName',
    'fontSize',
    'fontVariantCommonLigatures',
    'fontVariantContextualLigatures',
    'fontVariations',
    'guides',
    'layoutGrids',
    'leadingTrim',
    'letterSpacing',
    'lineHeight',
    'mask',
    'maskIsOutline',
    'maskType',
    'maxLines',
    'miterLimit',
    'semanticItalic',
    'semanticWeight',
    'strokeGeometry',
    'textDecorationFillPaints',
    'strokeJoin',
    'strokePaints',
    'strokeWeight',
    'textAutoResize',
    'textData',
    'textDecorationStyle',
    'textUnderlineOffset',
    'textDecorationThickness',
    'textPathStart',
    'textTracking',
    'toggledOffOTFeatures',
    'toggledOnOTFeatures',
    'vectorData'
  ],
  uiEditable: [
    'componentPropAssignments',
    'componentPropDefs',
    'exportSettings',
    'fontSize',
    'letterSpacing',
    'lineHeight',
    'strokeJoin',
    'strokeWeight',
    'textAutoResize'
  ],
  toolEditable: [
    'componentPropDefs',
    'effects',
    'fillPaints',
    'fontSize',
    'letterSpacing',
    'lineHeight',
    'strokeJoin',
    'strokePaints',
    'strokeWeight',
    'textAutoResize',
    'vectorData'
  ],
  roundTripOnly: [
    'annotationCategories',
    'brushType',
    'codeSyntax',
    'componentPropRefs',
    'description',
    'detachedSymbolId',
    'documentColorProfile',
    'editInfo',
    'fontVersion',
    'gridChildHorizontalAlign',
    'gridChildVerticalAlign',
    'gridColumnAnchor',
    'gridColumns',
    'gridColumnsSizing',
    'gridRowAnchor',
    'gridRows',
    'gridRowsSizing',
    'handoffStatusMap',
    'isPageDivider',
    'isSoftDeleted',
    'isStateGroup',
    'key',
    'lockMode',
    'maxSize',
    'minSize',
    'pageType',
    'parameterConsumptionMap',
    'prototypeInteractions',
    'prototypeStartNodeID',
    'scatterStrokeSettings',
    'sectionStatusInfo',
    'slideThemeMap',
    'sortPosition',
    'sourceLibraryKey',
    'stateGroupPropertyValueOrders',
    'styleIdForEffect',
    'styleIdForFill',
    'styleIdForGrid',
    'styleIdForStrokeFill',
    'styleIdForText',
    'styleType',
    'textExplicitLayoutVersion',
    'textUserLayoutVersion',
    'targetAspectRatio',
    'transitionInfo',
    'userFacingVersion',
    'variableConsumptionMap',
    'variableModeBySetMap',
    'variantPropSpecs',
    'vectorOperationVersion',
    'version'
  ],
  motionPrototypeRoundTrip: [
    'animationPresets',
    'backingAnimationPresetId',
    'behaviors',
    'bezierHandles',
    'clipId',
    'connectionType',
    'connectionURL',
    'destinationIsOverlay',
    'easingData',
    'easingType',
    'embedData',
    'interactionDuration',
    'interactionMaintained',
    'interactionType',
    'interpolationType',
    'isClip',
    'isEmbeddedPrototype',
    'keyTrigger',
    'keyframeOperation',
    'keyframeValue',
    'keyframeValueRef',
    'motionTransform',
    'navigationType',
    'objectAnimations',
    'overlayBackgroundAppearance',
    'overlayBackgroundInteraction',
    'overlayPositionType',
    'overlayRelativePosition',
    'playbackStyle',
    'prototypeBackgroundColor',
    'prototypeDevice',
    'prototypeStartingPoint',
    'richMediaData',
    'scrollBehavior',
    'scrollContractedState',
    'scrollDirection',
    'scrollOffset',
    'styleAnimations',
    'styleIdsForAnimation',
    'timelineAssignments',
    'timelineDefinitions',
    'timelineDisabled',
    'timelineDuration',
    'timelineOffset',
    'timelinePosition',
    'timelinePositionType',
    'transitionDuration',
    'transitionNodeID',
    'transitionOverrides',
    'transitionPreserveScroll',
    'transitionShouldSmartAnimate',
    'transitionTimeout',
    'transitionType',
    'useLegacySmartAnimate',
    'videoPlayback',
    'voiceEventPhrase'
  ],
  unsupportedUnknown: []
} as const satisfies Record<string, readonly string[]>

describe('Figma raw field coverage', () => {
  test('classifies every preserved raw node field', () => {
    const knownKeys = new Set(FIGMA_RAW_NODE_FIELD_KEYS)
    const classifiedKeys = new Set(Object.values(RAW_FIELD_COVERAGE).flat())

    expect(new Set(FIGMA_RAW_NODE_FIELD_KEYS).size).toBe(FIGMA_RAW_NODE_FIELD_KEYS.length)
    expect([...classifiedKeys].sort()).toEqual([...knownKeys].sort())
  })

  test('keeps unsupported raw field bucket explicit', () => {
    expect(RAW_FIELD_COVERAGE.unsupportedUnknown).toEqual([])
  })
})
