import type { IRFieldValidation } from '#compiler/ir/types'

import { docStateTypeScript, scriptExpression, scriptJson, type VueEmitContext } from '../shared'

export const VUE_VALIDATION_RUNTIME_FILE = 'src/lowcode-validation.ts'
export const VUE_VALIDATION_CSS_FILE = 'src/lowcode-validation.css'
export const VUE_ASYNC_VALIDATION_ERROR = 'Remote validation is unavailable in this Vue export.'

export function buildVueValidationRuntime(): string {
  return `// Auto-generated by OpenPencil. Do not edit by hand.
export interface OpenPencilValidationRules {
  required?: boolean
  pattern?: string
  minLength?: number
  maxLength?: number
  min?: number
  max?: number
  messages?: {
    required?: string
    pattern?: string
    minLength?: string
    maxLength?: string
    min?: string
    max?: string
  }
}

export function __opValidateValue(
  value: unknown,
  rules: OpenPencilValidationRules
): string | null {
  const messages = rules.messages
  const text = value == null ? '' : String(value)
  const requiredEmpty =
    value == null ||
    value === false ||
    (Array.isArray(value) && value.length === 0) ||
    (typeof value === 'string' && value.trim() === '')
  if (rules.required && requiredEmpty) {
    return messages?.required ?? 'This field is required'
  }
  if (text === '') return null
  if (rules.minLength != null && text.length < rules.minLength) {
    return messages?.minLength ?? 'Must be at least ' + rules.minLength + ' characters'
  }
  if (rules.maxLength != null && text.length > rules.maxLength) {
    return messages?.maxLength ?? 'Must be at most ' + rules.maxLength + ' characters'
  }
  if (rules.pattern != null && !new RegExp(rules.pattern).test(text)) {
    return messages?.pattern ?? 'Invalid format'
  }
  if (rules.min != null && Number(value) < rules.min) {
    return messages?.min ?? 'Must be at least ' + rules.min
  }
  if (rules.max != null && Number(value) > rules.max) {
    return messages?.max ?? 'Must be at most ' + rules.max
  }
  return null
}
`
}

export function buildVueValidationCss(): string {
  return `[data-openpencil-validation-invalid="true"] {
  border-color: var(--color-destructive, #dc2626) !important;
  outline: 1px solid var(--color-destructive, #dc2626);
  outline-offset: 1px;
}

.openpencil-validation-error {
  margin-top: 0.25rem;
  color: var(--color-destructive, #b91c1c);
  font-size: 0.875rem;
  line-height: 1.25rem;
}
`
}

export function buildVueValidationGlue(
  fields: readonly IRFieldValidation[],
  context: VueEmitContext
): string[] {
  if (fields.length === 0) return []
  const validators = fields.map((field) => buildValidator(field, context)).join('\n')
  return [
    `const __fieldErrors = __vueRef<Record<string, string | null>>({})`,
    `const __validators: Record<string, (valueOverride?: unknown) => string | null> = {`,
    validators,
    `}`,
    `function __validateFieldValue(id: string, value: unknown): string | null {`,
    `  const error = __validators[id]?.(value) ?? null`,
    `  __fieldErrors.value = { ...__fieldErrors.value, [id]: error }`,
    `  return error`,
    `}`,
    `function __validateField(id: string): string | null {`,
    `  const error = __validators[id]?.() ?? null`,
    `  __fieldErrors.value = { ...__fieldErrors.value, [id]: error }`,
    `  return error`,
    `}`,
    `function __validateFields(ids: readonly string[]): boolean {`,
    `  const next = { ...__fieldErrors.value }`,
    `  let valid = true`,
    `  for (const id of ids) {`,
    `    const error = __validators[id]?.() ?? null`,
    `    next[id] = error`,
    `    if (error !== null) valid = false`,
    `  }`,
    `  __fieldErrors.value = next`,
    `  return valid`,
    `}`
  ]
}

function buildValidator(field: IRFieldValidation, context: VueEmitContext): string {
  const stateAlias = context.identAliases.get(field.stateName) ?? field.stateName
  let stateRead = stateAlias
  if (field.stateKind === 'docState') {
    stateRead = `__getDocState<${docStateTypeScript(context.docStateTypes.get(field.stateName))}>(${scriptJson(field.stateName)})`
  } else if (context.refNames.has(stateAlias)) {
    stateRead = `${stateAlias}.value`
  }
  const lines = [
    `  ${scriptJson(field.key)}: (valueOverride?: unknown) => {`,
    `    const value = valueOverride !== undefined ? valueOverride : ${stateRead}`,
    `    let error = __opValidateValue(value, ${scriptJson(field.rules)})`
  ]
  if (field.custom) {
    lines.push(
      `    if (error === null && !(${scriptExpression(field.custom.ast, context.refNames, context.identAliases)})) error = ${scriptJson(field.custom.message)}`
    )
  }
  if (field.async) {
    lines.push(`    if (error === null) error = ${scriptJson(VUE_ASYNC_VALIDATION_ERROR)}`)
  }
  lines.push('    return error', '  },')
  return lines.join('\n')
}

export function vueValidationErrorId(key: string): string {
  let hash = 2166136261
  for (let index = 0; index < key.length; index++) {
    hash ^= key.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }
  return `openpencil-validation-error-${(hash >>> 0).toString(36)}`
}

export function vueValidationKeyBinding(context: VueEmitContext, key: string): string {
  const existing = context.validationKeyBindings.get(key)
  if (existing) return existing
  context.expressionIndex += 1
  const binding = `__opValidationKey_${context.expressionIndex}`
  context.validationKeyBindings.set(key, binding)
  context.templateBindings.push(`const ${binding} = ${scriptJson(key)}`)
  return binding
}
