/* eslint-disable max-lines -- emitted browser runtime is intentionally self-contained */
import type { ReactPrototypeManifest } from './types'

/** Build the zero-dependency browser prototype runtime. */
export function buildPrototypeRuntime(manifest: ReactPrototypeManifest): string {
  return `/* Generated by OpenPencil. */
export {}

type PrototypePlacement = 'center' | 'top' | 'right' | 'bottom' | 'left'
type PrototypeDirection = 'left' | 'right' | 'up' | 'down'
type PrototypeTransition =
  | { kind: 'instant' }
  | { kind: 'dissolve'; durationMs: number; easing: string }
  | { kind: 'slide' | 'push'; durationMs: number; easing: string; direction: PrototypeDirection }
  | { kind: 'smartMatch'; durationMs: number; easing: string; fallback: 'dissolve' | 'instant' }
type PrototypeAction =
  | { kind: 'navigate'; route: string; targetNodeId: string; targetPageId: string; targetKind: 'page' | 'frame' }
  | { kind: 'back' }
  | { kind: 'openOverlay'; targetNodeId: string; placement: PrototypePlacement; dismissOnOutside: boolean }
  | { kind: 'closeOverlay' }
interface PrototypeConnection {
  id: string
  sourceNodeId: string
  sourcePageId: string
  trigger: { kind: 'click' } | { kind: 'afterDelay'; delayMs: number }
  action: PrototypeAction
  transition: PrototypeTransition
  interruption: 'replace' | 'queue'
  playback: 'forward' | 'reverse'
}
interface PrototypeManifest {
  connections: PrototypeConnection[]
  pageRoutes: Record<string, string>
  pageTransitionKeys: Record<string, string[]>
  overlayTransitionKeys: Record<string, string[]>
}
interface PrototypeViewTransition {
  finished: Promise<void>
  ready: Promise<void>
  updateCallbackDone: Promise<void>
  skipTransition: () => void
}
interface PrototypeRuntimeHandle {
  dispose: () => void
  inspect: () => {
    activeConnectionId: string | null
    currentPageId: string | null
    delaySourceCount: number
    delayTimerCount: number
    overlayNodeIds: string[]
    queued: boolean
  }
  trigger: (sourceNodeId: string, connectionId?: string) => boolean
}
interface ActiveRun {
  connectionId: string
  controller: AbortController
  animations: Set<Animation>
  reducedMotionTerminated: boolean
  transitionNames: TransitionNameRecord[]
  viewTransition?: PrototypeViewTransition
}
interface OverlayRecord {
  target: HTMLElement
  targetNodeId: string
  parent: Node
  nextSibling: Node | null
  shell: HTMLElement
  backdrop: HTMLElement
  page: HTMLElement | null
  pageHadInert: boolean
  pageAriaHidden: string | null
  previousFocus: HTMLElement | null
  hidden: boolean
  style: string | null
  role: string | null
  ariaModal: string | null
  tabIndex: string | null
  keydown: (event: KeyboardEvent) => void
  outside: (event: PointerEvent) => void
}
interface TransitionNameRecord {
  element: HTMLElement
  priority: string
  value: string
}

declare global {
  interface Window {
    __OPENPENCIL_PROTOTYPE_RUNTIME__?: PrototypeRuntimeHandle
  }
}

const manifest: PrototypeManifest = ${JSON.stringify(manifest)}
const runtimeDocument = typeof document === 'undefined' ? null : document
const runtimeWindow = typeof window === 'undefined' ? null : window
const runtimeGlobal = globalThis as typeof globalThis & {
  __OPENPENCIL_PROTOTYPE_RUNTIME__?: PrototypeRuntimeHandle
}
runtimeGlobal.__OPENPENCIL_PROTOTYPE_RUNTIME__?.dispose()

const connectionsBySource = new Map<string, PrototypeConnection[]>()
for (const connection of manifest.connections) {
  const list = connectionsBySource.get(connection.sourceNodeId) ?? []
  list.push(connection)
  connectionsBySource.set(connection.sourceNodeId, list)
}

const SOURCE_SELECTOR = '[data-op-prototype-source]'
const PAGE_SELECTOR = '[data-op-prototype-page]'
const NODE_ATTRIBUTE = 'data-op-prototype-node'
const KEYBOARD_SOURCE_ATTRIBUTE = 'data-op-prototype-keyboard'
const TRANSITION_KEY_ATTRIBUTE = 'data-op-transition-key'
const PROTOTYPE_ANIMATION_ID = 'openpencil-prototype-transition'
const FOCUSABLE_SELECTOR = [
  'a[href]',
  'button:not([disabled])',
  'input:not([disabled])',
  'select:not([disabled])',
  'textarea:not([disabled])',
  '[tabindex]:not([tabindex="-1"])'
].join(',')
const delayStates = new WeakMap<Element, Map<string, number | null>>()
const delaySources = new Set<Element>()
const delayRecords = new Set<{ element: Element; id: string; timer: number }>()
const overlays: OverlayRecord[] = []
const routeStack: string[] = []
let activeRun: ActiveRun | null = null
let queueTail: Promise<void> = Promise.resolve()
let queueDepth = 0
let queueGeneration = 0
let disposed = false

const reducedMotionQuery =
  runtimeWindow && typeof runtimeWindow.matchMedia === 'function'
    ? runtimeWindow.matchMedia('(prefers-reduced-motion: reduce)')
    : null

const styleElement = runtimeDocument?.createElement('style') ?? null
if (styleElement) {
  styleElement.dataset.openpencilPrototype = 'runtime'
  styleElement.textContent =
    '@keyframes op-prototype-fade-in{from{opacity:0}to{opacity:1}}' +
    '@keyframes op-prototype-fade-out{from{opacity:1}to{opacity:0}}' +
    '@keyframes op-prototype-enter{from{transform:translate(var(--op-prototype-enter-x),var(--op-prototype-enter-y))}to{transform:translate(0,0)}}' +
    '@keyframes op-prototype-exit{from{transform:translate(0,0)}to{transform:translate(var(--op-prototype-exit-x),var(--op-prototype-exit-y))}}' +
    'html[data-op-prototype-kind="dissolve"]::view-transition-old(root){animation:op-prototype-fade-out var(--op-prototype-duration) var(--op-prototype-easing) both}' +
    'html[data-op-prototype-kind="dissolve"]::view-transition-new(root){animation:op-prototype-fade-in var(--op-prototype-duration) var(--op-prototype-easing) both}' +
    'html[data-op-prototype-kind="slide"]::view-transition-new(root){animation:op-prototype-enter var(--op-prototype-duration) var(--op-prototype-easing) both}' +
    'html[data-op-prototype-kind="push"]::view-transition-old(root){animation:op-prototype-exit var(--op-prototype-duration) var(--op-prototype-easing) both}' +
    'html[data-op-prototype-kind="push"]::view-transition-new(root){animation:op-prototype-enter var(--op-prototype-duration) var(--op-prototype-easing) both}' +
    'html[data-op-prototype-kind="smartMatch"]::view-transition-group(*){animation-duration:var(--op-prototype-duration);animation-timing-function:var(--op-prototype-easing)}'
  runtimeDocument.head.append(styleElement)
}

function currentPage(): HTMLElement | null {
  return runtimeDocument?.querySelector<HTMLElement>(PAGE_SELECTOR) ?? null
}

function currentPageId(): string | null {
  return currentPage()?.getAttribute('data-op-prototype-page') ?? null
}

const initialPageId = currentPageId()
if (initialPageId) routeStack.push(initialPageId)

function attrSelector(attribute: string, value: string): string {
  return '[' + attribute + '=' + JSON.stringify(value) + ']'
}

function nodeElement(nodeId: string, root: ParentNode = runtimeDocument as Document): HTMLElement | null {
  if (!root) return null
  return root.querySelector<HTMLElement>(attrSelector(NODE_ATTRIBUTE, nodeId))
}

function sourceElement(target: EventTarget | null): HTMLElement | null {
  return target instanceof Element ? target.closest<HTMLElement>(SOURCE_SELECTOR) : null
}

function isActiveSource(source: Element): boolean {
  if (source.closest('[data-op-prototype-overlay-target][hidden]')) return false
  const overlayShell = source.closest<HTMLElement>('[data-op-prototype-overlay]')
  if (overlayShell) return overlays.some((record) => record.shell === overlayShell)
  if (source.closest('[data-op-prototype-overlay-target]')) return false
  return source.closest(PAGE_SELECTOR) === currentPage()
}

function scheduleClickConnections(source: HTMLElement): void {
  const sourceNodeId = source.getAttribute(NODE_ATTRIBUTE)
  if (!sourceNodeId) return
  for (const connection of connectionsBySource.get(sourceNodeId) ?? []) {
    if (connection.trigger.kind === 'click') schedule(connection, source)
  }
}

function onClick(event: MouseEvent): void {
  const source = sourceElement(event.target)
  if (!source || !isActiveSource(source)) return
  scheduleClickConnections(source)
}

function onKeyDown(event: KeyboardEvent): void {
  if (event.defaultPrevented || event.repeat || event.altKey || event.ctrlKey || event.metaKey) return
  if (event.key !== 'Enter' && event.key !== ' ') return
  const source = sourceElement(event.target)
  if (
    !source ||
    event.target !== source ||
    !source.hasAttribute(KEYBOARD_SOURCE_ATTRIBUTE) ||
    !isActiveSource(source)
  ) return
  if (event.key === ' ') event.preventDefault()
  scheduleClickConnections(source)
}

function schedule(connection: PrototypeConnection, source?: Element): void {
  if (disposed) return
  if (connection.interruption === 'replace') {
    queueGeneration++
    cancelActiveRun()
    queueDepth = 0
    queueTail = executeManaged(connection, source)
    return
  }
  const generation = queueGeneration
  queueDepth++
  queueTail = queueTail
    .catch(() => undefined)
    .then(() =>
      generation === queueGeneration ? executeManaged(connection, source) : Promise.resolve()
    )
    .finally(() => {
      queueDepth = Math.max(0, queueDepth - 1)
    })
}

async function executeManaged(connection: PrototypeConnection, source?: Element): Promise<void> {
  if (disposed) return
  const controller = new AbortController()
  const run: ActiveRun = {
    connectionId: connection.id,
    controller,
    animations: new Set<Animation>(),
    reducedMotionTerminated: false,
    transitionNames: []
  }
  activeRun = run
  try {
    await executeConnection(connection, run, source)
  } catch (error) {
    if (!controller.signal.aborted) console.warn('[OpenPencil prototype]', error)
  } finally {
    if (activeRun === run) activeRun = null
  }
}

function cancelActiveRun(): void {
  const run = activeRun
  if (!run) return
  run.controller.abort()
  run.viewTransition?.skipTransition()
  for (const animation of run.animations) animation.cancel()
  run.animations.clear()
  clearRunTransitionNames(run)
  clearTransitionStyle()
  activeRun = null
}

async function executeConnection(
  connection: PrototypeConnection,
  run: ActiveRun,
  source?: Element
): Promise<void> {
  if (reducedMotionQuery?.matches === true || connection.transition.kind === 'instant') {
    await performAction(connection.action, run.controller.signal, source)
    return
  }
  if (connection.transition.kind === 'smartMatch') {
    await runSmartMatch(connection, run, source)
    return
  }
  await runBasicTransition(connection, run, source)
}

function startViewTransition(
  update: () => Promise<void>
): PrototypeViewTransition | undefined {
  if (!runtimeDocument) return undefined
  const candidate = runtimeDocument as Document & {
    startViewTransition?: (callback: () => Promise<void>) => PrototypeViewTransition
  }
  return typeof candidate.startViewTransition === 'function'
    ? candidate.startViewTransition(update)
    : undefined
}

async function runBasicTransition(
  connection: PrototypeConnection,
  run: ActiveRun,
  source?: Element
): Promise<void> {
  const transition = connection.transition
  if (transition.kind === 'instant' || transition.kind === 'smartMatch') return
  configureTransitionStyle(transition, connection.playback)
  const viewTransition = startViewTransition(async () => {
    await performAction(connection.action, run.controller.signal, source)
  })
  if (viewTransition) {
    run.viewTransition = viewTransition
    run.controller.signal.addEventListener('abort', () => viewTransition.skipTransition(), {
      once: true
    })
    await viewTransition.finished.catch(() => undefined)
    clearTransitionStyle()
    return
  }
  const scope = await performAction(connection.action, run.controller.signal, source)
  if (
    !scope ||
    run.controller.signal.aborted ||
    run.reducedMotionTerminated ||
    reducedMotionQuery?.matches === true
  ) {
    clearTransitionStyle()
    return
  }
  await animateFallback(scope, transition, connection.playback, run)
  clearTransitionStyle()
}

async function runSmartMatch(
  connection: PrototypeConnection,
  run: ActiveRun,
  source?: Element
): Promise<void> {
  if (connection.transition.kind !== 'smartMatch') return
  const oldScope = activeVisualScope(connection.action)
  const desiredKeys = targetTransitionKeys(connection.action)
  const oldMatches = uniqueTransitionElements(oldScope, desiredKeys)
  const fallback = smartFallback(connection.transition)
  if (!oldScope || oldMatches.size === 0 || !canStartViewTransition()) {
    await runFallbackAction(connection.action, fallback, connection.playback, run, source)
    return
  }

  const scopeToken = smartScopeToken(connection.action)
  const oldNamed: TransitionNameRecord[] = []
  for (const [key, element] of oldMatches) {
    const record = setTransitionName(element, transitionName(scopeToken, key))
    oldNamed.push(record)
    run.transitionNames.push(record)
  }
  configureTransitionStyle(connection.transition, connection.playback)
  let newScope: HTMLElement | null = null
  let completeMatch = true
  const viewTransition = startViewTransition(async () => {
    clearTransitionNames(oldNamed)
    newScope = await performAction(connection.action, run.controller.signal, source)
    if (run.reducedMotionTerminated || reducedMotionQuery?.matches === true) {
      completeMatch = false
      return
    }
    const newMatches = uniqueTransitionElements(newScope, [...oldMatches.keys()])
    completeMatch = newMatches.size === oldMatches.size
    if (completeMatch) {
      for (const [key, element] of newMatches) {
        const record = setTransitionName(element, transitionName(scopeToken, key))
        run.transitionNames.push(record)
      }
    }
  })
  if (!viewTransition) {
    clearRunTransitionNames(run)
    clearTransitionStyle()
    await runFallbackAction(connection.action, fallback, connection.playback, run, source)
    return
  }
  run.viewTransition = viewTransition
  run.controller.signal.addEventListener('abort', () => viewTransition.skipTransition(), {
    once: true
  })
  await viewTransition.updateCallbackDone.catch(() => {
    completeMatch = false
  })
  if (!completeMatch) viewTransition.skipTransition()
  await viewTransition.finished.catch(() => undefined)
  clearRunTransitionNames(run)
  clearTransitionStyle()
  if (!completeMatch && newScope && fallback.kind !== 'instant') {
    await animateFallback(newScope, fallback, connection.playback, run)
  }
}

function canStartViewTransition(): boolean {
  if (!runtimeDocument) return false
  return typeof (runtimeDocument as Document & { startViewTransition?: unknown })
    .startViewTransition === 'function'
}

function smartFallback(
  transition: Extract<PrototypeTransition, { kind: 'smartMatch' }>
): Extract<PrototypeTransition, { kind: 'instant' | 'dissolve' }> {
  return transition.fallback === 'instant'
    ? { kind: 'instant' }
    : { kind: 'dissolve', durationMs: transition.durationMs, easing: transition.easing }
}

async function runFallbackAction(
  action: PrototypeAction,
  transition: Extract<PrototypeTransition, { kind: 'instant' | 'dissolve' }>,
  playback: 'forward' | 'reverse',
  run: ActiveRun,
  source?: Element
): Promise<void> {
  const scope = await performAction(action, run.controller.signal, source)
  if (scope && transition.kind !== 'instant' && !run.controller.signal.aborted) {
    await animateFallback(scope, transition, playback, run)
  }
}

function activeVisualScope(action: PrototypeAction): HTMLElement | null {
  if (action.kind === 'closeOverlay') return overlays.at(-1)?.target ?? null
  return currentPage()
}

function targetTransitionKeys(action: PrototypeAction): string[] {
  if (action.kind === 'navigate') return manifest.pageTransitionKeys[action.targetPageId] ?? []
  if (action.kind === 'openOverlay') return manifest.overlayTransitionKeys[action.targetNodeId] ?? []
  if (action.kind === 'closeOverlay') return manifest.pageTransitionKeys[currentPageId() ?? ''] ?? []
  const targetPageId = routeStack.length > 1 ? routeStack[routeStack.length - 2] : ''
  return manifest.pageTransitionKeys[targetPageId] ?? []
}

function smartScopeToken(action: PrototypeAction): string {
  if (action.kind === 'openOverlay') return 'overlay:' + action.targetNodeId
  if (action.kind === 'closeOverlay') return 'overlay:' + (overlays.at(-1)?.targetNodeId ?? 'none')
  if (action.kind === 'navigate') return 'page:' + action.targetPageId
  return 'page:' + (routeStack.at(-2) ?? 'back')
}

function uniqueTransitionElements(
  scope: ParentNode | null,
  allowedKeys: readonly string[]
): Map<string, HTMLElement> {
  const out = new Map<string, HTMLElement>()
  if (!scope) return out
  const allowedCounts = occurrenceCounts(allowedKeys)
  const candidates: HTMLElement[] = []
  if (scope instanceof HTMLElement && scope.hasAttribute(TRANSITION_KEY_ATTRIBUTE)) {
    candidates.push(scope)
  }
  candidates.push(...scope.querySelectorAll<HTMLElement>('[' + TRANSITION_KEY_ATTRIBUTE + ']'))
  const byKey = new Map<string, HTMLElement[]>()
  for (const element of candidates) {
    if (element.hidden || element.closest('[data-op-prototype-overlay-target][hidden]')) continue
    const key = element.getAttribute(TRANSITION_KEY_ATTRIBUTE)
    if (!key || allowedCounts.get(key) !== 1) continue
    const list = byKey.get(key) ?? []
    list.push(element)
    byKey.set(key, list)
  }
  for (const [key, elements] of byKey) {
    if (elements.length === 1) out.set(key, elements[0])
  }
  return out
}

function occurrenceCounts(values: readonly string[]): Map<string, number> {
  const out = new Map<string, number>()
  for (const value of values) out.set(value, (out.get(value) ?? 0) + 1)
  return out
}

function transitionName(scopeToken: string, key: string): string {
  return 'opm-' + fnv1a(scopeToken + ':' + key)
}

function fnv1a(value: string): string {
  let hash = 0x811c9dc5
  for (let index = 0; index < value.length; index++) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 0x01000193)
  }
  return (hash >>> 0).toString(36)
}

function setTransitionName(element: HTMLElement, name: string): TransitionNameRecord {
  const record = {
    element,
    priority: element.style.getPropertyPriority('view-transition-name'),
    value: element.style.getPropertyValue('view-transition-name')
  }
  element.style.setProperty('view-transition-name', name)
  return record
}

function clearTransitionNames(records: readonly TransitionNameRecord[]): void {
  for (const record of records) {
    if (record.value) {
      record.element.style.setProperty('view-transition-name', record.value, record.priority)
    } else record.element.style.removeProperty('view-transition-name')
  }
}

function clearRunTransitionNames(run: ActiveRun): void {
  if (run.transitionNames.length === 0) return
  clearTransitionNames(run.transitionNames)
  run.transitionNames.length = 0
}

function configureTransitionStyle(
  transition: Exclude<PrototypeTransition, { kind: 'instant' }>,
  playback: 'forward' | 'reverse'
): void {
  if (!runtimeDocument) return
  const root = runtimeDocument.documentElement
  root.dataset.opPrototypeKind = transition.kind
  root.style.setProperty('--op-prototype-duration', String(transition.durationMs) + 'ms')
  root.style.setProperty('--op-prototype-easing', transition.easing)
  if (transition.kind === 'slide' || transition.kind === 'push') {
    const direction = playback === 'reverse' ? oppositeDirection(transition.direction) : transition.direction
    const vector = directionVector(direction)
    root.style.setProperty('--op-prototype-enter-x', String(-vector.x * 100) + '%')
    root.style.setProperty('--op-prototype-enter-y', String(-vector.y * 100) + '%')
    root.style.setProperty('--op-prototype-exit-x', String(vector.x * 100) + '%')
    root.style.setProperty('--op-prototype-exit-y', String(vector.y * 100) + '%')
  }
}

function clearTransitionStyle(): void {
  if (!runtimeDocument) return
  const root = runtimeDocument.documentElement
  delete root.dataset.opPrototypeKind
  for (const property of [
    '--op-prototype-duration',
    '--op-prototype-easing',
    '--op-prototype-enter-x',
    '--op-prototype-enter-y',
    '--op-prototype-exit-x',
    '--op-prototype-exit-y'
  ]) {
    root.style.removeProperty(property)
  }
}

/** Reduced motion can change while a transition is already running. Complete
 * then cancel fallback WAAPI effects so the action's final DOM state remains,
 * skip View Transitions, and synchronously remove every transient style. */
function finishActiveTransitionForReducedMotion(): void {
  if (reducedMotionQuery?.matches !== true) return
  const run = activeRun
  if (!run) return
  run.reducedMotionTerminated = true
  run.viewTransition?.skipTransition()
  for (const animation of run.animations) {
    try {
      animation.finish()
    } catch {
      // A detached animation may no longer be finishable; cancellation still
      // removes its transient effect without changing the completed action.
    }
    try {
      animation.cancel()
    } catch {
      // Some browser shims expose a partially detached Animation object.
    }
    try {
      animation.effect = null
    } catch {
      // A detached effect is already clear.
    }
  }
  run.animations.clear()
  clearRunTransitionNames(run)
  clearTransitionStyle()
}

function oppositeDirection(direction: PrototypeDirection): PrototypeDirection {
  if (direction === 'left') return 'right'
  if (direction === 'right') return 'left'
  if (direction === 'up') return 'down'
  return 'up'
}

function directionVector(direction: PrototypeDirection): { x: number; y: number } {
  if (direction === 'left') return { x: -1, y: 0 }
  if (direction === 'right') return { x: 1, y: 0 }
  if (direction === 'up') return { x: 0, y: -1 }
  return { x: 0, y: 1 }
}

async function animateFallback(
  scope: HTMLElement,
  transition: Exclude<PrototypeTransition, { kind: 'instant' | 'smartMatch' }>,
  playback: 'forward' | 'reverse',
  run: ActiveRun
): Promise<void> {
  if (run.reducedMotionTerminated || reducedMotionQuery?.matches === true) return
  if (typeof scope.animate !== 'function') return
  let frames: Keyframe[] = [{ opacity: 0 }, { opacity: 1 }]
  if (transition.kind === 'slide' || transition.kind === 'push') {
    const direction = playback === 'reverse' ? oppositeDirection(transition.direction) : transition.direction
    const vector = directionVector(direction)
    frames = [
      { transform: 'translate(' + String(-vector.x * 100) + '%, ' + String(-vector.y * 100) + '%)' },
      { transform: 'translate(0, 0)' }
    ]
  }
  const animation = scope.animate(frames, {
    duration: transition.durationMs,
    easing: transition.easing,
    fill: 'both'
  })
  animation.id = PROTOTYPE_ANIMATION_ID
  run.animations.add(animation)
  await animation.finished.catch(() => undefined)
  run.animations.delete(animation)
}

async function performAction(
  action: PrototypeAction,
  signal: AbortSignal,
  source?: Element
): Promise<HTMLElement | null> {
  if (signal.aborted) return null
  if (action.kind === 'navigate') return navigateTo(action, signal)
  if (action.kind === 'back') return navigateBack(signal)
  if (action.kind === 'openOverlay') return openOverlay(action, source)
  closeTopOverlay()
  return currentPage()
}

async function navigateTo(
  action: Extract<PrototypeAction, { kind: 'navigate' }>,
  signal: AbortSignal
): Promise<HTMLElement | null> {
  closeAllOverlays()
  const previousPage = currentPage()
  if (previousPage) deactivateDelaySources(previousPage)
  if (!runtimeWindow) return null
  runtimeWindow.history.pushState(
    { ...(runtimeWindow.history.state ?? {}), __openPencilPrototypePageId: action.targetPageId },
    '',
    action.route
  )
  routeStack.push(action.targetPageId)
  runtimeWindow.dispatchEvent(new PopStateEvent('popstate'))
  const page = await waitForPage(action.targetPageId, signal)
  if (page) {
    scanDelaySources(page)
    if (action.targetKind === 'frame') {
      const target = nodeElement(action.targetNodeId, page)
      target?.scrollIntoView({ block: 'nearest', inline: 'nearest' })
    }
  }
  return page
}

async function navigateBack(signal: AbortSignal): Promise<HTMLElement | null> {
  closeAllOverlays()
  const previousPage = currentPage()
  if (previousPage) deactivateDelaySources(previousPage)
  if (!runtimeWindow || routeStack.length < 2) {
    const previousPageId = currentPageId()
    runtimeWindow?.history.back()
    const page = await waitForAnyPageChange(previousPageId, signal)
    if (page) scanDelaySources(page)
    return page
  }
  const targetPageId = routeStack[routeStack.length - 2]
  runtimeWindow.history.back()
  const page = await waitForPage(targetPageId, signal)
  if (page) {
    syncRouteStack()
    scanDelaySources(page)
  }
  return page
}

function waitForPage(pageId: string, signal: AbortSignal): Promise<HTMLElement | null> {
  return waitForElement(() => {
    const page = currentPage()
    return page?.getAttribute('data-op-prototype-page') === pageId ? page : null
  }, signal)
}

function waitForAnyPageChange(
  previousPageId: string | null,
  signal: AbortSignal
): Promise<HTMLElement | null> {
  return waitForElement(() => {
    const page = currentPage()
    return page && page.getAttribute('data-op-prototype-page') !== previousPageId ? page : null
  }, signal)
}

function waitForElement(
  read: () => HTMLElement | null,
  signal: AbortSignal
): Promise<HTMLElement | null> {
  return new Promise((resolve) => {
    const started = performance.now()
    const poll = (): void => {
      const value = read()
      if (value || signal.aborted || performance.now() - started > 1500) {
        resolve(value)
        return
      }
      requestAnimationFrame(poll)
    }
    poll()
  })
}

function openOverlay(
  action: Extract<PrototypeAction, { kind: 'openOverlay' }>,
  source?: Element
): HTMLElement | null {
  if (!runtimeDocument) return null
  const existing = overlays.find((record) => record.targetNodeId === action.targetNodeId)
  if (existing) return existing.target
  const target = nodeElement(action.targetNodeId)
  if (!target?.parentNode) return null

  const shell = runtimeDocument.createElement('div')
  const backdrop = runtimeDocument.createElement('div')
  const page = currentPage()
  const record: OverlayRecord = {
    target,
    targetNodeId: action.targetNodeId,
    parent: target.parentNode,
    nextSibling: target.nextSibling,
    shell,
    backdrop,
    page,
    pageHadInert: page?.hasAttribute('inert') ?? false,
    pageAriaHidden: page?.getAttribute('aria-hidden') ?? null,
    previousFocus: runtimeDocument.activeElement instanceof HTMLElement ? runtimeDocument.activeElement : null,
    hidden: target.hidden,
    style: target.getAttribute('style'),
    role: target.getAttribute('role'),
    ariaModal: target.getAttribute('aria-modal'),
    tabIndex: target.getAttribute('tabindex'),
    keydown: () => undefined,
    outside: () => undefined
  }
  shell.dataset.opPrototypeOverlay = action.targetNodeId
  Object.assign(shell.style, {
    position: 'fixed',
    inset: '0',
    zIndex: '2147483000',
    pointerEvents: 'none'
  })
  Object.assign(backdrop.style, {
    position: 'absolute',
    inset: '0',
    background: 'color-mix(in srgb, CanvasText 35%, transparent)',
    pointerEvents: 'auto'
  })
  shell.append(backdrop)
  shell.append(target)
  runtimeDocument.body.append(shell)
  target.hidden = false
  target.setAttribute('role', 'dialog')
  target.setAttribute('aria-modal', 'true')
  if (!target.hasAttribute('tabindex')) target.setAttribute('tabindex', '-1')
  Object.assign(target.style, overlayPlacementStyle(action.placement), { pointerEvents: 'auto' })

  if (page) {
    ;(page as HTMLElement & { inert: boolean }).inert = true
    page.setAttribute('inert', '')
    page.setAttribute('aria-hidden', 'true')
  }
  record.keydown = (event) => onOverlayKeydown(event, record)
  record.outside = (event) => {
    if (action.dismissOnOutside && event.target === backdrop) closeOverlayRecord(record)
  }
  runtimeDocument.addEventListener('keydown', record.keydown, true)
  backdrop.addEventListener('pointerdown', record.outside)
  overlays.push(record)
  scanDelaySources(record.target)
  queueMicrotask(() => focusOverlay(record, source))
  return target
}

function overlayPlacementStyle(placement: PrototypePlacement): Partial<CSSStyleDeclaration> {
  const base: Partial<CSSStyleDeclaration> = { position: 'absolute', margin: '0' }
  if (placement === 'center') return { ...base, left: '50%', top: '50%', transform: 'translate(-50%, -50%)' }
  if (placement === 'top') return { ...base, left: '50%', top: '0', transform: 'translateX(-50%)' }
  if (placement === 'right') return { ...base, right: '0', top: '50%', transform: 'translateY(-50%)' }
  if (placement === 'bottom') return { ...base, left: '50%', bottom: '0', transform: 'translateX(-50%)' }
  return { ...base, left: '0', top: '50%', transform: 'translateY(-50%)' }
}

function focusOverlay(record: OverlayRecord, source?: Element): void {
  if (!record.shell.isConnected) return
  const focusable = focusableElements(record.target)[0]
  ;(focusable ?? record.target).focus()
  if (!record.previousFocus && source instanceof HTMLElement) record.previousFocus = source
}

function onOverlayKeydown(event: KeyboardEvent, record: OverlayRecord): void {
  if (overlays.at(-1) !== record) return
  if (event.key === 'Escape') {
    event.preventDefault()
    closeOverlayRecord(record)
    return
  }
  if (event.key !== 'Tab') return
  const focusable = focusableElements(record.target)
  if (focusable.length === 0) {
    event.preventDefault()
    record.target.focus()
    return
  }
  const current = runtimeDocument?.activeElement
  const index = focusable.indexOf(current as HTMLElement)
  const nextIndex = event.shiftKey
    ? index <= 0
      ? focusable.length - 1
      : index - 1
    : index === -1 || index === focusable.length - 1
      ? 0
      : index + 1
  event.preventDefault()
  focusable[nextIndex].focus()
}

function focusableElements(root: ParentNode): HTMLElement[] {
  return [...root.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR)].filter(
    (element) => !element.hidden && element.getAttribute('aria-hidden') !== 'true'
  )
}

function closeTopOverlay(): void {
  const record = overlays.at(-1)
  if (record) closeOverlayRecord(record)
}

function closeAllOverlays(): void {
  while (overlays.length > 0) closeOverlayRecord(overlays[overlays.length - 1])
}

function closeOverlayRecord(record: OverlayRecord): void {
  const index = overlays.indexOf(record)
  if (index !== -1) overlays.splice(index, 1)
  deactivateDelaySources(record.target)
  runtimeDocument?.removeEventListener('keydown', record.keydown, true)
  record.backdrop.removeEventListener('pointerdown', record.outside)
  restoreAttribute(record.target, 'role', record.role)
  restoreAttribute(record.target, 'aria-modal', record.ariaModal)
  restoreAttribute(record.target, 'tabindex', record.tabIndex)
  record.target.hidden = record.hidden
  restoreAttribute(record.target, 'style', record.style)
  if (record.parent.isConnected) record.parent.insertBefore(record.target, record.nextSibling)
  else record.target.remove()
  record.shell.remove()
  if (record.page) {
    ;(record.page as HTMLElement & { inert: boolean }).inert = record.pageHadInert
    if (record.pageHadInert) record.page.setAttribute('inert', '')
    else record.page.removeAttribute('inert')
    restoreAttribute(record.page, 'aria-hidden', record.pageAriaHidden)
  }
  if (record.previousFocus?.isConnected) record.previousFocus.focus()
}

function restoreAttribute(element: Element, name: string, value: string | null): void {
  if (value === null) element.removeAttribute(name)
  else element.setAttribute(name, value)
}

function scanDelaySources(root: ParentNode): void {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(SOURCE_SELECTOR)) elements.push(root)
  elements.push(...root.querySelectorAll(SOURCE_SELECTOR))
  for (const element of elements) scheduleDelayConnections(element)
}

function scheduleDelayConnections(element: Element): void {
  if (!element.isConnected || !isActiveSource(element)) {
    deactivateDelaySource(element)
    return
  }
  const sourceNodeId = element.getAttribute(NODE_ATTRIBUTE)
  if (!sourceNodeId) return
  const connections = (connectionsBySource.get(sourceNodeId) ?? []).filter(
    (connection) => connection.trigger.kind === 'afterDelay'
  )
  if (connections.length === 0) return
  const states = delayStates.get(element) ?? new Map<string, number | null>()
  delayStates.set(element, states)
  delaySources.add(element)
  for (const connection of connections) {
    if (connection.trigger.kind !== 'afterDelay' || states.has(connection.id)) continue
    const record = {
      element,
      id: connection.id,
      timer: runtimeWindow?.setTimeout(() => {
        delayRecords.delete(record)
        if (!element.isConnected || !isActiveSource(element)) {
          deactivateDelaySource(element)
          return
        }
        states.set(connection.id, null)
        schedule(connection, element)
      }, connection.trigger.delayMs) ?? 0
    }
    states.set(connection.id, record.timer)
    delayRecords.add(record)
  }
}

function deactivateDelaySource(element: Element): void {
  for (const record of delayRecords) {
    if (record.element !== element) continue
    runtimeWindow?.clearTimeout(record.timer)
    delayRecords.delete(record)
  }
  delayStates.delete(element)
  delaySources.delete(element)
}

function deactivateDelaySources(root: ParentNode): void {
  const elements: Element[] = []
  if (root instanceof Element && root.matches(SOURCE_SELECTOR)) elements.push(root)
  elements.push(...root.querySelectorAll(SOURCE_SELECTOR))
  for (const element of elements) deactivateDelaySource(element)
}

function clearInactiveDelays(): void {
  for (const element of delaySources) {
    if (element.isConnected && isActiveSource(element)) continue
    deactivateDelaySource(element)
  }
}

const observer = runtimeDocument
  ? new MutationObserver((records) => {
      for (const record of records) {
        for (const node of record.addedNodes) {
          if (node instanceof Element) scanDelaySources(node)
        }
      }
      clearInactiveDelays()
      syncRouteStack()
    })
  : null

function syncRouteStack(): void {
  const pageId = currentPageId()
  if (!pageId || routeStack.at(-1) === pageId) return
  if (routeStack.at(-2) === pageId) routeStack.pop()
  else routeStack.push(pageId)
}

function onPopState(): void {
  requestAnimationFrame(syncRouteStack)
}

function trigger(sourceNodeId: string, connectionId?: string): boolean {
  const candidates = connectionsBySource.get(sourceNodeId) ?? []
  const connection = connectionId
    ? candidates.find((candidate) => candidate.id === connectionId)
    : candidates[0]
  if (!connection) return false
  schedule(connection, nodeElement(sourceNodeId) ?? undefined)
  return true
}

function dispose(): void {
  if (disposed) return
  disposed = true
  runtimeDocument?.removeEventListener('click', onClick)
  runtimeDocument?.removeEventListener('keydown', onKeyDown)
  runtimeWindow?.removeEventListener('popstate', onPopState)
  reducedMotionQuery?.removeEventListener('change', finishActiveTransitionForReducedMotion)
  observer?.disconnect()
  for (const element of delaySources) deactivateDelaySource(element)
  cancelActiveRun()
  closeAllOverlays()
  clearTransitionStyle()
  styleElement?.remove()
  if (runtimeGlobal.__OPENPENCIL_PROTOTYPE_RUNTIME__ === handle) {
    delete runtimeGlobal.__OPENPENCIL_PROTOTYPE_RUNTIME__
  }
}

const handle: PrototypeRuntimeHandle = {
  dispose,
  inspect: () => ({
    activeConnectionId: activeRun?.connectionId ?? null,
    currentPageId: currentPageId(),
    delaySourceCount: delaySources.size,
    delayTimerCount: delayRecords.size,
    overlayNodeIds: overlays.map((record) => record.targetNodeId),
    queued: queueDepth > 0
  }),
  trigger
}

runtimeGlobal.__OPENPENCIL_PROTOTYPE_RUNTIME__ = handle
reducedMotionQuery?.addEventListener('change', finishActiveTransitionForReducedMotion)
if (runtimeDocument) {
  runtimeDocument.addEventListener('click', onClick)
  runtimeDocument.addEventListener('keydown', onKeyDown)
  scanDelaySources(runtimeDocument)
  observer?.observe(runtimeDocument.documentElement, { childList: true, subtree: true })
  requestAnimationFrame(syncRouteStack)
}
runtimeWindow?.addEventListener('popstate', onPopState)
`
}
