import type { CompilerOptions } from '#compiler/types'

import type { MiniProgramPagePlan } from '../miniprogram-shared'

export const MPX_CORE_VERSION = '2.11.1'
export const MPX_CLI_SERVICE_VERSION = '2.2.30'
export const MPX_CLI_PLUGIN_VERSION = '2.2.30'
export const PROCESS_BROWSER_VERSION = '0.11.10'
export const VUE_CLI_SERVICE_VERSION = '5.0.9'

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

function embeddedJSON(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029')
}

export function buildMpxPackage(options: CompilerOptions, packageName: string): string {
  const productName = options.productName || options.packageName || 'OpenPencil Mpx App'
  return json({
    name: packageName,
    version: '0.1.0',
    private: true,
    description: `${productName} — generated by OpenPencil`,
    scripts: {
      serve: 'mpx-cli-service serve',
      build: 'mpx-cli-service build'
    },
    dependencies: {
      '@mpxjs/core': MPX_CORE_VERSION
    },
    devDependencies: {
      '@mpxjs/mpx-cli-service': MPX_CLI_SERVICE_VERSION,
      '@mpxjs/vue-cli-plugin-mpx': MPX_CLI_PLUGIN_VERSION,
      '@mpxjs/webpack-plugin': MPX_CORE_VERSION,
      '@vue/cli-service': VUE_CLI_SERVICE_VERSION,
      process: PROCESS_BROWSER_VERSION
    },
    engines: { node: '>=22.13.0' }
  })
}

export function buildMpxVueConfig(): string {
  return `const { defineConfig } = require('@vue/cli-service')

module.exports = defineConfig({
  outputDir: \`dist/\${process.env.MPX_CURRENT_TARGET_MODE || 'wx'}\`,
  pluginOptions: {
    mpx: {
      srcMode: 'wx',
      plugin: { hackResolve: true },
      loader: {}
    }
  },
  configureWebpack: {
    resolve: { alias: { '@': require('node:path').resolve(__dirname, 'src') } }
  }
})
`
}

export function buildMpxProjectConfig(
  projectName: string,
  location: 'project-root' | 'compiled-output' = 'project-root'
): string {
  return json({
    description: 'OpenPencil generated Mpx WeChat Mini Program source project',
    ...(location === 'project-root' ? { miniprogramRoot: 'dist/wx/' } : {}),
    compileType: 'miniprogram',
    projectname: projectName,
    setting: {
      es6: true,
      minified: true,
      postcss: true,
      urlCheck: true
    }
  })
}

export function buildMpxApp(pages: readonly MiniProgramPagePlan[], title: string): string {
  const config = {
    pages: pages.map((page) => `./${page.route}`),
    window: {
      navigationBarTitleText: title,
      navigationBarBackgroundColor: '#ffffff',
      navigationBarTextStyle: 'black',
      backgroundColor: '#ffffff'
    }
  }
  return `<script>
import { createApp } from '@mpxjs/core'

createApp({})
</script>

<script type="application/json">
${embeddedJSON(config)}
</script>

<style>
page {
  box-sizing: border-box;
  min-height: 100%;
  background: #ffffff;
  color: #111827;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

view, text, image, button, input, textarea, form {
  box-sizing: border-box;
}
</style>
`
}

export function buildMpxGitignore(): string {
  return `node_modules/
dist/
project.private.config.json
.DS_Store
`
}

export function buildMpxReadme(): string {
  return `# OpenPencil Mpx export

This is a source-only Mpx project pinned to reviewed package versions for WeChat Mini Program output.

1. Install the exact dependencies in \`package.json\` with your approved package manager.
2. Run \`npm run build\` or \`npm run serve\`.
3. Open this directory in WeChat DevTools. \`project.config.json\` points to \`dist/wx/\`.
4. Configure the AppID only in WeChat DevTools or \`project.private.config.json\`.

Generation never runs a package manager or accesses the network. No AppID, AppSecret, credential, remote endpoint, or local source path is exported. Unsupported runtime features remain compiler diagnostics.
`
}

export function buildMpxPageConfig(title: string, components: Record<string, string>): string {
  return embeddedJSON({ navigationBarTitleText: title, usingComponents: components })
}
