<script setup lang="ts">
import { computed, nextTick, ref, useTemplateRef } from 'vue'

import { useEditorStore } from '@/app/editor/active-store'
import {
  AppDialogBody,
  AppDialogFooter,
  AppDialogHeader,
  AppDialogRoot
} from '@/components/ui/dialog'
import Tip from '@/components/ui/Tip.vue'

import {
  codePenReviewNotices,
  codePenTags,
  defaultCodePenTitle,
  type CodePenShowcaseTarget
} from './codepen-showcase/command'
import { useCodePenShowcase, type CodePenShowcaseInput } from './codepen-showcase/use'

const {
  target,
  uiKit,
  i18nEnabled = false,
  localesInput = '',
  iconOnly = false,
  showTrigger = true
} = defineProps<{
  target: CodePenShowcaseTarget
  uiKit: 'none' | 'shadcn'
  i18nEnabled?: boolean
  localesInput?: string
  iconOnly?: boolean
  showTrigger?: boolean
}>()

const store = useEditorStore()
const dialogOpen = ref(false)
const title = ref('')
const description = ref('')
const tags = ref('openpencil')
const privatePen = ref(false)
const confirmed = ref(false)
const titleInput = useTemplateRef<HTMLInputElement>('title-input')
const { status, available, unavailableReason, prepare, openInCodePen, cancel, reset } =
  useCodePenShowcase()

const busy = computed(
  () =>
    status.value.kind === 'compiling' ||
    status.value.kind === 'cancelling' ||
    status.value.kind === 'opening'
)
const cancellable = computed(() => status.value.kind === 'compiling')
const prepared = computed(
  () =>
    status.value.kind === 'ready' || status.value.kind === 'opening' || status.value.kind === 'done'
)
const result = computed(() => {
  const current = status.value
  return current.kind === 'ready' || current.kind === 'opening' || current.kind === 'done'
    ? current.result
    : null
})
const totalBytes = computed(() => {
  const data = result.value?.data
  if (!data) return 0
  const encoder = new TextEncoder()
  return (
    encoder.encode(data.html).byteLength +
    encoder.encode(data.css).byteLength +
    encoder.encode(data.js).byteLength
  )
})
const visibleSidecarNotices = computed(() => codePenReviewNotices(result.value?.diagnostics ?? []))
const visibleCompilerWarnings = computed(() => codePenReviewNotices(result.value?.warnings ?? []))
const visibleErrorDiagnostics = computed(() =>
  codePenReviewNotices(status.value.kind === 'error' ? (status.value.diagnostics ?? []) : [])
)
const omittedErrorDiagnostics = computed(() => {
  const count = status.value.kind === 'error' ? (status.value.diagnostics?.length ?? 0) : 0
  return Math.max(0, count - visibleErrorDiagnostics.value.length)
})
const omittedSidecarNotices = computed(() =>
  Math.max(0, (result.value?.diagnostics.length ?? 0) - visibleSidecarNotices.value.length)
)
const omittedCompilerWarnings = computed(() =>
  Math.max(0, (result.value?.warnings.length ?? 0) - visibleCompilerWarnings.value.length)
)

function openShowcase(): void {
  reset()
  title.value = defaultCodePenTitle(store.state.documentName)
  description.value = 'Interactive showcase generated by OpenPencil.'
  tags.value = 'openpencil'
  privatePen.value = false
  confirmed.value = false
  dialogOpen.value = true
  void nextTick(() => titleInput.value?.focus())
}

function requestClose(): void {
  if (busy.value) return
  dialogOpen.value = false
  reset()
}

function preventBusyDismiss(event: Event): void {
  if (busy.value) event.preventDefault()
}

async function prepareShowcase(): Promise<void> {
  confirmed.value = false
  await prepare(showcaseInput())
}

function showcaseInput(): CodePenShowcaseInput {
  return {
    target,
    uiKit,
    i18n: i18nEnabled,
    locales: localesInput
      .split(',')
      .map((value) => value.trim())
      .filter(Boolean),
    title: title.value,
    description: description.value,
    tags: codePenTags(tags.value),
    private: privatePen.value,
    layout: 'left'
  }
}

function editSettings(): void {
  confirmed.value = false
  reset()
  void nextTick(() => titleInput.value?.focus())
}

async function openReviewedShowcase(): Promise<void> {
  await openInCodePen(showcaseInput())
}

defineExpose({ openShowcase })
</script>

<template>
  <Tip v-if="showTrigger" label="Create a reviewed CodePen showcase draft">
    <button
      type="button"
      data-test-id="lowcode-codepen-showcase-toggle"
      aria-haspopup="dialog"
      class="flex h-7 shrink-0 items-center justify-center gap-1 rounded px-2 text-xs text-muted outline-none transition-colors hover:bg-hover hover:text-surface focus-visible:ring-1 focus-visible:ring-accent"
      :class="iconOnly ? 'w-7 px-0' : undefined"
      @click="openShowcase"
    >
      <icon-lucide-code-2 class="size-3.5" />
      <span v-if="!iconOnly">CodePen</span>
    </button>
  </Tip>

  <AppDialogRoot
    v-model:open="dialogOpen"
    size="md"
    data-test-id="lowcode-codepen-showcase-dialog"
    :aria-busy="busy"
    @escape-key-down="preventBusyDismiss"
    @pointer-down-outside="preventBusyDismiss"
    @interact-outside="preventBusyDismiss"
  >
    <AppDialogHeader
      heading="Open in CodePen"
      description="Compile the current unsaved canvas into a bounded HTML/CSS/JavaScript showcase, then open an unsaved CodePen draft."
      close-label="Close CodePen showcase"
      :show-close="!busy"
    />
    <AppDialogBody>
      <form class="flex flex-col gap-4" @submit.prevent="prepareShowcase">
        <div class="grid grid-cols-2 gap-3 rounded border border-border bg-panel p-3 text-xs">
          <div>
            <div class="text-muted">Target</div>
            <div class="mt-1 font-medium text-surface">
              {{ target === 'react' ? 'React' : 'Vue 3' }}
            </div>
          </div>
          <div>
            <div class="text-muted">Destination</div>
            <div class="mt-1 font-medium text-surface">CodePen Prefill draft</div>
          </div>
        </div>
        <label class="flex flex-col gap-1 text-xs text-muted">
          Title
          <input
            ref="title-input"
            v-model="title"
            maxlength="256"
            :disabled="busy || prepared"
            data-test-id="lowcode-codepen-title"
            class="h-8 rounded border border-border bg-input px-2 text-sm text-surface outline-none focus:border-panel-focus"
          />
        </label>
        <label class="flex flex-col gap-1 text-xs text-muted">
          Description
          <textarea
            v-model="description"
            maxlength="4096"
            :disabled="busy || prepared"
            data-test-id="lowcode-codepen-description"
            class="min-h-16 resize-y rounded border border-border bg-input p-2 text-sm text-surface outline-none focus:border-panel-focus"
          />
        </label>
        <label class="flex flex-col gap-1 text-xs text-muted">
          Tags (comma-separated, up to 5)
          <input
            v-model="tags"
            :disabled="busy || prepared"
            data-test-id="lowcode-codepen-tags"
            class="h-8 rounded border border-border bg-input px-2 text-sm text-surface outline-none focus:border-panel-focus"
          />
        </label>
        <label class="flex items-center gap-2 text-xs text-muted">
          <input
            v-model="privatePen"
            type="checkbox"
            :disabled="busy || prepared"
            data-test-id="lowcode-codepen-private"
          />
          Request a private Pen (requires a compatible CodePen plan when saving)
        </label>

        <div
          v-if="!available"
          class="rounded border border-danger/40 bg-danger/5 p-3 text-xs text-danger"
          role="alert"
        >
          {{ unavailableReason }}
        </div>
        <div
          v-else
          class="rounded border border-border bg-hover/40 p-3 text-xs leading-5 text-muted"
        >
          OpenPencil strips server artifacts, blocks preview bridges, scans source and bundled
          output for credentials, inlines bounded assets, and rejects dynamic chunks or panes over
          CodePen limits. No CodePen credential or cookie is read.
        </div>

        <p
          v-if="status.kind === 'compiling' || status.kind === 'cancelling'"
          class="flex items-center gap-2 text-xs text-muted"
          role="status"
          aria-live="polite"
        >
          <icon-lucide-loader-circle class="size-3.5 animate-spin" />
          {{
            status.kind === 'compiling'
              ? 'Compiling and running safety checks…'
              : 'Cancelling CodePen safety checks…'
          }}
        </p>
        <div
          v-else-if="status.kind === 'error'"
          class="rounded border border-danger/40 bg-danger/5 p-3 text-xs text-danger"
          role="alert"
        >
          <p>
            <span v-if="status.code" class="font-mono">{{ status.code }} — </span
            >{{ status.message }}
          </p>
          <ul v-if="visibleErrorDiagnostics.length" class="mt-2 list-disc space-y-1 pl-4">
            <li
              v-for="(diagnostic, index) in visibleErrorDiagnostics"
              :key="`${diagnostic.code}:${index}`"
            >
              <span class="font-mono">{{ diagnostic.code }}</span> — {{ diagnostic.message }}
            </li>
          </ul>
          <p v-if="omittedErrorDiagnostics" class="mt-2">
            {{ omittedErrorDiagnostics }} additional safety diagnostic(s) omitted from this view.
          </p>
        </div>

        <div
          v-if="result"
          class="flex flex-col gap-2 rounded border border-emerald-500/30 bg-emerald-500/5 p-3 text-xs"
        >
          <div class="font-medium text-surface">Safety checks passed</div>
          <div class="text-muted">
            {{ totalBytes.toLocaleString() }} bytes · {{ result.diagnostics.length }} adapter
            notice(s) · {{ result.warnings.length }} compiler warning(s)
          </div>
          <details v-if="visibleSidecarNotices.length" class="text-muted">
            <summary class="cursor-pointer select-none font-medium text-surface">
              Adapter notices ({{ result.diagnostics.length }})
            </summary>
            <ul class="mt-2 list-disc space-y-1 pl-4">
              <li
                v-for="(diagnostic, index) in visibleSidecarNotices"
                :key="`${diagnostic.code}:${index}`"
              >
                <span class="font-mono">{{ diagnostic.code }}</span> — {{ diagnostic.message }}
              </li>
            </ul>
            <p v-if="omittedSidecarNotices" class="mt-2">
              {{ omittedSidecarNotices }} additional adapter notice(s) omitted from this view.
            </p>
          </details>
          <details v-if="visibleCompilerWarnings.length" class="text-muted">
            <summary class="cursor-pointer select-none font-medium text-surface">
              Compiler warnings ({{ result.warnings.length }})
            </summary>
            <ul class="mt-2 list-disc space-y-1 pl-4">
              <li
                v-for="(warning, index) in visibleCompilerWarnings"
                :key="`${warning.code}:${index}`"
              >
                <span class="font-mono">{{ warning.code }}</span> — {{ warning.message }}
              </li>
            </ul>
            <p v-if="omittedCompilerWarnings" class="mt-2">
              {{ omittedCompilerWarnings }} additional compiler warning(s) omitted from this view.
            </p>
          </details>
          <label class="mt-1 flex items-start gap-2 text-muted">
            <input
              v-model="confirmed"
              type="checkbox"
              :disabled="busy || status.kind === 'done'"
              data-test-id="lowcode-codepen-confirm"
            />
            <span
              >I understand CodePen will receive this code in the system browser. The Pen is not
              saved yet; public Pens may be visible, forkable, and subject to CodePen's public
              licensing terms after I save.</span
            >
          </label>
        </div>
      </form>
    </AppDialogBody>
    <AppDialogFooter>
      <button
        v-if="cancellable || status.kind === 'cancelling'"
        type="button"
        data-test-id="lowcode-codepen-cancel"
        class="rounded px-3 py-1.5 text-xs text-muted hover:bg-hover disabled:opacity-40"
        :disabled="status.kind === 'cancelling'"
        @click="cancel"
      >
        {{ status.kind === 'cancelling' ? 'Cancelling…' : 'Cancel' }}
      </button>
      <button
        v-else
        type="button"
        class="rounded px-3 py-1.5 text-xs text-muted hover:bg-hover"
        :disabled="busy"
        @click="requestClose"
      >
        Close
      </button>
      <button
        v-if="status.kind === 'ready'"
        type="button"
        data-test-id="lowcode-codepen-edit-settings"
        class="rounded px-3 py-1.5 text-xs text-muted hover:bg-hover"
        @click="editSettings"
      >
        Edit settings
      </button>
      <button
        v-if="!prepared"
        type="button"
        data-test-id="lowcode-codepen-prepare"
        class="rounded bg-accent px-3 py-1.5 text-xs text-accent-foreground disabled:opacity-40"
        :disabled="!available || busy || !title.trim()"
        @click="prepareShowcase"
      >
        Run safety checks
      </button>
      <button
        v-else-if="status.kind === 'ready' || status.kind === 'opening'"
        type="button"
        data-test-id="lowcode-codepen-open"
        class="rounded bg-accent px-3 py-1.5 text-xs text-accent-foreground disabled:opacity-40"
        :disabled="busy || !confirmed"
        @click="openReviewedShowcase"
      >
        {{ status.kind === 'opening' ? 'Opening…' : 'Open unsaved draft' }}
      </button>
    </AppDialogFooter>
  </AppDialogRoot>
</template>
