import { describe, expect, test } from 'bun:test'

import type { CodePenSidecarSuccessResult } from '@open-pencil/compiler/codepen/sidecar-wire'
import { SceneGraph } from '@open-pencil/scene-graph'

import { CodePenShowcaseSidecarError } from '@/app/lowcode/preview-pane/codepen-showcase/errors'
import { createCodePenShowcaseAbortError } from '@/app/lowcode/preview-pane/codepen-showcase/runner'
import {
  createCodePenShowcaseController,
  digestCodePenShowcaseInput,
  type CodePenShowcaseDependencies,
  type CodePenShowcaseInput,
  type CodePenShowcaseStore
} from '@/app/lowcode/preview-pane/codepen-showcase/use'

type Listener = () => void

interface FakeStoreHarness {
  store: CodePenShowcaseStore
  state: {
    documentName: string
    currentPageId: string
    sceneVersion: number
  }
  emit(event: string): void
  changeSource(): void
}

function fakeStore(name = 'Showcase'): FakeStoreHarness {
  const listeners = new Map<string, Set<Listener>>()
  const sourceListeners = new Set<Listener>()
  const state = { documentName: name, currentPageId: 'page:1', sceneVersion: 7 }
  const graph = new SceneGraph()
  let sourceIdentity = Object.freeze({ handle: null, path: null as string | null })
  const add = (event: string, listener: Listener): (() => void) => {
    const registered = listeners.get(event) ?? new Set<Listener>()
    registered.add(listener)
    listeners.set(event, registered)
    return () => registered.delete(listener)
  }
  const store: CodePenShowcaseStore = {
    graph,
    state,
    getSourceIdentity: () => sourceIdentity,
    onEditorEvent: (event, listener) => add(event, listener),
    onSourceChanged: (listener: Listener) => {
      sourceListeners.add(listener)
      return () => sourceListeners.delete(listener)
    }
  }
  return {
    store,
    state,
    emit(event) {
      for (const listener of listeners.get(event) ?? []) listener()
    },
    changeSource() {
      sourceIdentity = Object.freeze({ handle: null, path: '/next.fig' })
      for (const listener of sourceListeners) listener()
    }
  }
}

function sidecarResult(): CodePenSidecarSuccessResult {
  return {
    compatible: true,
    target: 'react',
    packageName: 'showcase',
    data: {
      title: 'Showcase',
      html: '<div id="root"></div>',
      html_pre_processor: 'none',
      css: '',
      css_pre_processor: 'none',
      js: '',
      js_pre_processor: 'none'
    },
    diagnostics: []
  }
}

const INPUT: CodePenShowcaseInput = Object.freeze({
  target: 'react',
  title: 'Showcase',
  description: 'Generated by OpenPencil',
  tags: ['openpencil'],
  private: false,
  layout: 'left',
  uiKit: 'none',
  i18n: false,
  locales: []
})

function deferred<T>(): {
  promise: Promise<T>
  resolve(value: T): void
  reject(error: unknown): void
} {
  let resolvePromise: (value: T) => void = () => undefined
  let rejectPromise: (error: unknown) => void = () => undefined
  const promise = new Promise<T>((resolve, reject) => {
    resolvePromise = resolve
    rejectPromise = reject
  })
  return { promise, resolve: resolvePromise, reject: rejectPromise }
}

async function flushMicrotasks(): Promise<void> {
  await Promise.resolve()
  await Promise.resolve()
  await Promise.resolve()
  await Promise.resolve()
}

function controllerHarness(
  options: {
    store?: FakeStoreHarness
    compileProject?: CodePenShowcaseDependencies['compileProject']
    runSidecar?: CodePenShowcaseDependencies['runSidecar']
    openPrefill?: CodePenShowcaseDependencies['openPrefill']
  } = {}
) {
  const storeHarness = options.store ?? fakeStore()
  let activeStore = storeHarness.store
  let openCalls = 0
  const dependencies: CodePenShowcaseDependencies = {
    getActiveStore: () => activeStore,
    compileProject:
      options.compileProject ??
      (async () => ({ files: new Map([['src/main.tsx', 'export {}']]), warnings: [] })),
    runSidecar: options.runSidecar ?? (async () => sidecarResult()),
    openPrefill:
      options.openPrefill ??
      (async () => {
        openCalls++
      }),
    digestInput: async (input) => JSON.stringify(input)
  }
  return {
    storeHarness,
    controller: createCodePenShowcaseController(dependencies, {
      available: true,
      unavailableReason: null
    }),
    openCalls: () => openCalls,
    setActiveStore(store: CodePenShowcaseStore) {
      activeStore = store
    }
  }
}

describe('CodePen showcase review lifecycle', () => {
  test('keeps bounded structured sidecar diagnostics available for review', async () => {
    const harness = controllerHarness({
      runSidecar: async () => {
        throw new CodePenShowcaseSidecarError('unsafe-stylesheet-url', 'Stylesheet blocked.', [
          {
            code: 'external-css-network',
            severity: 'error',
            message: 'External stylesheet network access is not allowed.',
            path: 'src/private.css'
          }
        ])
      }
    })

    await harness.controller.prepare(INPUT)

    expect(harness.controller.status.value).toEqual({
      kind: 'error',
      code: 'unsafe-stylesheet-url',
      message: 'Stylesheet blocked.',
      diagnostics: [
        {
          code: 'external-css-network',
          severity: 'error',
          message: 'External stylesheet network access is not allowed.',
          path: 'src/private.css'
        }
      ]
    })
  })

  test('stays cancelling until the sidecar child settles', async () => {
    const child = deferred<CodePenSidecarSuccessResult>()
    let signal: AbortSignal | null = null
    const harness = controllerHarness({
      runSidecar: async (_options, _files, activeSignal) => {
        signal = activeSignal
        return child.promise
      }
    })

    const preparing = harness.controller.prepare(INPUT)
    await flushMicrotasks()
    expect(harness.controller.status.value.kind).toBe('compiling')

    harness.controller.cancel()
    expect(signal?.aborted).toBe(true)
    expect(harness.controller.status.value.kind).toBe('cancelling')

    child.reject(createCodePenShowcaseAbortError())
    await preparing
    expect(harness.controller.status.value.kind).toBe('idle')
  })

  test('passes the in-memory VFS to the sidecar and merges compiler warnings', async () => {
    const files = new Map<string, string | Uint8Array>([['src/main.tsx', 'export {}']])
    let receivedFiles: Map<string, string | Uint8Array> | null = null
    const harness = controllerHarness({
      compileProject: async () => ({
        files,
        warnings: [{ code: 'visual-degraded', message: 'A visual feature was omitted.' }]
      }),
      runSidecar: async (_options, sidecarFiles) => {
        receivedFiles = sidecarFiles
        return sidecarResult()
      }
    })

    await harness.controller.prepare(INPUT)

    expect(receivedFiles).toBe(files)
    const status = harness.controller.status.value
    expect(status.kind).toBe('ready')
    if (status.kind !== 'ready') throw new Error('Expected a ready CodePen result.')
    expect(status.result.warnings).toEqual([
      { code: 'visual-degraded', message: 'A visual feature was omitted.' }
    ])
  })

  test('rejects oversized UTF-8 metadata before compiling the VFS', async () => {
    let compileCalls = 0
    const harness = controllerHarness({
      compileProject: async () => {
        compileCalls++
        return { files: new Map(), warnings: [] }
      }
    })

    await harness.controller.prepare({ ...INPUT, title: '界'.repeat(86) })

    expect(compileCalls).toBe(0)
    expect(harness.controller.status.value).toMatchObject({
      kind: 'error',
      message: expect.stringContaining('256 UTF-8 bytes')
    })
  })

  test('rejects a prepared result after scene, page, source, or active-document drift', async () => {
    const cases: Array<(harness: ReturnType<typeof controllerHarness>) => void> = [
      (harness) => {
        harness.storeHarness.state.sceneVersion++
      },
      (harness) => {
        harness.storeHarness.state.currentPageId = 'page:2'
      },
      (harness) => harness.storeHarness.changeSource(),
      (harness) => harness.setActiveStore(fakeStore('Other').store)
    ]

    for (const drift of cases) {
      const harness = controllerHarness()
      await harness.controller.prepare(INPUT)
      expect(harness.controller.status.value.kind).toBe('ready')
      drift(harness)

      await harness.controller.openInCodePen(INPUT)

      expect(harness.controller.status.value.kind).toBe('error')
      expect(harness.openCalls()).toBe(0)
    }
  })

  test('rejects changed options instead of publishing stale reviewed data', async () => {
    const harness = controllerHarness()
    await harness.controller.prepare(INPUT)

    await harness.controller.openInCodePen({ ...INPUT, title: 'Changed after review' })

    expect(harness.controller.status.value).toMatchObject({
      kind: 'error',
      message: expect.stringContaining('settings changed')
    })
    expect(harness.openCalls()).toBe(0)
  })

  test('invalidates a ready result as soon as the reviewed scene changes', async () => {
    const harness = controllerHarness()
    await harness.controller.prepare(INPUT)
    harness.storeHarness.state.sceneVersion++
    harness.storeHarness.emit('render:requested')

    expect(harness.controller.status.value).toMatchObject({
      kind: 'error',
      message: expect.stringContaining('changed after safety checks')
    })
  })

  test('uses a stable SHA-256 digest over effective CodePen options', async () => {
    const first = await digestCodePenShowcaseInput(INPUT)
    const equivalent = await digestCodePenShowcaseInput({
      ...INPUT,
      title: '  Showcase  ',
      description: '  Generated by OpenPencil  ',
      locales: ['ignored-while-i18n-is-off']
    })
    const changed = await digestCodePenShowcaseInput({ ...INPUT, private: true })

    expect(first).toMatch(/^[0-9a-f]{64}$/)
    expect(equivalent).toBe(first)
    expect(changed).not.toBe(first)
  })
})
